// Supplier Bills. Loosely typed: the module validates every input.
type QueryClient = { query(text: string, values?: unknown[]): Promise<{ rows: any[]; rowCount?: number | null }> };
export declare const SUPPLIER_BILL_PERMISSIONS: any;
export declare const SUPPLIER_BILL_VIEWS: any;
export declare const SUPPLIER_BILL_SOURCE_TYPES: any;
export declare function calculateSupplierBillTotals(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function getBillablePurchaseOrderQuantity(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function getPurchaseOrderBillingProposal(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function receiptLineEligibility(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function approveSupplierBill(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function cancelDraftSupplierBill(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function checkDuplicateSupplierInvoice(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function createBillFromGoodsReceipt(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function createBillFromPurchaseOrder(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function createDirectExpenseBill(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function createSupplierBill(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function createSupplierBillFromPurchaseOrder(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function postSupplierBill(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function reverseSupplierBill(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function updateDraftSupplierBill(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function validateSupplierBillForPosting(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function validateSupplierInvoiceNumber(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function applySupplierAdvance(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function applySupplierCredit(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function recordSupplierBillPayment(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function reverseSupplierPayment(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function calculateSupplierBillBalance(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function getSupplierBill(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function getSupplierBillAging(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function getSupplierBillHistory(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function getSupplierBillOptions(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function getSupplierBillOverdueStatus(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function getSupplierBillPaymentStatus(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function listSupplierBills(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function reconcileSupplierBill(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare const SUPPLIER_BILL_FILE_ENTITY: any;
export declare function listSupplierBillFiles(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function prepareSupplierBillFileUpload(input: { fileName: string; bytes: Uint8Array }, env?: Record<string, string | undefined>): Promise<any>;
export declare function readSupplierBillFile(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function removeSupplierBillFile(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function uploadSupplierBillFile(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function completeSupplierBillPayment(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function previewSupplierBill(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function addDirectBillExpenseLine(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function createDirectSupplierBill(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function getSupplierBillAccounting(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function getSupplierBillOutstandingBalance(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function listExpenseCategories(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function removeDirectBillExpenseLine(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function resolveSupplierBillDefaults(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function saveExpenseCategory(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function updateDirectBillExpenseLine(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function validateDirectBillAccounts(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function validateDirectBillTaxTreatment(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function calculateSupplierBillDueDate(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function validatePartialBillAmounts(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function validatePartialBillQuantities(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function validatePurchaseOrderPriceMatching(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function getPurchaseOrderLineBillingEligibility(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function calculatePartialBillDiscounts(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function calculateSupplierBillTaxes(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function getFixedValueServiceBillingEligibility(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function getGoodsReceiptBillingEligibility(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function getPurchaseOrderBillingProgress(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function getRelatedSupplierBills(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function allocateBillLineToGoodsReceipts(eligibility: any[], orderLineId: string, quantity: bigint, entry?: any): any[];
export declare function evaluateTwoWayMatch(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function approveSupportedMatchException(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function evaluateStoredBill(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function getSupplierBillMatchingResult(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function recheckSupplierBillMatching(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function getPurchaseOrderBillingMatchingSummary(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare const MATCH_APPROVABLE_CODES: readonly string[];
export declare const MATCH_DISCREPANCY_LABELS: Record<string, string>;
export declare const MATCH_RESULTS: Record<string, string>;
export declare function matchFingerprint(line: any, code: string, revision: number | null): string;
export declare const MATCHING_POLICIES: Record<string, string>;
export declare const MATCH_RECEIPT_CODES: readonly string[];
export declare function evaluateThreeWayMatch(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function getPurchaseOrderMatchingPolicy(order: any, settings?: any): string;
export declare function getGoodsReceiptBillingProgress(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function getPurchaseOrderMatchingSummary(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function getSupplierBillMatchStatus(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function getEligibleGoodsReceiptLines(client: QueryClient, ...args: any[]): Promise<any>;
