export type AccountingClientOptions = { baseUrl?: string; fetchImpl?: typeof fetch };
export type AccountingInput = Record<string, unknown>;
export type AccountingClient = {
  dashboard(filters?: AccountingInput): Promise<unknown>;
  options(companyId?: string): Promise<unknown>;
  journals(filters?: AccountingInput): Promise<unknown>;
  journal(id: string): Promise<unknown>;
  createJournal(input: AccountingInput): Promise<unknown>;
  journalAction(id: string, action: string, input?: AccountingInput): Promise<unknown>;
  receivables(filters?: AccountingInput): Promise<unknown>;
  receivable(id: string): Promise<unknown>;
  createReceivable(input: AccountingInput): Promise<unknown>;
  receivableAction(id: string, action: string, input?: AccountingInput): Promise<unknown>;
  receipts(filters?: AccountingInput): Promise<unknown>;
  createReceipt(input: AccountingInput): Promise<unknown>;
  receiptAction(id: string, action: string, input?: AccountingInput): Promise<unknown>;
  importSalesInvoiceRequest(id: string): Promise<unknown>;
  payables(filters?: AccountingInput): Promise<unknown>;
  payable(id: string): Promise<unknown>;
  createPayable(input: AccountingInput): Promise<unknown>;
  payableAction(id: string, action: string, input?: AccountingInput): Promise<unknown>;
  payments(filters?: AccountingInput): Promise<unknown>;
  createPayment(input: AccountingInput): Promise<unknown>;
  paymentAction(id: string, action: string, input?: AccountingInput): Promise<unknown>;
  vendorBillMatch(id: string): Promise<unknown>;
  evaluateVendorBillMatch(id: string, input: AccountingInput): Promise<unknown>;
  overrideVendorBillMatch(id: string, reason: string): Promise<unknown>;
  bankAccounts(filters?: AccountingInput): Promise<unknown>;
  createBankAccount(input: AccountingInput): Promise<unknown>;
  bankStatements(filters?: AccountingInput): Promise<unknown>;
  importBankStatement(input: AccountingInput): Promise<unknown>;
  bankStatement(id: string): Promise<unknown>;
  bankStatementAction(id: string, action: string, input?: AccountingInput): Promise<unknown>;
  bankReconciliationAction(id: string, action: string, input?: AccountingInput): Promise<unknown>;
  report(name: string, filters?: AccountingInput): Promise<unknown>;
  closeRuns(filters?: AccountingInput): Promise<unknown>;
  closeRun(id: string): Promise<unknown>;
  createCloseRun(input: AccountingInput): Promise<unknown>;
  closeRunAction(id: string, action: string, input?: AccountingInput): Promise<unknown>;
};
export function createAccountingClient(options?: AccountingClientOptions): AccountingClient;
