import type { StockContext } from "./index.js";
type Row = Record<string, unknown>;
type Client = any;
type File = { fileName: string; contentType: string; body: string | Uint8Array; rowCount: number };
export declare const ALERT_CONDITIONS: ReadonlyArray<{ id: string; label: string; severity: string }>;
export declare const ALERT_VIEWS: ReadonlyArray<{ id: string; label: string; filters?: Row }>;
export declare function getLowStockAlerts(client: Client, context: StockContext, filters?: Row): Promise<Row>;
export declare function getOpenLowStockAlerts(client: Client, context: StockContext, filters?: Row): Promise<Row>;
export declare function getOutOfStockAlerts(client: Client, context: StockContext, filters?: Row): Promise<Row>;
export declare function getReplenishmentRequiredAlerts(client: Client, context: StockContext, filters?: Row): Promise<Row>;
export declare function getLowStockCoveredAlerts(client: Client, context: StockContext, filters?: Row): Promise<Row>;
export declare function getLowStockAlert(client: Client, context: StockContext, alertId: string): Promise<Row>;
export declare function getLowStockAlertHistory(client: Client, context: StockContext, alertId: string): Promise<Row[]>;
export declare function getLowStockDemandBreakdown(client: Client, context: StockContext, alertId: string): Promise<Row[]>;
export declare function getLowStockIncomingBreakdown(client: Client, context: StockContext, alertId: string): Promise<Row[]>;
export declare function getLowStockOtherWarehouseAvailability(client: Client, context: StockContext, alertId: string): Promise<Row[]>;
export declare function acknowledgeLowStockAlert(client: Client, context: StockContext, alertId: string, input?: { notes?: string }): Promise<Row>;
export declare function acknowledgeLowStockAlerts(client: Client, context: StockContext, alertIds?: string[], input?: { notes?: string }): Promise<{ acknowledged: number; skipped: Row[] }>;
export declare function createPurchaseDraftFromLowStockAlert(client: Client, context: StockContext, alertId: string, input?: Row): Promise<Row>;
export declare function createTransferDraftFromLowStockAlert(client: Client, context: StockContext, alertId: string, input?: Row): Promise<Row>;
export declare function evaluateLowStockAlert(client: Client, context: StockContext, ruleId: string): Promise<string | null>;
export declare function evaluateAffectedLowStockAlerts(client: Client, context: StockContext, pairs?: Array<{ itemId: string; warehouseId: string }>): Promise<{ evaluated: number }>;
export declare function resolveLowStockAlertIfConditionCleared(client: Client, context: StockContext, ruleId: string): Promise<string | null>;
export declare function escalateLowStockAlert(client: Client, context: StockContext, ruleId: string): Promise<string | null>;
export declare function reconcileLowStockAlerts(client: Client, context: StockContext): Promise<Row>;
export declare function dispatchLowStockAlertNotifications(client: Client, context: StockContext, options?: { limit?: number }): Promise<{ transitions: number; delivered: number }>;
export declare function getLowStockAlertCounts(client: Client, context: StockContext, input?: { warehouseId?: string | null }): Promise<Row | null>;
export declare function exportLowStockAlerts(client: Client, context: StockContext, filters?: Row, format?: "csv" | "xlsx"): Promise<File>;
export declare function getLowStockAlertOptions(context: StockContext): Row;
