import type { StockContext } from "./index.js";
type Row = Record<string, unknown>;
export declare function getStockSettings(client: any, context: StockContext): Promise<Row>;
export declare function updateStockSettings(client: any, context: StockContext, input?: Row): Promise<Row>;
export declare function lookupStockByCode(client: any, context: StockContext, input?: { code?: string }): Promise<Row>;
export declare function createStockBatch(client: any, context: StockContext, input?: Row): Promise<Row>;
export declare function setStockBatchStatus(client: any, context: StockContext, batchId: string, status: string, reason?: string): Promise<Row>;
export declare function listStockBatchesWithBalance(client: any, context: StockContext, options?: { withinDays?: number | string | null; limit?: number }): Promise<Row[]>;
export declare function receiveSerializedStock(client: any, context: StockContext, input?: Row): Promise<{ movement: Row; serials: Row[]; replayed: boolean }>;
export declare function listStockSerialsDetailed(client: any, context: StockContext, options?: { itemId?: string | null; status?: string | null; limit?: number }): Promise<Row[]>;
export declare function saveStockReorderRule(client: any, context: StockContext, input?: Row): Promise<Row>;
export declare function listStockReorderRulesDetailed(client: any, context: StockContext): Promise<Row[]>;
export declare function guardStockItemIdentity(client: any, organizationId: string, itemId: string, input?: Row): Promise<void>;
