import type { StockContext } from "./index.js";
type Row = Record<string, unknown>;
type Client = any;
type File = { fileName: string; contentType: string; body: string | Uint8Array; rowCount: number };
export declare const MOVEMENT_CATEGORIES: ReadonlyArray<{ id: string; label: string }>;
export declare const MOVEMENT_HISTORY_VIEWS: ReadonlyArray<{ id: string; label: string; filters?: Row }>;
export declare function getInventoryMovementHistory(client: Client, context: StockContext, filters?: Row): Promise<Row>;
export declare function searchInventoryMovements(client: Client, context: StockContext, search: string, filters?: Row): Promise<Row>;
export declare function getItemMovementHistory(client: Client, context: StockContext, itemId: string, filters?: Row): Promise<Row>;
export declare function getWarehouseMovementHistory(client: Client, context: StockContext, warehouseId: string, filters?: Row): Promise<Row>;
export declare function getLocationMovementHistory(client: Client, context: StockContext, warehouseId: string, locationId: string, filters?: Row): Promise<Row>;
export declare function getBatchMovementHistory(client: Client, context: StockContext, batchId: string, filters?: Row): Promise<Row>;
export declare function getSourceDocumentMovements(client: Client, context: StockContext, sourceType: string, sourceId: string, filters?: Row): Promise<Row>;
export declare function getMovementGroups(client: Client, context: StockContext, filters?: Row): Promise<Row>;
export declare function getMovementHistoryDetail(client: Client, context: StockContext, groupId: string): Promise<Row>;
export declare function getSerialMovementHistory(client: Client, context: StockContext, input: { serialId?: string | null; serialNumber?: string | null }): Promise<Row>;
export declare function getTransferMovementHistory(client: Client, context: StockContext, transferId: string): Promise<Row>;
export declare function getMovementHistoryAsOf(client: Client, context: StockContext, input: { itemId?: string | null; warehouseId?: string | null; locationId?: string | null; batchId?: string | null; serialId?: string | null; at?: string | null; movementId?: string | null }): Promise<Row>;
export declare function getMovementBalanceAfter(client: Client, context: StockContext, movementId: string): Promise<Row>;
export declare function getMovementValuation(client: Client, context: StockContext, groupId: string): Promise<Row | null>;
export declare function getRelatedMovements(client: Client, context: StockContext, groupId: string): Promise<Row[]>;
export declare function checkMovementHistoryIntegrity(client: Client, context: StockContext): Promise<Row>;
export declare function exportInventoryMovementHistory(client: Client, context: StockContext, filters?: Row, format?: "csv" | "xlsx"): Promise<File>;
export declare function getMovementHistoryOptions(client: Client, context: StockContext): Promise<Row>;
