import type { StockContext } from "./index.js";
import { StockError } from "./errors.js";
type Row = Record<string, unknown>;
type Client = any;
type File = { fileName: string; contentType: string; body: string | Uint8Array; rowCount: number };
export declare class ReorderError extends StockError {}
export declare const REORDER_STATUSES: ReadonlyArray<{ id: string; label: string }>;
export declare const IMPORT_TEMPLATE_COLUMNS: ReadonlyArray<{ key: string; label: string }>;
export declare function calculateSuggestedReplenishmentQuantity(input: { target: number | string; projected: number | string; orderMultiple?: number | string | null; wholeUnits?: boolean }): number;
export declare function createReorderRule(client: Client, context: StockContext, input?: Row): Promise<Row>;
export declare function updateReorderRule(client: Client, context: StockContext, ruleId: string, input?: Row): Promise<Row>;
export declare function enableReorderRule(client: Client, context: StockContext, ruleId: string): Promise<Row>;
export declare function disableReorderRule(client: Client, context: StockContext, ruleId: string): Promise<Row>;
export declare function getReorderRule(client: Client, context: StockContext, ruleId: string): Promise<Row>;
export declare function getReorderRules(client: Client, context: StockContext, filters?: Row): Promise<Row>;
export declare function getReorderRequirements(client: Client, context: StockContext, filters?: Row): Promise<Row>;
export declare function getReorderCoveredByIncoming(client: Client, context: StockContext, filters?: Row): Promise<Row>;
export declare function getItemsBelowReorder(client: Client, context: StockContext, filters?: Row): Promise<Row>;
export declare function getReorderDemandBreakdown(client: Client, context: StockContext, itemId: string, warehouseId: string): Promise<Row[]>;
export declare function getReorderIncomingBreakdown(client: Client, context: StockContext, itemId: string, warehouseId: string): Promise<Row[]>;
export declare function getOtherWarehouseAvailability(client: Client, context: StockContext, itemId: string, warehouseId: string): Promise<Row[]>;
export declare function calculateReorderStatus(client: Client, context: StockContext, ruleId: string): Promise<{ ruleId: string; status: string }>;
export declare function calculateCurrentPlanningPosition(client: Client, context: StockContext, itemId: string, warehouseId: string): Promise<number>;
export declare function calculateFirmOpenDemand(client: Client, context: StockContext, itemId: string, warehouseId: string): Promise<number>;
export declare function calculateFirmIncoming(client: Client, context: StockContext, itemId: string, warehouseId: string): Promise<number>;
export declare function getPlanningPosition(client: Client, context: StockContext, itemId: string, warehouseId: string): Promise<Row>;
export declare function createPurchaseDraftFromReorder(client: Client, context: StockContext, ruleId: string, input?: Row): Promise<Row>;
export declare function createTransferDraftFromReorder(client: Client, context: StockContext, ruleId: string, input?: Row): Promise<Row>;
export declare function dismissReplenishmentRecommendation(client: Client, context: StockContext, ruleId: string, input?: { reason?: string }): Promise<Row>;
export declare function recalculateAffectedReorderRules(client: Client, context: StockContext, pairs?: Array<{ itemId: string; warehouseId: string }>): Promise<{ recalculated: number }>;
export declare function reconcileReorderStatusProjection(client: Client, context: StockContext, options?: { recordRun?: boolean }): Promise<Row>;
export declare function exportReorderRules(client: Client, context: StockContext, filters?: Row, format?: "csv" | "xlsx"): Promise<File>;
export declare function importReorderRules(client: Client, context: StockContext, input?: { fileName?: string; bytes?: Uint8Array | string; apply?: boolean }): Promise<Row>;
export declare function getReorderSummary(client: Client, context: StockContext, input?: { itemId?: string | null; warehouseId?: string | null }): Promise<Row | null>;
export declare function getReorderOptions(client: Client, context: StockContext): Promise<Row>;
