import type { StockContext } from "./index.js";
type Row = Record<string, unknown>;
type Client = any;
export declare const INVENTORY_VALUATION_METHODS: ReadonlyArray<{ id: "moving_average" | "fifo"; label: string }>;
export declare const VALUATION_EXCEPTIONS: Readonly<Record<string, string>>;
export declare function valuationCapabilities(context: StockContext): Record<string, boolean>;
export declare function getInventoryValuation(client: Client, context: StockContext, filters?: Row): Promise<Row>;
export declare function getItemValuation(client: Client, context: StockContext, itemId: string): Promise<Row>;
export declare function getWarehouseValuation(client: Client, context: StockContext, warehouseId: string): Promise<Row>;
export declare function getFifoLayers(client: Client, context: StockContext, filters?: Row): Promise<Row>;
export declare function getValuationMovements(client: Client, context: StockContext, filters?: Row): Promise<Row>;
export declare function getValuationEntry(client: Client, context: StockContext, entryId: string): Promise<Row>;
export declare function reconcileInventoryValuation(client: Client, context: StockContext, options?: { record?: boolean }): Promise<Row>;
export declare function reconcileInventoryWithFinance(client: Client, context: StockContext): Promise<Row>;
export declare function rebuildInventoryValuationProjection(client: Client, context: StockContext, input: { reason: string }): Promise<Row>;
export declare function listValuationEvents(client: Client, context: StockContext): Promise<Row[]>;
export declare function exportInventoryValuation(client: Client, context: StockContext, filters?: Row, format?: "csv" | "xlsx"): Promise<{ fileName: string; contentType: string; body: string | Uint8Array; rowCount: number }>;
export declare function valuationOfMovement(client: Client, context: StockContext, movementId: string): Promise<Row | null>;
