import type { StockContext } from "./index.js";
type Row = Record<string, unknown>;
type Client = any;
export declare class WarehouseError extends Error {
  status: number;
  code: string;
  details?: unknown;
  constructor(status: number, message: string, code?: string, details?: unknown);
}
export declare const WAREHOUSE_OPERATIONS: readonly string[];
export declare const WAREHOUSE_OPERATION_LABELS: Readonly<Record<string, string>>;
export declare const WAREHOUSE_TYPES: ReadonlyArray<{ code: string; label: string }>;
export declare const LOCATION_PURPOSES: ReadonlyArray<{ code: string; label: string }>;
export declare const LOCATION_STRUCTURES: readonly string[];
export declare function normalizeWarehouseCode(value: unknown): string;
export declare function warehouseCapabilities(context: StockContext): Record<string, boolean>;
export declare function listWarehouses(client: Client, context: StockContext, filters?: Row): Promise<Row>;
export declare function getWarehouse(client: Client, context: StockContext, warehouseId: string): Promise<Row>;
export declare function createWarehouse(client: Client, context: StockContext, input?: Row): Promise<Row>;
export declare function updateWarehouse(client: Client, context: StockContext, warehouseId: string, input?: Row): Promise<Row>;
export declare function setCompanyDefaultWarehouse(client: Client, context: StockContext, warehouseId: string): Promise<Row>;
export declare function validateWarehouseForDeactivation(client: Client, context: StockContext, warehouseId: string): Promise<Array<{ code: string; message: string }>>;
export declare function setWarehouseStatus(client: Client, context: StockContext, warehouseId: string, status: string, input?: Row): Promise<Row>;
export declare function deleteWarehouse(client: Client, context: StockContext, warehouseId: string): Promise<{ deleted: true }>;
export declare function getWarehouseLocations(client: Client, context: StockContext, warehouseId: string): Promise<Row[]>;
export declare function createWarehouseLocation(client: Client, context: StockContext, warehouseId: string, input?: Row): Promise<Row>;
export declare function updateWarehouseLocation(client: Client, context: StockContext, locationId: string, input?: Row): Promise<Row>;
export declare function setWarehouseLocationStatus(client: Client, context: StockContext, locationId: string, status: string): Promise<Row>;
export declare function setDefaultWarehouseLocation(client: Client, context: StockContext, warehouseId: string, kind: string, locationId: string | null): Promise<Row[]>;
export declare function getWarehouseAccess(client: Client, context: StockContext, warehouseId: string): Promise<Row[]>;
export declare function setWarehouseAccess(client: Client, context: StockContext, warehouseId: string, entries?: Array<{ userId: string; operations?: string[] }>): Promise<Row[]>;
export declare function canUseWarehouse(client: Client, context: StockContext, warehouseId: string, operation: string | null): Promise<boolean>;
export declare function validateUserWarehouseAccess(client: Client, context: StockContext, warehouseId: string, operation: string | null): Promise<void>;
export declare function validateWarehouseOperation(client: Client, context: StockContext, warehouseId: string, operation: string | null, options?: Row): Promise<{ warehouse: Row; locationId: string | null }>;
export declare function ledgerLocation(client: Client, organizationId: string, warehouseId: string, locationId: string | null, options?: Row): Promise<string | null>;
export declare function defaultLocationOf(client: Client, organizationId: string, warehouseId: string, kind: string): Promise<string | null>;
export declare function resolveDefaultWarehouse(client: Client, context: StockContext, operation?: string | null): Promise<{ warehouseId: string; code: string; name: string; source: "user" | "company" } | null>;
export declare function setUserDefaultWarehouse(client: Client, context: StockContext, warehouseId: string | null): Promise<Row | null>;
export declare function getWarehouseItemBalances(client: Client, context: StockContext, warehouseId: string, filters?: Row): Promise<Row>;
export declare function getWarehouseMovements(client: Client, context: StockContext, warehouseId: string, filters?: Row): Promise<Row[]>;
export declare function getWarehouseIncoming(client: Client, context: StockContext, warehouseId: string): Promise<Row[]>;
export declare function getWarehouseOutgoing(client: Client, context: StockContext, warehouseId: string): Promise<Row[]>;
export declare function getWarehouseTransfers(client: Client, context: StockContext, warehouseId: string): Promise<Row[]>;
export declare function getWarehouseBatches(client: Client, context: StockContext, warehouseId: string): Promise<Row[]>;
export declare function getWarehouseSerials(client: Client, context: StockContext, warehouseId: string): Promise<Row[]>;
export declare function getWarehouseHistory(client: Client, context: StockContext, warehouseId: string): Promise<Row[]>;
export declare function getWarehouseOptions(client: Client, context: StockContext): Promise<Row>;
