export const CRM_RESOURCE_KEYS = Object.freeze([
  "leads",
  "opportunities",
  "activities",
  "campaigns",
  "communications",
  "pipelines",
  "stages",
  "sources",
  "lost-reasons",
  "qualification-criteria",
  "tags",
  "scoring-rules",
  "assignment-rules",
  "sequences",
  "sequence-steps",
  "sequence-enrollments",
  "automation-rules",
  "capture-forms",
  "competitors",
  "forecast-targets",
  "integrations",
  "sales-teams",
  "sales-team-members",
  "territories",
  "territory-assignments",
  "quota-plans",
  "forecast-periods",
  "forecast-submissions",
  "account-plans",
  "account-stakeholders",
  "playbooks",
  "playbook-questions",
  "playbook-responses",
  "consent-events",
  "privacy-requests",
  "data-quality-scores",
  "engagement-templates",
  "meeting-links",
  "sync-accounts",
  "conversations",
  "conversation-insights",
  "pipeline-inspections",
  "deal-risks",
  "recommendations",
  "buying-committees",
  "buying-committee-members",
  "relationship-edges",
  "account-signals",
  "partner-accounts",
  "partner-deals",
  "report-definitions",
  "dashboards",
  "dashboard-widgets",
  "custom-object-definitions",
  "custom-field-definitions",
  "custom-records",
  "field-visits",
  "enrichment-jobs",
  "ai-predictions",
  "ai-feedback",
]);

export const CRM_LEAD_STATUSES = Object.freeze([
  "new",
  "contacted",
  "working",
]);

export const CRM_LEAD_RECORD_STATUSES = Object.freeze([
  "active",
  "converted",
  "archived",
]);

export const CRM_OPPORTUNITY_STATUSES = Object.freeze([
  "open",
  "won",
  "lost",
  "abandoned",
  "archived",
]);

export const CRM_ACTIVITY_TYPES = Object.freeze([
  "task",
  "call",
  "meeting",
  "email",
  "whatsapp",
  "sms",
  "note",
]);

export const CRM_CHANNELS = Object.freeze([
  "email",
  "whatsapp",
  "sms",
  "call",
  "chat",
  "other",
]);
