/** Canonical 510-register feature slice for this module. Requirement IDs are permanent evidence identifiers, not source-folder names. */
export const PROCUREMENT_FEATURES = Object.freeze([
  ["F063", "Supplier master"],
  ["F064", "Supplier contacts and addresses"],
  ["F065", "Supplier onboarding"],
  ["F066", "Supplier categories"],
  ["F067", "Purchase requisitions"],
  ["F068", "Requisition approvals"],
  ["F069", "RFQ creation"],
  ["F070", "RFQ to multiple vendors"],
  ["F071", "Supplier quotations"],
  ["F072", "Bid comparison"],
  ["F073", "Supplier selection"],
  ["F074", "Purchase orders"],
  ["F075", "PO approvals"],
  ["F076", "PO amendments"],
  ["F077", "Blanket purchase orders"],
  ["F078", "Purchase agreements and contracts"],
  ["F079", "Supplier price lists"],
  ["F080", "Goods receipt / GRN"],
  ["F081", "Partial receipts"],
  ["F082", "Rejected receipts"],
  ["F083", "Purchase returns"],
  ["F084", "Supplier invoices"],
  ["F085", "2-way matching"],
  ["F086", "3-way matching: PO – GRN – Invoice"],
  ["F087", "Landed costs"],
  ["F088", "Payment terms"],
  ["F089", "Supplier performance"],
  ["F090", "Supplier rating"],
  ["F091", "Supplier lead times"],
  ["F092", "Spend analysis"],
  ["F093", "Purchase history"],
  ["F094", "Reorder-generated purchasing"],
  ["F095", "Subcontract purchasing"],
  ["F096", "Procurement dashboard"],
] as const);

export type ProcurementFeatureId = (typeof PROCUREMENT_FEATURES)[number][0];
