// Plain data (no components) so a Server Component page can read it.
export const MANUFACTURING_PAGES: Record<string, { title: string }> = {
  boms: { title: "Bills of materials" },
  "bom-versions": { title: "BOM versions" },
  "where-used": { title: "Where used" },
  "engineering-changes": { title: "Engineering changes" },
  routings: { title: "Routings" },
  "work-centers": { title: "Work centers" },
  calendars: { title: "Shift calendars" },
  shifts: { title: "Shifts" },
  "calendar-exceptions": { title: "Holidays and closures" },
  capacity: { title: "Capacity" },
  "production-orders": { title: "Production orders" },
  "shop-floor": { title: "Shop floor" },
  operations: { title: "Operations" },
  reservations: { title: "Material reservations" },
  consumption: { title: "Material consumption" },
  wip: { title: "Work in progress" },
  "finished-output": { title: "Finished output" },
  "by-products": { title: "By-products" },
  "scrap-rework": { title: "Scrap and rework" },
  settings: { title: "Manufacturing settings" },
  mrp: { title: "MRP" },
  "time-tracking": { title: "Time tracking" },
  inspections: { title: "Production inspections" },
  downtime: { title: "Downtime" },
  subcontracting: { title: "Subcontracting" },
  "material-planning": { title: "Material planning" },
  scheduling: { title: "Scheduling" },
};
