packages:
  - apps/*
  - packages/*
  - platform/*
allowBuilds:
  '@nestjs/core': true
  '@scarf/scarf': false
  argon2: true
  esbuild: true
  msgpackr-extract: true
  sharp: false
minimumReleaseAgeExclude:
  - '@simplewebauthn/server@14.0.2'
