type Row = Record<string, unknown>;
export type ManufacturingContext = { organizationId: string; userId: string; permissions: string[]; roleSlugs: string[] };
export declare function manufacturingContext(session: Record<string, unknown>): ManufacturingContext;
export declare function createBom(client: any, context: ManufacturingContext, input?: Row): Promise<Row>;
export declare function updateDraftBom(client: any, context: ManufacturingContext, bomId: string, input?: Row): Promise<Row>;
export declare function submitBom(client: any, context: ManufacturingContext, bomId: string): Promise<Row>;
export declare function approveBom(client: any, context: ManufacturingContext, bomId: string): Promise<Row>;
export declare function rejectBom(client: any, context: ManufacturingContext, bomId: string, reason?: string): Promise<Row>;
export declare function obsoleteBom(client: any, context: ManufacturingContext, bomId: string, reason?: string): Promise<Row>;
export declare function reviseBom(client: any, context: ManufacturingContext, bomId: string, input?: Row): Promise<Row>;
export declare function addComponentAlternate(client: any, context: ManufacturingContext, componentId: string, input?: Row): Promise<Row>;
export declare function removeComponentAlternate(client: any, context: ManufacturingContext, alternateId: string): Promise<Row>;
export declare function listBoms(client: any, context: ManufacturingContext, options?: { status?: string | null; itemId?: string | null; limit?: number }): Promise<Row[]>;
export declare function getBom(client: any, context: ManufacturingContext, bomId: string): Promise<Row & { components: Row[]; versions: Row[]; otherStructures: Row[] }>;
export declare function explodeBom(client: any, context: ManufacturingContext, options?: { bomId?: string | null; itemId?: string | null; quantity?: number | string; asOf?: string | null }): Promise<{ bomId: string; bomCode: string; quantity: string; asOf: string; lines: Row[]; purchasedTotals: Row[] }>;
export declare function resolveBomForItem(client: any, context: ManufacturingContext, itemId: string, day?: string | null): Promise<Row | null>;
