import type { ManufacturingContext } from "./engineering.js";
type Row = Record<string, any>;
export declare const DOWNTIME_REASONS: string[];
export declare function holdProductionOrder(client: any, context: ManufacturingContext, id: string, reason?: string): Promise<Row>;
export declare function resumeProductionOrder(client: any, context: ManufacturingContext, id: string, note?: string): Promise<Row>;
export declare function logTime(client: any, context: ManufacturingContext, operationId: string, input?: Row): Promise<Row>;
export declare function startTimer(client: any, context: ManufacturingContext, operationId: string, input?: Row): Promise<Row>;
export declare function stopTimer(client: any, context: ManufacturingContext, entryId: string): Promise<Row>;
export declare function listTimeEntries(client: any, context: ManufacturingContext, options?: { workOrderId?: string | null; limit?: number }): Promise<Row[]>;
export declare function recordInspection(client: any, context: ManufacturingContext, workOrderId: string, input?: Row): Promise<Row>;
export declare function operationInspectionSatisfied(client: any, context: ManufacturingContext, operationId: string): Promise<boolean>;
export declare function listInspections(client: any, context: ManufacturingContext, options?: { limit?: number }): Promise<Row[]>;
export declare function startDowntime(client: any, context: ManufacturingContext, input?: Row): Promise<Row>;
export declare function endDowntime(client: any, context: ManufacturingContext, id: string): Promise<Row>;
export declare function listDowntime(client: any, context: ManufacturingContext, options?: { openOnly?: boolean }): Promise<Row[]>;
export declare function getDowntimeSummary(client: any, context: ManufacturingContext, options?: { days?: number | string }): Promise<Row>;
export declare function linkWorkCenterAsset(client: any, context: ManufacturingContext, workCenterId: string, assetId?: string | null): Promise<Row>;
export declare function sendToSubcontractor(client: any, context: ManufacturingContext, operationId: string, input?: Row): Promise<Row>;
export declare function receiveFromSubcontractor(client: any, context: ManufacturingContext, jobId: string, input?: Row): Promise<Row>;
export declare function listSubcontractJobs(client: any, context: ManufacturingContext): Promise<Row[]>;
