import type { ManufacturingContext } from "./engineering.js";
type Row = Record<string, unknown>;
export declare function saveCalendar(client: any, context: ManufacturingContext, input?: Row): Promise<Row>;
export declare function addShift(client: any, context: ManufacturingContext, input?: Row): Promise<Row>;
export declare function removeShift(client: any, context: ManufacturingContext, shiftId: string): Promise<Row>;
export declare function addCalendarException(client: any, context: ManufacturingContext, input?: Row): Promise<Row>;
export declare function removeCalendarException(client: any, context: ManufacturingContext, exceptionId: string): Promise<Row>;
export declare function listCalendars(client: any, context: ManufacturingContext): Promise<Row[]>;
export declare function listManufacturingShifts(client: any, context: ManufacturingContext): Promise<Row[]>;
export declare function listCalendarExceptions(client: any, context: ManufacturingContext): Promise<Row[]>;
export declare function saveWorkCenter(client: any, context: ManufacturingContext, input?: Row): Promise<Row>;
export declare function listWorkCenters(client: any, context: ManufacturingContext): Promise<Row[]>;
export declare function createRouting(client: any, context: ManufacturingContext, input?: Row): Promise<Row>;
export declare function updateDraftRouting(client: any, context: ManufacturingContext, routingId: string, input?: Row): Promise<Row>;
export declare function activateRouting(client: any, context: ManufacturingContext, routingId: string): Promise<Row>;
export declare function reviseRouting(client: any, context: ManufacturingContext, routingId: string): Promise<Row>;
export declare function obsoleteRouting(client: any, context: ManufacturingContext, routingId: string, reason?: string): Promise<Row>;
export declare function listRoutings(client: any, context: ManufacturingContext, options?: { status?: string | null }): Promise<Row[]>;
export declare function getRouting(client: any, context: ManufacturingContext, routingId: string): Promise<Row & { operations: Row[]; versions: Row[] }>;
export declare function getCapacityPlan(client: any, context: ManufacturingContext, options?: { from?: string | null; days?: number | string }): Promise<{ from: string; days: number; centers: Array<Record<string, any>> }>;
