apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: google-oauth-secrets
  namespace: vercentlabs
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/${GCP_PROJECT_ID}/secrets/${SECRET_PREFIX}-google-oauth-client-secret/versions/latest"
        path: "GOOGLE_OAUTH_CLIENT_SECRET"
