export const CRM_PERMISSIONS: Readonly<{
  view: "crm.view";
  recordsViewAll: "crm.records.view_all";
  leadsManage: "crm.leads.manage";
  opportunitiesManage: "crm.opportunities.manage";
  activitiesManage: "crm.activities.manage";
  campaignsManage: "crm.campaigns.manage";
  communicationsManage: "crm.communications.manage";
  automationManage: "crm.automation.manage";
  captureManage: "crm.capture.manage";
  import: "crm.import";
  export: "crm.export";
  reportsView: "crm.reports.view";
  settingsManage: "crm.settings.manage";
  revenueManage: "crm.revenue.manage";
  accountsManage: "crm.accounts.manage";
  playbooksManage: "crm.playbooks.manage";
  privacyManage: "crm.privacy.manage";
  dataQualityManage: "crm.data-quality.manage";
  integrationsManage: "crm.integrations.manage";
  aiManage: "crm.ai.manage";
  analyticsManage: "crm.analytics.manage";
  customizationManage: "crm.customization.manage";
  partnersManage: "crm.partners.manage";
  fieldSalesManage: "crm.field-sales.manage";
}>;
