export const HR_PAYROLL_PERMISSIONS = Object.freeze({
  view: "hr_payroll.view",
  employeeView: "hr_payroll.employee.view",
  employeeManage: "hr_payroll.employee.manage",
  sensitiveView: "hr_payroll.sensitive.view",
  attendanceManage: "hr_payroll.attendance.manage",
  shiftManage: "hr_payroll.shift.manage",
  leaveManage: "hr_payroll.leave.manage",
  leaveApprove: "hr_payroll.leave.approve",
  expenseManage: "hr_payroll.expense.manage",
  expenseApprove: "hr_payroll.expense.approve",
  payrollPrepare: "hr_payroll.payroll.prepare",
  payrollApprove: "hr_payroll.payroll.approve",
  payrollPost: "hr_payroll.payroll.post",
  payslipView: "hr_payroll.payslip.view",
  compensationManage: "hr_payroll.compensation.manage",
  statutoryManage: "hr_payroll.statutory.manage",
  reportsView: "hr_payroll.reports.view",
  settingsManage: "hr_payroll.settings.manage",
  auditView: "hr_payroll.audit.view",
});
