// Products and Services: the catalogue every module shares.
export const PRODUCT_PERMISSIONS = Object.freeze({
  view: "products.view",
  create: "products.create",
  edit: "products.edit",
  activate: "products.activate",
  delete: "products.delete",
  import: "products.import",
  export: "products.export",
  editTax: "products.edit_tax",
  editInventory: "products.edit_inventory",
  manageCategories: "products.manage_categories",
  deleteCategories: "products.delete_categories",
  reclassify: "products.reclassify",
  categoryInventoryDefaults: "products.category_inventory_defaults",
  categoryAccountingDefaults: "products.category_accounting_defaults",
  categoryTaxDefaults: "products.category_tax_defaults",
  manageUnits: "products.manage_units",
  manageIdentifiers: "products.manage_identifiers",
  configureTracking: "products.configure_tracking",
  configureAccounting: "products.configure_accounting",
  viewStock: "products.view_stock",
  viewCost: "products.view_cost",
  editCost: "products.edit_cost",
  generateSku: "products.generate_sku",
  enterSku: "products.enter_sku",
  changeSku: "products.change_sku",
  viewSkuHistory: "products.view_sku_history",
  configureSkuNumbering: "products.configure_sku_numbering",
  manageUomMaster: "products.manage_uom_master",
  changeUomConversions: "products.change_uom_conversions",
  changeDefaultUoms: "products.change_default_uoms",
});
