export const PROJECT_PERMISSIONS = Object.freeze({
  view: "projects.view",
  manage: "projects.manage",
  create: "projects.create",
  approve: "projects.approve",
  taskManage: "projects.tasks.manage",
  milestoneManage: "projects.milestones.manage",
  resourceManage: "projects.resources.manage",
  timeEnter: "projects.time.enter",
  timeApprove: "projects.time.approve",
  expenseEnter: "projects.expense.enter",
  expenseApprove: "projects.expense.approve",
  budgetManage: "projects.budget.manage",
  procurementLink: "projects.procurement.link",
  billingManage: "projects.billing.manage",
  profitabilityView: "projects.profitability.view",
  reportsView: "projects.reports.view",
  settingsManage: "projects.settings.manage",
  auditView: "projects.audit.view",
});
