type C = Record<string, unknown>;
type Q = unknown;
type R = Record<string, any>;
export declare function getSupportSettings(client: Q, c: C): Promise<any>;
export declare function saveSupportSettings(client: Q, c: C, input: R): Promise<any>;
export declare function listCategories(client: Q, c: C): Promise<any[]>;
export declare function saveCategory(client: Q, c: C, input: R): Promise<any>;
export declare function listQueues(client: Q, c: C): Promise<any[]>;
export declare function saveQueue(client: Q, c: C, input: R): Promise<any>;
export declare function listQueueMembers(client: Q, c: C, queueId: string): Promise<any[]>;
export declare function setQueueMember(client: Q, c: C, input: R): Promise<any>;
export declare function removeQueueMember(client: Q, c: C, queueId: string, userId: string): Promise<any>;
export declare function listRoutingRules(client: Q, c: C): Promise<any[]>;
export declare function saveRoutingRule(client: Q, c: C, input: R): Promise<any>;
export declare function deactivateRoutingRule(client: Q, c: C, id: string): Promise<any>;
export declare function listSlaPolicies(client: Q, c: C): Promise<any[]>;
export declare function saveSlaPolicy(client: Q, c: C, input: R): Promise<any>;
export declare function deactivateSlaPolicy(client: Q, c: C, id: string): Promise<any>;
export declare function listEscalationPolicies(client: Q, c: C): Promise<any[]>;
export declare function saveEscalationPolicy(client: Q, c: C, input: R): Promise<any>;
export declare function createTicket(client: Q, c: C, input: R, opts?: { portal?: boolean }): Promise<any>;
export declare function listTickets(client: Q, c: C, filters?: R): Promise<any[]>;
export declare function getTicket(client: Q, c: C, id: string, opts?: { forceCustomerId?: string }): Promise<any>;
export declare function updateTicket(client: Q, c: C, id: string, input: R): Promise<any>;
export declare function assignTicket(client: Q, c: C, id: string, input: R): Promise<any>;
export declare function transitionTicket(client: Q, c: C, id: string, input: R, opts?: { internal?: boolean }): Promise<any>;
export declare function mergeTickets(client: Q, c: C, input: R): Promise<any>;
export declare function listCommunications(client: Q, c: C, ticketId: string, opts?: { forceCustomerId?: string }): Promise<any[]>;
export declare function addCommunication(client: Q, c: C, ticketId: string, input: R, opts?: R): Promise<any>;
export declare function listAttachments(client: Q, c: C, ticketId: string, opts?: { forceCustomerId?: string }): Promise<any[]>;
export declare function addAttachment(client: Q, c: C, ticketId: string, input: { prepared: import("../../core/platform/files/index.js").PreparedUpload; privateNote?: boolean; communicationId?: string | null }, opts?: { forceCustomerId?: string; storage?: import("@vercentlabs/document-engine").ObjectStorage; purpose?: "attachment" | "inbound_mail"; communicationId?: string | null }): Promise<any>;
export declare function getAttachmentContent(client: Q, c: C, attachmentId: string, opts?: { forceCustomerId?: string; storage?: import("@vercentlabs/document-engine").ObjectStorage }): Promise<{ id: string; fileName: string; mimeType: string; sizeBytes: number; contentSha256: string | null; body: Buffer }>;
export declare function removeAttachment(client: Q, c: C, id: string): Promise<any>;
export declare function listEscalations(client: Q, c: C, filters?: R): Promise<any[]>;
export declare function escalateTicket(client: Q, c: C, ticketId: string, input: R): Promise<any>;
export declare function decideEscalation(client: Q, c: C, id: string, input: R): Promise<any>;
export declare function checkSlaBreaches(client: Q, c: C): Promise<{ raised: number }>;
export declare function getTicketHistory(client: Q, c: C, ticketId: string): Promise<any>;
