import type { QueryClient } from "../../index.js";
export type AccountingContext = { organizationId: string; userId: string; permissions: string[]; roleSlugs: string[] };
export class AccountingError extends Error { readonly status: number; readonly code: string; constructor(status: number, message: string, code?: string); }
export type AccountingRecord = Record<string, unknown>;
export function getAccountingDashboard(client: QueryClient, context: AccountingContext, filters?: AccountingRecord): Promise<AccountingRecord>;
export function getAccountingOptions(client: QueryClient, context: AccountingContext): Promise<AccountingRecord>;
export function getAccountingSettings(client: QueryClient, context: AccountingContext): Promise<AccountingRecord>;
export function updateAccountingSettings(client: QueryClient, context: AccountingContext, input: AccountingRecord): Promise<AccountingRecord>;
export function createAccountingAccount(client: QueryClient, context: AccountingContext, input: AccountingRecord): Promise<AccountingRecord>;
export function upsertAccountMapping(client: QueryClient, context: AccountingContext, input: AccountingRecord): Promise<AccountingRecord>;
export function listJournalEntries(client: QueryClient, context: AccountingContext, filters?: AccountingRecord): Promise<AccountingRecord[]>;
export function getJournalEntry(client: QueryClient, context: AccountingContext, id: string): Promise<{ entry: AccountingRecord; lines: AccountingRecord[]; events: AccountingRecord[] }>;
export function createJournalEntry(client: QueryClient, context: AccountingContext, input: AccountingRecord, options?: AccountingRecord): Promise<{ entry: AccountingRecord; lines: AccountingRecord[] }>;
export function submitJournalEntry(client: QueryClient, context: AccountingContext, id: string, assignedTo?: string | null): Promise<AccountingRecord>;
export function approveJournalEntry(client: QueryClient, context: AccountingContext, id: string, contentHash: string): Promise<AccountingRecord>;
export function rejectJournalApproval(client: QueryClient, context: AccountingContext, id: string): Promise<AccountingRecord>;
export function postJournalEntry(client: QueryClient, context: AccountingContext, id: string, options?: AccountingRecord): Promise<AccountingRecord>;
export function reverseJournalEntry(client: QueryClient, context: AccountingContext, id: string, input?: AccountingRecord): Promise<AccountingRecord>;
export function listCustomerInvoices(client: QueryClient, context: AccountingContext, filters?: AccountingRecord): Promise<AccountingRecord[]>;
export function getCustomerInvoice(client: QueryClient, context: AccountingContext, id: string): Promise<AccountingRecord>;
export function createCustomerInvoice(client: QueryClient, context: AccountingContext, input: AccountingRecord, options?: AccountingRecord): Promise<AccountingRecord>;
export function replaceCustomerInvoiceDraft(client: QueryClient, context: AccountingContext, invoiceId: string, input: AccountingRecord, options?: { internal?: boolean }): Promise<{ lineIds: string[]; dueDate: string }>;
export function cancelCustomerInvoiceDraft(client: QueryClient, context: AccountingContext, invoiceId: string, input?: { reason?: string | null }, options?: { internal?: boolean }): Promise<{ id: string; status: string; changed: boolean }>;
export function reverseCustomerInvoice(client: QueryClient, context: AccountingContext, invoiceId: string, input: { reason: string; accountingDate?: string }, options?: { internal?: boolean }): Promise<{ id: string; status: string; changed: boolean; reversalEntryId?: string }>;
export function submitCustomerInvoice(client: QueryClient, context: AccountingContext, id: string, assignedTo?: string | null): Promise<AccountingRecord>;
export function approveCustomerInvoice(client: QueryClient, context: AccountingContext, id: string, contentHash: string): Promise<AccountingRecord>;
export function rejectCustomerInvoiceApproval(client: QueryClient, context: AccountingContext, id: string): Promise<AccountingRecord>;
export function postCustomerInvoice(client: QueryClient, context: AccountingContext, id: string): Promise<AccountingRecord>;
export function applyCustomerCreditNote(client: QueryClient, context: AccountingContext, id: string, input: AccountingRecord): Promise<AccountingRecord>;
export function createCustomerReceipt(client: QueryClient, context: AccountingContext, input: AccountingRecord): Promise<AccountingRecord>;
export function postCustomerReceipt(client: QueryClient, context: AccountingContext, id: string): Promise<AccountingRecord>;
export function allocateCustomerReceipt(client: QueryClient, context: AccountingContext, id: string, input: AccountingRecord): Promise<AccountingRecord>;
export function listVendorBills(client: QueryClient, context: AccountingContext, filters?: AccountingRecord): Promise<AccountingRecord[]>;
export function getVendorBill(client: QueryClient, context: AccountingContext, id: string): Promise<AccountingRecord>;
export function createVendorBill(client: QueryClient, context: AccountingContext, input: AccountingRecord): Promise<AccountingRecord>;
export function submitVendorBill(client: QueryClient, context: AccountingContext, id: string, assignedTo?: string | null): Promise<AccountingRecord>;
export function approveVendorBill(client: QueryClient, context: AccountingContext, id: string, contentHash: string): Promise<AccountingRecord>;
export function rejectVendorBillApproval(client: QueryClient, context: AccountingContext, id: string): Promise<AccountingRecord>;
export function postVendorBill(client: QueryClient, context: AccountingContext, id: string): Promise<AccountingRecord>;
export function applyVendorCreditNote(client: QueryClient, context: AccountingContext, id: string, input: AccountingRecord): Promise<AccountingRecord>;
export function createVendorPayment(client: QueryClient, context: AccountingContext, input: AccountingRecord): Promise<AccountingRecord>;
export function submitVendorPayment(client: QueryClient, context: AccountingContext, id: string, assignedTo?: string | null): Promise<AccountingRecord>;
export function approveVendorPayment(client: QueryClient, context: AccountingContext, id: string, contentHash: string): Promise<AccountingRecord>;
export function rejectVendorPaymentApproval(client: QueryClient, context: AccountingContext, id: string): Promise<AccountingRecord>;
export function postVendorPayment(client: QueryClient, context: AccountingContext, id: string): Promise<AccountingRecord>;
export function allocateVendorPayment(client: QueryClient, context: AccountingContext, id: string, input: AccountingRecord): Promise<AccountingRecord>;
export function listBankAccounts(client: QueryClient, context: AccountingContext): Promise<AccountingRecord[]>;
export function createBankAccount(client: QueryClient, context: AccountingContext, input: AccountingRecord): Promise<AccountingRecord>;
export function importBankStatement(client: QueryClient, context: AccountingContext, input: AccountingRecord): Promise<AccountingRecord>;
export function listBankStatements(client: QueryClient, context: AccountingContext, filters?: AccountingRecord): Promise<AccountingRecord[]>;
export function getBankStatement(client: QueryClient, context: AccountingContext, id: string): Promise<AccountingRecord>;
export function suggestBankMatches(client: QueryClient, context: AccountingContext, statementLineId: string): Promise<AccountingRecord[]>;
export function startBankReconciliation(client: QueryClient, context: AccountingContext, input: AccountingRecord): Promise<AccountingRecord>;
export function matchBankStatementLine(client: QueryClient, context: AccountingContext, reconciliationId: string, input: AccountingRecord): Promise<AccountingRecord>;
export function completeBankReconciliation(client: QueryClient, context: AccountingContext, reconciliationId: string): Promise<AccountingRecord>;
export function listFiscalPeriods(client: QueryClient, context: AccountingContext, filters?: AccountingRecord): Promise<AccountingRecord[]>;
export function getPeriodCloseBlockers(client: QueryClient, context: AccountingContext, periodId: string): Promise<AccountingRecord[]>;
export function updateFiscalPeriodStatus(client: QueryClient, context: AccountingContext, id: string, input: AccountingRecord): Promise<AccountingRecord>;
export function createCloseRun(client: QueryClient, context: AccountingContext, input: AccountingRecord): Promise<AccountingRecord>;
export function listCloseRuns(client: QueryClient, context: AccountingContext): Promise<AccountingRecord[]>;
export function getCloseRun(client: QueryClient, context: AccountingContext, id: string): Promise<AccountingRecord>;
export function updateCloseTask(client: QueryClient, context: AccountingContext, runId: string, taskId: string, input: AccountingRecord): Promise<AccountingRecord>;
export function completeCloseRun(client: QueryClient, context: AccountingContext, id: string, input?: AccountingRecord): Promise<AccountingRecord>;
export function getAccountingReport(client: QueryClient, context: AccountingContext, reportKey: string, filters?: AccountingRecord): Promise<AccountingRecord[]>;
export function initializeAccountingOrganization(
  client: QueryClient,
  input: { organizationId: string; userId: string },
): Promise<{ ledgerId: string; accountCount: number }>;
export function getVendorBillMatch(client: QueryClient, context: AccountingContext, id: string): Promise<AccountingRecord | null>;
export function evaluateVendorBillMatch(client: QueryClient, context: AccountingContext, id: string, input?: AccountingRecord): Promise<AccountingRecord>;
export function overrideVendorBillMatch(client: QueryClient, context: AccountingContext, id: string, input?: AccountingRecord): Promise<AccountingRecord>;
export function allocateInstallments(total: string | number, termLines: AccountingRecord[], precision?: number): AccountingRecord[];

export function calculateSettlementBaseAmounts(client: QueryClient, context: AccountingContext, input: AccountingRecord): Promise<AccountingRecord>;
export function createCustomerSettlementAdjustment(client: QueryClient, context: AccountingContext, input: AccountingRecord): Promise<AccountingRecord>;
export function createVendorSettlementAdjustment(client: QueryClient, context: AccountingContext, input: AccountingRecord): Promise<AccountingRecord>;
export function reverseCustomerCreditNote(client: QueryClient, context: AccountingContext, id: string, input: { reason: string; accountingDate?: string }, options?: { internal?: boolean }): Promise<AccountingRecord>;
export function changeCustomerInvoiceDueDate(client: QueryClient, context: AccountingContext, id: string, input: { dueDate: string; reason: string }, options?: { internal?: boolean }): Promise<AccountingRecord>;
export * from "./refunds/index.js";
export function resolvePaymentSchedule(client: QueryClient, context: AccountingContext, options: AccountingRecord): Promise<AccountingRecord>;
export declare function recordVendorCreditRefund(client: any, context: any, ...args: any[]): Promise<any>;
export declare function reverseVendorCreditRefund(client: any, context: any, ...args: any[]): Promise<any>;
export declare function unapplyVendorCreditNote(client: any, context: any, ...args: any[]): Promise<any>;
export declare function reverseVendorCreditNote(client: any, context: any, ...args: any[]): Promise<any>;
export declare function reduceBillSchedules(client: any, context: any, ...args: any[]): Promise<any>;
export declare function restoreBillSchedules(client: any, context: any, ...args: any[]): Promise<any>;
