// Plain data (no components) so a Server Component page can read it.
export const ACCOUNTING_PAGES: Record<string, { title: string }> = {
  "chart-of-accounts": { title: "Chart of accounts" },
  journals: { title: "Journal entries" },
  "journal-new": { title: "New journal entry" },
  "customer-invoices": { title: "Customer invoices" },
  "invoice-new": { title: "New customer invoice" },
  receipts: { title: "Customer receipts" },
  "supplier-invoices": { title: "Supplier bills" },
  "bill-new": { title: "New supplier bill" },
  payments: { title: "Supplier payments" },
  "bank-accounts": { title: "Bank accounts" },
  "bank-transactions": { title: "Bank statements" },
  gst: { title: "Tax returns" },
  budgets: { title: "Budgets" },
  accruals: { title: "Accruals" },
  fx: { title: "Revaluation runs" },
  intercompany: { title: "Intercompany rules" },
  consolidation: { title: "Consolidation groups" },
  "fiscal-periods": { title: "Fiscal periods" },
  "period-close": { title: "Period close" },
  "close-checklist": { title: "Close runs" },
  assets: { title: "Fixed assets" },
  "trial-balance": { title: "Trial balance" },
  "profit-loss": { title: "Profit and loss" },
  "balance-sheet": { title: "Balance sheet" },
  "cash-flow": { title: "Cash flow" },
  "general-ledger": { title: "General ledger" },
  "ar-aging": { title: "Receivables aging" },
  "ap-aging": { title: "Payables aging" },
  "tax-reports": { title: "Tax summary" },
  "statutory-reports": { title: "Subledger reconciliation" },
  "budget-actual": { title: "Budget vs actual" },
  reconciliation: { title: "Bank reconciliation" },
  prepayments: { title: "Prepayments" },
  "revenue-schedules": { title: "Revenue schedules" },
};
