// Plain data (no components) so a Server Component page can read it.
export const ACCOUNTING_PAGES: Record<string, { title: string }> = {
  "chart-of-accounts": { title: "Chart of accounts" },
  journals: { title: "Journal entries" },
  "journal-new": { title: "New journal entry" },
  "customer-invoices": { title: "Customer invoices" },
  "invoice-new": { title: "New customer invoice" },
  receipts: { title: "Customer receipts" },
  "supplier-invoices": { title: "Supplier bills" },
  "bill-new": { title: "New supplier bill" },
  payments: { title: "Supplier payments" },
  "bank-accounts": { title: "Bank accounts" },
  "bank-transactions": { title: "Bank statements" },
  "fiscal-periods": { title: "Fiscal periods" },
  "close-checklist": { title: "Close runs" },
  "trial-balance": { title: "Trial balance" },
  "profit-loss": { title: "Profit and loss" },
  "balance-sheet": { title: "Balance sheet" },
  "general-ledger": { title: "General ledger" },
  reconciliation: { title: "Bank reconciliation" },
};
