/** Canonical 510-register feature slice for this module. Requirement IDs are permanent evidence identifiers, not source-folder names. */
export const SALES_FEATURES = Object.freeze([
  ["F031", "Customer master"],
  ["F032", "Customer addresses and contacts"],
  ["F033", "Products and services"],
  ["F034", "Price lists"],
  ["F035", "Customer-specific prices"],
  ["F036", "Quotations"],
  ["F037", "Quotation versions and revisions"],
  ["F038", "Quotation expiry"],
  ["F039", "Discounts"],
  ["F040", "Taxes"],
  ["F041", "Approval workflow"],
  ["F042", "Sales orders"],
  ["F043", "Order confirmation"],
  ["F044", "Order amendments"],
  ["F045", "Availability check"],
  ["F046", "Stock reservation"],
  ["F047", "Partial fulfilment"],
  ["F048", "Backorders"],
  ["F049", "Delivery and shipment"],
  ["F050", "Sales invoices"],
  ["F051", "Partial invoicing"],
  ["F052", "Advance payments"],
  ["F053", "Credit limits"],
  ["F054", "Customer returns"],
  ["F055", "Credit notes and refunds"],
  ["F056", "Drop shipping"],
  ["F057", "Sales commissions"],
  ["F058", "Payment terms"],
  ["F059", "Order status tracking"],
  ["F060", "Sales analytics"],
  ["F061", "Margin and profitability"],
  ["F062", "Order-to-cash reporting"],
] as const);

export type SalesFeatureId = (typeof SALES_FEATURES)[number][0];
