"use client";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";

type OptionRow = Record<string, string | number | boolean | null>;
type Options = { companies: OptionRow[]; branches: OptionRow[]; parties: OptionRow[]; contacts: OptionRow[]; addresses: OptionRow[]; items: OptionRow[]; uoms: OptionRow[]; warehouses: OptionRow[]; priceLists: OptionRow[]; paymentTerms: OptionRow[]; currencies: OptionRow[]; users: OptionRow[]; opportunities: OptionRow[]; opportunityItems: OptionRow[] };
type SalesPreview = { totals: { subtotal: unknown; discountTotal: unknown; taxTotal: unknown; grandTotal: unknown } };
type Line = { itemId: string; uomId: string; warehouseId: string; description: string; quantity: string; unitPrice: string; discountPercent: string; requestedDeliveryDate: string; manualPriceReason: string };
const emptyLine = (): Line => ({ itemId:"",uomId:"",warehouseId:"",description:"",quantity:"1",unitPrice:"",discountPercent:"0",requestedDeliveryDate:"",manualPriceReason:"" });
const iso = (days=0) => { const d=new Date();d.setDate(d.getDate()+days);return d.toISOString().slice(0,10); };
export default function SalesDocumentEditor({ mode, opportunityId }: { mode: "quotation"|"order"; opportunityId?: string }) {
  const router=useRouter(); const [options,setOptions]=useState<Options|null>(null); const [pending,setPending]=useState(false); const [message,setMessage]=useState(""); const [preview,setPreview]=useState<SalesPreview|null>(null);
  const [form,setForm]=useState({companyId:"",branchId:"",partyId:"",contactId:"",ownerUserId:"",currencyCode:"",exchangeRate:"1",priceListId:"",paymentTermId:"",billingAddressId:"",shippingAddressId:"",validUntil:iso(15),requestedDeliveryDate:"",customerPoNumber:"",customerPoDate:"",priority:"normal",deliveryTerms:"",shippingMethod:"",incoterm:"",placeOfSupply:"",supplyType:"domestic",customerNotes:"",internalNotes:"",termsAndConditions:""});
  const [lines,setLines]=useState<Line[]>([emptyLine()]);
  useEffect(()=>{ fetch(`/api/sales/options${opportunityId?`?opportunityId=${encodeURIComponent(opportunityId)}`:""}`,{cache:"no-store"}).then(r=>r.json()).then(data=>{if(!data.ok)throw new Error(data.message);const value=data.options as Options;setOptions(value);const opportunity=value.opportunities[0];const company=opportunity?.company_id||value.companies[0]?.id||"";const party=opportunity?.party_id||value.parties[0]?.id||"";const currency=opportunity?.currency_code||value.currencies[0]?.code||"";setForm(current=>({...current,companyId:String(company),branchId:String(opportunity?.branch_id||""),partyId:String(party),contactId:String(opportunity?.contact_id||""),ownerUserId:String(opportunity?.owner_user_id||value.users[0]?.id||""),currencyCode:String(currency),priceListId:String(value.opportunityItems[0]?.price_list_id||value.priceLists.find(p=>p.currency_code===currency)?.id||""),paymentTermId:String(value.parties.find(p=>p.id===party)?.payment_term_id||value.paymentTerms[0]?.id||"")}));if(value.opportunityItems.length)setLines(value.opportunityItems.map(item=>({itemId:String(item.item_id),uomId:String(item.uom_id||""),warehouseId:"",description:String(item.description||""),quantity:String(item.quantity||1),unitPrice:String(item.unit_price||""),discountPercent:String(item.discount_percent||0),requestedDeliveryDate:"",manualPriceReason:"Imported from CRM opportunity"})));}).catch(error=>setMessage(error.message)); },[opportunityId]);
  const partyContacts=useMemo(()=>options?.contacts.filter(c=>c.party_id===form.partyId)||[],[options,form.partyId]); const partyAddresses=useMemo(()=>options?.addresses.filter(a=>a.party_id===form.partyId)||[],[options,form.partyId]); const companyBranches=useMemo(()=>options?.branches.filter(b=>b.company_id===form.companyId)||[],[options,form.companyId]); const companyWarehouses=useMemo(()=>options?.warehouses.filter(w=>w.company_id===form.companyId)||[],[options,form.companyId]);
  function updateLine(index:number,key:keyof Line,value:string){setLines(current=>current.map((line,i)=>i===index?{...line,[key]:value}:line));}
  function itemChanged(index:number,itemId:string){const item=options?.items.find(row=>row.id===itemId);setLines(current=>current.map((line,i)=>i===index?{...line,itemId,uomId:String(item?.uom_id||""),description:String(item?.description||""),unitPrice:""}:line));}
  const payload=()=>({ ...form, opportunityId:opportunityId||null, branchId:form.branchId||null,contactId:form.contactId||null,ownerUserId:form.ownerUserId||null,priceListId:form.priceListId||null,paymentTermId:form.paymentTermId||null,billingAddressId:form.billingAddressId||null,shippingAddressId:form.shippingAddressId||null,requestedDeliveryDate:form.requestedDeliveryDate||null,customerPoDate:form.customerPoDate||null,lines:lines.map(line=>({...line,uomId:line.uomId||null,warehouseId:line.warehouseId||null,unitPrice:line.unitPrice||null,requestedDeliveryDate:line.requestedDeliveryDate||null,manualPriceReason:line.manualPriceReason||null})),charges:[] });
  async function previewDocument(){setPending(true);setMessage("");try{const response=await fetch("/api/sales/pricing/preview",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload())});const data=await response.json();if(!data.ok)throw new Error(data.message);setPreview(data.preview as SalesPreview);}catch(error){setMessage(error instanceof Error?error.message:"Preview failed.");}finally{setPending(false);}}
  async function save(){setPending(true);setMessage("");try{const endpoint=mode==="quotation"?"/api/sales/quotations":"/api/sales/orders";const response=await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload())});const data=await response.json();if(!data.ok)throw new Error(data.message);router.push(mode==="quotation"?`/sales/quotations/${data.quotation.id}`:`/sales/orders/${data.order.id}`);router.refresh();}catch(error){setMessage(error instanceof Error?error.message:"Save failed.");}finally{setPending(false);}}
  if(!options)return <section className="panel"><p>{message||"Loading Sales master data…"}</p></section>;
  return <div className="sales-editor">
    {message?<div className="form-message error" role="alert">{message}</div>:null}
    <section className="panel sales-editor-header"><div><p className="eyebrow">Commercial context</p><h2>{mode==="quotation"?"Quotation header":"Sales order header"}</h2></div><div className="sales-form-grid">
      <label>Company<select value={form.companyId} onChange={e=>setForm({...form,companyId:e.target.value,branchId:""})}>{options.companies.map(o=><option key={String(o.id)} value={String(o.id)}>{String(o.name)}</option>)}</select></label>
      <label>Branch<select value={form.branchId} onChange={e=>setForm({...form,branchId:e.target.value})}><option value="">No branch</option>{companyBranches.map(o=><option key={String(o.id)} value={String(o.id)}>{String(o.name)}</option>)}</select></label>
      <label>Customer<select value={form.partyId} onChange={e=>setForm({...form,partyId:e.target.value,contactId:"",billingAddressId:"",shippingAddressId:""})}>{options.parties.map(o=><option key={String(o.id)} value={String(o.id)}>{String(o.display_name)} · {String(o.party_type)}</option>)}</select></label>
      <label>Contact<select value={form.contactId} onChange={e=>setForm({...form,contactId:e.target.value})}><option value="">No contact</option>{partyContacts.map(o=><option key={String(o.id)} value={String(o.id)}>{String(o.first_name)} {String(o.last_name||"")}</option>)}</select></label>
      <label>Currency<select value={form.currencyCode} onChange={e=>setForm({...form,currencyCode:e.target.value,priceListId:""})}>{options.currencies.map(o=><option key={String(o.code)} value={String(o.code)}>{String(o.code)} · {String(o.name)}</option>)}</select></label>
      <label>Exchange rate<input value={form.exchangeRate} onChange={e=>setForm({...form,exchangeRate:e.target.value})}/></label>
      <label>Price list<select value={form.priceListId} onChange={e=>setForm({...form,priceListId:e.target.value})}><option value="">Item default prices</option>{options.priceLists.filter(o=>o.currency_code===form.currencyCode).map(o=><option key={String(o.id)} value={String(o.id)}>{String(o.name)}</option>)}</select></label>
      <label>Payment term<select value={form.paymentTermId} onChange={e=>setForm({...form,paymentTermId:e.target.value})}><option value="">Customer default</option>{options.paymentTerms.map(o=><option key={String(o.id)} value={String(o.id)}>{String(o.name)}</option>)}</select></label>
      <label>Billing address<select value={form.billingAddressId} onChange={e=>setForm({...form,billingAddressId:e.target.value})}><option value="">No address</option>{partyAddresses.map(o=><option key={String(o.id)} value={String(o.id)}>{String(o.address_type)} · {String(o.line1)}, {String(o.city)}</option>)}</select></label>
      <label>Shipping address<select value={form.shippingAddressId} onChange={e=>setForm({...form,shippingAddressId:e.target.value})}><option value="">No address</option>{partyAddresses.map(o=><option key={String(o.id)} value={String(o.id)}>{String(o.address_type)} · {String(o.line1)}, {String(o.city)}</option>)}</select></label>
      {mode==="quotation"?<label>Valid until<input type="date" value={form.validUntil} onChange={e=>setForm({...form,validUntil:e.target.value})}/></label>:<><label>Requested delivery<input type="date" value={form.requestedDeliveryDate} onChange={e=>setForm({...form,requestedDeliveryDate:e.target.value})}/></label><label>Customer PO<input value={form.customerPoNumber} onChange={e=>setForm({...form,customerPoNumber:e.target.value})}/></label></>}
      <label>Place of supply<input value={form.placeOfSupply} onChange={e=>setForm({...form,placeOfSupply:e.target.value.toUpperCase()})} placeholder="State code"/></label>
    </div></section>
    <section className="panel"><div className="sales-section-title"><div><p className="eyebrow">Line editor</p><h2>Products and services</h2></div><button className="secondary-button" type="button" onClick={()=>setLines([...lines,emptyLine()])}>Add line</button></div><div className="sales-line-table"><div className="sales-line-row sales-line-head"><span>Item</span><span>Qty</span><span>UOM</span><span>Unit price</span><span>Discount %</span><span>Warehouse</span><span/></div>{lines.map((line,index)=><div className="sales-line-row" key={index}><select aria-label={`Line ${index+1} item`} value={line.itemId} onChange={e=>itemChanged(index,e.target.value)}><option value="">Select item</option>{options.items.filter(i=>!i.company_id||i.company_id===form.companyId).map(o=><option key={String(o.id)} value={String(o.id)}>{String(o.code)} · {String(o.name)}</option>)}</select><input aria-label={`Line ${index+1} quantity`} value={line.quantity} onChange={e=>updateLine(index,"quantity",e.target.value)}/><select aria-label={`Line ${index+1} UOM`} value={line.uomId} onChange={e=>updateLine(index,"uomId",e.target.value)}>{options.uoms.map(o=><option key={String(o.id)} value={String(o.id)}>{String(o.code)}</option>)}</select><input aria-label={`Line ${index+1} unit price`} value={line.unitPrice} placeholder="Calculated" onChange={e=>updateLine(index,"unitPrice",e.target.value)}/><input aria-label={`Line ${index+1} discount`} value={line.discountPercent} onChange={e=>updateLine(index,"discountPercent",e.target.value)}/><select aria-label={`Line ${index+1} warehouse`} value={line.warehouseId} onChange={e=>updateLine(index,"warehouseId",e.target.value)}><option value="">Not selected</option>{companyWarehouses.map(o=><option key={String(o.id)} value={String(o.id)}>{String(o.name)}</option>)}</select><button className="link-button danger" type="button" onClick={()=>setLines(lines.filter((_,i)=>i!==index))} disabled={lines.length===1}>Remove</button><textarea className="sales-line-description" value={line.description} onChange={e=>updateLine(index,"description",e.target.value)} placeholder="Customer-facing line description"/><input className="sales-line-reason" value={line.manualPriceReason} onChange={e=>updateLine(index,"manualPriceReason",e.target.value)} placeholder="Required when overriding calculated price"/></div>)}</div></section>
    <section className="sales-editor-footer"><div className="panel sales-notes"><label>Customer notes<textarea value={form.customerNotes} onChange={e=>setForm({...form,customerNotes:e.target.value})}/></label><label>Terms and conditions<textarea value={form.termsAndConditions} onChange={e=>setForm({...form,termsAndConditions:e.target.value})}/></label></div><aside className="panel sales-summary"><p className="eyebrow">Commercial summary</p>{preview?<dl><div><dt>Subtotal</dt><dd>{String(preview.totals.subtotal)}</dd></div><div><dt>Discount</dt><dd>{String(preview.totals.discountTotal)}</dd></div><div><dt>Tax</dt><dd>{String(preview.totals.taxTotal)}</dd></div><div><dt>Grand total</dt><dd><strong>{form.currencyCode} {String(preview.totals.grandTotal)}</strong></dd></div></dl>:<p>Preview to validate pricing, tax and margin controls on the server.</p>}<div className="sales-actions"><button className="secondary-button" type="button" onClick={previewDocument} disabled={pending}>Preview</button><button className="primary-button" type="button" onClick={save} disabled={pending}>{pending?"Working…":mode==="quotation"?"Create quotation":"Create sales order"}</button></div></aside></section>
  </div>;
}
