// Supplier Debit Notes & Vendor Credits.
export declare const DEBIT_CLAIM_STATUS_LABELS: any;
export declare const VENDOR_CREDIT_ORIGINS: any;
export declare const VENDOR_CREDIT_REASONS: any;
export declare const VENDOR_CREDIT_TAX_TREATMENTS: any;
export declare const VENDOR_CREDIT_PERMISSIONS: any;
export declare const VENDOR_CREDIT_VIEWS: any;
export declare function closeSupplierDebitClaim(client: any, context: any, ...args: any[]): Promise<any>;
export declare function createSupplierDebitClaim(client: any, context: any, ...args: any[]): Promise<any>;
export declare function getOpenSupplierClaims(client: any, context: any, ...args: any[]): Promise<any>;
export declare function getSupplierDebitClaim(client: any, context: any, ...args: any[]): Promise<any>;
export declare function getSupplierDebitClaims(client: any, context: any, ...args: any[]): Promise<any>;
export declare function issueDebitClaim(client: any, context: any, ...args: any[]): Promise<any>;
export declare function recordPartialClaimAcceptance(client: any, context: any, ...args: any[]): Promise<any>;
export declare function recordSupplierClaimResponse(client: any, context: any, ...args: any[]): Promise<any>;
export declare function updateDraftDebitClaim(client: any, context: any, ...args: any[]): Promise<any>;
export declare function approveVendorCredit(client: any, context: any, ...args: any[]): Promise<any>;
export declare function calculateAvailableCreditEntitlement(client: any, context: any, ...args: any[]): Promise<any>;
export declare function calculateVendorCreditTaxes(client: any, context: any, ...args: any[]): Promise<any>;
export declare function calculateVendorCreditTotals(client: any, context: any, ...args: any[]): Promise<any>;
export declare function cancelDraftVendorCredit(client: any, context: any, ...args: any[]): Promise<any>;
export declare function checkDuplicateSupplierCreditNote(client: any, context: any, ...args: any[]): Promise<any>;
export declare function createCreditFromAcceptedClaim(client: any, context: any, ...args: any[]): Promise<any>;
export declare function createCreditFromPurchaseReturn(client: any, context: any, ...args: any[]): Promise<any>;
export declare function createCreditFromSupplierBill(client: any, context: any, ...args: any[]): Promise<any>;
export declare function createVendorCredit(client: any, context: any, ...args: any[]): Promise<any>;
export declare function postVendorCredit(client: any, context: any, ...args: any[]): Promise<any>;
export declare function reverseVendorCredit(client: any, context: any, ...args: any[]): Promise<any>;
export declare function updateDraftVendorCredit(client: any, context: any, ...args: any[]): Promise<any>;
export declare function validatePurchaseReturnCreditEligibility(client: any, context: any, ...args: any[]): Promise<any>;
export declare function validateSupplierCreditNote(client: any, context: any, ...args: any[]): Promise<any>;
export declare function validateVendorCreditForPosting(client: any, context: any, ...args: any[]): Promise<any>;
export declare function validateVendorCreditQuantities(client: any, context: any, ...args: any[]): Promise<any>;
export declare function validateVendorCreditSource(client: any, context: any, ...args: any[]): Promise<any>;
export declare function allocateVendorCreditToBills(client: any, context: any, ...args: any[]): Promise<any>;
export declare function getSupplierCreditBalance(client: any, context: any, ...args: any[]): Promise<any>;
export declare function getVendorCreditAllocations(client: any, context: any, ...args: any[]): Promise<any>;
export declare function getVendorCreditAvailableBalance(client: any, context: any, ...args: any[]): Promise<any>;
export declare function getVendorCreditRefunds(client: any, context: any, ...args: any[]): Promise<any>;
export declare function recordSupplierRefund(client: any, context: any, ...args: any[]): Promise<any>;
export declare function reverseSupplierRefund(client: any, context: any, ...args: any[]): Promise<any>;
export declare function unapplyVendorCredit(client: any, context: any, ...args: any[]): Promise<any>;
export declare function getPurchaseReturnCreditProgress(client: any, context: any, ...args: any[]): Promise<any>;
export declare function getSupplierBillCreditSummary(client: any, context: any, ...args: any[]): Promise<any>;
export declare function getSupplierCreditStatement(client: any, context: any, ...args: any[]): Promise<any>;
export declare function getVendorCredit(client: any, context: any, ...args: any[]): Promise<any>;
export declare function getVendorCreditOptions(client: any, context: any, ...args: any[]): Promise<any>;
export declare function getVendorCredits(client: any, context: any, ...args: any[]): Promise<any>;
export declare function listDebitNotesAndCredits(client: any, context: any, ...args: any[]): Promise<any>;
