import { createHash } from "node:crypto";
import { allocate, decimal, format } from "./money.js";
export class ProcurementError extends Error { constructor(status,message,code="PROCUREMENT_ERROR"){ super(message); this.name="ProcurementError"; this.status=status; this.code=code; } }
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const TABLES=Object.freeze({
  suppliers:"procurement_suppliers", categories:"procurement_categories", catalogs:"procurement_catalogs",
  requisitions:"procurement_requisitions", "sourcing-events":"procurement_sourcing_events",
  agreements:"procurement_agreements", "purchase-orders":"procurement_purchase_orders",
  receipts:"procurement_receipts", "service-entries":"procurement_service_entries",
  returns:"procurement_returns", "match-exceptions":"procurement_match_exceptions"
});
function permission(context,key){ if(!(context.roleSlugs||[]).includes("organization_owner") && !(context.permissions||[]).includes(key)) throw new ProcurementError(403,"You do not have permission to perform this action."); }
function id(value,label="Record"){ if(!UUID.test(String(value||""))) throw new ProcurementError(400,`${label} is invalid.`); return String(value); }
function stable(value){ if(Array.isArray(value)) return `[${value.map(stable).join(",")}]`; if(value&&typeof value==="object") return `{${Object.keys(value).sort().map(k=>`${JSON.stringify(k)}:${stable(value[k])}`).join(",")}}`; return JSON.stringify(value); }
export function contentHash(value){ return createHash("sha256").update(stable(value)).digest("hex"); }
export function procurementContext(session){ return { organizationId:session.organizationId, userId:session.userId, activeCompanyId:session.activeCompanyId||null, activeBranchId:session.activeBranchId||null, allowAllCompanies:(session.roleSlugs||[]).some(v=>["organization_owner","system_administrator"].includes(v)), permissions:session.permissions||[], roleSlugs:session.roleSlugs||[] }; }
export async function listProcurementRecords(client,context,resource,filters={}){ permission(context,"procurement.view"); const table=TABLES[resource]; if(!table) throw new ProcurementError(404,"Unknown Procurement resource."); const limit=Math.min(Math.max(Number(filters.limit||50),1),200); const offset=Math.max(Number(filters.offset||0),0); const values=[context.organizationId]; let where="organization_id=$1"; if(filters.status){values.push(String(filters.status));where+=` AND status=$${values.length}`;} if(filters.search){values.push(`%${String(filters.search).trim()}%`);where+=` AND search_text ILIKE $${values.length}`;} const count=await client.query(`SELECT count(*)::int AS total FROM tenant.${table} WHERE ${where}`,values); const rows=await client.query(`SELECT * FROM tenant.${table} WHERE ${where} ORDER BY updated_at DESC,id DESC LIMIT ${limit} OFFSET ${offset}`,values); return {rows:rows.rows,total:Number(count.rows[0]?.total||0),limit,offset}; }
export async function getProcurementRecord(client,context,resource,recordId){ permission(context,"procurement.view"); const table=TABLES[resource]; if(!table) throw new ProcurementError(404,"Unknown Procurement resource."); const result=await client.query(`SELECT * FROM tenant.${table} WHERE organization_id=$1 AND id=$2`,[context.organizationId,id(recordId)]); if(!result.rows[0]) throw new ProcurementError(404,"Procurement record not found."); return result.rows[0]; }
export async function createProcurementRecord(client,context,resource,input){ const table=TABLES[resource]; if(!table) throw new ProcurementError(404,"Unknown Procurement resource."); const permissionKey=resource==="requisitions"?"procurement.requisition.create":resource==="purchase-orders"?"procurement.po.create":"procurement.settings.manage"; permission(context,permissionKey); const companyId=input.companyId||context.activeCompanyId; if(!companyId) throw new ProcurementError(409,"Select an active company."); const payload={...input,companyId,branchId:input.branchId||context.activeBranchId||null}; const result=await client.query(`INSERT INTO tenant.${table}(organization_id,company_id,branch_id,status,search_text,data,content_hash,created_by,updated_by) VALUES($1,$2,$3,'draft',$4,$5::jsonb,$6,$7,$7) RETURNING *`,[context.organizationId,id(companyId,"Company"),payload.branchId?id(payload.branchId,"Branch"):null,String(input.name||input.title||input.number||resource),JSON.stringify(payload),contentHash(payload),context.userId]); return result.rows[0]; }
export async function transitionProcurementRecord(client,context,resource,recordId,action,input={}){ const table=TABLES[resource]; if(!table) throw new ProcurementError(404,"Unknown Procurement resource."); const allowed={submit:["draft","submitted"],approve:["submitted","approved"],reject:["submitted","rejected"],activate:["approved","active"],dispatch:["approved","dispatched"],acknowledge:["dispatched","acknowledged"],close:["active","closed"],cancel:["draft","cancelled"]}; const transition=allowed[action]; if(!transition) throw new ProcurementError(400,"Unsupported Procurement action."); permission(context, action==="approve"?"procurement.po.approve":"procurement.settings.manage"); const current=await getProcurementRecord(client,context,resource,recordId); if(current.status!==transition[0]) throw new ProcurementError(409,`Cannot ${action} a ${current.status} record.`); if(action==="approve" && current.created_by===context.userId) throw new ProcurementError(409,"The creator cannot approve the same document."); const result=await client.query(`UPDATE tenant.${table} SET status=$3,version=version+1,updated_by=$4,updated_at=now() WHERE organization_id=$1 AND id=$2 RETURNING *`,[context.organizationId,id(recordId),transition[1],context.userId]); await client.query(`INSERT INTO tenant.procurement_events(organization_id,company_id,entity_type,entity_id,event_type,payload,actor_user_id) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7)`,[context.organizationId,current.company_id,resource,recordId,action,JSON.stringify(input),context.userId]); return result.rows[0]; }
export async function getProcurementDashboard(client,context){ permission(context,"procurement.view"); const r=await client.query(`SELECT (SELECT count(*) FROM tenant.procurement_requisitions WHERE organization_id=$1 AND status IN ('submitted','pending_approval'))::int pending_requisitions,(SELECT count(*) FROM tenant.procurement_sourcing_events WHERE organization_id=$1 AND status='active')::int active_sourcing,(SELECT count(*) FROM tenant.procurement_purchase_orders WHERE organization_id=$1 AND status IN ('approved','dispatched','acknowledged','partially_received'))::int open_orders,(SELECT count(*) FROM tenant.procurement_receipts WHERE organization_id=$1 AND status='draft')::int pending_receipts,(SELECT count(*) FROM tenant.procurement_match_exceptions WHERE organization_id=$1 AND status='open')::int match_exceptions,(SELECT count(*) FROM tenant.procurement_suppliers WHERE organization_id=$1 AND status IN ('conditional','blocked','suspended'))::int supplier_risks`,[context.organizationId]); return r.rows[0]||{}; }
export async function getProcurementReport(client,context,report,filters={}){ permission(context,"procurement.reports.view"); const allowed=new Set(["spend-analysis","supplier-performance","purchase-price-variance","contract-compliance","maverick-spend","open-commitments","overdue-orders","matching-exceptions","savings","cycle-time","supplier-risk","agreement-consumption"]); if(!allowed.has(report)) throw new ProcurementError(404,"Unknown Procurement report."); const result=await client.query(`SELECT report_key,metric_key,metric_value,dimension_key,dimension_value FROM tenant.procurement_reporting_facts WHERE organization_id=$1 AND report_key=$2 ORDER BY metric_value DESC LIMIT 500`,[context.organizationId,report]); return {report,filters,rows:result.rows}; }
export function evaluateSupplierScore(weights,scores){ const keys=Object.keys(weights); const allocations=allocate("100",keys.map(k=>weights[k])); let total=0n; keys.forEach((k,i)=>{ total += decimal(scores[k]||0)*allocations[i]/decimal("100"); }); return format(total,2); }
export { allocate, decimal, format };
