#!/usr/bin/env node
// Durable, repeatable full-repository source export.
//
// Replaces the ad-hoc "vercentlabs-all-code-*.txt(.gz)" snapshots that were
// previously generated by hand (with no fixed enumeration/exclusion rules
// and no manifest) — the September export that seeded the Prompt 1-5
// integrity review was one such snapshot, and it silently omitted
// newly-created Prompt 3-5 files because it predated them and there was no
// script to regenerate it against the current tree.
//
// Enumerates every Git-visible source file (tracked + staged + modified +
// untracked-but-not-ignored), excludes secrets/build output/binary assets,
// and writes a self-describing manifest (branch/commit/dirty state, and a
// byte offset + size + SHA-256 checksum per included file) alongside the
// archive so a later run can prove the archive is complete and unmodified —
// see verify-source-export.mjs.
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { gzipSync } from "node:zlib";
import fs from "node:fs";
import path from "node:path";

const repoRoot = execFileSync("git", ["rev-parse", "--show-toplevel"], {
  encoding: "utf8",
}).trim();

// Directories that are never source-of-truth: dependencies, build/tool
// output, generated caches, and this exporter's own output directory.
const EXCLUDED_DIR_SEGMENTS = new Set([
  "node_modules", ".git", ".next", "out", "dist", "build", "coverage",
  ".turbo", ".pnpm", ".pnpm-store", "test-results", "playwright-report",
  "blob-report", ".lighthouse-reports", ".cache", "tmp", "temp",
  "exports", ".expo", "android", "ios",
]);

// Exact basenames that must never appear in an export, even if somehow
// git-visible (defense in depth on top of .gitignore, which already keeps
// most of these untracked).
const EXCLUDED_EXACT_BASENAMES = new Set([
  "credentials.json", "secrets.json", "service-account.json",
]);

// .env* is excluded by default; only committed *.example templates (the
// project's own established convention — see .gitignore) are safe to keep.
const ALLOWED_DOTENV_SUFFIXES = [".example", ".sample"];

const EXCLUDED_PATH_PATTERNS = [
  /(^|\/)\.env(\.|$)/i,
  /credential/i,
  /secret/i,
  /private[-_]?key/i,
  /\.(pem|key|crt|p12|pfx)$/i,
  /\.(dump|bak|backup)$/i,
  /(^|\/)(dumps|backups)\//i,
];

// Binary/media assets are excluded by default ("unless deliberately
// included" — none of this program's CRM/API/web source is binary, so a
// blanket exclusion by extension is safe and keeps the archive text-only
// and human/LLM-readable).
const BINARY_EXTENSIONS = new Set([
  ".png", ".jpg", ".jpeg", ".gif", ".webp", ".ico", ".bmp",
  ".woff", ".woff2", ".ttf", ".otf", ".eot",
  ".mp4", ".mov", ".webm", ".avi",
  ".zip", ".gz", ".tar", ".7z", ".rar",
  ".pdf", ".db", ".sqlite", ".sqlite3",
]);

function isAllowedDotenv(basename) {
  return ALLOWED_DOTENV_SUFFIXES.some((suffix) => basename.endsWith(suffix));
}

function shouldExclude(relPath) {
  const segments = relPath.split("/");
  if (segments.some((segment) => EXCLUDED_DIR_SEGMENTS.has(segment))) return true;
  const basename = segments[segments.length - 1];
  if (basename.startsWith(".env")) return !isAllowedDotenv(basename);
  if (EXCLUDED_EXACT_BASENAMES.has(basename)) return true;
  if (EXCLUDED_PATH_PATTERNS.some((pattern) => pattern.test(relPath))) return true;
  const ext = path.extname(basename).toLowerCase();
  if (BINARY_EXTENSIONS.has(ext)) return true;
  return false;
}

function listGitVisibleFiles() {
  // --cached (tracked, including staged changes to tracked files) +
  // --others --exclude-standard (untracked files not covered by
  // .gitignore) together are the canonical superset: tracked, modified,
  // staged and untracked-nonignored source, exactly as required. -z avoids
  // any ambiguity from filenames containing spaces or special characters.
  const output = execFileSync(
    "git",
    ["ls-files", "--cached", "--others", "--exclude-standard", "-z"],
    { cwd: repoRoot, maxBuffer: 1024 * 1024 * 256 },
  );
  return output.toString("utf8").split("\0").filter(Boolean);
}

function gitInfo() {
  const branch = execFileSync("git", ["rev-parse", "--abbrev-ref", "HEAD"], {
    cwd: repoRoot,
    encoding: "utf8",
  }).trim();
  const commitSha = execFileSync("git", ["rev-parse", "HEAD"], {
    cwd: repoRoot,
    encoding: "utf8",
  }).trim();
  const dirty = execFileSync("git", ["status", "--porcelain"], {
    cwd: repoRoot,
    encoding: "utf8",
  }).trim().length > 0;
  return { branch, commitSha, dirty };
}

function buildArchive(relPaths) {
  const chunks = [];
  const manifestFiles = [];
  let cursor = 0;
  let skipped = 0;

  for (const relPath of relPaths.sort()) {
    const fullPath = path.join(repoRoot, relPath);
    let raw;
    try {
      raw = fs.readFileSync(fullPath);
    } catch {
      // A path git reported can race with a concurrent local edit/delete;
      // skip defensively rather than fail the whole export.
      skipped += 1;
      continue;
    }
    const sha256 = createHash("sha256").update(raw).digest("hex");
    const header = Buffer.from(
      `\n=== FILE START: ${relPath} (${raw.length} bytes, sha256 ${sha256}) ===\n`,
      "utf8",
    );
    const footer = Buffer.from(`\n=== FILE END: ${relPath} ===\n`, "utf8");
    chunks.push(header);
    cursor += header.length;
    const offset = cursor;
    chunks.push(raw);
    cursor += raw.length;
    chunks.push(footer);
    cursor += footer.length;
    manifestFiles.push({ path: relPath, size: raw.length, sha256, offset });
  }

  return { body: Buffer.concat(chunks), manifestFiles, skipped };
}

function main() {
  const allPaths = listGitVisibleFiles();
  const included = allPaths.filter((relPath) => !shouldExclude(relPath));
  const excludedCount = allPaths.length - included.length;

  const { body, manifestFiles, skipped } = buildArchive(included);
  const { branch, commitSha, dirty } = gitInfo();

  const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
  const exportId = createHash("sha256")
    .update(`${commitSha}:${timestamp}:${Math.random()}`)
    .digest("hex")
    .slice(0, 16);

  const outDir = path.join(repoRoot, "exports");
  fs.mkdirSync(outDir, { recursive: true });

  const baseName = `vercentlabs-all-code-${timestamp}`;
  const txtFile = `${baseName}.txt`;
  const gzFile = `${baseName}.txt.gz`;
  const manifestFile = `${baseName}.manifest.json`;

  fs.writeFileSync(path.join(outDir, txtFile), body);
  fs.writeFileSync(path.join(outDir, gzFile), gzipSync(body));

  const manifest = {
    exportId,
    generatedAt: new Date().toISOString(),
    branch,
    commitSha,
    dirty,
    fileCount: manifestFiles.length,
    excludedCount,
    skippedUnreadableCount: skipped,
    archiveFile: txtFile,
    archiveGzFile: gzFile,
    archiveSize: body.length,
    archiveSha256: createHash("sha256").update(body).digest("hex"),
    files: manifestFiles,
  };
  fs.writeFileSync(path.join(outDir, manifestFile), JSON.stringify(manifest, null, 2));

  console.log(`Source export written to exports/${txtFile}`);
  console.log(`  gzip:     exports/${gzFile}`);
  console.log(`  manifest: exports/${manifestFile}`);
  console.log(`  files included: ${manifestFiles.length} (excluded ${excludedCount}, unreadable/skipped ${skipped})`);
  console.log(`  branch: ${branch}  commit: ${commitSha}  dirty: ${dirty}`);

  return path.join(outDir, manifestFile);
}

main();
