BEGIN;

INSERT INTO permissions (key,name,category,description) VALUES
  ('roles.view','View roles','Access','View organisation role templates, custom roles and effective permissions.'),
  ('roles.assign','Assign roles','Access','Assign one or more roles and access scopes to organisation users.'),
  ('access.sod.override','Override access conflict warnings','Access','Acknowledge warning-level segregation-of-duties conflicts during access administration.')
ON CONFLICT (key) DO UPDATE SET name=EXCLUDED.name,category=EXCLUDED.category,description=EXCLUDED.description;

ALTER TABLE roles ADD COLUMN IF NOT EXISTS module_key text NOT NULL DEFAULT 'platform';
ALTER TABLE roles ADD COLUMN IF NOT EXISTS template_key text;
ALTER TABLE roles ADD COLUMN IF NOT EXISTS assignable boolean NOT NULL DEFAULT true;
ALTER TABLE roles ADD COLUMN IF NOT EXISTS risk_level text NOT NULL DEFAULT 'standard';
ALTER TABLE roles ADD COLUMN IF NOT EXISTS version integer NOT NULL DEFAULT 1;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='roles'::regclass AND conname='roles_module_key_check') THEN
    ALTER TABLE roles ADD CONSTRAINT roles_module_key_check CHECK (module_key IN ('platform','crm','sales','accounting','procurement','stock','manufacturing','hr-payroll')) NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='roles'::regclass AND conname='roles_risk_level_check') THEN
    ALTER TABLE roles ADD CONSTRAINT roles_risk_level_check CHECK (risk_level IN ('standard','sensitive','privileged')) NOT VALID;
  END IF;
END $$;
ALTER TABLE roles VALIDATE CONSTRAINT roles_module_key_check;
ALTER TABLE roles VALIDATE CONSTRAINT roles_risk_level_check;
CREATE INDEX IF NOT EXISTS roles_org_module_assignable_idx ON roles(organization_id,module_key,assignable,status,name);
CREATE UNIQUE INDEX IF NOT EXISTS teams_organization_id_id_uidx ON teams(organization_id,id);
CREATE UNIQUE INDEX IF NOT EXISTS organization_invitations_organization_id_id_uidx
  ON organization_invitations(organization_id,id);

ALTER TABLE user_role_assignments ADD COLUMN IF NOT EXISTS is_primary boolean NOT NULL DEFAULT false;
ALTER TABLE user_role_assignments ADD COLUMN IF NOT EXISTS starts_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE user_role_assignments ADD COLUMN IF NOT EXISTS expires_at timestamptz;
ALTER TABLE user_role_assignments ADD COLUMN IF NOT EXISTS status text NOT NULL DEFAULT 'active';
ALTER TABLE user_role_assignments ADD COLUMN IF NOT EXISTS reason text NOT NULL DEFAULT '';
ALTER TABLE user_role_assignments ADD COLUMN IF NOT EXISTS revoked_at timestamptz;
ALTER TABLE user_role_assignments ADD COLUMN IF NOT EXISTS revoked_by uuid REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE user_role_assignments ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='user_role_assignments'::regclass AND conname='user_role_assignments_status_check') THEN
    ALTER TABLE user_role_assignments ADD CONSTRAINT user_role_assignments_status_check CHECK (status IN ('active','suspended','revoked')) NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='user_role_assignments'::regclass AND conname='user_role_assignments_period_check') THEN
    ALTER TABLE user_role_assignments ADD CONSTRAINT user_role_assignments_period_check CHECK (expires_at IS NULL OR expires_at > starts_at) NOT VALID;
  END IF;
END $$;
ALTER TABLE user_role_assignments VALIDATE CONSTRAINT user_role_assignments_status_check;
ALTER TABLE user_role_assignments VALIDATE CONSTRAINT user_role_assignments_period_check;

WITH ranked AS (
  SELECT organization_id,user_id,role_id,
         row_number() OVER (PARTITION BY organization_id,user_id ORDER BY CASE WHEN r.slug='organization_owner' THEN 0 WHEN r.slug='system_administrator' THEN 1 ELSE 2 END, ura.created_at, ura.role_id) AS rn
  FROM user_role_assignments ura JOIN roles r ON r.id=ura.role_id
  WHERE ura.status='active'
)
UPDATE user_role_assignments ura SET is_primary=(ranked.rn=1),updated_at=now()
FROM ranked WHERE ura.organization_id=ranked.organization_id AND ura.user_id=ranked.user_id AND ura.role_id=ranked.role_id;
CREATE UNIQUE INDEX IF NOT EXISTS user_role_assignments_one_primary_idx ON user_role_assignments(organization_id,user_id) WHERE is_primary AND status='active';
CREATE INDEX IF NOT EXISTS user_role_assignments_effective_idx ON user_role_assignments(organization_id,user_id,status,starts_at,expires_at);

CREATE TABLE IF NOT EXISTS membership_team_access (
  organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  team_id uuid NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (organization_id,user_id,team_id),
  FOREIGN KEY (organization_id,team_id) REFERENCES teams(organization_id,id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS organization_invitation_roles (
  invitation_id uuid NOT NULL REFERENCES organization_invitations(id) ON DELETE CASCADE,
  organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  role_id uuid NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
  is_primary boolean NOT NULL DEFAULT false,
  starts_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz,
  PRIMARY KEY (invitation_id,role_id),
  FOREIGN KEY (organization_id,invitation_id)
    REFERENCES organization_invitations(organization_id,id) ON DELETE CASCADE,
  FOREIGN KEY (organization_id,role_id)
    REFERENCES roles(organization_id,id) ON DELETE CASCADE,
  CHECK (expires_at IS NULL OR expires_at > starts_at)
);
CREATE UNIQUE INDEX IF NOT EXISTS organization_invitation_roles_primary_idx ON organization_invitation_roles(invitation_id) WHERE is_primary;
INSERT INTO organization_invitation_roles(invitation_id,organization_id,role_id,is_primary)
SELECT id,organization_id,role_id,true FROM organization_invitations WHERE role_id IS NOT NULL
ON CONFLICT (invitation_id,role_id) DO UPDATE SET is_primary=true;

CREATE TABLE IF NOT EXISTS organization_invitation_team_access (
  invitation_id uuid NOT NULL REFERENCES organization_invitations(id) ON DELETE CASCADE,
  organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  team_id uuid NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  PRIMARY KEY (invitation_id,team_id),
  FOREIGN KEY (organization_id,invitation_id)
    REFERENCES organization_invitations(organization_id,id) ON DELETE CASCADE,
  FOREIGN KEY (organization_id,team_id)
    REFERENCES teams(organization_id,id) ON DELETE CASCADE
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='organization_invitation_company_access'::regclass AND conname='organization_invitation_company_access_organization_invitation_fkey') THEN
    ALTER TABLE organization_invitation_company_access
      ADD CONSTRAINT organization_invitation_company_access_organization_invitation_fkey
      FOREIGN KEY (organization_id,invitation_id)
      REFERENCES organization_invitations(organization_id,id) ON DELETE CASCADE NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='organization_invitation_branch_access'::regclass AND conname='organization_invitation_branch_access_organization_invitation_fkey') THEN
    ALTER TABLE organization_invitation_branch_access
      ADD CONSTRAINT organization_invitation_branch_access_organization_invitation_fkey
      FOREIGN KEY (organization_id,invitation_id)
      REFERENCES organization_invitations(organization_id,id) ON DELETE CASCADE NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='organization_invitation_department_access'::regclass AND conname='organization_invitation_department_access_organization_invitation_fkey') THEN
    ALTER TABLE organization_invitation_department_access
      ADD CONSTRAINT organization_invitation_department_access_organization_invitation_fkey
      FOREIGN KEY (organization_id,invitation_id)
      REFERENCES organization_invitations(organization_id,id) ON DELETE CASCADE NOT VALID;
  END IF;
END $$;
ALTER TABLE organization_invitation_company_access
  VALIDATE CONSTRAINT organization_invitation_company_access_organization_invitation_fkey;
ALTER TABLE organization_invitation_branch_access
  VALIDATE CONSTRAINT organization_invitation_branch_access_organization_invitation_fkey;
ALTER TABLE organization_invitation_department_access
  VALIDATE CONSTRAINT organization_invitation_department_access_organization_invitation_fkey;

DO $$
DECLARE relation_name text; trigger_name text;
BEGIN
  FOREACH relation_name IN ARRAY ARRAY[
    'organization_memberships','user_role_assignments','membership_company_access',
    'membership_branch_access','membership_department_access','membership_team_access'
  ] LOOP
    trigger_name := 'revoke_sessions_after_' || relation_name || '_change';
    EXECUTE format('DROP TRIGGER IF EXISTS %I ON %I',trigger_name,relation_name);
    EXECUTE format(
      'CREATE TRIGGER %I AFTER UPDATE OR DELETE ON %I FOR EACH ROW EXECUTE FUNCTION revoke_sessions_after_access_change()',
      trigger_name,relation_name
    );
  END LOOP;
END $$;

CREATE TABLE IF NOT EXISTS role_version_snapshots (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  role_id uuid NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
  version integer NOT NULL,
  snapshot jsonb NOT NULL,
  reason text NOT NULL DEFAULT '',
  created_by uuid REFERENCES users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (organization_id,role_id,version),
  FOREIGN KEY (organization_id,role_id)
    REFERENCES roles(organization_id,id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS access_assignment_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  actor_user_id uuid REFERENCES users(id) ON DELETE SET NULL,
  event_type text NOT NULL,
  before_state jsonb,
  after_state jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS access_assignment_events_user_idx ON access_assignment_events(organization_id,user_id,created_at DESC);

CREATE OR REPLACE FUNCTION prevent_access_evidence_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN RAISE EXCEPTION 'Access evidence is immutable'; END; $$;
DROP TRIGGER IF EXISTS role_version_snapshots_immutable ON role_version_snapshots;
CREATE TRIGGER role_version_snapshots_immutable BEFORE UPDATE OR DELETE ON role_version_snapshots FOR EACH ROW EXECUTE FUNCTION prevent_access_evidence_mutation();
DROP TRIGGER IF EXISTS access_assignment_events_immutable ON access_assignment_events;
CREATE TRIGGER access_assignment_events_immutable BEFORE UPDATE OR DELETE ON access_assignment_events FOR EACH ROW EXECUTE FUNCTION prevent_access_evidence_mutation();

CREATE TABLE IF NOT EXISTS access_conflict_rules (
  key text PRIMARY KEY,
  first_permission_key text NOT NULL REFERENCES permissions(key) ON DELETE CASCADE,
  second_permission_key text NOT NULL REFERENCES permissions(key) ON DELETE CASCADE,
  severity text NOT NULL CHECK (severity IN ('warning','blocking')),
  description text NOT NULL,
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active','inactive')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (first_permission_key <> second_permission_key)
);
INSERT INTO access_conflict_rules(key,first_permission_key,second_permission_key,severity,description) VALUES
    ('journal_prepare_approve','accounting.journal.create','accounting.journal.approve','blocking','The same access profile must not prepare and approve journals.'),
    ('payment_prepare_approve','accounting.payments.manage','accounting.payments.approve','blocking','Payment execution and payment approval must be separated.'),
    ('sales_order_create_approve','sales.order.create','sales.order.approve','blocking','Sales-order creation and approval must be separated.'),
    ('purchase_order_create_approve','procurement.po.create','procurement.po.approve','blocking','Purchase-order creation and approval must be separated.'),
    ('quotation_create_approve','sales.quotation.create','sales.quotation.approve','warning','Quotation creation and approval should normally be separated.'),
    ('supplier_manage_sensitive','procurement.suppliers.manage','procurement.suppliers.sensitive','warning','Supplier maintenance and sensitive supplier access should be reviewed.'),
    ('sourcing_evaluate_award','procurement.sourcing.evaluate','procurement.sourcing.award','warning','Bid evaluation and award authority should normally be separated.')
ON CONFLICT (key) DO UPDATE SET first_permission_key=EXCLUDED.first_permission_key,second_permission_key=EXCLUDED.second_permission_key,severity=EXCLUDED.severity,description=EXCLUDED.description,status='active',updated_at=now();

WITH template(name,slug,description,module_key,risk_level,assignable) AS (
  VALUES
    ('Organisation Owner','organization_owner','Full organisation ownership and governance.','platform','privileged',false),
    ('System Administrator','system_administrator','Platform configuration, security and access administration.','platform','privileged',true),
    ('Company Administrator','company_administrator','Company, branch, department, user and module administration without organisation ownership or billing control.','platform','privileged',true),
    ('Employee','employee','Basic employee access. Business permissions must be added through another role.','platform','standard',true),
    ('Auditor','auditor','Read-only governance, audit and released-module reporting access.','platform','sensitive',true),
    ('Read-only User','read_only','Read-only access to the released business modules and reports within assigned companies and branches.','platform','standard',true),
    ('CRM Administrator','crm_administrator','CRM configuration, integrations, data quality, automation and administration.','crm','privileged',true),
    ('Sales Head','sales_head','Organisation-wide sales leadership, forecasts, approvals, targets and commercial governance.','sales','privileged',true),
    ('Sales Manager','sales_manager','Team pipeline, opportunities, forecasts, quotations and sales approvals.','sales','sensitive',true),
    ('Sales Representative','sales_representative','Manage assigned leads, accounts, opportunities, activities, quotations and sales orders.','sales','standard',true),
    ('Sales Operations','sales_operations','Sales data quality, assignment, imports, configuration and reporting without commercial approval authority.','sales','sensitive',true),
    ('Marketing Manager','marketing_manager','Campaigns, segments, journeys, forms, events, attribution and marketing integrations.','crm','sensitive',true),
    ('Customer Success Manager','customer_success_manager','Customer health, success plans, renewals, feedback, playbooks and account engagement.','crm','standard',true),
    ('Partner Manager','partner_manager','Partner onboarding, deal registration, MDF, partner performance and field engagement.','crm','sensitive',true),
    ('Finance Manager','finance_manager','Finance governance, period close, budgets, taxes, policies and accounting approvals.','accounting','privileged',true),
    ('Accountant','accountant','Journal preparation, receivables, payables and routine accounting operations without approval authority.','accounting','sensitive',true),
    ('Accounts Receivable Executive','accounts_receivable_executive','Customer invoices, receipts, allocations, disputes and collections.','accounting','sensitive',true),
    ('Accounts Payable Executive','accounts_payable_executive','Supplier bills, matching and payment preparation without payment approval.','accounting','sensitive',true),
    ('Treasury Executive','treasury_executive','Payment execution, bank accounts, statements, reconciliation and cash operations without payment approval.','accounting','privileged',true),
    ('Tax and Compliance Accountant','tax_compliance_accountant','Tax setup, returns, compliance evidence, FX reporting and audit support.','accounting','sensitive',true),
    ('Procurement Manager','purchase_manager','Procurement governance, supplier lifecycle, sourcing, contracts and purchasing approvals.','procurement','privileged',true),
    ('Buyer / Purchase Officer','buyer','Supplier enquiries, sourcing, contracts and purchase-order preparation without approval authority.','procurement','sensitive',true),
    ('Purchase Requester','purchase_requester','Create and track purchase requisitions within assigned organisational scope.','procurement','standard',true),
    ('Purchase Approver','purchase_approver','Approve requisitions, contracts and purchase orders without creating or dispatching them.','procurement','privileged',true),
    ('Goods Receipt User','goods_receipt_user','Record receipts, inspections, discrepancies and supplier returns.','procurement','standard',true),
    ('Supplier Manager','supplier_manager','Supplier onboarding, qualification, catalogues, sensitive details and performance records.','procurement','sensitive',true),
    ('Inventory Manager','inventory_manager','Future Stock module role. Unavailable until the module is released.','stock','sensitive',false),
    ('Manufacturing Manager','manufacturing_manager','Future Manufacturing module role. Unavailable until the module is released.','manufacturing','sensitive',false),
    ('HR Manager','hr_manager','Future HR & Payroll role. Unavailable until the module is released.','hr-payroll','sensitive',false)
)
INSERT INTO roles(organization_id,name,slug,description,is_system,module_key,template_key,assignable,risk_level)
SELECT o.id,t.name,t.slug,t.description,true,t.module_key,t.slug,t.assignable,t.risk_level
FROM organizations o CROSS JOIN template t
ON CONFLICT (organization_id,slug) DO UPDATE SET
  name=EXCLUDED.name,
  description=EXCLUDED.description,
  module_key=EXCLUDED.module_key,
  template_key=EXCLUDED.template_key,
  assignable=EXCLUDED.assignable,
  risk_level=EXCLUDED.risk_level,
  is_system=true,
  status='active',
  updated_at=now();

DELETE FROM role_permissions rp USING roles r
WHERE rp.role_id=r.id AND r.is_system=true AND r.template_key IS NOT NULL;
WITH seed(role_slug,permission_key) AS (
  VALUES
    ('organization_owner','workspace.view'),
    ('organization_owner','organization.manage'),
    ('organization_owner','company.manage'),
    ('organization_owner','branch.manage'),
    ('organization_owner','department.manage'),
    ('organization_owner','cost_center.manage'),
    ('organization_owner','team.manage'),
    ('organization_owner','users.view'),
    ('organization_owner','users.manage'),
    ('organization_owner','roles.view'),
    ('organization_owner','roles.manage'),
    ('organization_owner','roles.assign'),
    ('organization_owner','access.sod.override'),
    ('organization_owner','audit.view'),
    ('organization_owner','notifications.view'),
    ('organization_owner','modules.manage'),
    ('organization_owner','numbering.manage'),
    ('organization_owner','approvals.manage'),
    ('organization_owner','profile.manage'),
    ('organization_owner','sessions.manage'),
    ('organization_owner','business_data.view'),
    ('organization_owner','parties.manage'),
    ('organization_owner','items.manage'),
    ('organization_owner','inventory_setup.manage'),
    ('organization_owner','finance_setup.manage'),
    ('organization_owner','business_data.import'),
    ('organization_owner','crm.view'),
    ('organization_owner','crm.leads.manage'),
    ('organization_owner','crm.opportunities.manage'),
    ('organization_owner','crm.activities.manage'),
    ('organization_owner','crm.campaigns.manage'),
    ('organization_owner','crm.communications.manage'),
    ('organization_owner','crm.automation.manage'),
    ('organization_owner','crm.capture.manage'),
    ('organization_owner','crm.import'),
    ('organization_owner','crm.export'),
    ('organization_owner','crm.reports.view'),
    ('organization_owner','crm.settings.manage'),
    ('organization_owner','crm.revenue.manage'),
    ('organization_owner','crm.accounts.manage'),
    ('organization_owner','crm.playbooks.manage'),
    ('organization_owner','crm.privacy.manage'),
    ('organization_owner','crm.data-quality.manage'),
    ('organization_owner','crm.integrations.manage'),
    ('organization_owner','crm.ai.manage'),
    ('organization_owner','crm.analytics.manage'),
    ('organization_owner','crm.customization.manage'),
    ('organization_owner','crm.partners.manage'),
    ('organization_owner','crm.field-sales.manage'),
    ('organization_owner','accounting.view'),
    ('organization_owner','accounting.journal.create'),
    ('organization_owner','accounting.journal.submit'),
    ('organization_owner','accounting.journal.approve'),
    ('organization_owner','accounting.journal.post'),
    ('organization_owner','accounting.journal.reverse'),
    ('organization_owner','accounting.receivables.manage'),
    ('organization_owner','accounting.receivables.approve'),
    ('organization_owner','accounting.receipts.manage'),
    ('organization_owner','accounting.collections.manage'),
    ('organization_owner','accounting.payables.manage'),
    ('organization_owner','accounting.payables.approve'),
    ('organization_owner','accounting.payments.manage'),
    ('organization_owner','accounting.payments.approve'),
    ('organization_owner','accounting.bank.manage'),
    ('organization_owner','accounting.bank.reconcile'),
    ('organization_owner','accounting.period.manage'),
    ('organization_owner','accounting.close.manage'),
    ('organization_owner','accounting.close.waive'),
    ('organization_owner','accounting.budget.manage'),
    ('organization_owner','accounting.tax.manage'),
    ('organization_owner','accounting.fx.manage'),
    ('organization_owner','accounting.intercompany.manage'),
    ('organization_owner','accounting.assets.manage'),
    ('organization_owner','accounting.recurring.manage'),
    ('organization_owner','accounting.consolidation.manage'),
    ('organization_owner','accounting.reports.view'),
    ('organization_owner','accounting.settings.manage'),
    ('organization_owner','accounting.audit.view'),
    ('organization_owner','sales.view'),
    ('organization_owner','sales.quotation.create'),
    ('organization_owner','sales.quotation.send'),
    ('organization_owner','sales.quotation.approve'),
    ('organization_owner','sales.quotation.accept_on_behalf'),
    ('organization_owner','sales.order.create'),
    ('organization_owner','sales.order.confirm'),
    ('organization_owner','sales.order.approve'),
    ('organization_owner','sales.order.amend'),
    ('organization_owner','sales.order.hold'),
    ('organization_owner','sales.order.cancel'),
    ('organization_owner','sales.fulfillment.request'),
    ('organization_owner','sales.invoice.request'),
    ('organization_owner','sales.price.override'),
    ('organization_owner','sales.margin.view'),
    ('organization_owner','sales.credit.override'),
    ('organization_owner','sales.reports.view'),
    ('organization_owner','sales.settings.manage'),
    ('organization_owner','procurement.view'),
    ('organization_owner','procurement.settings.manage'),
    ('organization_owner','procurement.suppliers.view'),
    ('organization_owner','procurement.suppliers.manage'),
    ('organization_owner','procurement.suppliers.qualify'),
    ('organization_owner','procurement.suppliers.sensitive'),
    ('organization_owner','procurement.catalog.manage'),
    ('organization_owner','procurement.requisition.create'),
    ('organization_owner','procurement.requisition.manage'),
    ('organization_owner','procurement.requisition.approve'),
    ('organization_owner','procurement.sourcing.manage'),
    ('organization_owner','procurement.sourcing.evaluate'),
    ('organization_owner','procurement.sourcing.award'),
    ('organization_owner','procurement.contracts.manage'),
    ('organization_owner','procurement.contracts.approve'),
    ('organization_owner','procurement.po.create'),
    ('organization_owner','procurement.po.manage'),
    ('organization_owner','procurement.po.approve'),
    ('organization_owner','procurement.po.dispatch'),
    ('organization_owner','procurement.po.amend'),
    ('organization_owner','procurement.po.cancel'),
    ('organization_owner','procurement.receipts.manage'),
    ('organization_owner','procurement.receipts.approve'),
    ('organization_owner','procurement.inspection.manage'),
    ('organization_owner','procurement.returns.manage'),
    ('organization_owner','procurement.matching.manage'),
    ('organization_owner','procurement.matching.override'),
    ('organization_owner','procurement.supplier_portal.manage'),
    ('organization_owner','procurement.reports.view'),
    ('organization_owner','procurement.audit.view'),
    ('organization_owner','billing.view'),
    ('organization_owner','billing.manage'),
    ('organization_owner','billing.checkout'),
    ('organization_owner','billing.audit'),
    ('system_administrator','workspace.view'),
    ('system_administrator','organization.manage'),
    ('system_administrator','company.manage'),
    ('system_administrator','branch.manage'),
    ('system_administrator','department.manage'),
    ('system_administrator','cost_center.manage'),
    ('system_administrator','team.manage'),
    ('system_administrator','users.view'),
    ('system_administrator','users.manage'),
    ('system_administrator','roles.view'),
    ('system_administrator','roles.manage'),
    ('system_administrator','roles.assign'),
    ('system_administrator','access.sod.override'),
    ('system_administrator','audit.view'),
    ('system_administrator','notifications.view'),
    ('system_administrator','modules.manage'),
    ('system_administrator','numbering.manage'),
    ('system_administrator','approvals.manage'),
    ('system_administrator','profile.manage'),
    ('system_administrator','sessions.manage'),
    ('system_administrator','business_data.view'),
    ('system_administrator','parties.manage'),
    ('system_administrator','items.manage'),
    ('system_administrator','inventory_setup.manage'),
    ('system_administrator','finance_setup.manage'),
    ('system_administrator','business_data.import'),
    ('system_administrator','crm.view'),
    ('system_administrator','crm.leads.manage'),
    ('system_administrator','crm.opportunities.manage'),
    ('system_administrator','crm.activities.manage'),
    ('system_administrator','crm.campaigns.manage'),
    ('system_administrator','crm.communications.manage'),
    ('system_administrator','crm.automation.manage'),
    ('system_administrator','crm.capture.manage'),
    ('system_administrator','crm.import'),
    ('system_administrator','crm.export'),
    ('system_administrator','crm.reports.view'),
    ('system_administrator','crm.settings.manage'),
    ('system_administrator','crm.revenue.manage'),
    ('system_administrator','crm.accounts.manage'),
    ('system_administrator','crm.playbooks.manage'),
    ('system_administrator','crm.privacy.manage'),
    ('system_administrator','crm.data-quality.manage'),
    ('system_administrator','crm.integrations.manage'),
    ('system_administrator','crm.ai.manage'),
    ('system_administrator','crm.analytics.manage'),
    ('system_administrator','crm.customization.manage'),
    ('system_administrator','crm.partners.manage'),
    ('system_administrator','crm.field-sales.manage'),
    ('system_administrator','accounting.view'),
    ('system_administrator','accounting.journal.create'),
    ('system_administrator','accounting.journal.submit'),
    ('system_administrator','accounting.journal.approve'),
    ('system_administrator','accounting.journal.post'),
    ('system_administrator','accounting.journal.reverse'),
    ('system_administrator','accounting.receivables.manage'),
    ('system_administrator','accounting.receivables.approve'),
    ('system_administrator','accounting.receipts.manage'),
    ('system_administrator','accounting.collections.manage'),
    ('system_administrator','accounting.payables.manage'),
    ('system_administrator','accounting.payables.approve'),
    ('system_administrator','accounting.payments.manage'),
    ('system_administrator','accounting.payments.approve'),
    ('system_administrator','accounting.bank.manage'),
    ('system_administrator','accounting.bank.reconcile'),
    ('system_administrator','accounting.period.manage'),
    ('system_administrator','accounting.close.manage'),
    ('system_administrator','accounting.close.waive'),
    ('system_administrator','accounting.budget.manage'),
    ('system_administrator','accounting.tax.manage'),
    ('system_administrator','accounting.fx.manage'),
    ('system_administrator','accounting.intercompany.manage'),
    ('system_administrator','accounting.assets.manage'),
    ('system_administrator','accounting.recurring.manage'),
    ('system_administrator','accounting.consolidation.manage'),
    ('system_administrator','accounting.reports.view'),
    ('system_administrator','accounting.settings.manage'),
    ('system_administrator','accounting.audit.view'),
    ('system_administrator','sales.view'),
    ('system_administrator','sales.quotation.create'),
    ('system_administrator','sales.quotation.send'),
    ('system_administrator','sales.quotation.approve'),
    ('system_administrator','sales.quotation.accept_on_behalf'),
    ('system_administrator','sales.order.create'),
    ('system_administrator','sales.order.confirm'),
    ('system_administrator','sales.order.approve'),
    ('system_administrator','sales.order.amend'),
    ('system_administrator','sales.order.hold'),
    ('system_administrator','sales.order.cancel'),
    ('system_administrator','sales.fulfillment.request'),
    ('system_administrator','sales.invoice.request'),
    ('system_administrator','sales.price.override'),
    ('system_administrator','sales.margin.view'),
    ('system_administrator','sales.credit.override'),
    ('system_administrator','sales.reports.view'),
    ('system_administrator','sales.settings.manage'),
    ('system_administrator','procurement.view'),
    ('system_administrator','procurement.settings.manage'),
    ('system_administrator','procurement.suppliers.view'),
    ('system_administrator','procurement.suppliers.manage'),
    ('system_administrator','procurement.suppliers.qualify'),
    ('system_administrator','procurement.suppliers.sensitive'),
    ('system_administrator','procurement.catalog.manage'),
    ('system_administrator','procurement.requisition.create'),
    ('system_administrator','procurement.requisition.manage'),
    ('system_administrator','procurement.requisition.approve'),
    ('system_administrator','procurement.sourcing.manage'),
    ('system_administrator','procurement.sourcing.evaluate'),
    ('system_administrator','procurement.sourcing.award'),
    ('system_administrator','procurement.contracts.manage'),
    ('system_administrator','procurement.contracts.approve'),
    ('system_administrator','procurement.po.create'),
    ('system_administrator','procurement.po.manage'),
    ('system_administrator','procurement.po.approve'),
    ('system_administrator','procurement.po.dispatch'),
    ('system_administrator','procurement.po.amend'),
    ('system_administrator','procurement.po.cancel'),
    ('system_administrator','procurement.receipts.manage'),
    ('system_administrator','procurement.receipts.approve'),
    ('system_administrator','procurement.inspection.manage'),
    ('system_administrator','procurement.returns.manage'),
    ('system_administrator','procurement.matching.manage'),
    ('system_administrator','procurement.matching.override'),
    ('system_administrator','procurement.supplier_portal.manage'),
    ('system_administrator','procurement.reports.view'),
    ('system_administrator','procurement.audit.view'),
    ('system_administrator','billing.view'),
    ('system_administrator','billing.manage'),
    ('system_administrator','billing.checkout'),
    ('system_administrator','billing.audit'),
    ('company_administrator','workspace.view'),
    ('company_administrator','company.manage'),
    ('company_administrator','branch.manage'),
    ('company_administrator','department.manage'),
    ('company_administrator','cost_center.manage'),
    ('company_administrator','team.manage'),
    ('company_administrator','users.view'),
    ('company_administrator','users.manage'),
    ('company_administrator','roles.view'),
    ('company_administrator','roles.manage'),
    ('company_administrator','roles.assign'),
    ('company_administrator','access.sod.override'),
    ('company_administrator','audit.view'),
    ('company_administrator','notifications.view'),
    ('company_administrator','modules.manage'),
    ('company_administrator','numbering.manage'),
    ('company_administrator','approvals.manage'),
    ('company_administrator','profile.manage'),
    ('company_administrator','sessions.manage'),
    ('company_administrator','business_data.view'),
    ('company_administrator','parties.manage'),
    ('company_administrator','items.manage'),
    ('company_administrator','inventory_setup.manage'),
    ('company_administrator','finance_setup.manage'),
    ('company_administrator','business_data.import'),
    ('company_administrator','crm.view'),
    ('company_administrator','crm.leads.manage'),
    ('company_administrator','crm.opportunities.manage'),
    ('company_administrator','crm.activities.manage'),
    ('company_administrator','crm.campaigns.manage'),
    ('company_administrator','crm.communications.manage'),
    ('company_administrator','crm.automation.manage'),
    ('company_administrator','crm.capture.manage'),
    ('company_administrator','crm.import'),
    ('company_administrator','crm.export'),
    ('company_administrator','crm.reports.view'),
    ('company_administrator','crm.settings.manage'),
    ('company_administrator','crm.revenue.manage'),
    ('company_administrator','crm.accounts.manage'),
    ('company_administrator','crm.playbooks.manage'),
    ('company_administrator','crm.privacy.manage'),
    ('company_administrator','crm.data-quality.manage'),
    ('company_administrator','crm.integrations.manage'),
    ('company_administrator','crm.analytics.manage'),
    ('company_administrator','crm.customization.manage'),
    ('company_administrator','crm.partners.manage'),
    ('company_administrator','crm.field-sales.manage'),
    ('company_administrator','accounting.view'),
    ('company_administrator','accounting.journal.create'),
    ('company_administrator','accounting.journal.submit'),
    ('company_administrator','accounting.journal.approve'),
    ('company_administrator','accounting.journal.post'),
    ('company_administrator','accounting.journal.reverse'),
    ('company_administrator','accounting.receivables.manage'),
    ('company_administrator','accounting.receivables.approve'),
    ('company_administrator','accounting.receipts.manage'),
    ('company_administrator','accounting.collections.manage'),
    ('company_administrator','accounting.payables.manage'),
    ('company_administrator','accounting.payables.approve'),
    ('company_administrator','accounting.payments.manage'),
    ('company_administrator','accounting.payments.approve'),
    ('company_administrator','accounting.bank.manage'),
    ('company_administrator','accounting.bank.reconcile'),
    ('company_administrator','accounting.period.manage'),
    ('company_administrator','accounting.close.manage'),
    ('company_administrator','accounting.close.waive'),
    ('company_administrator','accounting.budget.manage'),
    ('company_administrator','accounting.tax.manage'),
    ('company_administrator','accounting.fx.manage'),
    ('company_administrator','accounting.intercompany.manage'),
    ('company_administrator','accounting.assets.manage'),
    ('company_administrator','accounting.recurring.manage'),
    ('company_administrator','accounting.consolidation.manage'),
    ('company_administrator','accounting.reports.view'),
    ('company_administrator','accounting.settings.manage'),
    ('company_administrator','accounting.audit.view'),
    ('company_administrator','sales.view'),
    ('company_administrator','sales.quotation.create'),
    ('company_administrator','sales.quotation.send'),
    ('company_administrator','sales.quotation.approve'),
    ('company_administrator','sales.quotation.accept_on_behalf'),
    ('company_administrator','sales.order.create'),
    ('company_administrator','sales.order.confirm'),
    ('company_administrator','sales.order.approve'),
    ('company_administrator','sales.order.amend'),
    ('company_administrator','sales.order.hold'),
    ('company_administrator','sales.order.cancel'),
    ('company_administrator','sales.fulfillment.request'),
    ('company_administrator','sales.invoice.request'),
    ('company_administrator','sales.price.override'),
    ('company_administrator','sales.margin.view'),
    ('company_administrator','sales.credit.override'),
    ('company_administrator','sales.reports.view'),
    ('company_administrator','sales.settings.manage'),
    ('company_administrator','procurement.view'),
    ('company_administrator','procurement.settings.manage'),
    ('company_administrator','procurement.suppliers.view'),
    ('company_administrator','procurement.suppliers.manage'),
    ('company_administrator','procurement.suppliers.qualify'),
    ('company_administrator','procurement.suppliers.sensitive'),
    ('company_administrator','procurement.catalog.manage'),
    ('company_administrator','procurement.requisition.create'),
    ('company_administrator','procurement.requisition.manage'),
    ('company_administrator','procurement.requisition.approve'),
    ('company_administrator','procurement.sourcing.manage'),
    ('company_administrator','procurement.sourcing.evaluate'),
    ('company_administrator','procurement.sourcing.award'),
    ('company_administrator','procurement.contracts.manage'),
    ('company_administrator','procurement.contracts.approve'),
    ('company_administrator','procurement.po.create'),
    ('company_administrator','procurement.po.manage'),
    ('company_administrator','procurement.po.approve'),
    ('company_administrator','procurement.po.dispatch'),
    ('company_administrator','procurement.po.amend'),
    ('company_administrator','procurement.po.cancel'),
    ('company_administrator','procurement.receipts.manage'),
    ('company_administrator','procurement.receipts.approve'),
    ('company_administrator','procurement.inspection.manage'),
    ('company_administrator','procurement.returns.manage'),
    ('company_administrator','procurement.matching.manage'),
    ('company_administrator','procurement.matching.override'),
    ('company_administrator','procurement.supplier_portal.manage'),
    ('company_administrator','procurement.reports.view'),
    ('company_administrator','procurement.audit.view'),
    ('company_administrator','billing.view'),
    ('employee','workspace.view'),
    ('employee','notifications.view'),
    ('employee','profile.manage'),
    ('employee','business_data.view'),
    ('auditor','workspace.view'),
    ('auditor','notifications.view'),
    ('auditor','profile.manage'),
    ('auditor','users.view'),
    ('auditor','roles.view'),
    ('auditor','audit.view'),
    ('auditor','business_data.view'),
    ('auditor','crm.view'),
    ('auditor','crm.export'),
    ('auditor','crm.reports.view'),
    ('auditor','billing.view'),
    ('auditor','billing.audit'),
    ('auditor','sales.view'),
    ('auditor','sales.margin.view'),
    ('auditor','sales.reports.view'),
    ('auditor','accounting.view'),
    ('auditor','accounting.reports.view'),
    ('auditor','accounting.audit.view'),
    ('auditor','procurement.view'),
    ('auditor','procurement.suppliers.view'),
    ('auditor','procurement.reports.view'),
    ('auditor','procurement.audit.view'),
    ('read_only','workspace.view'),
    ('read_only','notifications.view'),
    ('read_only','profile.manage'),
    ('read_only','business_data.view'),
    ('read_only','crm.view'),
    ('read_only','crm.reports.view'),
    ('read_only','sales.view'),
    ('read_only','sales.reports.view'),
    ('read_only','accounting.view'),
    ('read_only','accounting.reports.view'),
    ('read_only','procurement.view'),
    ('read_only','procurement.suppliers.view'),
    ('read_only','procurement.reports.view'),
    ('crm_administrator','workspace.view'),
    ('crm_administrator','notifications.view'),
    ('crm_administrator','profile.manage'),
    ('crm_administrator','business_data.view'),
    ('crm_administrator','crm.view'),
    ('crm_administrator','crm.reports.view'),
    ('crm_administrator','parties.manage'),
    ('crm_administrator','crm.leads.manage'),
    ('crm_administrator','crm.opportunities.manage'),
    ('crm_administrator','crm.activities.manage'),
    ('crm_administrator','crm.campaigns.manage'),
    ('crm_administrator','crm.communications.manage'),
    ('crm_administrator','crm.automation.manage'),
    ('crm_administrator','crm.capture.manage'),
    ('crm_administrator','crm.import'),
    ('crm_administrator','crm.export'),
    ('crm_administrator','crm.settings.manage'),
    ('crm_administrator','crm.revenue.manage'),
    ('crm_administrator','crm.accounts.manage'),
    ('crm_administrator','crm.playbooks.manage'),
    ('crm_administrator','crm.privacy.manage'),
    ('crm_administrator','crm.data-quality.manage'),
    ('crm_administrator','crm.integrations.manage'),
    ('crm_administrator','crm.ai.manage'),
    ('crm_administrator','crm.analytics.manage'),
    ('crm_administrator','crm.customization.manage'),
    ('crm_administrator','crm.partners.manage'),
    ('crm_administrator','crm.field-sales.manage'),
    ('sales_head','workspace.view'),
    ('sales_head','notifications.view'),
    ('sales_head','profile.manage'),
    ('sales_head','business_data.view'),
    ('sales_head','crm.view'),
    ('sales_head','crm.reports.view'),
    ('sales_head','sales.view'),
    ('sales_head','sales.reports.view'),
    ('sales_head','approvals.manage'),
    ('sales_head','parties.manage'),
    ('sales_head','crm.leads.manage'),
    ('sales_head','crm.opportunities.manage'),
    ('sales_head','crm.activities.manage'),
    ('sales_head','crm.communications.manage'),
    ('sales_head','crm.revenue.manage'),
    ('sales_head','crm.accounts.manage'),
    ('sales_head','crm.playbooks.manage'),
    ('sales_head','crm.analytics.manage'),
    ('sales_head','sales.quotation.send'),
    ('sales_head','sales.quotation.approve'),
    ('sales_head','sales.quotation.accept_on_behalf'),
    ('sales_head','sales.order.confirm'),
    ('sales_head','sales.order.approve'),
    ('sales_head','sales.order.amend'),
    ('sales_head','sales.order.hold'),
    ('sales_head','sales.order.cancel'),
    ('sales_head','sales.fulfillment.request'),
    ('sales_head','sales.invoice.request'),
    ('sales_head','sales.price.override'),
    ('sales_head','sales.margin.view'),
    ('sales_head','sales.credit.override'),
    ('sales_head','sales.settings.manage'),
    ('sales_manager','workspace.view'),
    ('sales_manager','notifications.view'),
    ('sales_manager','profile.manage'),
    ('sales_manager','business_data.view'),
    ('sales_manager','crm.view'),
    ('sales_manager','crm.reports.view'),
    ('sales_manager','sales.view'),
    ('sales_manager','sales.reports.view'),
    ('sales_manager','approvals.manage'),
    ('sales_manager','parties.manage'),
    ('sales_manager','crm.leads.manage'),
    ('sales_manager','crm.opportunities.manage'),
    ('sales_manager','crm.activities.manage'),
    ('sales_manager','crm.communications.manage'),
    ('sales_manager','crm.revenue.manage'),
    ('sales_manager','crm.accounts.manage'),
    ('sales_manager','crm.playbooks.manage'),
    ('sales_manager','crm.analytics.manage'),
    ('sales_manager','sales.quotation.send'),
    ('sales_manager','sales.quotation.approve'),
    ('sales_manager','sales.order.confirm'),
    ('sales_manager','sales.order.approve'),
    ('sales_manager','sales.order.amend'),
    ('sales_manager','sales.order.hold'),
    ('sales_manager','sales.order.cancel'),
    ('sales_manager','sales.price.override'),
    ('sales_manager','sales.margin.view'),
    ('sales_manager','sales.credit.override'),
    ('sales_representative','workspace.view'),
    ('sales_representative','notifications.view'),
    ('sales_representative','profile.manage'),
    ('sales_representative','business_data.view'),
    ('sales_representative','crm.view'),
    ('sales_representative','crm.reports.view'),
    ('sales_representative','sales.view'),
    ('sales_representative','sales.reports.view'),
    ('sales_representative','parties.manage'),
    ('sales_representative','crm.leads.manage'),
    ('sales_representative','crm.opportunities.manage'),
    ('sales_representative','crm.activities.manage'),
    ('sales_representative','crm.communications.manage'),
    ('sales_representative','crm.accounts.manage'),
    ('sales_representative','crm.playbooks.manage'),
    ('sales_representative','crm.field-sales.manage'),
    ('sales_representative','sales.quotation.create'),
    ('sales_representative','sales.quotation.send'),
    ('sales_representative','sales.order.create'),
    ('sales_representative','sales.fulfillment.request'),
    ('sales_representative','sales.invoice.request'),
    ('sales_operations','workspace.view'),
    ('sales_operations','notifications.view'),
    ('sales_operations','profile.manage'),
    ('sales_operations','business_data.view'),
    ('sales_operations','crm.view'),
    ('sales_operations','crm.reports.view'),
    ('sales_operations','sales.view'),
    ('sales_operations','sales.reports.view'),
    ('sales_operations','parties.manage'),
    ('sales_operations','crm.leads.manage'),
    ('sales_operations','crm.opportunities.manage'),
    ('sales_operations','crm.activities.manage'),
    ('sales_operations','crm.import'),
    ('sales_operations','crm.export'),
    ('sales_operations','crm.settings.manage'),
    ('sales_operations','crm.data-quality.manage'),
    ('sales_operations','crm.analytics.manage'),
    ('sales_operations','crm.customization.manage'),
    ('sales_operations','sales.settings.manage'),
    ('sales_operations','sales.margin.view'),
    ('marketing_manager','workspace.view'),
    ('marketing_manager','notifications.view'),
    ('marketing_manager','profile.manage'),
    ('marketing_manager','business_data.view'),
    ('marketing_manager','crm.view'),
    ('marketing_manager','crm.reports.view'),
    ('marketing_manager','parties.manage'),
    ('marketing_manager','crm.leads.manage'),
    ('marketing_manager','crm.activities.manage'),
    ('marketing_manager','crm.campaigns.manage'),
    ('marketing_manager','crm.communications.manage'),
    ('marketing_manager','crm.automation.manage'),
    ('marketing_manager','crm.capture.manage'),
    ('marketing_manager','crm.import'),
    ('marketing_manager','crm.export'),
    ('marketing_manager','crm.integrations.manage'),
    ('marketing_manager','crm.analytics.manage'),
    ('customer_success_manager','workspace.view'),
    ('customer_success_manager','notifications.view'),
    ('customer_success_manager','profile.manage'),
    ('customer_success_manager','business_data.view'),
    ('customer_success_manager','crm.view'),
    ('customer_success_manager','crm.reports.view'),
    ('customer_success_manager','parties.manage'),
    ('customer_success_manager','crm.accounts.manage'),
    ('customer_success_manager','crm.activities.manage'),
    ('customer_success_manager','crm.communications.manage'),
    ('customer_success_manager','crm.playbooks.manage'),
    ('customer_success_manager','crm.revenue.manage'),
    ('customer_success_manager','crm.analytics.manage'),
    ('partner_manager','workspace.view'),
    ('partner_manager','notifications.view'),
    ('partner_manager','profile.manage'),
    ('partner_manager','business_data.view'),
    ('partner_manager','crm.view'),
    ('partner_manager','crm.reports.view'),
    ('partner_manager','parties.manage'),
    ('partner_manager','crm.opportunities.manage'),
    ('partner_manager','crm.activities.manage'),
    ('partner_manager','crm.partners.manage'),
    ('partner_manager','crm.field-sales.manage'),
    ('partner_manager','crm.analytics.manage'),
    ('finance_manager','workspace.view'),
    ('finance_manager','notifications.view'),
    ('finance_manager','profile.manage'),
    ('finance_manager','business_data.view'),
    ('finance_manager','accounting.view'),
    ('finance_manager','accounting.reports.view'),
    ('finance_manager','approvals.manage'),
    ('finance_manager','parties.manage'),
    ('finance_manager','finance_setup.manage'),
    ('finance_manager','billing.view'),
    ('finance_manager','billing.manage'),
    ('finance_manager','billing.checkout'),
    ('finance_manager','billing.audit'),
    ('finance_manager','sales.view'),
    ('finance_manager','sales.quotation.approve'),
    ('finance_manager','sales.order.approve'),
    ('finance_manager','sales.invoice.request'),
    ('finance_manager','sales.margin.view'),
    ('finance_manager','sales.credit.override'),
    ('finance_manager','accounting.journal.approve'),
    ('finance_manager','accounting.journal.post'),
    ('finance_manager','accounting.journal.reverse'),
    ('finance_manager','accounting.receivables.approve'),
    ('finance_manager','accounting.payables.approve'),
    ('finance_manager','accounting.payments.approve'),
    ('finance_manager','accounting.period.manage'),
    ('finance_manager','accounting.close.manage'),
    ('finance_manager','accounting.close.waive'),
    ('finance_manager','accounting.budget.manage'),
    ('finance_manager','accounting.tax.manage'),
    ('finance_manager','accounting.fx.manage'),
    ('finance_manager','accounting.intercompany.manage'),
    ('finance_manager','accounting.assets.manage'),
    ('finance_manager','accounting.recurring.manage'),
    ('finance_manager','accounting.consolidation.manage'),
    ('finance_manager','accounting.settings.manage'),
    ('finance_manager','accounting.audit.view'),
    ('accountant','workspace.view'),
    ('accountant','notifications.view'),
    ('accountant','profile.manage'),
    ('accountant','business_data.view'),
    ('accountant','accounting.view'),
    ('accountant','accounting.reports.view'),
    ('accountant','parties.manage'),
    ('accountant','finance_setup.manage'),
    ('accountant','accounting.journal.create'),
    ('accountant','accounting.journal.submit'),
    ('accountant','accounting.receivables.manage'),
    ('accountant','accounting.receipts.manage'),
    ('accountant','accounting.collections.manage'),
    ('accountant','accounting.payables.manage'),
    ('accountant','accounting.tax.manage'),
    ('accountant','accounting.fx.manage'),
    ('accountant','accounting.assets.manage'),
    ('accountant','accounting.recurring.manage'),
    ('accounts_receivable_executive','workspace.view'),
    ('accounts_receivable_executive','notifications.view'),
    ('accounts_receivable_executive','profile.manage'),
    ('accounts_receivable_executive','business_data.view'),
    ('accounts_receivable_executive','accounting.view'),
    ('accounts_receivable_executive','accounting.reports.view'),
    ('accounts_receivable_executive','parties.manage'),
    ('accounts_receivable_executive','accounting.receivables.manage'),
    ('accounts_receivable_executive','accounting.receipts.manage'),
    ('accounts_receivable_executive','accounting.collections.manage'),
    ('accounts_payable_executive','workspace.view'),
    ('accounts_payable_executive','notifications.view'),
    ('accounts_payable_executive','profile.manage'),
    ('accounts_payable_executive','business_data.view'),
    ('accounts_payable_executive','accounting.view'),
    ('accounts_payable_executive','accounting.reports.view'),
    ('accounts_payable_executive','parties.manage'),
    ('accounts_payable_executive','accounting.payables.manage'),
    ('treasury_executive','workspace.view'),
    ('treasury_executive','notifications.view'),
    ('treasury_executive','profile.manage'),
    ('treasury_executive','business_data.view'),
    ('treasury_executive','accounting.view'),
    ('treasury_executive','accounting.reports.view'),
    ('treasury_executive','accounting.payments.manage'),
    ('treasury_executive','accounting.bank.manage'),
    ('treasury_executive','accounting.bank.reconcile'),
    ('treasury_executive','accounting.fx.manage'),
    ('tax_compliance_accountant','workspace.view'),
    ('tax_compliance_accountant','notifications.view'),
    ('tax_compliance_accountant','profile.manage'),
    ('tax_compliance_accountant','business_data.view'),
    ('tax_compliance_accountant','accounting.view'),
    ('tax_compliance_accountant','accounting.reports.view'),
    ('tax_compliance_accountant','finance_setup.manage'),
    ('tax_compliance_accountant','accounting.tax.manage'),
    ('tax_compliance_accountant','accounting.fx.manage'),
    ('tax_compliance_accountant','accounting.audit.view'),
    ('purchase_manager','workspace.view'),
    ('purchase_manager','notifications.view'),
    ('purchase_manager','profile.manage'),
    ('purchase_manager','business_data.view'),
    ('purchase_manager','procurement.view'),
    ('purchase_manager','procurement.suppliers.view'),
    ('purchase_manager','procurement.reports.view'),
    ('purchase_manager','approvals.manage'),
    ('purchase_manager','parties.manage'),
    ('purchase_manager','items.manage'),
    ('purchase_manager','finance_setup.manage'),
    ('purchase_manager','procurement.settings.manage'),
    ('purchase_manager','procurement.suppliers.manage'),
    ('purchase_manager','procurement.suppliers.qualify'),
    ('purchase_manager','procurement.suppliers.sensitive'),
    ('purchase_manager','procurement.catalog.manage'),
    ('purchase_manager','procurement.requisition.manage'),
    ('purchase_manager','procurement.requisition.approve'),
    ('purchase_manager','procurement.sourcing.manage'),
    ('purchase_manager','procurement.sourcing.evaluate'),
    ('purchase_manager','procurement.sourcing.award'),
    ('purchase_manager','procurement.contracts.manage'),
    ('purchase_manager','procurement.contracts.approve'),
    ('purchase_manager','procurement.po.manage'),
    ('purchase_manager','procurement.po.approve'),
    ('purchase_manager','procurement.po.amend'),
    ('purchase_manager','procurement.po.cancel'),
    ('purchase_manager','procurement.receipts.approve'),
    ('purchase_manager','procurement.matching.override'),
    ('purchase_manager','procurement.supplier_portal.manage'),
    ('purchase_manager','procurement.audit.view'),
    ('buyer','workspace.view'),
    ('buyer','notifications.view'),
    ('buyer','profile.manage'),
    ('buyer','business_data.view'),
    ('buyer','procurement.view'),
    ('buyer','procurement.suppliers.view'),
    ('buyer','procurement.reports.view'),
    ('buyer','parties.manage'),
    ('buyer','items.manage'),
    ('buyer','procurement.suppliers.manage'),
    ('buyer','procurement.suppliers.qualify'),
    ('buyer','procurement.catalog.manage'),
    ('buyer','procurement.requisition.manage'),
    ('buyer','procurement.sourcing.manage'),
    ('buyer','procurement.sourcing.evaluate'),
    ('buyer','procurement.contracts.manage'),
    ('buyer','procurement.po.create'),
    ('buyer','procurement.po.manage'),
    ('buyer','procurement.po.dispatch'),
    ('buyer','procurement.po.amend'),
    ('buyer','procurement.po.cancel'),
    ('buyer','procurement.supplier_portal.manage'),
    ('purchase_requester','workspace.view'),
    ('purchase_requester','notifications.view'),
    ('purchase_requester','profile.manage'),
    ('purchase_requester','business_data.view'),
    ('purchase_requester','procurement.view'),
    ('purchase_requester','procurement.suppliers.view'),
    ('purchase_requester','procurement.reports.view'),
    ('purchase_requester','items.manage'),
    ('purchase_requester','procurement.requisition.create'),
    ('purchase_approver','workspace.view'),
    ('purchase_approver','notifications.view'),
    ('purchase_approver','profile.manage'),
    ('purchase_approver','business_data.view'),
    ('purchase_approver','procurement.view'),
    ('purchase_approver','procurement.suppliers.view'),
    ('purchase_approver','procurement.reports.view'),
    ('purchase_approver','approvals.manage'),
    ('purchase_approver','procurement.requisition.approve'),
    ('purchase_approver','procurement.contracts.approve'),
    ('purchase_approver','procurement.po.approve'),
    ('purchase_approver','procurement.receipts.approve'),
    ('goods_receipt_user','workspace.view'),
    ('goods_receipt_user','notifications.view'),
    ('goods_receipt_user','profile.manage'),
    ('goods_receipt_user','business_data.view'),
    ('goods_receipt_user','procurement.view'),
    ('goods_receipt_user','procurement.suppliers.view'),
    ('goods_receipt_user','procurement.reports.view'),
    ('goods_receipt_user','procurement.receipts.manage'),
    ('goods_receipt_user','procurement.inspection.manage'),
    ('goods_receipt_user','procurement.returns.manage'),
    ('supplier_manager','workspace.view'),
    ('supplier_manager','notifications.view'),
    ('supplier_manager','profile.manage'),
    ('supplier_manager','business_data.view'),
    ('supplier_manager','procurement.view'),
    ('supplier_manager','procurement.suppliers.view'),
    ('supplier_manager','procurement.reports.view'),
    ('supplier_manager','parties.manage'),
    ('supplier_manager','procurement.suppliers.manage'),
    ('supplier_manager','procurement.suppliers.qualify'),
    ('supplier_manager','procurement.suppliers.sensitive'),
    ('supplier_manager','procurement.catalog.manage'),
    ('supplier_manager','procurement.supplier_portal.manage'),
    ('inventory_manager','workspace.view'),
    ('inventory_manager','notifications.view'),
    ('inventory_manager','profile.manage'),
    ('inventory_manager','business_data.view'),
    ('inventory_manager','items.manage'),
    ('inventory_manager','inventory_setup.manage'),
    ('manufacturing_manager','workspace.view'),
    ('manufacturing_manager','notifications.view'),
    ('manufacturing_manager','profile.manage'),
    ('manufacturing_manager','business_data.view'),
    ('manufacturing_manager','items.manage'),
    ('manufacturing_manager','inventory_setup.manage'),
    ('hr_manager','workspace.view'),
    ('hr_manager','notifications.view'),
    ('hr_manager','profile.manage'),
    ('hr_manager','business_data.view')
)
INSERT INTO role_permissions(role_id,permission_key)
SELECT r.id,s.permission_key FROM roles r JOIN seed s ON s.role_slug=r.slug
JOIN permissions p ON p.key=s.permission_key
WHERE r.is_system=true
ON CONFLICT DO NOTHING;

WITH privileged(role_slug) AS (VALUES ('organization_owner'),('system_administrator'),('company_administrator'))
INSERT INTO role_permissions(role_id,permission_key)
SELECT r.id,p.key FROM roles r JOIN privileged x ON x.role_slug=r.slug CROSS JOIN permissions p
WHERE r.slug IN ('organization_owner','system_administrator')
ON CONFLICT DO NOTHING;

INSERT INTO role_permissions(role_id,permission_key)
SELECT r.id,p.key FROM roles r JOIN permissions p ON p.key IN ('roles.view','roles.assign','access.sod.override','users.view','users.manage','roles.manage')
WHERE r.slug IN ('organization_owner','system_administrator','company_administrator')
ON CONFLICT DO NOTHING;
INSERT INTO role_permissions(role_id,permission_key)
SELECT r.id,'roles.view' FROM roles r WHERE r.slug IN ('auditor')
ON CONFLICT DO NOTHING;

UPDATE user_role_assignments ura
SET status='revoked',is_primary=false,revoked_at=COALESCE(revoked_at,now()),updated_at=now(),reason=CASE WHEN reason='' THEN 'Role unavailable until its module is released' ELSE reason END
FROM roles r
WHERE r.id=ura.role_id AND r.assignable=false AND r.slug NOT IN ('organization_owner') AND ura.status='active';

INSERT INTO role_version_snapshots(organization_id,role_id,version,snapshot,reason,created_by)
SELECT r.organization_id,r.id,r.version,
       jsonb_build_object('name',r.name,'slug',r.slug,'description',r.description,'moduleKey',r.module_key,'riskLevel',r.risk_level,'assignable',r.assignable,'permissionKeys',COALESCE((SELECT jsonb_agg(rp.permission_key ORDER BY rp.permission_key) FROM role_permissions rp WHERE rp.role_id=r.id),'[]'::jsonb)),
       'Enterprise RBAC template baseline',o.created_by
FROM roles r JOIN organizations o ON o.id=r.organization_id
WHERE r.is_system=true
ON CONFLICT (organization_id,role_id,version) DO NOTHING;


-- The migration tightens existing system-role permissions and can revoke future-role
-- assignments. Force every active session to rebuild its cumulative permission set.
UPDATE sessions
SET revoked_at=COALESCE(revoked_at,now()),
    revoked_reason=COALESCE(revoked_reason,'enterprise_rbac_migrated')
WHERE revoked_at IS NULL
  AND EXISTS (
    SELECT 1 FROM organization_memberships membership
    WHERE membership.user_id=sessions.user_id
  );

COMMIT;
