import { getAccountingOrganisationOptions, listConsolidationGroups, listConsolidationRuns, listDunningRuns, listIntercompanyRules, listRevaluationRuns } from "@vercentlabs/api";
import SimpleAccountingForm from "@/modules/accounting/components/simple-accounting-form";
import { requireWorkspace } from "@/core/auth";
import { hasPermission, PERMISSIONS } from "@/core/authorization";
import { accountingContext } from "@/modules/accounting";
import { tenantTransaction } from "@/core/db";

export const dynamic = "force-dynamic";
type Row = Record<string, unknown>;

export default async function AccountingOperationsPage() {
  const session = await requireWorkspace();
  if (!hasPermission(session, PERMISSIONS.accountingView)) return <section className="panel"><h1>Accounting access required</h1></section>;
  const context = accountingContext(session);
  const data = await tenantTransaction(context.organizationId, async (client) => ({ options: await getAccountingOrganisationOptions(client, context), revaluations: await listRevaluationRuns(client, context), dunning: await listDunningRuns(client, context), rules: await listIntercompanyRules(client, context), groups: await listConsolidationGroups(client, context), consolidations: await listConsolidationRuns(client, context) })) as unknown as { options: { companies: Row[]; currencies: Row[] }; revaluations: Row[]; dunning: Row[]; rules: Row[]; groups: Row[]; consolidations: Row[] };
  const companies = data.options.companies.map((row) => ({ value: String(row.id), label: String(row.name) }));
  const currencies = data.options.currencies.map((row) => ({ value: String(row.code), label: `${String(row.code)} · ${String(row.name)}` }));
  return <>
    <section className="page-heading"><div><p className="eyebrow">Advanced accounting</p><h1>FX, collections, intercompany and consolidation</h1><p>Operate multi-company finance without weakening company-ledger, currency or approval boundaries.</p></div></section>
    <div className="accounting-two-column"><section className="panel"><p className="eyebrow">Foreign currency</p><h2>Revaluation runs</h2><div className="accounting-list">{data.revaluations.map((row) => <div key={String(row.id)}><span><strong>{String(row.run_number)} · {String(row.source_currency_code)}</strong><small>{String(row.company_name)} · {String(row.valuation_date).slice(0, 10)}</small></span><b>{String(row.status)} · gain {String(row.gain_total)} / loss {String(row.loss_total)}</b></div>)}{!data.revaluations.length ? <p>No revaluation runs exist.</p> : null}</div></section><section className="panel"><p className="eyebrow">Collections</p><h2>Dunning runs</h2><div className="accounting-list">{data.dunning.map((row) => <div key={String(row.id)}><span><strong>{String(row.company_name)} · {String(row.run_date).slice(0, 10)}</strong><small>{String(row.action_count)} planned actions</small></span><b>{String(row.overdue_amount)}</b></div>)}{!data.dunning.length ? <p>No dunning run exists.</p> : null}</div></section></div>
    <div className="accounting-two-column"><section className="panel"><p className="eyebrow">Intercompany</p><h2>Balancing rules</h2><div className="accounting-list">{data.rules.map((row) => <div key={String(row.id)}><span><strong>{String(row.from_company_name)} → {String(row.to_company_name)}</strong><small>Due to {String(row.due_to_account_code)} / due from {String(row.due_from_account_code)}</small></span><b>{String(row.status)}</b></div>)}{!data.rules.length ? <p>No intercompany rules are configured.</p> : null}</div></section><section className="panel"><p className="eyebrow">Consolidation</p><h2>Groups and runs</h2><div className="accounting-list">{data.groups.map((row) => <div key={String(row.id)}><span><strong>{String(row.code)} · {String(row.name)}</strong><small>{String(row.member_count)} members · {String(row.reporting_currency_code)}</small></span><b>{String(row.status)}</b></div>)}{data.consolidations.map((row) => <div key={String(row.id)}><span><strong>{String(row.group_code)} · {String(row.period_end).slice(0, 10)}</strong><small>{String(row.balance_count)} translated balances</small></span><b>{String(row.status)}</b></div>)}</div></section></div>
    {session.activeCompanyId && hasPermission(session, PERMISSIONS.accountingFxManage) ? <SimpleAccountingForm title="Calculate FX revaluation" description="Revalue open receivable and payable exposures in functional currency." endpoint="/api/accounting/fx/revaluations" submitLabel="Calculate revaluation" basePayload={{ companyId: session.activeCompanyId }} fields={[{ name: "valuationDate", label: "Valuation date", type: "date", required: true }, { name: "sourceCurrencyCode", label: "Foreign currency", type: "select", required: true, options: currencies }, { name: "rate", label: "Override rate", type: "number" }]} /> : null}
    {session.activeCompanyId && hasPermission(session, PERMISSIONS.accountingCollectionsManage) ? <SimpleAccountingForm title="Run customer collections" description="Calculate risk-based notices, calls, holds and legal-review actions for overdue invoices." endpoint="/api/accounting/collections/dunning" submitLabel="Calculate dunning run" basePayload={{ companyId: session.activeCompanyId }} fields={[{ name: "runDate", label: "Run date", type: "date", required: true }, { name: "minimumDaysOverdue", label: "Minimum days overdue", type: "number", defaultValue: 1 }, { name: "minimumAmount", label: "Minimum outstanding amount", type: "number", defaultValue: 0 }]} /> : null}
    <section className="accounting-capability-grid">{[["Intercompany mirror posting", "One governed command creates balanced entries in both company ledgers with a shared correlation ID."], ["Currency conversion", "Each company remains balanced in its own functional currency using an effective-dated exchange rate."], ["Consolidation", "Translate member ledgers, apply ownership method, record eliminations and finalize only balanced adjustments."], ["Foreign currency", "Revalue open subledger exposure and post unrealized gain or loss journals."], ["Collections", "Age receivables, calculate dunning level and preserve every collection action."], ["Audit and close", "Advanced runs remain traceable and must complete before a hard period close."]].map(([title, description]) => <article key={title}><strong>{title}</strong><span>{description}</span></article>)}</section>
    <section className="panel"><p className="eyebrow">Organisation scope</p><h2>Available companies</h2><div className="accounting-list">{companies.map((company) => <div key={company.value}><span><strong>{company.label}</strong><small>Available for governed intercompany and consolidation configuration.</small></span></div>)}</div></section>
  </>;
}
