apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: crm-inbound-secrets-secrets
  namespace: vercentlabs
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/${GCP_PROJECT_ID}/secrets/${SECRET_PREFIX}-crm-capture-proxy-secret/versions/latest"
        path: "CRM_CAPTURE_PROXY_SECRET"
      - resourceName: "projects/${GCP_PROJECT_ID}/secrets/${SECRET_PREFIX}-crm-inbound-email-secret/versions/latest"
        path: "CRM_INBOUND_EMAIL_SECRET"
      - resourceName: "projects/${GCP_PROJECT_ID}/secrets/${SECRET_PREFIX}-crm-provider-webhook-secret/versions/latest"
        path: "CRM_PROVIDER_WEBHOOK_SECRET"
      - resourceName: "projects/${GCP_PROJECT_ID}/secrets/${SECRET_PREFIX}-crm-acquisition-webhook-secret/versions/latest"
        path: "CRM_ACQUISITION_WEBHOOK_SECRET"
