type C = Record<string, unknown>;
type Q = unknown;
type R = Record<string, any>;
export declare function listSalaryComponents(client: Q, c: C, filters?: R): Promise<any[]>;
export declare function saveSalaryComponent(client: Q, c: C, input: R): Promise<any>;
export declare function ensureSystemComponent(client: Q, c: C, code: string, name: string, type: string, kind: string, opts?: R): Promise<any>;
export declare function listSalaryStructures(client: Q, c: C, filters?: R): Promise<any[]>;
export declare function getSalaryStructure(client: Q, c: C, id: string): Promise<any>;
export declare function createSalaryStructure(client: Q, c: C, input: R): Promise<any>;
export declare function updateDraftStructure(client: Q, c: C, id: string, input: R): Promise<any>;
export declare function submitSalaryStructure(client: Q, c: C, id: string): Promise<any>;
export declare function decideSalaryStructure(client: Q, c: C, id: string, input: { approve: boolean; note?: string }): Promise<any>;
export declare function reviseSalaryStructure(client: Q, c: C, id: string): Promise<any>;
export declare function obsoleteSalaryStructure(client: Q, c: C, id: string, reason: string): Promise<any>;
export declare function previewSalaryStructure(client: Q, c: C, input: R): Promise<any>;
export declare function listCompensation(client: Q, c: C, filters?: R): Promise<any[]>;
export declare function proposeCompensation(client: Q, c: C, input: R): Promise<any>;
export declare function decideCompensation(client: Q, c: C, id: string, input: { approve: boolean; note?: string }): Promise<any>;
export declare function getMyCompensation(client: Q, c: C): Promise<any>;
