type C = Record<string, unknown>;
type Q = unknown;
type R = Record<string, any>;
export declare function listLeaveTypes(client: Q, c: C): Promise<any[]>;
export declare function saveLeaveType(client: Q, c: C, input: R): Promise<any>;
export declare function listLeavePolicies(client: Q, c: C): Promise<any[]>;
export declare function saveLeavePolicy(client: Q, c: C, input: R): Promise<any>;
export declare function setPolicyEntry(client: Q, c: C, input: R): Promise<any>;
export declare function removePolicyEntry(client: Q, c: C, id: string): Promise<any>;
export declare function assignLeavePolicy(client: Q, c: C, input: R): Promise<any>;
export declare function listLeaveBalances(client: Q, c: C, filters?: R): Promise<any[]>;
export declare function getLeaveLedger(client: Q, c: C, filters?: R): Promise<any[]>;
export declare function adjustLeaveBalance(client: Q, c: C, input: R): Promise<any>;
export declare function runLeaveAccrual(client: Q, c: C, input?: R): Promise<any>;
export declare function runYearEndCarryForward(client: Q, c: C, input?: R): Promise<any>;
export declare function applyLeave(client: Q, c: C, input: R): Promise<any>;
export declare function decideLeave(client: Q, c: C, id: string, input: { approve: boolean; note?: string }): Promise<any>;
export declare function cancelLeave(client: Q, c: C, id: string, reason: string): Promise<any>;
export declare function listLeaveRequests(client: Q, c: C, filters?: R): Promise<any[]>;
export declare function getLeaveCalendar(client: Q, c: C, filters?: R): Promise<any[]>;
export declare function getLeaveDashboard(client: Q, c: C): Promise<any>;
