type C = Record<string, unknown>;
type Q = unknown;
type R = Record<string, any>;
export declare function listPayrollPeriods(client: Q, c: C, filters?: R): Promise<any[]>;
export declare function generatePayrollPeriods(client: Q, c: C, input: R): Promise<any>;
export declare function lockPayrollPeriod(client: Q, c: C, id: string, input?: R): Promise<any>;
export declare function unlockPayrollPeriod(client: Q, c: C, id: string, reason: string): Promise<any>;
export declare function closePayrollPeriod(client: Q, c: C, id: string): Promise<any>;
export declare function startPayrollRun(client: Q, c: C, input: R): Promise<any>;
export declare function runPayrollCalculation(client: Q, c: C, id: string, input?: R): Promise<any>;
export declare function submitPayrollRun(client: Q, c: C, id: string): Promise<any>;
export declare function returnPayrollRun(client: Q, c: C, id: string, reason: string): Promise<any>;
export declare function decidePayrollRun(client: Q, c: C, id: string, input: { approve: boolean; note?: string }): Promise<any>;
export declare function cancelPayroll(client: Q, c: C, id: string, reason: string): Promise<any>;
export declare function listPayrollExceptions(client: Q, c: C, filters?: R): Promise<any[]>;
export declare function resolvePayrollException(client: Q, c: C, id: string, note: string): Promise<any>;
export declare function listPayrollRuns(client: Q, c: C, filters?: R): Promise<any[]>;
export declare function getPayrollRun(client: Q, c: C, id: string): Promise<any>;
export declare function listPayslips(client: Q, c: C, filters?: R): Promise<any[]>;
export declare function getPayslip(client: Q, c: C, id: string): Promise<any>;
export declare function listMyPayslips(client: Q, c: C): Promise<any[]>;
export declare function verifyPayrollDeterminism(client: Q, c: C, id: string): Promise<any>;
export declare function holdPayslip(client: Q, c: C, id: string, reason: string): Promise<any>;
export declare function releasePayslipHold(client: Q, c: C, id: string): Promise<any>;
export declare function getPayrollDashboard(client: Q, c: C): Promise<any>;
export declare function registerPayrollHook(name: string, fn: (...args: any[]) => any): void;
export declare const PAYROLL_HOOKS: Record<string, unknown>;
