type C = Record<string, unknown>;
type Q = unknown;
type R = Record<string, any>;
export declare function listPayrollInputs(client: Q, c: C, filters?: R): Promise<any[]>;
export declare function createPayrollInput(client: Q, c: C, input: R): Promise<any>;
export declare function bulkCreatePayrollInputs(client: Q, c: C, input: R): Promise<any>;
export declare function decidePayrollInput(client: Q, c: C, id: string, input: { approve: boolean; note?: string }): Promise<any>;
export declare function cancelPayrollInput(client: Q, c: C, id: string, reason: string): Promise<any>;
export declare function listExpenseCategories(client: Q, c: C): Promise<any[]>;
export declare function saveExpenseCategory(client: Q, c: C, input: R): Promise<any>;
export declare function listExpenses(client: Q, c: C, filters?: R): Promise<any[]>;
export declare function saveExpense(client: Q, c: C, input: R): Promise<any>;
export declare function decideExpense(client: Q, c: C, id: string, input: { approve: boolean; note?: string }): Promise<any>;
export declare function buildSchedule(principal: number, annualRate: number, n: number, firstMonth: string): { emi: number; rows: any[] };
export declare function listLoans(client: Q, c: C, filters?: R): Promise<any[]>;
export declare function getLoan(client: Q, c: C, id: string): Promise<any>;
export declare function requestLoan(client: Q, c: C, input: R): Promise<any>;
export declare function decideLoan(client: Q, c: C, id: string, input: { approve: boolean; note?: string }): Promise<any>;
export declare function skipLoanInstallment(client: Q, c: C, id: string, reason: string): Promise<any>;
export declare function prepayLoan(client: Q, c: C, id: string, input: R): Promise<any>;
export declare function calculateArrears(client: Q, c: C, employeeId: string): Promise<any>;
