type C = Record<string, unknown>;
type Q = unknown;
type R = Record<string, any>;
export declare function listGoals(client: Q, c: C, filters?: R): Promise<any[]>;
export declare function saveGoal(client: Q, c: C, input: R): Promise<any>;
export declare function checkInGoal(client: Q, c: C, id: string, input: R): Promise<any>;
export declare function closeGoal(client: Q, c: C, id: string, input: { status: string; note: string }): Promise<any>;
export declare function listReviewCycles(client: Q, c: C): Promise<any[]>;
export declare function saveReviewCycle(client: Q, c: C, input: R): Promise<any>;
export declare function openReviewCycle(client: Q, c: C, id: string): Promise<any>;
export declare function closeReviewCycle(client: Q, c: C, id: string, reason: string): Promise<any>;
export declare function listAppraisals(client: Q, c: C, filters?: R): Promise<any[]>;
export declare function getAppraisal(client: Q, c: C, id: string): Promise<any>;
export declare function submitSelfReview(client: Q, c: C, id: string, input: R): Promise<any>;
export declare function submitPeerFeedback(client: Q, c: C, id: string, input: R): Promise<any>;
export declare function submitManagerReview(client: Q, c: C, id: string, input: R): Promise<any>;
export declare function calibrateAppraisal(client: Q, c: C, id: string, input: R): Promise<any>;
export declare function listSkills(client: Q, c: C): Promise<any[]>;
export declare function saveSkill(client: Q, c: C, input: R): Promise<any>;
export declare function listEmployeeSkills(client: Q, c: C, filters?: R): Promise<any[]>;
export declare function setEmployeeSkill(client: Q, c: C, input: R): Promise<any>;
export declare function listCourses(client: Q, c: C): Promise<any[]>;
export declare function saveCourse(client: Q, c: C, input: R): Promise<any>;
export declare function listTrainingSessions(client: Q, c: C, filters?: R): Promise<any[]>;
export declare function scheduleTrainingSession(client: Q, c: C, input: R): Promise<any>;
export declare function cancelTrainingSession(client: Q, c: C, id: string, reason: string): Promise<any>;
export declare function listTrainingEnrolments(client: Q, c: C, filters?: R): Promise<any[]>;
export declare function enrollInTraining(client: Q, c: C, input: R): Promise<any>;
export declare function recordTrainingCompletion(client: Q, c: C, id: string, input: R): Promise<any>;
export declare function getPerformanceDashboard(client: Q, c: C): Promise<any>;
