type C = Record<string, unknown>;
type Q = unknown;
type R = Record<string, any>;
export declare function listJobOpenings(client: Q, c: C, filters?: R): Promise<any[]>;
export declare function saveJobOpening(client: Q, c: C, input: R): Promise<any>;
export declare function submitJobOpening(client: Q, c: C, id: string): Promise<any>;
export declare function decideJobOpening(client: Q, c: C, id: string, input: { approve: boolean; note?: string }): Promise<any>;
export declare function setOpeningStatus(client: Q, c: C, id: string, input: { action: string; reason?: string }): Promise<any>;
export declare function listCandidates(client: Q, c: C, filters?: R): Promise<any[]>;
export declare function saveCandidate(client: Q, c: C, input: R): Promise<any>;
export declare function applyToOpening(client: Q, c: C, input: R): Promise<any>;
export declare function listApplications(client: Q, c: C, filters?: R): Promise<any[]>;
export declare function moveApplication(client: Q, c: C, id: string, input: { stage: string; reason?: string }): Promise<any>;
export declare function getRecruitmentPipeline(client: Q, c: C, input?: { openingId?: string }): Promise<any>;
export declare function listInterviews(client: Q, c: C, filters?: R): Promise<any[]>;
export declare function scheduleInterview(client: Q, c: C, input: R): Promise<any>;
export declare function cancelInterview(client: Q, c: C, id: string, reason: string): Promise<any>;
export declare function submitInterviewFeedback(client: Q, c: C, id: string, input: R): Promise<any>;
export declare function markInterviewNoShow(client: Q, c: C, id: string): Promise<any>;
export declare function listOffers(client: Q, c: C, filters?: R): Promise<any[]>;
export declare function createOffer(client: Q, c: C, input: R): Promise<any>;
export declare function submitOffer(client: Q, c: C, id: string): Promise<any>;
export declare function decideOffer(client: Q, c: C, id: string, input: { approve: boolean; note?: string }): Promise<any>;
export declare function sendOffer(client: Q, c: C, id: string): Promise<any>;
export declare function recordOfferDecision(client: Q, c: C, id: string, input: { accepted: boolean; note?: string }): Promise<any>;
export declare function withdrawOffer(client: Q, c: C, id: string, reason: string): Promise<any>;
export declare function convertOfferToEmployee(client: Q, c: C, offerId: string, input?: R): Promise<any>;
