type C = Record<string, unknown>;
type Q = unknown;
type R = Record<string, any>;
export declare function listShifts(client: Q, c: C): Promise<any[]>;
export declare function saveShift(client: Q, c: C, input: R): Promise<any>;
export declare function listShiftAssignments(client: Q, c: C, filters?: R): Promise<any[]>;
export declare function assignShift(client: Q, c: C, input: R): Promise<any>;
export declare function listHolidayCalendars(client: Q, c: C): Promise<any[]>;
export declare function saveHolidayCalendar(client: Q, c: C, input: R): Promise<any>;
export declare function listHolidays(client: Q, c: C, filters?: R): Promise<any[]>;
export declare function addHoliday(client: Q, c: C, input: R): Promise<any>;
export declare function removeHoliday(client: Q, c: C, id: string): Promise<any>;
export declare function assignHolidayCalendar(client: Q, c: C, input: R): Promise<any>;
export declare function punch(client: Q, c: C, input: R): Promise<any>;
export declare function recordAttendance(client: Q, c: C, input: R): Promise<any>;
export declare function listAttendance(client: Q, c: C, filters?: R): Promise<any[]>;
export declare function getMyPunchState(client: Q, c: C): Promise<any>;
export declare function listRegularizations(client: Q, c: C, filters?: R): Promise<any[]>;
export declare function requestRegularization(client: Q, c: C, input: R): Promise<any>;
export declare function decideRegularization(client: Q, c: C, id: string, input: { approve: boolean; note?: string }): Promise<any>;
export declare function cancelRegularization(client: Q, c: C, id: string): Promise<any>;
export declare function listOvertime(client: Q, c: C, filters?: R): Promise<any[]>;
export declare function decideOvertime(client: Q, c: C, id: string, input: { approve: boolean; note?: string }): Promise<any>;
export declare function getLateEarlyReport(client: Q, c: C, filters?: R): Promise<any>;
export declare function getAttendanceSummary(client: Q, c: C, input: R): Promise<any>;
export declare function computeAttendanceSummary(client: Q, c: C, employeeId: string, from: string, to: string): Promise<any>;
export declare function recomputeDay(client: Q, c: C, employee: R, date: string): Promise<any>;
