type C = Record<string, unknown>;
type Q = unknown;
export declare function getHrSettings(client: Q, c: C): Promise<Record<string, any>>;
export declare function saveHrSettings(client: Q, c: C, input: Record<string, any>): Promise<Record<string, any>>;
export declare function listDocumentTypes(client: Q, c: C): Promise<any[]>;
export declare function saveDocumentType(client: Q, c: C, input: Record<string, any>): Promise<any>;
export declare function listDepartments(client: Q, c: C): Promise<any[]>;
export declare function saveDepartment(client: Q, c: C, input: Record<string, any>): Promise<any>;
export declare function listDesignations(client: Q, c: C): Promise<any[]>;
export declare function saveDesignation(client: Q, c: C, input: Record<string, any>): Promise<any>;
export declare function saveEmployee(client: Q, c: C, input: Record<string, any>): Promise<any>;
export declare function updateEmployee(client: Q, c: C, id: string, input: Record<string, any>): Promise<any>;
export declare function completeJoining(client: Q, c: C, id: string): Promise<any>;
export declare function listEmployees(client: Q, c: C, filters?: Record<string, any>): Promise<any[]>;
export declare function getEmployee(client: Q, c: C, id: string): Promise<any>;
export declare function getOrgChart(client: Q, c: C): Promise<any[]>;
export declare function listEmployeeDocuments(client: Q, c: C, filters?: Record<string, any>): Promise<any[]>;
export declare function addEmployeeDocument(client: Q, c: C, input: Record<string, any>): Promise<any>;
export declare function reviewEmployeeDocument(client: Q, c: C, id: string, input: { verify: boolean; note?: string }): Promise<any>;
export declare function removeEmployeeDocument(client: Q, c: C, id: string): Promise<any>;
export declare function proposeEmployeeChange(client: Q, c: C, input: Record<string, any>): Promise<any>;
export declare function decideEmployeeChange(client: Q, c: C, id: string, input: { approve: boolean; note?: string }): Promise<any>;
export declare function applyDueEmployeeChanges(client: Q, c: C): Promise<any>;
export declare function cancelEmployeeChange(client: Q, c: C, id: string, reason: string): Promise<any>;
export declare function listEmployeeChanges(client: Q, c: C, filters?: Record<string, any>): Promise<any[]>;
export declare function listProbation(client: Q, c: C): Promise<any[]>;
export declare function listLifecycleTasks(client: Q, c: C, filters?: Record<string, any>): Promise<any[]>;
export declare function addLifecycleTask(client: Q, c: C, input: Record<string, any>): Promise<any>;
export declare function completeLifecycleTask(client: Q, c: C, id: string, input?: { note?: string; waive?: boolean }): Promise<any>;
export declare function listSeparations(client: Q, c: C, filters?: Record<string, any>): Promise<any[]>;
export declare function initiateSeparation(client: Q, c: C, input: Record<string, any>): Promise<any>;
export declare function decideSeparation(client: Q, c: C, id: string, input: { approve: boolean; note?: string; lastWorkingDay?: string }): Promise<any>;
export declare function withdrawSeparation(client: Q, c: C, id: string, reason: string): Promise<any>;
export declare function recordExitInterview(client: Q, c: C, id: string, input: Record<string, any>): Promise<any>;
export declare function completeSeparation(client: Q, c: C, id: string, input?: Record<string, any>): Promise<any>;
export declare function getMyProfile(client: Q, c: C): Promise<any>;
export declare function updateMyProfile(client: Q, c: C, input: Record<string, any>): Promise<any>;
export declare function requestProfileChange(client: Q, c: C, input: Record<string, any>): Promise<any>;
export declare function listProfileChangeRequests(client: Q, c: C, filters?: Record<string, any>): Promise<any[]>;
export declare function decideProfileChange(client: Q, c: C, id: string, input: { approve: boolean; note?: string }): Promise<any>;
export declare function getWorkforceDashboard(client: Q, c: C): Promise<any>;
export declare function getAttritionReport(client: Q, c: C, input?: { months?: number }): Promise<any>;
