type C = Record<string, unknown>;
type Q = unknown;
export declare function getHrSettings(client: Q, c: C): Promise<Record<string, any>>;
export declare function saveHrSettings(client: Q, c: C, input: Record<string, any>): Promise<Record<string, any>>;
export declare function listDepartments(client: Q, c: C): Promise<any[]>;
export declare function saveDepartment(client: Q, c: C, input: Record<string, any>): Promise<any>;
export declare function listDesignations(client: Q, c: C): Promise<any[]>;
export declare function saveDesignation(client: Q, c: C, input: Record<string, any>): Promise<any>;
export declare function saveEmployee(client: Q, c: C, input: Record<string, any>): Promise<any>;
export declare function updateEmployee(client: Q, c: C, id: string, input: Record<string, any>): Promise<any>;
export declare function completeJoining(client: Q, c: C, id: string): Promise<any>;
export declare function listEmployees(client: Q, c: C, filters?: Record<string, any>): Promise<any[]>;
export declare function getEmployee(client: Q, c: C, id: string): Promise<any>;
export declare function getOrgChart(client: Q, c: C): Promise<any[]>;
export declare function listLifecycleTasks(client: Q, c: C, filters?: Record<string, any>): Promise<any[]>;
export declare function addLifecycleTask(client: Q, c: C, input: Record<string, any>): Promise<any>;
export declare function completeLifecycleTask(client: Q, c: C, id: string, input?: { note?: string; waive?: boolean }): Promise<any>;
export declare function getMyProfile(client: Q, c: C): Promise<any>;
export declare function updateMyProfile(client: Q, c: C, input: Record<string, any>): Promise<any>;
export declare function getWorkforceDashboard(client: Q, c: C): Promise<any>;
