type C = Record<string, unknown>;
type Q = unknown;
type R = Record<string, any>;
export declare function getQualitySettings(client: Q, c: C): Promise<any>;
export declare function saveQualitySettings(client: Q, c: C, input: R): Promise<any>;
export declare function listSamplingPlans(client: Q, c: C): Promise<any[]>;
export declare function saveSamplingPlan(client: Q, c: C, input: R): Promise<any>;
export declare function listQualityPlans(client: Q, c: C, filters?: R): Promise<any[]>;
export declare function getQualityPlan(client: Q, c: C, id: string): Promise<any>;
export declare function createQualityPlan(client: Q, c: C, input: R): Promise<any>;
export declare function approveQualityPlan(client: Q, c: C, id: string): Promise<any>;
export declare function reviseQualityPlan(client: Q, c: C, id: string): Promise<any>;
export declare function retireQualityPlan(client: Q, c: C, id: string, reason: string): Promise<any>;
export declare function listInspections(client: Q, c: C, filters?: R): Promise<any[]>;
export declare function getInspection(client: Q, c: C, id: string): Promise<any>;
export declare function createInspection(client: Q, c: C, input: R): Promise<any>;
export declare function recordInspectionResults(client: Q, c: C, id: string, input: R): Promise<any>;
export declare function completeInspection(client: Q, c: C, id: string, input?: R): Promise<any>;
export declare function releaseInspection(client: Q, c: C, id: string, input?: R): Promise<any>;
export declare function cancelInspection(client: Q, c: C, id: string, reason: string): Promise<any>;
