type C = Record<string, unknown>;
type Q = unknown;
type R = Record<string, any>;
export declare function listSupplierQualityRecords(client: Q, c: C, filters?: R): Promise<any[]>;
export declare function recomputeSupplierQualityRecord(client: Q, c: C, input: R): Promise<any>;
export declare function listAudits(client: Q, c: C, filters?: R): Promise<any[]>;
export declare function getAudit(client: Q, c: C, id: string): Promise<any>;
export declare function saveAudit(client: Q, c: C, input: R): Promise<any>;
export declare function startAudit(client: Q, c: C, id: string): Promise<any>;
export declare function addAuditFinding(client: Q, c: C, auditId: string, input: R): Promise<any>;
export declare function linkFindingCapa(client: Q, c: C, findingId: string, capaId: string): Promise<any>;
export declare function closeAuditFinding(client: Q, c: C, findingId: string): Promise<any>;
export declare function completeAudit(client: Q, c: C, id: string, input?: R): Promise<any>;
export declare function listCalibrationRecords(client: Q, c: C, filters?: R): Promise<any[]>;
export declare function recordCalibration(client: Q, c: C, input: R): Promise<any>;
export declare function markOverdueCalibrations(client: Q, c: C): Promise<{ expired: number }>;
export declare function listCertificates(client: Q, c: C, filters?: R): Promise<any[]>;
export declare function saveCertificate(client: Q, c: C, input: R): Promise<any>;
export declare function issueCertificate(client: Q, c: C, id: string): Promise<any>;
export declare function voidCertificate(client: Q, c: C, id: string, reason: string): Promise<any>;
export declare function listQualityDocuments(client: Q, c: C, filters?: R): Promise<any[]>;
export declare function saveQualityDocument(client: Q, c: C, input: R): Promise<any>;
export declare function submitQualityDocument(client: Q, c: C, id: string): Promise<any>;
export declare function approveQualityDocument(client: Q, c: C, id: string): Promise<any>;
export declare function reviseQualityDocument(client: Q, c: C, id: string): Promise<any>;
export declare function obsoleteQualityDocument(client: Q, c: C, id: string, reason: string): Promise<any>;
export declare function listCustomerComplaints(client: Q, c: C, filters?: R): Promise<any[]>;
export declare function getCustomerComplaint(client: Q, c: C, id: string): Promise<any>;
export declare function createCustomerComplaint(client: Q, c: C, input: R): Promise<any>;
export declare function investigateComplaint(client: Q, c: C, id: string, input?: R): Promise<any>;
export declare function resolveComplaint(client: Q, c: C, id: string, input: R): Promise<any>;
export declare function closeComplaint(client: Q, c: C, id: string): Promise<any>;
export declare function getBatchTraceability(client: Q, c: C, input: { batchId?: string; serialId?: string }): Promise<any>;
export declare function getQualityCostReport(client: Q, c: C, filters?: R): Promise<any>;
export declare function getQualityKpiDashboard(client: Q, c: C): Promise<any>;
export declare function listQualityOptions(client: Q, c: C): Promise<Record<string, Array<{ id: string; code: string; name: string }>>>;
