type C = Record<string, unknown>;
type Q = unknown;
type R = Record<string, any>;
export declare function listQualityHolds(client: Q, c: C, filters?: R): Promise<any[]>;
export declare function getQualityHold(client: Q, c: C, id: string): Promise<any>;
export declare function createQualityHold(client: Q, c: C, input: R, opts?: { internal?: boolean }): Promise<any>;
export declare function cancelQualityHold(client: Q, c: C, id: string, reason: string): Promise<any>;
export declare function releaseQualityHold(client: Q, c: C, holdId: string, input?: R): Promise<any>;
export declare function listNonconformances(client: Q, c: C, filters?: R): Promise<any[]>;
export declare function getNonconformance(client: Q, c: C, id: string): Promise<any>;
export declare function createNonconformance(client: Q, c: C, input: R): Promise<any>;
export declare function transitionNonconformance(client: Q, c: C, id: string, input: R): Promise<any>;
export declare function setDisposition(client: Q, c: C, id: string, input: R): Promise<any>;
export declare function approveUseAsIs(client: Q, c: C, id: string, input: R): Promise<any>;
export declare function closeNonconformance(client: Q, c: C, id: string, input?: R): Promise<any>;
export declare function cancelNonconformance(client: Q, c: C, id: string, reason: string): Promise<any>;
export declare function listCapa(client: Q, c: C, filters?: R): Promise<any[]>;
export declare function getCapa(client: Q, c: C, id: string): Promise<any>;
export declare function createCapa(client: Q, c: C, input: R): Promise<any>;
export declare function recordRootCause(client: Q, c: C, id: string, input: R): Promise<any>;
export declare function recordCapaActions(client: Q, c: C, id: string, input: R): Promise<any>;
export declare function submitCapaForVerification(client: Q, c: C, id: string): Promise<any>;
export declare function verifyCapa(client: Q, c: C, id: string, input: R): Promise<any>;
export declare function closeCapa(client: Q, c: C, id: string): Promise<any>;
