type C = Record<string, unknown>;
type Q = unknown;
type R = Record<string, any>;
export declare function listNonconformances(client: Q, c: C, filters?: R): Promise<any[]>;
export declare function getNonconformance(client: Q, c: C, id: string): Promise<any>;
export declare function createNonconformance(client: Q, c: C, input: R): Promise<any>;
export declare function transitionNonconformance(client: Q, c: C, id: string, input: R): Promise<any>;
export declare function setDisposition(client: Q, c: C, id: string, input: R): Promise<any>;
export declare function approveUseAsIs(client: Q, c: C, id: string, input: R): Promise<any>;
export declare function closeNonconformance(client: Q, c: C, id: string, input?: R): Promise<any>;
export declare function cancelNonconformance(client: Q, c: C, id: string, reason: string): Promise<any>;
