services:
  landing:
    build:
      context: ../..
      dockerfile: infrastructure/docker/Dockerfile.landing
    env_file: ../../apps/landing/.env.production
    restart: unless-stopped
    ports:
      - "3000:3000"
    read_only: true
    tmpfs: [/tmp]
    security_opt: [no-new-privileges:true]

  web:
    build:
      context: ../..
      dockerfile: infrastructure/docker/Dockerfile.web
    env_file: ../../apps/web/.env.production
    restart: unless-stopped
    ports:
      - "3001:3001"
    read_only: true
    tmpfs: [/tmp]
    security_opt: [no-new-privileges:true]

  worker:
    build:
      context: ../..
      dockerfile: infrastructure/docker/Dockerfile.worker
    env_file: ../../apps/web/.env.production
    restart: unless-stopped
    read_only: true
    tmpfs: [/tmp]
    security_opt: [no-new-privileges:true]
