"use client";

// The item form: Basic Information, Commercial Use, Units, Inventory, Tax, Identifiers and Physical Details. Sections follow the type: a
// service has no inventory, tracking, expiry, valuation, barcodes or physical details; only a stock item is tracked. Groups the user may
// not change are read-only. Stock, prices and costs are never fields here — they come from Inventory, price lists and purchase orders.
// A new item takes its category's defaults (resolved up the category tree), each marked with where it came from until changed by hand.
// An existing item's category is changed with Reclassify on the item page, its SKU with Change SKU. A new item's SKU follows the
// organization's numbering: typed (checked as it is typed), or generated by the server on save — never in the browser.
import { useEffect, useState } from "react";
import Link from "next/link";
import { useMutation, useQuery } from "@tanstack/react-query";
import { Badge, Button, Checkbox, ComboBox, NumberField, Radio, RadioGroup, Select, TextArea, TextField } from "@vercentlabs/design-system";

import { FormSection } from "@/shared/ui/FormSection";
import { scopedQueryKey } from "@/shell/workspace-context/queryKeys";
import { useWorkspaceContext } from "@/shell/workspace-context/WorkspaceContext";
import { useSubmitKey } from "@/shared/http/submit-once";
import { useFormChangesWarning } from "@/features/procurement/shared/navigation";

import {
  checkSku, createItem, errorMessage, fieldErrors, findDuplicateItems, getCategoryDefaults, previewSku, updateItem, type DefaultField, type Item, type ItemInput, type ItemOptions, type ItemType, type Lifecycle,
} from "../api/items-api";
import { ErrorBanner, NONE, orNull, withNone } from "../item-format";

type Values = {
  type: ItemType; code: string; name: string; categoryId: string; description: string; salesDescription: string; purchaseDescription: string; brand: string;
  manufacturerName: string; manufacturerPartNumber: string; baseUomId: string; salesUomId: string; salesUomFactor: number; purchaseUomId: string; purchaseUomFactor: number;
  isSellable: boolean; isPurchasable: boolean; hsnSacCode: string; taxCategoryId: string; trackingType: string;
  requiresExpiryDate: boolean; shelfLifeDays: number; valuationMethod: string; netWeight: number; grossWeight: number; weightUomId: string; length: number; width: number;
  height: number; dimensionUomId: string; barcode: string; alternateBarcodes: string; isVariantTemplate: boolean; inventoryProfileId: string; accountingProfileId: string;
};
// Each category default, the form value it fills and the value it falls back to.
const DEFAULT_FIELDS: Array<[DefaultField, string]> = [["valuationMethod", "moving_average"], ["inventoryProfileId", NONE], ["accountingProfileId", NONE], ["taxCategoryId", NONE], ["hsnSacCode", ""]];

const number = (value: number | null | undefined) => (value === null || value === undefined ? Number.NaN : value);
const numberOrNull = (value: number) => (Number.isFinite(value) ? value : null);

function initial(item?: Item): Values {
  return {
    type: item?.type ?? "stock", code: item?.code ?? "", name: item?.name ?? "", categoryId: item?.categoryId ?? NONE, description: item?.description ?? "",
    salesDescription: item?.salesDescription ?? "", purchaseDescription: item?.purchaseDescription ?? "", brand: item?.brand ?? "", manufacturerName: item?.manufacturerName ?? "",
    manufacturerPartNumber: item?.manufacturerPartNumber ?? "", baseUomId: item?.baseUomId ?? "",
    salesUomId: item && item.salesUomId !== item.baseUomId ? item.salesUomId : NONE, salesUomFactor: item?.salesUomFactor ?? 1,
    purchaseUomId: item && item.purchaseUomId !== item.baseUomId ? item.purchaseUomId : NONE, purchaseUomFactor: item?.purchaseUomFactor ?? 1,
    isSellable: item?.isSellable ?? true, isPurchasable: item?.isPurchasable ?? true, hsnSacCode: item?.hsnSacCode ?? "", taxCategoryId: item?.taxCategoryId ?? NONE,
    trackingType: item?.trackingType ?? "none",
    requiresExpiryDate: item?.requiresExpiryDate ?? false, shelfLifeDays: number(item?.shelfLifeDays), valuationMethod: item?.valuationMethod ?? "moving_average",
    netWeight: number(item?.netWeight), grossWeight: number(item?.grossWeight), weightUomId: item?.weightUomId ?? NONE, length: number(item?.length), width: number(item?.width),
    height: number(item?.height), dimensionUomId: item?.dimensionUomId ?? NONE, barcode: "", alternateBarcodes: "", isVariantTemplate: item?.isVariantTemplate ?? false,
    inventoryProfileId: item?.inventoryProfileId ?? NONE, accountingProfileId: item?.accountingProfileId ?? NONE,
  };
}

function toInput(values: Values): ItemInput {
  const service = values.type === "service";
  const stock = values.type === "stock" && !values.isVariantTemplate;
  const input: ItemInput = {
    type: values.isVariantTemplate && values.type === "stock" ? "non_stock" : values.type, name: values.name.trim(), categoryId: orNull(values.categoryId),
    description: values.description.trim() || null, salesDescription: values.salesDescription.trim() || null, purchaseDescription: values.purchaseDescription.trim() || null,
    brand: values.brand.trim() || null, manufacturerName: values.manufacturerName.trim() || null, manufacturerPartNumber: values.manufacturerPartNumber.trim() || null,
    baseUomId: values.baseUomId, salesUomId: orNull(values.salesUomId), salesUomFactor: orNull(values.salesUomId) ? values.salesUomFactor : null,
    purchaseUomId: orNull(values.purchaseUomId), purchaseUomFactor: orNull(values.purchaseUomId) ? values.purchaseUomFactor : null,
    hsnSacCode: values.hsnSacCode.trim() || null, taxCategoryId: orNull(values.taxCategoryId), accountingProfileId: orNull(values.accountingProfileId),
  };
  if (!service) input.inventoryProfileId = orNull(values.inventoryProfileId);
  if (!values.isVariantTemplate) Object.assign(input, { isSellable: values.isSellable, isPurchasable: values.isPurchasable });
  if (values.code.trim()) input.code = values.code.trim();
  if (stock) Object.assign(input, {
    trackingType: values.trackingType, requiresExpiryDate: values.trackingType === "batch" && values.requiresExpiryDate,
    shelfLifeDays: values.trackingType === "batch" && values.requiresExpiryDate ? numberOrNull(values.shelfLifeDays) : null, valuationMethod: values.valuationMethod,
  });
  if (!service) Object.assign(input, {
    netWeight: numberOrNull(values.netWeight), grossWeight: numberOrNull(values.grossWeight), weightUomId: orNull(values.weightUomId),
    length: numberOrNull(values.length), width: numberOrNull(values.width), height: numberOrNull(values.height), dimensionUomId: orNull(values.dimensionUomId),
  });
  return input;
}


export function ItemForm({ options, item, onSaved, onCancel }: { options: ItemOptions; item?: Item; onSaved: (item: Item) => void; onCancel: () => void }) {
  const workspace = useWorkspaceContext();
  const editing = Boolean(item);
  const can = options.capabilities;
  const [values, setValues] = useState<Values>(() => initial(item));
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [error, setError] = useState<string | null>(null);
  // Category defaults still as inherited (field -> where from); a field changed by hand is the user's own from then on.
  const [inherited, setInherited] = useState<Partial<Record<DefaultField, string>>>({});
  const [ownFields, setOwnFields] = useState<Set<string>>(() => new Set());
  // A new item's SKU: generated on save, or typed — as the numbering setting and the user's permissions allow.
  const skuSetting = options.sku.mode;
  const canGenerate = skuSetting !== "manual" && can.generateSku;
  const canType = skuSetting !== "automatic" && can.enterSku;
  const [skuChoice, setSkuChoice] = useState<"generate" | "type">(canGenerate ? "generate" : "type");
  const generating = !editing && skuChoice === "generate";
  const set = <K extends keyof Values>(key: K) => (value: Values[K]) => {
    setValues((current) => ({ ...current, [key]: value }));
    setErrors((current) => ({ ...current, [key]: "" }));
    if (DEFAULT_FIELDS.some(([field]) => field === key)) {
      setInherited((current) => { const next = { ...current }; delete next[key as DefaultField]; return next; });
      setOwnFields((current) => new Set(current).add(key));
    }
  };
  const service = values.type === "service";
  const template = values.isVariantTemplate;
  const stock = values.type === "stock" && !template;
  // Who may change which group of fields; on a new item the creator sets everything except cost.
  const may = {
    inventory: !editing || can.editInventory, units: !editing || can.manageUnits, tracking: !editing || can.configureTracking, accounting: !editing || can.configureAccounting,
    tax: !editing || can.editTax, cost: can.editCost && options.showsCost, barcodes: can.manageIdentifiers,
  };
  const dirty = useFormChangesWarning(values);

  // A new item takes its category's defaults, resolved through the parents to the company default, for every field not set by hand.
  const [categoryError, setCategoryError] = useState<string | null>(null);
  const chooseCategory = (categoryId: string) => {
    setValues((current) => ({ ...current, categoryId }));
    setErrors((current) => ({ ...current, categoryId: "" }));
    if (editing) return;
    setCategoryError(null);
    if (categoryId === NONE) { setInherited({}); return; }
    getCategoryDefaults(categoryId).then((defaults) => {
      const fill: Partial<Values> = {};
      const from: Partial<Record<DefaultField, string>> = {};
      for (const [field, fallback] of DEFAULT_FIELDS) {
        if (ownFields.has(field)) continue;
        const entry = defaults[field];
        (fill as Record<string, unknown>)[field] = entry?.value ?? fallback;
        if (entry?.value) from[field] = entry.source === "company" ? "Company default" : `Inherited from ${entry.fromName}`;
      }
      setValues((current) => (current.categoryId === categoryId ? { ...current, ...fill } : current));
      setInherited(from);
    }).catch((failure) => setCategoryError(errorMessage(failure, "The category's defaults could not be loaded.")));
  };
  const hint = (field: DefaultField, fallback?: string) => inherited[field] ?? fallback;

  const skuPreview = useQuery({
    queryKey: scopedQueryKey(workspace, "products", "sku-preview", orNull(values.categoryId)),
    queryFn: () => previewSku(orNull(values.categoryId)),
    enabled: generating,
    staleTime: 10_000,
  });
  const [typedSku, setTypedSku] = useState("");
  useEffect(() => {
    const timer = setTimeout(() => setTypedSku(!editing && skuChoice === "type" ? values.code.trim() : ""), 400);
    return () => clearTimeout(timer);
  }, [values.code, skuChoice, editing]);
  const skuCheck = useQuery({
    queryKey: scopedQueryKey(workspace, "products", "sku-check", typedSku),
    queryFn: () => checkSku(typedSku),
    enabled: Boolean(typedSku),
    staleTime: 5_000,
  });
  const skuHint = skuCheck.data && !skuCheck.data.valid ? skuCheck.data.problem
    : skuCheck.data?.reason === "in_use" ? `Already the SKU of ${skuCheck.data.holder?.name} (${skuCheck.data.holder?.code}).`
    : skuCheck.data?.reason === "previous" ? `Used before by ${skuCheck.data.holder?.name} (now ${skuCheck.data.holder?.code}); a SKU is never reused.` : null;

  const [probe, setProbe] = useState({ code: "", name: "", barcode: "", manufacturerName: "", manufacturerPartNumber: "" });
  useEffect(() => {
    const timer = setTimeout(() => setProbe({ code: values.code.trim(), name: values.name.trim(), barcode: values.barcode.trim(), manufacturerName: values.manufacturerName.trim(),
      manufacturerPartNumber: values.manufacturerPartNumber.trim() }), 450);
    return () => clearTimeout(timer);
  }, [values.code, values.name, values.barcode, values.manufacturerName, values.manufacturerPartNumber]);
  const duplicates = useQuery({
    queryKey: scopedQueryKey(workspace, "products", "duplicates", probe, item?.id ?? null),
    queryFn: () => findDuplicateItems({ ...probe, excludeId: item?.id ?? null }),
    enabled: probe.name.length >= 3 || Boolean(probe.code || probe.barcode || probe.manufacturerPartNumber),
    staleTime: 30_000,
  });
  const matches = duplicates.data?.matches ?? [];
  const strong = matches.filter((match) => match.strength === "strong");

  const submitKey = useSubmitKey();
  const save = useMutation({
    mutationFn: (status: Lifecycle | null) => submitKey.run(async () => {
      const input = toInput(values);
      // A generated SKU is the server's: nothing is sent for it.
      if (!item && generating) delete input.code;
      if (!item) {
        const barcodes = [values.barcode, ...values.alternateBarcodes.split(/[\s,;]+/)].map((value) => value.trim()).filter(Boolean);
        for (const field of ["inventoryProfileId", "accountingProfileId"] as const) if (!ownFields.has(field) || !input[field]) delete input[field];
        return createItem({ ...input, isVariantTemplate: template || undefined, barcode: barcodes[0] ?? null, alternateBarcodes: barcodes.slice(1), status: status ?? "active" });
      }
      const before = toInput(initial(item));
      const changed = Object.fromEntries(Object.entries(input).filter(([key, value]) => JSON.stringify(value ?? null) !== JSON.stringify((before as Record<string, unknown>)[key] ?? null)));
      return updateItem(item.id, { ...changed, expectedVersion: item.version });
    }),
    onSuccess: onSaved,
    onError: (failure) => { setErrors(fieldErrors(failure)); setError(errorMessage(failure)); },
  });
  const submit = (status: Lifecycle | null) => {
    const missing: Record<string, string> = {};
    if (!values.name.trim()) missing.name = "Enter the item name.";
    if (!editing && skuChoice === "type" && !values.code.trim()) missing.code = "Enter the SKU.";
    if (!editing && skuChoice === "type" && skuHint) missing.code = skuHint;
    if (!values.baseUomId) missing.baseUomId = service ? "Choose the unit the service is sold in, such as Hour." : "Choose the base unit.";
    if (status === "active" && stock && values.categoryId === NONE) missing.categoryId = "A stock item needs a category.";
    if (Object.keys(missing).length) { setErrors(missing); return; }
    setError(null);
    save.mutate(status);
  };

  // Every category by its path; one that does not hold this item type cannot be chosen.
  const itemType: ItemType = template && values.type === "stock" ? "non_stock" : values.type;
  const categoryChoices = [{ value: NONE, label: "No category" }, ...options.categories.map((entry) => ({
    value: entry.id, label: entry.effectiveItemTypes.includes(itemType) ? entry.name : `${entry.name} (not for this type)`, isDisabled: !entry.effectiveItemTypes.includes(itemType),
  }))];
  const profileChoices = (list: ItemOptions["inventoryProfiles"]) => withNone(list.map((entry) => ({ value: entry.id, label: entry.name })), "None (account mappings apply)");
  const uomOptions = (category?: string) => options.uoms.filter((uom) => !category || uom.category === category).map((uom) => ({ value: uom.id, label: `${uom.name} (${uom.code})` }));
  const baseCode = options.uoms.find((uom) => uom.id === values.baseUomId)?.code ?? "base units";
  const unitChoices = withNone(uomOptions().filter((entry) => entry.value !== values.baseUomId), "Same as base unit");
  // A tax category for goods only is not offered for a service, nor one for services only for goods.
  const taxChoices = withNone(options.taxCategories.filter((entry) => entry.appliesTo !== (service ? "goods" : "services"))
    .map((entry) => ({ value: entry.id, label: [entry.name, entry.gstRate !== null ? `GST ${entry.gstRate}%` : null, entry.cessRate ? `Cess ${entry.cessRate}%` : null].filter(Boolean).join(" · ") })));

  return (
    <div className="flex flex-col gap-5">
      <ErrorBanner message={error} />

      <FormSection title="Basic information">
        <TextField className="sm:col-span-2" label="Item name" isRequired value={values.name} onChange={set("name")} errorMessage={errors.name} autoFocus={!editing} />
        <div className="flex flex-col gap-2">
          {!editing && canGenerate && canType && (
            <RadioGroup aria-label="How the SKU is given" orientation="horizontal" value={skuChoice} onChange={(value) => { setSkuChoice(value as "generate" | "type"); setErrors((current) => ({ ...current, code: "" })); }}>
              <Radio value="generate">Generate</Radio>
              <Radio value="type">Enter manually</Radio>
            </RadioGroup>
          )}
          {generating ? (
            <TextField label="SKU" isReadOnly value="" placeholder={skuPreview.data ? `${skuPreview.data.sku} (expected)` : "Generated on save"} errorMessage={errors.code}
              description={skuPreview.data ? `Generated on save${skuPreview.data.prefixSource === "category" ? ` with ${skuPreview.data.prefixFrom}'s prefix ${skuPreview.data.prefix}` : ""}. The final number is taken when you save.` : "Generated on save."} />
          ) : (
            <TextField label="SKU" isRequired={!editing} value={values.code} onChange={(value) => set("code")(value.toUpperCase())} isReadOnly={editing} isDisabled={!editing && !canType}
              description={editing ? "To correct the SKU, use Change SKU on the item page. The item, its stock and documents stay the same."
                : !canType ? "You may not type SKUs here." : skuCheck.data?.available ? `${skuCheck.data.sku} is free.` : "Letters, numbers, dashes, dots, underscores or slashes; no spaces. Up to 40."}
              errorMessage={errors.code || (skuHint ?? undefined)} />
          )}
        </div>
        <Select label="Item type" isRequired selectedKey={values.type} isDisabled={!may.inventory} onSelectionChange={(key) => set("type")(String(key) as ItemType)}
          options={options.types.map((entry) => ({ value: entry.code, label: entry.label }))} errorMessage={errors.type}
          description={service ? "No inventory: no warehouse stock, batches or serials." : stock ? "Quantity tracked in warehouses, valued in Inventory." : "Bought or sold physically, but stock is not tracked."} />
        <ComboBox label="Category" isRequired={stock} selectedKey={values.categoryId} onSelectionChange={(key) => key !== null && chooseCategory(String(key))}
          options={categoryChoices} errorMessage={errors.categoryId ?? categoryError ?? undefined} isDisabled={editing} placeholder="Search categories"
          description={editing ? "To move the item to another category, use Reclassify on the item page." : "The category fills in its defaults; you can still change each one."} />
        {!service && <TextField label="Brand" value={values.brand} onChange={set("brand")} errorMessage={errors.brand} />}
        {!service && <TextField label="Manufacturer" value={values.manufacturerName} onChange={set("manufacturerName")} errorMessage={errors.manufacturerName} />}
        {!service && <TextField label="Manufacturer part number" value={values.manufacturerPartNumber} onChange={(value) => set("manufacturerPartNumber")(value.toUpperCase())} errorMessage={errors.manufacturerPartNumber} />}
        <TextArea className="sm:col-span-2" label="Description" description="Internal." rows={2} value={values.description} onChange={set("description")} />
        {!editing && !service && (
          <div className="sm:col-span-2">
            <Checkbox isSelected={values.isVariantTemplate} onChange={set("isVariantTemplate")}>This is a variant template (T-Shirt), with variants (Black / Small …) as their own items</Checkbox>
            {template && <p className="mt-1 text-xs text-text-muted">A template is never stocked, bought or sold. Create its variants from the item page; each has its own SKU, barcode and stock.</p>}
          </div>
        )}
      </FormSection>

      {matches.length > 0 && (
        <div role={strong.length ? "alert" : "status"} className={`flex flex-col gap-1 rounded-[var(--radius-control)] border px-3 py-2 text-sm ${strong.length ? "border-warning-emphasis/40 bg-warning-soft" : "border-border bg-surface-muted"}`}>
          <p className="font-medium">{strong.length ? "Already in the catalogue" : "Possibly the same item"}</p>
          {matches.map((match) => (
            <p key={`${match.id}-${match.reasons[0]?.signal}`} className="flex flex-wrap items-center gap-2">
              <Badge tone={match.strength === "strong" ? "warning" : "neutral"}>{match.reasons.map((reason) => reason.label).join(", ")}</Badge>
              <Link href={match.href} target="_blank" className="text-brand underline-offset-2 hover:underline">{match.name} ({match.code})</Link>
            </p>
          ))}
          {!strong.length && <p className="text-xs text-text-muted">Two items may share a name. Save if this is a different item.</p>}
        </div>
      )}

      {!template && (
        <FormSection title="Commercial use" description="Purchase orders offer only purchasable items; quotations and orders only sellable ones.">
          <Checkbox isSelected={values.isPurchasable} onChange={set("isPurchasable")}>Purchasable</Checkbox>
          <Checkbox isSelected={values.isSellable} onChange={set("isSellable")}>Sellable</Checkbox>
          {values.isSellable && <TextArea className="sm:col-span-2" label="Sales description" description="Copied onto quotations, orders and invoices." rows={2} value={values.salesDescription} onChange={set("salesDescription")} />}
          {values.isPurchasable && <TextArea className="sm:col-span-2" label="Purchase description" rows={2} value={values.purchaseDescription} onChange={set("purchaseDescription")} />}
        </FormSection>
      )}

      <FormSection title="Units" description={editing ? "More units (a carton of 120) are added under Units & Identifiers." : "More units can be added after saving, under Units & Identifiers."}>
        <Select label={service ? "Unit" : "Base unit"} isRequired isDisabled={editing && !can.editInventory} selectedKey={values.baseUomId || null} placeholder="Choose a unit"
          onSelectionChange={(key) => set("baseUomId")(String(key))} options={uomOptions()} errorMessage={errors.baseUomId}
          description={service ? "Hour, Day, Month, Licence…" : "Stock is always counted in this unit. It cannot change once the item is used."} />
        <span aria-hidden="true" />
        {(values.isPurchasable || template) && (
          <>
            <Select label="Purchase unit" selectedKey={values.purchaseUomId} onSelectionChange={(key) => set("purchaseUomId")(String(key))} options={unitChoices} isDisabled={!may.units} errorMessage={errors.purchaseUomId} />
            {values.purchaseUomId !== NONE ? (
              <NumberField label={`${baseCode} per purchase unit`} value={values.purchaseUomFactor} onChange={set("purchaseUomFactor")} minValue={0.000001} isDisabled={!may.units} errorMessage={errors.purchaseUomFactor} />
            ) : <span aria-hidden="true" />}
          </>
        )}
        {(values.isSellable || template) && (
          <>
            <Select label="Sales unit" selectedKey={values.salesUomId} onSelectionChange={(key) => set("salesUomId")(String(key))} options={unitChoices} isDisabled={!may.units} errorMessage={errors.salesUomId} />
            {values.salesUomId !== NONE ? (
              <NumberField label={`${baseCode} per sales unit`} value={values.salesUomFactor} onChange={set("salesUomFactor")} minValue={0.000001} isDisabled={!may.units} errorMessage={errors.salesUomFactor} />
            ) : <span aria-hidden="true" />}
          </>
        )}
      </FormSection>

      {stock && (
        <FormSection title="Inventory" description="On-hand, reserved and available stock, batches and serials are kept by Inventory transactions, never typed here.">
          <Select label="Tracking mode" selectedKey={values.trackingType} isDisabled={!may.tracking} onSelectionChange={(key) => set("trackingType")(String(key))}
            options={options.trackingModes.map((entry) => ({ value: entry.code, label: entry.label }))} errorMessage={errors.trackingType}
            description="Fixed once stock has moved. Serial needs a whole-number base unit." />
          <Select label="Valuation method" selectedKey={values.valuationMethod} isDisabled={!may.accounting} onSelectionChange={(key) => set("valuationMethod")(String(key))}
            options={options.valuationMethods.map((entry) => ({ value: entry.code, label: entry.label }))} errorMessage={errors.valuationMethod} description={hint("valuationMethod")} />
          {values.trackingType === "batch" && (
            <>
              <div className="flex items-end"><Checkbox isSelected={values.requiresExpiryDate} isDisabled={!may.tracking} onChange={set("requiresExpiryDate")}>Expiry tracking: every batch needs an expiry date</Checkbox></div>
              {values.requiresExpiryDate ? (
                <NumberField label="Typical shelf life (days)" value={values.shelfLifeDays} onChange={set("shelfLifeDays")} minValue={1} maxValue={36500} isDisabled={!may.tracking} errorMessage={errors.shelfLifeDays} />
              ) : <span aria-hidden="true" />}
            </>
          )}
        </FormSection>
      )}

      <FormSection title="Tax" description="Defaults for documents: the tax engine works out CGST, SGST or IGST on each document. Changes apply to new documents only.">
        <TextField label={service ? "SAC" : "HSN"} value={values.hsnSacCode} onChange={(value) => set("hsnSacCode")(value.replace(/\s/g, ""))} isDisabled={!may.tax}
          description={hint("hsnSacCode", service ? "6 digits starting 99, such as 998313." : "4, 6 or 8 digits, such as 8413.")} errorMessage={errors.hsnSacCode} />
        <Select label="Tax profile" selectedKey={values.taxCategoryId} isDisabled={!may.tax} onSelectionChange={(key) => set("taxCategoryId")(String(key))} options={taxChoices}
          errorMessage={errors.taxCategoryId} description={hint("taxCategoryId")} />
      </FormSection>

      {!template && (
        <FormSection title="Accounting" description="Finance's profiles decide which accounts this item posts to. Changing a category later never changes them.">
          {!service && (
            <Select label="Inventory profile" selectedKey={values.inventoryProfileId} isDisabled={!can.configureAccounting} onSelectionChange={(key) => set("inventoryProfileId")(String(key))}
              options={profileChoices(options.inventoryProfiles)} errorMessage={errors.inventoryProfileId} description={hint("inventoryProfileId", "Inventory asset and goods-received clearing accounts.")} />
          )}
          <Select label="Accounting profile" selectedKey={values.accountingProfileId} isDisabled={!can.configureAccounting} onSelectionChange={(key) => set("accountingProfileId")(String(key))}
            options={profileChoices(options.accountingProfiles)} errorMessage={errors.accountingProfileId} description={hint("accountingProfileId", "Revenue, expense, cost of goods sold and price variance accounts.")} />
        </FormSection>
      )}

      {!editing && !service && !template && may.barcodes && (
        <FormSection title="Identifiers" description="Barcodes are unique in your organization. More can be added later, also per unit (a carton barcode).">
          <TextField label="Primary barcode" value={values.barcode} onChange={(value) => set("barcode")(value.replace(/\s/g, ""))} description="UPC, EAN, GTIN or your own code." errorMessage={errors.barcode} />
          <TextField label="Alternate barcodes" value={values.alternateBarcodes} onChange={set("alternateBarcodes")} description="Separate several with commas." />
        </FormSection>
      )}

      {!service && (
        <FormSection title="Physical details" description="Optional. Used for shipping, storage and packaging.">
          <NumberField label="Net weight" value={values.netWeight} onChange={set("netWeight")} minValue={0} errorMessage={errors.netWeight} />
          <NumberField label="Gross weight" value={values.grossWeight} onChange={set("grossWeight")} minValue={0} errorMessage={errors.grossWeight} />
          <Select label="Weight unit" selectedKey={values.weightUomId} onSelectionChange={(key) => set("weightUomId")(String(key))} options={withNone(uomOptions("weight"))} errorMessage={errors.weightUomId} />
          <span aria-hidden="true" />
          <NumberField label="Length" value={values.length} onChange={set("length")} minValue={0} errorMessage={errors.length} />
          <NumberField label="Width" value={values.width} onChange={set("width")} minValue={0} errorMessage={errors.width} />
          <NumberField label="Height" value={values.height} onChange={set("height")} minValue={0} errorMessage={errors.height} />
          <Select label="Dimension unit" selectedKey={values.dimensionUomId} onSelectionChange={(key) => set("dimensionUomId")(String(key))} options={withNone(uomOptions("length"))} errorMessage={errors.dimensionUomId} />
        </FormSection>
      )}

      <div className="flex flex-wrap justify-end gap-2">
        <Button variant="secondary" onPress={onCancel}>Cancel</Button>
        {editing ? (
          <Button variant="primary" onPress={() => submit(null)} isLoading={save.isPending || save.isSuccess} isDisabled={strong.length > 0 || !dirty}>Save changes</Button>
        ) : (
          <>
            <Button variant="outline" onPress={() => submit("draft")} isLoading={save.isPending && save.variables === "draft"} isDisabled={strong.length > 0 || save.isPending}>Save draft</Button>
            <Button variant="primary" onPress={() => submit("active")} isLoading={(save.isPending && save.variables === "active") || save.isSuccess} isDisabled={strong.length > 0 || save.isPending}>
              {template ? "Create template" : "Activate item"}
            </Button>
          </>
        )}
      </div>
    </div>
  );
}
