// Purchase Returns. Loosely typed: the module validates every input.
type QueryClient = { query(text: string, values?: unknown[]): Promise<{ rows: any[]; rowCount?: number | null }> };
export declare function cancelDraftPurchaseReturn(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function createPurchaseReturn(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function createPurchaseReturnFromGoodsReceipt(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function createPurchaseReturnFromPurchaseOrder(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function createPurchaseReturnFromRejection(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function postPurchaseReturn(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function reversePostedPurchaseReturn(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function updateDraftPurchaseReturn(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function validatePurchaseReturnForPosting(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function getPurchaseReturnFinancialStatus(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function getReturnBillingAllocations(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function linkReplacementPurchaseOrder(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function linkSupplierCreditToPurchaseReturn(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function linkSupplierRefund(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function recordPurchaseReturnResolution(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function recordSupplierAcknowledgment(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function getReturnableGoodsReceiptLines(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function getGoodsReceiptReturnSummary(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function getPurchaseOrderReturnSummary(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function getPurchaseReturn(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function getPurchaseReturnInventoryMovements(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function getSupplierPurchaseReturns(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function listPurchaseReturns(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function listPurchaseReturnFiles(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function readPurchaseReturnFile(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function removePurchaseReturnFile(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function uploadPurchaseReturnFile(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function getPurchaseReturnOptions(context: any): any;
export declare function calculateRemainingReturnableQuantity(line: any): any;
export declare function preparePurchaseReturnFileUpload(...args: any[]): Promise<any>;
export declare const PURCHASE_RETURN_FILE_ENTITY: string;
export declare const PURCHASE_RETURN_COMMERCIAL_REASONS: readonly string[];
export declare const PURCHASE_RETURN_EXPECTED_RESOLUTIONS: Record<string, string>;
export declare const PURCHASE_RETURN_PERMISSIONS: Record<string, string>;
export declare const PURCHASE_RETURN_REASONS: ReadonlyArray<{ code: string; label: string }>;
export declare const PURCHASE_RETURN_VIEWS: ReadonlyArray<{ key: string; label: string }>;
export declare class PurchaseReturnError extends Error { status: number; code: string; details?: unknown; }
