BEGIN;

-- CRM role hierarchy correction (generated by
-- scripts/database/generate-crm-canonical-role-migration.mjs from the
-- canonical ROLE_TEMPLATES in packages/permissions/src/roles.js — do not edit
-- by hand; regenerate instead).
--
-- Built-in (is_system) roles cannot be edited from the UI, and bootstrap only
-- ever inserts, so older tenants kept whatever CRM grants earlier migrations
-- gave them (036/037 granted Contact/Account sensitive access to nine roles
-- the templates never included) while new tenants got only the templates.
-- This makes every tenant's built-in roles carry exactly the canonical CRM
-- permissions: missing grants are added and CRM grants outside the canonical
-- set are removed. Only crm.* keys on is_system roles are touched — custom
-- roles and every non-CRM permission are left exactly as they are.
-- Idempotent: running it again changes nothing.
--
-- Notable changes: Sales Manager loses crm.records.view_all (now team-scoped
-- through crm_sales_teams); Company Administrator keeps only crm.view and
-- crm.reports.view; Contact/Account sensitive access is granted consistently
-- to the CRM/sales roles that work with customer contacts. Resource-specific
-- visibility replaces the umbrella crm.records.view_all where a role needs
-- only one kind of record: Marketing -> crm.leads.view_all, Customer Success
-- -> crm.customers.view_all, Partner Manager -> partner relationships
-- (crm.partners.manage); Auditor and Read-only gain company-wide CRM read.
-- To reverse, re-run the previous grants (036/037 and the prior templates);
-- no data other than role_permissions rows is affected.

INSERT INTO permissions (key, name, category, description) VALUES
  ('crm.leads.view_all', 'View all CRM Leads', 'CRM', 'See every Lead in the permitted companies/branches regardless of owner. Does not widen Opportunities, Accounts or Activities.'),
  ('crm.customers.view_all', 'View all customer Accounts', 'CRM', 'See every customer Account (not prospects), its Contacts and the Activities logged on them, regardless of owner.')
ON CONFLICT (key) DO UPDATE SET name=EXCLUDED.name, category=EXCLUDED.category, description=EXCLUDED.description;

CREATE TEMP TABLE crm_canonical_role_permissions (slug text NOT NULL, permission_key text NOT NULL) ON COMMIT DROP;

INSERT INTO crm_canonical_role_permissions (slug, permission_key) VALUES
  ('auditor', 'crm.export'),
  ('auditor', 'crm.records.view_all'),
  ('auditor', 'crm.reports.view'),
  ('auditor', 'crm.view'),
  ('company_administrator', 'crm.reports.view'),
  ('company_administrator', 'crm.view'),
  ('crm_administrator', 'crm.accounts.manage'),
  ('crm_administrator', 'crm.accounts.view_sensitive'),
  ('crm_administrator', 'crm.activities.manage'),
  ('crm_administrator', 'crm.ai.manage'),
  ('crm_administrator', 'crm.analytics.manage'),
  ('crm_administrator', 'crm.automation.manage'),
  ('crm_administrator', 'crm.campaigns.manage'),
  ('crm_administrator', 'crm.capture.manage'),
  ('crm_administrator', 'crm.communications.manage'),
  ('crm_administrator', 'crm.contacts.view_sensitive'),
  ('crm_administrator', 'crm.customers.view_all'),
  ('crm_administrator', 'crm.customization.manage'),
  ('crm_administrator', 'crm.data-quality.manage'),
  ('crm_administrator', 'crm.export'),
  ('crm_administrator', 'crm.field-sales.manage'),
  ('crm_administrator', 'crm.import'),
  ('crm_administrator', 'crm.integrations.manage'),
  ('crm_administrator', 'crm.leads.manage'),
  ('crm_administrator', 'crm.leads.view_all'),
  ('crm_administrator', 'crm.leads.view_sensitive'),
  ('crm_administrator', 'crm.opportunities.manage'),
  ('crm_administrator', 'crm.partners.manage'),
  ('crm_administrator', 'crm.playbooks.manage'),
  ('crm_administrator', 'crm.privacy.manage'),
  ('crm_administrator', 'crm.records.view_all'),
  ('crm_administrator', 'crm.reports.view'),
  ('crm_administrator', 'crm.revenue.manage'),
  ('crm_administrator', 'crm.saved_views.share'),
  ('crm_administrator', 'crm.settings.manage'),
  ('crm_administrator', 'crm.view'),
  ('customer_success_manager', 'crm.accounts.manage'),
  ('customer_success_manager', 'crm.activities.manage'),
  ('customer_success_manager', 'crm.analytics.manage'),
  ('customer_success_manager', 'crm.communications.manage'),
  ('customer_success_manager', 'crm.contacts.view_sensitive'),
  ('customer_success_manager', 'crm.customers.view_all'),
  ('customer_success_manager', 'crm.playbooks.manage'),
  ('customer_success_manager', 'crm.reports.view'),
  ('customer_success_manager', 'crm.revenue.manage'),
  ('customer_success_manager', 'crm.view'),
  ('marketing_manager', 'crm.activities.manage'),
  ('marketing_manager', 'crm.analytics.manage'),
  ('marketing_manager', 'crm.automation.manage'),
  ('marketing_manager', 'crm.campaigns.manage'),
  ('marketing_manager', 'crm.capture.manage'),
  ('marketing_manager', 'crm.communications.manage'),
  ('marketing_manager', 'crm.contacts.view_sensitive'),
  ('marketing_manager', 'crm.export'),
  ('marketing_manager', 'crm.import'),
  ('marketing_manager', 'crm.integrations.manage'),
  ('marketing_manager', 'crm.leads.manage'),
  ('marketing_manager', 'crm.leads.view_all'),
  ('marketing_manager', 'crm.leads.view_sensitive'),
  ('marketing_manager', 'crm.reports.view'),
  ('marketing_manager', 'crm.saved_views.share'),
  ('marketing_manager', 'crm.view'),
  ('partner_manager', 'crm.activities.manage'),
  ('partner_manager', 'crm.analytics.manage'),
  ('partner_manager', 'crm.field-sales.manage'),
  ('partner_manager', 'crm.opportunities.manage'),
  ('partner_manager', 'crm.partners.manage'),
  ('partner_manager', 'crm.reports.view'),
  ('partner_manager', 'crm.view'),
  ('read_only', 'crm.records.view_all'),
  ('read_only', 'crm.reports.view'),
  ('read_only', 'crm.view'),
  ('sales_head', 'crm.accounts.manage'),
  ('sales_head', 'crm.accounts.view_sensitive'),
  ('sales_head', 'crm.activities.manage'),
  ('sales_head', 'crm.analytics.manage'),
  ('sales_head', 'crm.communications.manage'),
  ('sales_head', 'crm.contacts.view_sensitive'),
  ('sales_head', 'crm.leads.manage'),
  ('sales_head', 'crm.leads.view_sensitive'),
  ('sales_head', 'crm.opportunities.manage'),
  ('sales_head', 'crm.playbooks.manage'),
  ('sales_head', 'crm.records.view_all'),
  ('sales_head', 'crm.reports.view'),
  ('sales_head', 'crm.revenue.manage'),
  ('sales_head', 'crm.saved_views.share'),
  ('sales_head', 'crm.view'),
  ('sales_manager', 'crm.accounts.manage'),
  ('sales_manager', 'crm.accounts.view_sensitive'),
  ('sales_manager', 'crm.activities.manage'),
  ('sales_manager', 'crm.analytics.manage'),
  ('sales_manager', 'crm.communications.manage'),
  ('sales_manager', 'crm.contacts.view_sensitive'),
  ('sales_manager', 'crm.leads.manage'),
  ('sales_manager', 'crm.leads.view_sensitive'),
  ('sales_manager', 'crm.opportunities.manage'),
  ('sales_manager', 'crm.playbooks.manage'),
  ('sales_manager', 'crm.reports.view'),
  ('sales_manager', 'crm.revenue.manage'),
  ('sales_manager', 'crm.saved_views.share'),
  ('sales_manager', 'crm.view'),
  ('sales_operations', 'crm.accounts.view_sensitive'),
  ('sales_operations', 'crm.activities.manage'),
  ('sales_operations', 'crm.analytics.manage'),
  ('sales_operations', 'crm.contacts.view_sensitive'),
  ('sales_operations', 'crm.customization.manage'),
  ('sales_operations', 'crm.data-quality.manage'),
  ('sales_operations', 'crm.export'),
  ('sales_operations', 'crm.import'),
  ('sales_operations', 'crm.leads.manage'),
  ('sales_operations', 'crm.leads.view_sensitive'),
  ('sales_operations', 'crm.opportunities.manage'),
  ('sales_operations', 'crm.records.view_all'),
  ('sales_operations', 'crm.reports.view'),
  ('sales_operations', 'crm.saved_views.share'),
  ('sales_operations', 'crm.settings.manage'),
  ('sales_operations', 'crm.view'),
  ('sales_representative', 'crm.accounts.manage'),
  ('sales_representative', 'crm.accounts.view_sensitive'),
  ('sales_representative', 'crm.activities.manage'),
  ('sales_representative', 'crm.communications.manage'),
  ('sales_representative', 'crm.contacts.view_sensitive'),
  ('sales_representative', 'crm.field-sales.manage'),
  ('sales_representative', 'crm.leads.manage'),
  ('sales_representative', 'crm.leads.view_sensitive'),
  ('sales_representative', 'crm.opportunities.manage'),
  ('sales_representative', 'crm.playbooks.manage'),
  ('sales_representative', 'crm.reports.view'),
  ('sales_representative', 'crm.view'),
  ('support_manager', 'crm.view');

-- Organisation Owner and System Administrator: every CRM permission in the catalog.
INSERT INTO crm_canonical_role_permissions (slug, permission_key)
SELECT role_slug.slug, permission.key
  FROM (VALUES ('organization_owner'), ('system_administrator')) AS role_slug(slug)
 CROSS JOIN permissions permission
 WHERE permission.key LIKE 'crm.%';

-- Remove CRM grants on built-in roles that the canonical matrix does not include.
DELETE FROM role_permissions role_permission
 USING roles role
 WHERE role_permission.role_id = role.id
   AND role.is_system = true
   AND role.slug IN ('accountant', 'accounts_payable_executive', 'accounts_receivable_executive', 'asset_manager', 'auditor', 'buyer', 'company_administrator', 'crm_administrator', 'customer_success_manager', 'employee', 'finance_manager', 'goods_receipt_user', 'hr_manager', 'inventory_manager', 'manufacturing_manager', 'marketing_manager', 'organization_owner', 'partner_manager', 'pos_cashier', 'pos_manager', 'pos_supervisor', 'project_manager', 'purchase_approver', 'purchase_manager', 'purchase_requester', 'quality_manager', 'read_only', 'sales_head', 'sales_manager', 'sales_operations', 'sales_representative', 'supplier_manager', 'support_manager', 'system_administrator', 'tax_compliance_accountant', 'treasury_executive')
   AND role_permission.permission_key LIKE 'crm.%'
   AND NOT EXISTS (
     SELECT 1 FROM crm_canonical_role_permissions canonical
      WHERE canonical.slug = role.slug AND canonical.permission_key = role_permission.permission_key
   );

-- Add the canonical CRM grants that are missing (only for permissions that exist in the catalog).
INSERT INTO role_permissions (role_id, permission_key)
SELECT role.id, canonical.permission_key
  FROM roles role
  JOIN crm_canonical_role_permissions canonical ON canonical.slug = role.slug
  JOIN permissions permission ON permission.key = canonical.permission_key
 WHERE role.is_system = true
ON CONFLICT DO NOTHING;

COMMIT;
