import type { CrmResourceKey } from "@vercentlabs/shared-types";
import { PERMISSIONS } from "@/core/authorization";
import { company, config, owner, status, workspace, type CrmDefinition } from "./core";

export const analyticsForecastingDefinitions = {
"forecast-targets": config(
    "forecast-targets",
    "Forecast targets",
    "target",
    PERMISSIONS.crmSettingsManage,
    [
      company,
      {
        name: "userId",
        label: "Salesperson",
        type: "select",
        optionsKey: "users",
      },
      {
        name: "periodStart",
        label: "Period start",
        type: "date",
        required: true,
      },
      { name: "periodEnd", label: "Period end", type: "date", required: true },
      {
        name: "currencyCode",
        label: "Currency",
        type: "select",
        optionsKey: "currencies",
      },
      { name: "targetAmount", label: "Target amount", type: "number" },
    ],
  ),
"forecast-periods": config(
    "forecast-periods",
    "Forecast periods",
    "forecast period",
    PERMISSIONS.crmRevenueManage,
    [
      company,
      { name: "name", label: "Name", type: "text", required: true },
      {
        name: "periodType",
        label: "Period type",
        type: "select",
        options: status("week", "month", "quarter", "year", "custom"),
      },
      {
        name: "periodStart",
        label: "Period start",
        type: "date",
        required: true,
      },
      { name: "periodEnd", label: "Period end", type: "date", required: true },
      {
        name: "currencyCode",
        label: "Currency",
        type: "select",
        optionsKey: "currencies",
      },
      { name: "freezeAt", label: "Freeze at", type: "datetime-local" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status("planned", "open", "frozen", "closed"),
      },
    ],
  ),
"forecast-submissions": {
    key: "forecast-submissions",
    title: "Forecast submissions",
    singular: "forecast submission",
    group: "Work",
    description:
      "Submit seller and manager forecasts with pipeline, best-case, commit, closed and confidence values.",
    permission: PERMISSIONS.crmRevenueManage,
    columns: [
      { key: "ownerUserId", label: "Owner", optionsKey: "users" },
      { key: "periodId", label: "Period", optionsKey: "forecastPeriods" },
      { key: "commitAmount", label: "Commit", format: "currency" },
      { key: "bestCaseAmount", label: "Best case", format: "currency" },
      { key: "closedAmount", label: "Closed", format: "currency" },
      { key: "status", label: "Status", format: "status" },
    ],
    fields: [
      company,
      {
        name: "periodId",
        label: "Forecast period",
        type: "select",
        optionsKey: "forecastPeriods",
        required: true,
      },
      {
        name: "teamId",
        label: "Sales team",
        type: "select",
        optionsKey: "salesTeams",
      },
      {
        name: "territoryId",
        label: "Territory",
        type: "select",
        optionsKey: "territories",
      },
      owner,
      { name: "pipelineAmount", label: "Pipeline amount", type: "number" },
      { name: "bestCaseAmount", label: "Best-case amount", type: "number" },
      { name: "commitAmount", label: "Commit amount", type: "number" },
      { name: "closedAmount", label: "Closed amount", type: "number" },
      {
        name: "managerAdjustment",
        label: "Manager adjustment",
        type: "number",
      },
      {
        name: "currencyCode",
        label: "Currency",
        type: "select",
        optionsKey: "currencies",
      },
      { name: "confidencePercent", label: "Confidence %", type: "number" },
      { name: "notes", label: "Notes", type: "textarea" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status(
          "draft",
          "submitted",
          "approved",
          "rejected",
          "superseded",
        ),
      },
    ],
  },
"report-definitions": workspace(
    "report-definitions",
    "Custom report definitions",
    "report definition",
    "Analytics",
    PERMISSIONS.crmAnalyticsManage,
    "Define governed dimensions, measures, filters and visualisations without embedding tenant SQL.",
    [
      company,
      { name: "name", label: "Name", type: "text", required: true },
      { name: "resource", label: "Resource", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea" },
      { name: "dimensions", label: "Dimensions JSON", type: "textarea" },
      { name: "measures", label: "Measures JSON", type: "textarea" },
      { name: "filters", label: "Filters JSON", type: "textarea" },
      {
        name: "visualization",
        label: "Visualisation",
        type: "select",
        options: status(
          "table",
          "metric",
          "bar",
          "line",
          "area",
          "funnel",
          "pie",
        ),
      },
      { name: "isShared", label: "Shared", type: "checkbox" },
      owner,
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status("draft", "active", "inactive", "archived"),
      },
    ],
    [
      { key: "name", label: "Report" },
      { key: "resource", label: "Resource" },
      { key: "visualization", label: "Visualisation", format: "status" },
      { key: "isShared", label: "Shared" },
      { key: "status", label: "Status", format: "status" },
    ],
  ),
dashboards: workspace(
    "dashboards",
    "CRM dashboards",
    "dashboard",
    "Analytics",
    PERMISSIONS.crmAnalyticsManage,
    "Create role, team, company and organisation dashboards from governed report definitions.",
    [
      company,
      { name: "name", label: "Name", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea" },
      {
        name: "audience",
        label: "Audience",
        type: "select",
        options: status("private", "team", "company", "organization"),
      },
      { name: "isDefault", label: "Default dashboard", type: "checkbox" },
      { name: "layout", label: "Layout JSON", type: "textarea" },
      owner,
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status("active", "inactive", "archived"),
      },
    ],
    [
      { key: "name", label: "Dashboard" },
      { key: "audience", label: "Audience", format: "status" },
      { key: "isDefault", label: "Default" },
      { key: "ownerUserId", label: "Owner", optionsKey: "users" },
      { key: "status", label: "Status", format: "status" },
    ],
  ),
"dashboard-widgets": workspace(
    "dashboard-widgets",
    "Dashboard widgets",
    "dashboard widget",
    "Analytics",
    PERMISSIONS.crmAnalyticsManage,
    "Compose dashboards using governed metrics, reports, activity feeds and chart widgets.",
    [
      company,
      {
        name: "dashboardId",
        label: "Dashboard",
        type: "select",
        optionsKey: "dashboards",
        required: true,
      },
      {
        name: "reportDefinitionId",
        label: "Report definition",
        type: "select",
        optionsKey: "reportDefinitions",
      },
      { name: "title", label: "Title", type: "text", required: true },
      {
        name: "widgetType",
        label: "Widget type",
        type: "select",
        options: status(
          "metric",
          "table",
          "bar",
          "line",
          "area",
          "funnel",
          "pie",
          "activity_feed",
        ),
        required: true,
      },
      { name: "position", label: "Position JSON", type: "textarea" },
      { name: "configuration", label: "Configuration JSON", type: "textarea" },
      { name: "sequence", label: "Sequence", type: "number" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status("active", "inactive"),
      },
    ],
    [
      { key: "title", label: "Widget" },
      { key: "dashboardId", label: "Dashboard", optionsKey: "dashboards" },
      { key: "widgetType", label: "Type", format: "status" },
      { key: "sequence", label: "Sequence" },
      { key: "status", label: "Status", format: "status" },
    ],
  ),
campaigns: {
    key: "campaigns",
    title: "Campaigns",
    singular: "campaign",
    group: "Engagement",
    description:
      "Attribute lead origin, budget, responses and conversions to governed campaigns.",
    permission: PERMISSIONS.crmCampaignsManage,
    columns: [
      { key: "code", label: "Code" },
      { key: "name", label: "Campaign" },
      { key: "campaignType", label: "Type" },
      { key: "status", label: "Status", format: "status" },
      { key: "budget", label: "Budget", format: "currency" },
      { key: "startDate", label: "Start", format: "date" },
    ],
    fields: [
      company,
      { name: "name", label: "Campaign name", type: "text", required: true },
      {
        name: "campaignType",
        label: "Campaign type",
        type: "select",
        options: status(
          "email",
          "event",
          "webinar",
          "referral",
          "partner",
          "advertising",
          "social",
          "other",
        ),
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status(
          "planned",
          "active",
          "paused",
          "completed",
          "cancelled",
        ),
      },
      { name: "startDate", label: "Start date", type: "date" },
      { name: "endDate", label: "End date", type: "date" },
      { name: "budget", label: "Budget", type: "number" },
      { name: "expectedRevenue", label: "Expected revenue", type: "number" },
      { name: "actualCost", label: "Actual cost", type: "number" },
      owner,
      { name: "description", label: "Description", type: "textarea" },
    ],
  },
} satisfies Partial<Record<CrmResourceKey, CrmDefinition>>;
