import type { CrmResourceKey } from "@vercentlabs/shared-types";
import { PERMISSIONS } from "@/core/authorization";
import { branch, company, config, owner, status, workspace, type CrmDefinition } from "./core";

export const conversionHandoffDefinitions = {
"partner-accounts": workspace(
    "partner-accounts",
    "Partner accounts",
    "partner account",
    "Partner",
    PERMISSIONS.crmPartnersManage,
    "Manage referral, reseller, distributor, systems-integrator, technology and affiliate partners with governed tiers and agreements.",
    [
      company,
      {
        name: "partyId",
        label: "Business partner",
        type: "select",
        optionsKey: "parties",
        required: true,
      },
      { name: "name", label: "Partner name", type: "text", required: true },
      {
        name: "partnerType",
        label: "Partner type",
        type: "select",
        options: status(
          "referral",
          "reseller",
          "distributor",
          "system_integrator",
          "technology",
          "affiliate",
          "other",
        ),
        required: true,
      },
      {
        name: "tier",
        label: "Tier",
        type: "select",
        options: status(
          "registered",
          "silver",
          "gold",
          "platinum",
          "strategic",
        ),
      },
      { name: "region", label: "Region", type: "text" },
      owner,
      { name: "agreementStart", label: "Agreement start", type: "date" },
      { name: "agreementEnd", label: "Agreement end", type: "date" },
      { name: "referralPercent", label: "Referral percent", type: "number" },
      { name: "metadata", label: "Metadata JSON", type: "textarea" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status(
          "prospect",
          "active",
          "suspended",
          "inactive",
          "archived",
        ),
      },
    ],
    [
      { key: "name", label: "Partner" },
      { key: "partnerType", label: "Type", format: "status" },
      { key: "tier", label: "Tier", format: "status" },
      { key: "region", label: "Region" },
      { key: "status", label: "Status", format: "status" },
    ],
  ),
"partner-deals": workspace(
    "partner-deals",
    "Partner deals",
    "partner deal",
    "Partner",
    PERMISSIONS.crmPartnersManage,
    "Register, approve and attribute partner-sourced or partner-influenced leads and opportunities.",
    [
      company,
      {
        name: "partnerAccountId",
        label: "Partner",
        type: "select",
        optionsKey: "partnerAccounts",
        required: true,
      },
      {
        name: "opportunityId",
        label: "Opportunity",
        type: "select",
        optionsKey: "opportunities",
      },
      { name: "leadId", label: "Lead", type: "select", optionsKey: "leads" },
      {
        name: "dealRegistrationCode",
        label: "Registration code",
        type: "text",
        required: true,
      },
      { name: "registeredAt", label: "Registered at", type: "datetime-local" },
      { name: "expiresAt", label: "Expires at", type: "datetime-local" },
      { name: "partnerOwnerName", label: "Partner owner", type: "text" },
      {
        name: "internalOwnerUserId",
        label: "Internal owner",
        type: "select",
        optionsKey: "users",
      },
      { name: "expectedValue", label: "Expected value", type: "number" },
      {
        name: "currencyCode",
        label: "Currency",
        type: "select",
        optionsKey: "currencies",
      },
      {
        name: "contributionPercent",
        label: "Contribution percent",
        type: "number",
      },
      { name: "notes", label: "Notes", type: "textarea" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status(
          "submitted",
          "approved",
          "rejected",
          "active",
          "won",
          "lost",
          "expired",
          "cancelled",
        ),
      },
    ],
    [
      { key: "dealRegistrationCode", label: "Registration" },
      {
        key: "partnerAccountId",
        label: "Partner",
        optionsKey: "partnerAccounts",
      },
      { key: "expectedValue", label: "Value", format: "currency" },
      { key: "registeredAt", label: "Registered", format: "datetime" },
      { key: "status", label: "Status", format: "status" },
    ],
  ),
} satisfies Partial<Record<CrmResourceKey, CrmDefinition>>;
