import type { CrmResourceKey } from "@vercentlabs/shared-types";
import { PERMISSIONS } from "@/core/authorization";
import { branch, company, config, owner, status, workspace, type CrmDefinition } from "./core";

export const dataOperationsDefinitions = {
integrations: config(
    "integrations",
    "Communication integrations",
    "integration",
    PERMISSIONS.crmIntegrationsManage,
    [
      {
        name: "provider",
        label: "Provider",
        type: "select",
        options: status(
          "gmail",
          "microsoft365",
          "whatsapp",
          "twilio",
          "zoom",
          "webhook",
          "other",
        ),
      },
      {
        name: "displayName",
        label: "Display name",
        type: "text",
        required: true,
      },
      {
        name: "credentialReference",
        label: "Secret-manager reference",
        type: "text",
      },
      {
        name: "configuration",
        label: "Non-secret configuration JSON",
        type: "textarea",
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status("disconnected", "connected", "error", "disabled"),
      },
    ],
  ),
"webhook-subscriptions": config(
    "webhook-subscriptions",
    "Webhook subscriptions",
    "webhook",
    PERMISSIONS.crmIntegrationsManage,
    [
      { name: "name", label: "Name", type: "text", required: true },
      {
        name: "endpointUrl",
        label: "Endpoint URL",
        type: "text",
        required: true,
      },
      { name: "eventTypes", label: "Event types JSON", type: "textarea" },
      {
        name: "secretReference",
        label: "Secret-manager reference",
        type: "text",
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status("active", "inactive"),
      },
    ],
  ),
"consent-events": {
    key: "consent-events",
    title: "Consent evidence",
    singular: "consent event",
    group: "Engagement",
    description:
      "Keep immutable channel, purpose, lawful-basis and evidence records for customer communication consent.",
    permission: PERMISSIONS.crmPrivacyManage,
    columns: [
      { key: "channel", label: "Channel", format: "status" },
      { key: "purpose", label: "Purpose", format: "status" },
      { key: "action", label: "Action", format: "status" },
      { key: "source", label: "Source" },
      { key: "occurredAt", label: "Occurred", format: "datetime" },
    ],
    fields: [
      company,
      { name: "leadId", label: "Lead", type: "select", optionsKey: "leads" },
      {
        name: "contactId",
        label: "Contact",
        type: "select",
        optionsKey: "contacts",
      },
      {
        name: "partyId",
        label: "Account",
        type: "select",
        optionsKey: "parties",
      },
      {
        name: "channel",
        label: "Channel",
        type: "select",
        options: status("email", "sms", "whatsapp", "call", "postal", "all"),
        required: true,
      },
      {
        name: "purpose",
        label: "Purpose",
        type: "select",
        options: status(
          "sales",
          "marketing",
          "service",
          "transactional",
          "research",
          "other",
        ),
      },
      {
        name: "action",
        label: "Action",
        type: "select",
        options: status(
          "granted",
          "withdrawn",
          "suppressed",
          "resubscribed",
          "expired",
        ),
        required: true,
      },
      {
        name: "lawfulBasis",
        label: "Lawful basis",
        type: "select",
        options: status(
          "consent",
          "contract",
          "legal_obligation",
          "legitimate_interest",
          "vital_interest",
          "public_task",
        ),
      },
      {
        name: "source",
        label: "Source",
        type: "select",
        options: status(
          "form",
          "manual",
          "import",
          "integration",
          "preference_center",
          "system",
        ),
      },
      { name: "evidence", label: "Evidence JSON", type: "textarea" },
      { name: "occurredAt", label: "Occurred at", type: "datetime-local" },
      { name: "expiresAt", label: "Expires at", type: "datetime-local" },
    ],
  },
"privacy-requests": {
    key: "privacy-requests",
    title: "Privacy requests",
    singular: "privacy request",
    group: "Work",
    description:
      "Track access, export, correction, deletion, restriction, objection and consent-withdrawal requests.",
    permission: PERMISSIONS.crmPrivacyManage,
    columns: [
      { key: "requestType", label: "Request", format: "status" },
      { key: "subjectType", label: "Subject", format: "status" },
      { key: "requesterName", label: "Requester" },
      { key: "dueAt", label: "Due", format: "datetime" },
      { key: "status", label: "Status", format: "status" },
    ],
    fields: [
      company,
      {
        name: "requestType",
        label: "Request type",
        type: "select",
        options: status(
          "access",
          "export",
          "correction",
          "deletion",
          "restriction",
          "objection",
          "consent_withdrawal",
        ),
        required: true,
      },
      {
        name: "subjectType",
        label: "Subject type",
        type: "select",
        options: status("lead", "contact", "party"),
        required: true,
      },
      { name: "subjectId", label: "Subject ID", type: "text", required: true },
      { name: "requesterName", label: "Requester name", type: "text" },
      { name: "requesterEmail", label: "Requester email", type: "email" },
      {
        name: "identityVerifiedAt",
        label: "Identity verified",
        type: "datetime-local",
      },
      {
        name: "dueAt",
        label: "Due at",
        type: "datetime-local",
        required: true,
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status(
          "received",
          "verification_pending",
          "in_progress",
          "completed",
          "rejected",
          "cancelled",
        ),
      },
      { name: "resolutionNotes", label: "Resolution notes", type: "textarea" },
      { name: "completedAt", label: "Completed at", type: "datetime-local" },
      {
        name: "assignedTo",
        label: "Assigned to",
        type: "select",
        optionsKey: "users",
      },
    ],
  },
"data-quality-scores": {
    key: "data-quality-scores",
    title: "Data quality scores",
    singular: "data quality score",
    group: "Configuration",
    description:
      "Measure completeness, validity, freshness and duplicate risk for governed CRM records.",
    permission: PERMISSIONS.crmDataQualityManage,
    columns: [
      { key: "entityType", label: "Entity", format: "status" },
      { key: "entityId", label: "Entity ID" },
      { key: "overallScore", label: "Overall", format: "score" },
      { key: "duplicateRiskScore", label: "Duplicate risk", format: "score" },
      { key: "calculatedAt", label: "Calculated", format: "datetime" },
    ],
    fields: [
      company,
      {
        name: "entityType",
        label: "Entity type",
        type: "select",
        options: status("lead", "opportunity", "party", "contact"),
        required: true,
      },
      { name: "entityId", label: "Entity ID", type: "text", required: true },
      {
        name: "completenessScore",
        label: "Completeness score",
        type: "number",
        required: true,
      },
      {
        name: "validityScore",
        label: "Validity score",
        type: "number",
        required: true,
      },
      {
        name: "freshnessScore",
        label: "Freshness score",
        type: "number",
        required: true,
      },
      {
        name: "duplicateRiskScore",
        label: "Duplicate risk",
        type: "number",
        required: true,
      },
      {
        name: "overallScore",
        label: "Overall score",
        type: "number",
        required: true,
      },
      { name: "issues", label: "Issues JSON", type: "textarea" },
      { name: "calculatedAt", label: "Calculated at", type: "datetime-local" },
      {
        name: "calculationVersion",
        label: "Calculation version",
        type: "text",
      },
    ],
  },
"sync-accounts": workspace(
    "sync-accounts",
    "Email and calendar sync accounts",
    "sync account",
    "Engagement",
    PERMISSIONS.crmIntegrationsManage,
    "Manage provider-neutral inbox, calendar, telephony and messaging synchronization accounts without storing raw credentials.",
    [
      company,
      {
        name: "userId",
        label: "User",
        type: "select",
        optionsKey: "users",
        required: true,
      },
      {
        name: "provider",
        label: "Provider",
        type: "select",
        options: status(
          "gmail",
          "microsoft365",
          "imap",
          "calendar",
          "telephony",
          "whatsapp",
          "other",
        ),
        required: true,
      },
      { name: "externalAccountId", label: "External account ID", type: "text" },
      {
        name: "displayName",
        label: "Display name",
        type: "text",
        required: true,
      },
      {
        name: "credentialReference",
        label: "Secret-manager reference",
        type: "text",
        required: true,
      },
      { name: "scopes", label: "Scopes JSON", type: "textarea" },
      {
        name: "syncDirection",
        label: "Sync direction",
        type: "select",
        options: status("inbound", "outbound", "two_way"),
      },
      { name: "syncCursor", label: "Sync cursor", type: "text" },
      { name: "lastSyncedAt", label: "Last synced", type: "datetime-local" },
      { name: "lastError", label: "Last error", type: "textarea" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status(
          "disconnected",
          "connected",
          "syncing",
          "error",
          "disabled",
        ),
      },
    ],
    [
      { key: "displayName", label: "Account" },
      { key: "provider", label: "Provider", format: "status" },
      { key: "syncDirection", label: "Direction", format: "status" },
      { key: "lastSyncedAt", label: "Last synced", format: "datetime" },
      { key: "status", label: "Status", format: "status" },
    ],
  ),
"custom-object-definitions": workspace(
    "custom-object-definitions",
    "Custom object definitions",
    "custom object",
    "Customization",
    PERMISSIONS.crmCustomizationManage,
    "Create governed tenant-specific CRM objects without modifying core tables or bypassing permissions.",
    [
      { name: "objectKey", label: "Object key", type: "text", required: true },
      {
        name: "singularLabel",
        label: "Singular label",
        type: "text",
        required: true,
      },
      {
        name: "pluralLabel",
        label: "Plural label",
        type: "text",
        required: true,
      },
      { name: "description", label: "Description", type: "textarea" },
      { name: "primaryNameField", label: "Primary name field", type: "text" },
      { name: "companyScoped", label: "Company scoped", type: "checkbox" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status("draft", "active", "inactive", "archived"),
      },
    ],
    [
      { key: "objectKey", label: "Object key" },
      { key: "pluralLabel", label: "Object" },
      { key: "primaryNameField", label: "Primary field" },
      { key: "companyScoped", label: "Company scoped" },
      { key: "status", label: "Status", format: "status" },
    ],
  ),
"custom-field-definitions": workspace(
    "custom-field-definitions",
    "Custom field definitions",
    "custom field",
    "Customization",
    PERMISSIONS.crmCustomizationManage,
    "Define typed, validated and ordered fields for tenant custom CRM objects.",
    [
      {
        name: "objectDefinitionId",
        label: "Custom object",
        type: "select",
        optionsKey: "customObjects",
        required: true,
      },
      { name: "fieldKey", label: "Field key", type: "text", required: true },
      { name: "label", label: "Label", type: "text", required: true },
      {
        name: "dataType",
        label: "Data type",
        type: "select",
        options: status(
          "text",
          "textarea",
          "number",
          "currency",
          "boolean",
          "date",
          "datetime",
          "email",
          "phone",
          "url",
          "select",
          "multi_select",
          "json",
        ),
        required: true,
      },
      { name: "required", label: "Required", type: "checkbox" },
      { name: "uniqueValue", label: "Unique", type: "checkbox" },
      { name: "indexed", label: "Indexed", type: "checkbox" },
      {
        name: "dependsOnFieldKey",
        label: "Depends on field key (select/multi_select only)",
        type: "text",
      },
      {
        name: "options",
        label: 'Options JSON — flat array, or {"parentValue":["childOption",...]} if "Depends on field key" is set',
        type: "textarea",
      },
      { name: "defaultValue", label: "Default JSON", type: "textarea" },
      { name: "validation", label: "Validation JSON", type: "textarea" },
      { name: "sequence", label: "Sequence", type: "number" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status("active", "inactive", "archived"),
      },
    ],
    [
      { key: "label", label: "Field" },
      {
        key: "objectDefinitionId",
        label: "Object",
        optionsKey: "customObjects",
      },
      { key: "fieldKey", label: "Key" },
      { key: "dataType", label: "Type", format: "status" },
      { key: "status", label: "Status", format: "status" },
    ],
  ),
"custom-records": workspace(
    "custom-records",
    "Custom CRM records",
    "custom record",
    "Customization",
    PERMISSIONS.crmCustomizationManage,
    "Store governed tenant-defined CRM records as validated JSON linked to an active custom-object definition.",
    [
      company,
      {
        name: "objectDefinitionId",
        label: "Custom object",
        type: "select",
        optionsKey: "customObjects",
        required: true,
      },
      {
        name: "recordName",
        label: "Record name",
        type: "text",
        required: true,
      },
      owner,
      { name: "data", label: "Record data JSON", type: "textarea" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status("active", "inactive", "archived"),
      },
    ],
    [
      { key: "recordName", label: "Record" },
      {
        key: "objectDefinitionId",
        label: "Object",
        optionsKey: "customObjects",
      },
      { key: "ownerUserId", label: "Owner", optionsKey: "users" },
      { key: "updatedAt", label: "Updated", format: "datetime" },
      { key: "status", label: "Status", format: "status" },
    ],
  ),
"saved-views": config(
    "saved-views",
    "Saved views",
    "saved view",
    PERMISSIONS.crmView,
    [
      {
        name: "resource",
        label: "Resource",
        type: "select",
        options: status(
          "leads",
          "opportunities",
          "activities",
          "campaigns",
          "communications",
        ),
      },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "filters", label: "Filters JSON", type: "textarea" },
      { name: "sort", label: "Sort JSON", type: "textarea" },
      { name: "columns", label: "Columns JSON", type: "textarea" },
      { name: "isDefault", label: "Default view", type: "checkbox" },
    ],
  ),
"automation-rules": config(
    "automation-rules",
    "Automation rules",
    "automation rule",
    PERMISSIONS.crmAutomationManage,
    [
      { name: "name", label: "Name", type: "text", required: true },
      {
        name: "eventType",
        label: "Event",
        type: "select",
        options: status(
          "lead.created",
          "lead.updated",
          "lead.qualified",
          "opportunity.created",
          "opportunity.stage_changed",
          "activity.overdue",
          "campaign.member_responded",
        ),
      },
      { name: "sequence", label: "Sequence", type: "number" },
      { name: "conditions", label: "Conditions JSON", type: "textarea" },
      { name: "actions", label: "Actions JSON", type: "textarea" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status("active", "inactive"),
      },
    ],
  ),
} satisfies Partial<Record<CrmResourceKey, CrmDefinition>>;
