import type { CrmResourceKey } from "@vercentlabs/shared-types";
import { PERMISSIONS } from "@/core/authorization";
import { branch, company, config, owner, status, workspace, type CrmDefinition } from "./core";

export const leadLifecycleDefinitions = {
"lost-reasons": config(
    "lost-reasons",
    "Won / lost reasons",
    "outcome reason",
    PERMISSIONS.crmSettingsManage,
    [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "code", label: "Code", type: "text", required: true },
      { name: "category", label: "Category", type: "text" },
      {
        name: "outcomeType",
        label: "Outcome",
        type: "select",
        options: status("won", "lost", "both"),
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status("active", "inactive"),
      },
    ],
  ),
"qualification-criteria": workspace(
    "qualification-criteria",
    "Lead qualification criteria",
    "qualification criterion",
    "Configuration",
    PERMISSIONS.crmSettingsManage,
    "Configure the readiness checklist evaluated before a Lead can be marked qualified — required criteria block the decision, recommended criteria are shown but never block it.",
    [
      { name: "criterionKey", label: "Criterion key", type: "text", required: true },
      { name: "label", label: "Label", type: "text", required: true },
      {
        name: "tier",
        label: "Tier",
        type: "select",
        options: status("required", "recommended"),
        required: true,
      },
      {
        name: "checkType",
        label: "Check type",
        type: "select",
        options: status("non_empty_any", "positive_number"),
        required: true,
      },
      {
        name: "fieldKeys",
        label: "Lead field key(s), comma-separated",
        type: "text",
        required: true,
      },
      { name: "sequence", label: "Sequence", type: "number" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status("active", "inactive"),
      },
    ],
    [
      { key: "label", label: "Criterion" },
      { key: "tier", label: "Tier", format: "status" },
      { key: "checkType", label: "Check" },
      { key: "sequence", label: "Sequence" },
      { key: "status", label: "Status", format: "status" },
    ],
  ),
"scoring-rules": config(
    "scoring-rules",
    "Lead scoring rules",
    "scoring rule",
    PERMISSIONS.crmAutomationManage,
    [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "sequence", label: "Sequence", type: "number" },
      { name: "fieldName", label: "Lead field", type: "text", required: true },
      {
        name: "operator",
        label: "Operator",
        type: "select",
        options: status(
          "equals",
          "not_equals",
          "contains",
          "not_empty",
          "empty",
          "greater_than",
          "less_than",
          "in",
        ),
      },
      { name: "comparisonValue", label: "Comparison JSON", type: "textarea" },
      { name: "points", label: "Points", type: "number" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status("active", "inactive"),
      },
    ],
  ),
"assignment-rules": config(
    "assignment-rules",
    "Assignment rules",
    "assignment rule",
    PERMISSIONS.crmSettingsManage,
    [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "sequence", label: "Sequence", type: "number" },
      { name: "criteria", label: "Criteria JSON", type: "textarea" },
      {
        name: "assignmentMode",
        label: "Mode",
        type: "select",
        options: status("fixed", "round_robin"),
      },
      {
        name: "assigneeUserId",
        label: "Fixed assignee",
        type: "select",
        optionsKey: "users",
      },
      {
        name: "roundRobinUserIds",
        label: "Round-robin user IDs JSON",
        type: "textarea",
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status("active", "inactive"),
      },
    ],
  ),
playbooks: config(
    "playbooks",
    "Sales playbooks",
    "playbook",
    PERMISSIONS.crmPlaybooksManage,
    [
      company,
      {
        name: "pipelineId",
        label: "Pipeline",
        type: "select",
        optionsKey: "pipelines",
      },
      { name: "name", label: "Name", type: "text", required: true },
      {
        name: "framework",
        label: "Framework",
        type: "select",
        options: status(
          "bant",
          "meddic",
          "meddpicc",
          "spin",
          "challenger",
          "custom",
        ),
      },
      { name: "description", label: "Description", type: "textarea" },
      { name: "guidance", label: "Guidance", type: "textarea" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status("draft", "active", "inactive", "archived"),
      },
    ],
  ),
"playbook-questions": {
    key: "playbook-questions",
    title: "Playbook questions",
    singular: "playbook question",
    group: "Configuration",
    description:
      "Define qualification evidence, stage requirements and guided questions for each playbook.",
    permission: PERMISSIONS.crmPlaybooksManage,
    columns: [
      { key: "playbookId", label: "Playbook", optionsKey: "playbooks" },
      { key: "prompt", label: "Question" },
      { key: "responseType", label: "Response", format: "status" },
      { key: "required", label: "Required" },
      { key: "blocksStageExit", label: "Blocks stage exit" },
      { key: "status", label: "Status", format: "status" },
    ],
    fields: [
      company,
      {
        name: "playbookId",
        label: "Playbook",
        type: "select",
        optionsKey: "playbooks",
        required: true,
      },
      {
        name: "stageId",
        label: "Pipeline stage",
        type: "select",
        optionsKey: "stages",
      },
      {
        name: "questionKey",
        label: "Question key",
        type: "text",
        required: true,
      },
      { name: "prompt", label: "Question", type: "textarea", required: true },
      {
        name: "responseType",
        label: "Response type",
        type: "select",
        options: status(
          "text",
          "number",
          "date",
          "boolean",
          "select",
          "multi_select",
        ),
      },
      {
        name: "responseOptions",
        label: "Response options JSON",
        type: "textarea",
      },
      { name: "required", label: "Required", type: "checkbox" },
      { name: "blocksStageExit", label: "Block stage exit", type: "checkbox" },
      { name: "sequence", label: "Sequence", type: "number" },
      { name: "scoringWeight", label: "Scoring weight", type: "number" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status("active", "inactive"),
      },
    ],
  },
"playbook-responses": {
    key: "playbook-responses",
    title: "Playbook responses",
    singular: "playbook response",
    group: "Work",
    description:
      "Capture auditable qualification evidence for leads and opportunities before governed stage progression.",
    permission: PERMISSIONS.crmPlaybooksManage,
    columns: [
      { key: "questionId", label: "Question", optionsKey: "playbookQuestions" },
      {
        key: "opportunityId",
        label: "Opportunity",
        optionsKey: "opportunities",
      },
      { key: "leadId", label: "Lead", optionsKey: "leads" },
      { key: "respondedBy", label: "Responded by", optionsKey: "users" },
      { key: "respondedAt", label: "Responded", format: "datetime" },
      { key: "source", label: "Source", format: "status" },
    ],
    fields: [
      company,
      {
        name: "playbookId",
        label: "Playbook",
        type: "select",
        optionsKey: "playbooks",
        required: true,
      },
      {
        name: "questionId",
        label: "Question",
        type: "select",
        optionsKey: "playbookQuestions",
        required: true,
      },
      {
        name: "opportunityId",
        label: "Opportunity",
        type: "select",
        optionsKey: "opportunities",
      },
      { name: "leadId", label: "Lead", type: "select", optionsKey: "leads" },
      {
        name: "response",
        label: "Response JSON",
        type: "textarea",
        required: true,
      },
      {
        name: "respondedBy",
        label: "Responded by",
        type: "select",
        optionsKey: "users",
      },
      { name: "respondedAt", label: "Responded at", type: "datetime-local" },
      {
        name: "source",
        label: "Source",
        type: "select",
        options: status("manual", "import", "integration", "ai_suggestion"),
      },
    ],
  },
"ai-predictions": workspace(
    "ai-predictions",
    "AI predictions",
    "AI prediction",
    "Intelligence",
    PERMISSIONS.crmAiManage,
    "Store explainable, expiring and reviewable lead, opportunity, account, forecast and conversation predictions.",
    [
      company,
      {
        name: "entityType",
        label: "Entity type",
        type: "select",
        options: status(
          "lead",
          "opportunity",
          "party",
          "forecast",
          "conversation",
        ),
        required: true,
      },
      { name: "entityId", label: "Entity ID", type: "text", required: true },
      {
        name: "predictionType",
        label: "Prediction type",
        type: "select",
        options: status(
          "lead_conversion",
          "opportunity_win",
          "account_growth",
          "forecast",
          "churn_risk",
          "sentiment",
          "next_best_action",
        ),
        required: true,
      },
      { name: "score", label: "Score", type: "number" },
      { name: "label", label: "Label", type: "text" },
      { name: "explanation", label: "Explanation JSON", type: "textarea" },
      { name: "inputSnapshot", label: "Input snapshot JSON", type: "textarea" },
      {
        name: "modelProvider",
        label: "Model provider",
        type: "text",
        required: true,
      },
      { name: "modelName", label: "Model name", type: "text", required: true },
      { name: "modelVersion", label: "Model version", type: "text" },
      { name: "generatedAt", label: "Generated at", type: "datetime-local" },
      { name: "expiresAt", label: "Expires at", type: "datetime-local" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status("active", "expired", "superseded", "rejected"),
      },
    ],
    [
      { key: "predictionType", label: "Prediction", format: "status" },
      { key: "entityType", label: "Entity", format: "status" },
      { key: "score", label: "Score" },
      { key: "modelName", label: "Model" },
      { key: "status", label: "Status", format: "status" },
    ],
  ),
"ai-feedback": workspace(
    "ai-feedback",
    "AI feedback",
    "AI feedback record",
    "Intelligence",
    PERMISSIONS.crmAiManage,
    "Capture immutable user feedback for predictions and recommendations to support evaluation and governance.",
    [
      company,
      {
        name: "predictionId",
        label: "Prediction",
        type: "select",
        optionsKey: "aiPredictions",
      },
      {
        name: "recommendationId",
        label: "Recommendation",
        type: "select",
        optionsKey: "recommendations",
      },
      {
        name: "userId",
        label: "User",
        type: "select",
        optionsKey: "users",
        required: true,
      },
      {
        name: "outcome",
        label: "Outcome",
        type: "select",
        options: status(
          "accepted",
          "rejected",
          "modified",
          "correct",
          "incorrect",
          "not_actionable",
        ),
        required: true,
      },
      { name: "feedback", label: "Feedback", type: "textarea" },
      {
        name: "correctedValue",
        label: "Corrected value JSON",
        type: "textarea",
      },
    ],
    [
      { key: "outcome", label: "Outcome", format: "status" },
      { key: "userId", label: "User", optionsKey: "users" },
      { key: "predictionId", label: "Prediction", optionsKey: "aiPredictions" },
      {
        key: "recommendationId",
        label: "Recommendation",
        optionsKey: "recommendations",
      },
      { key: "createdAt", label: "Created", format: "datetime" },
    ],
  ),
} satisfies Partial<Record<CrmResourceKey, CrmDefinition>>;
