import type { CrmResourceKey } from "@vercentlabs/shared-types";
import { PERMISSIONS } from "@/core/authorization";
import { branch, company, config, owner, status, workspace, type CrmDefinition } from "./core";

export const opportunityPipelineDefinitions = {
opportunities: {
    key: "opportunities",
    title: "Opportunities",
    singular: "opportunity",
    group: "Work",
    description:
      "Create and maintain governed revenue opportunities with accountable ownership and linked customer context.",
    permission: PERMISSIONS.crmOpportunitiesManage,
    columns: [
      { key: "code", label: "Code" },
      { key: "name", label: "Opportunity" },
      { key: "stageId", label: "Stage", optionsKey: "stages" },
      { key: "amount", label: "Amount", format: "currency" },
      { key: "probability", label: "Probability" },
      { key: "expectedRevenue", label: "Expected revenue", format: "currency" },
      { key: "expectedCloseDate", label: "Expected close", format: "date" },
      { key: "status", label: "Status", format: "status" },
    ],
    fields: [
      company,
      branch,
      { name: "name", label: "Opportunity name", type: "text", required: true },
      {
        name: "pipelineId",
        label: "Pipeline",
        type: "select",
        optionsKey: "pipelines",
      },
      { name: "stageId", label: "Stage", type: "select", optionsKey: "stages" },
      { name: "leadId", label: "Lead", type: "select", optionsKey: "leads" },
      {
        name: "partyId",
        label: "Customer",
        type: "select",
        optionsKey: "parties",
      },
      {
        name: "contactId",
        label: "Contact",
        type: "select",
        optionsKey: "contacts",
      },
      owner,
      { name: "amount", label: "Amount", type: "number" },
      {
        name: "currencyCode",
        label: "Currency",
        type: "select",
        optionsKey: "currencies",
      },
      { name: "probability", label: "Probability %", type: "number", formHidden: true },
      { name: "expectedCloseDate", label: "Expected close date", type: "date" },
      {
        name: "forecastCategory",
        label: "Forecast category",
        type: "select",
        options: status(
          "pipeline",
          "best_case",
          "committed",
          "closed",
          "omitted",
        ),
        formHidden: true,
      },
      { name: "nextStep", label: "Next step", type: "textarea" },
      { name: "description", label: "Description", type: "textarea" },
    ],
  },
pipelines: config(
    "pipelines",
    "Pipelines",
    "pipeline",
    PERMISSIONS.crmSettingsManage,
    [
      company,
      { name: "name", label: "Name", type: "text", required: true },
      { name: "code", label: "Code", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea" },
      { name: "isDefault", label: "Default pipeline", type: "checkbox" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status("active", "inactive"),
      },
    ],
  ),
stages: config(
    "stages",
    "Pipeline stages",
    "stage",
    PERMISSIONS.crmSettingsManage,
    [
      {
        name: "pipelineId",
        label: "Pipeline",
        type: "select",
        optionsKey: "pipelines",
        required: true,
      },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "code", label: "Code", type: "text", required: true },
      { name: "sequence", label: "Sequence", type: "number" },
      { name: "probability", label: "Probability %", type: "number" },
      {
        name: "forecastCategory",
        label: "Forecast category",
        type: "select",
        options: status(
          "pipeline",
          "best_case",
          "committed",
          "closed",
          "omitted",
        ),
      },
      { name: "isWon", label: "Won stage", type: "checkbox" },
      { name: "isLost", label: "Lost stage", type: "checkbox" },
      { name: "staleAfterDays", label: "Stale after days", type: "number" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status("active", "inactive"),
      },
    ],
  ),
competitors: config(
    "competitors",
    "Competitors",
    "competitor",
    PERMISSIONS.crmSettingsManage,
    [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "website", label: "Website", type: "text" },
      { name: "strengths", label: "Strengths", type: "textarea" },
      { name: "weaknesses", label: "Weaknesses", type: "textarea" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status("active", "inactive"),
      },
    ],
  ),
"pipeline-inspections": workspace(
    "pipeline-inspections",
    "Pipeline inspections",
    "pipeline inspection",
    "Intelligence",
    PERMISSIONS.crmRevenueManage,
    "Capture immutable pipeline-health snapshots, stage aging, inactivity, slippage and recommended actions.",
    [
      company,
      {
        name: "opportunityId",
        label: "Opportunity",
        type: "select",
        optionsKey: "opportunities",
        required: true,
      },
      { name: "inspectedAt", label: "Inspected at", type: "datetime-local" },
      { name: "stageAgeDays", label: "Stage age days", type: "number" },
      {
        name: "daysSinceActivity",
        label: "Days since activity",
        type: "number",
      },
      {
        name: "closeDateSlipDays",
        label: "Close-date slip days",
        type: "number",
      },
      { name: "amountChange", label: "Amount change", type: "number" },
      {
        name: "probabilityChange",
        label: "Probability change",
        type: "number",
      },
      {
        name: "healthScore",
        label: "Health score",
        type: "number",
        required: true,
      },
      {
        name: "healthStatus",
        label: "Health status",
        type: "select",
        options: status("healthy", "watch", "at_risk", "critical"),
        required: true,
      },
      { name: "issues", label: "Issues JSON", type: "textarea" },
      {
        name: "recommendedActions",
        label: "Recommended actions JSON",
        type: "textarea",
      },
      {
        name: "calculationVersion",
        label: "Calculation version",
        type: "text",
      },
    ],
    [
      {
        key: "opportunityId",
        label: "Opportunity",
        optionsKey: "opportunities",
      },
      { key: "healthStatus", label: "Health", format: "status" },
      { key: "healthScore", label: "Score", format: "score" },
      { key: "stageAgeDays", label: "Stage age" },
      { key: "inspectedAt", label: "Inspected", format: "datetime" },
    ],
  ),
"deal-risks": workspace(
    "deal-risks",
    "Deal risks",
    "deal risk",
    "Intelligence",
    PERMISSIONS.crmRevenueManage,
    "Track explainable opportunity risks, severity, evidence and resolution ownership.",
    [
      company,
      {
        name: "opportunityId",
        label: "Opportunity",
        type: "select",
        optionsKey: "opportunities",
        required: true,
      },
      {
        name: "riskType",
        label: "Risk type",
        type: "select",
        options: status(
          "stale_activity",
          "close_date_slip",
          "missing_stakeholder",
          "missing_next_step",
          "low_engagement",
          "competitor",
          "pricing",
          "qualification",
          "forecast",
          "custom",
        ),
        required: true,
      },
      {
        name: "severity",
        label: "Severity",
        type: "select",
        options: status("low", "medium", "high", "critical"),
      },
      { name: "title", label: "Title", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea" },
      { name: "evidence", label: "Evidence JSON", type: "textarea" },
      { name: "detectedAt", label: "Detected", type: "datetime-local" },
      { name: "resolvedAt", label: "Resolved", type: "datetime-local" },
      { name: "resolutionNotes", label: "Resolution notes", type: "textarea" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status("open", "acknowledged", "resolved", "dismissed"),
      },
    ],
    [
      { key: "title", label: "Risk" },
      {
        key: "opportunityId",
        label: "Opportunity",
        optionsKey: "opportunities",
      },
      { key: "severity", label: "Severity", format: "status" },
      { key: "detectedAt", label: "Detected", format: "datetime" },
      { key: "status", label: "Status", format: "status" },
    ],
  ),
recommendations: workspace(
    "recommendations",
    "Next-best actions",
    "recommendation",
    "Intelligence",
    PERMISSIONS.crmAiManage,
    "Govern explainable rule-based, AI-assisted and manual recommendations with human decisions and action payloads.",
    [
      company,
      {
        name: "entityType",
        label: "Entity type",
        type: "select",
        options: status(
          "lead",
          "opportunity",
          "party",
          "contact",
          "conversation",
        ),
        required: true,
      },
      { name: "entityId", label: "Entity ID", type: "text", required: true },
      {
        name: "recommendationType",
        label: "Recommendation type",
        type: "select",
        options: status(
          "next_best_action",
          "follow_up",
          "stakeholder",
          "content",
          "risk_mitigation",
          "cross_sell",
          "upsell",
          "renewal",
          "data_quality",
        ),
        required: true,
      },
      { name: "title", label: "Title", type: "text", required: true },
      {
        name: "rationale",
        label: "Rationale",
        type: "textarea",
        required: true,
      },
      { name: "actionPayload", label: "Action payload JSON", type: "textarea" },
      {
        name: "priority",
        label: "Priority",
        type: "select",
        options: status("low", "medium", "high", "urgent"),
      },
      { name: "confidence", label: "Confidence", type: "number" },
      {
        name: "source",
        label: "Source",
        type: "select",
        options: status("rules", "ai", "manual"),
      },
      { name: "modelProvider", label: "Model provider", type: "text" },
      { name: "modelName", label: "Model name", type: "text" },
      { name: "dueAt", label: "Due", type: "datetime-local" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status(
          "open",
          "accepted",
          "completed",
          "rejected",
          "expired",
          "superseded",
        ),
      },
      {
        name: "decidedBy",
        label: "Decided by",
        type: "select",
        optionsKey: "users",
      },
      { name: "decidedAt", label: "Decided at", type: "datetime-local" },
      { name: "decisionNotes", label: "Decision notes", type: "textarea" },
    ],
    [
      { key: "title", label: "Recommendation" },
      { key: "recommendationType", label: "Type", format: "status" },
      { key: "priority", label: "Priority", format: "status" },
      { key: "confidence", label: "Confidence" },
      { key: "status", label: "Status", format: "status" },
    ],
  ),
} satisfies Partial<Record<CrmResourceKey, CrmDefinition>>;
