import type { CrmResourceKey } from "@vercentlabs/shared-types";
import { PERMISSIONS } from "@/core/authorization";
import { branch, company, config, owner, status, workspace, type CrmDefinition } from "./core";

export const prospectAndRelationshipDefinitions = {
leads: {
    key: "leads",
    title: "Leads",
    singular: "lead",
    group: "Work",
    description:
      "Capture, qualify, score, assign and convert every enquiry without losing its history.",
    permission: PERMISSIONS.crmLeadsManage,
    columns: [
      { key: "code", label: "Code" },
      { key: "fullName", label: "Lead" },
      { key: "companyName", label: "Company" },
      { key: "status", label: "Status", format: "status" },
      { key: "score", label: "Score", format: "score" },
      { key: "estimatedValue", label: "Value", format: "currency" },
      { key: "nextFollowUpAt", label: "Next follow-up", format: "datetime" },
    ],
    fields: [
      company,
      branch,
      { name: "firstName", label: "First name", type: "text", required: true },
      { name: "lastName", label: "Last name", type: "text" },
      { name: "companyName", label: "Company / organisation", type: "text" },
      { name: "jobTitle", label: "Job title", type: "text" },
      { name: "email", label: "Email", type: "email" },
      {
        name: "mobile",
        label: "Mobile number",
        type: "text",
      },
      { name: "phone", label: "Alternate number", type: "text" },
      {
        name: "sourceId",
        label: "Source",
        type: "select",
        optionsKey: "sources",
      },
      { name: "referrerName", label: "Referred by", type: "text" },
      owner,
      {
        name: "priority",
        label: "Priority",
        type: "select",
        options: status("low", "medium", "high", "urgent"),
      },
      {
        name: "rating",
        label: "Rating",
        type: "select",
        options: status("cold", "warm", "hot"),
      },
      { name: "estimatedValue", label: "Estimated value", type: "number" },
      {
        name: "currencyCode",
        label: "Currency",
        type: "select",
        optionsKey: "currencies",
      },
      { name: "industry", label: "Industry", type: "text" },
      { name: "website", label: "Website", type: "text" },
      { name: "city", label: "City", type: "text" },
      { name: "state", label: "State", type: "text" },
      { name: "countryCode", label: "Country code", type: "text" },
      { name: "productInterest", label: "Product interest", type: "textarea" },
      {
        name: "nextFollowUpAt",
        label: "Next follow-up",
        type: "datetime-local",
      },
      { name: "consentEmail", label: "Email consent", type: "checkbox" },
      { name: "consentSms", label: "SMS consent", type: "checkbox" },
      { name: "consentWhatsapp", label: "WhatsApp consent", type: "checkbox" },
      { name: "doNotContact", label: "Do not contact", type: "checkbox" },
    ],
  },
sources: config(
    "sources",
    "Lead sources",
    "source",
    PERMISSIONS.crmSettingsManage,
    [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea" },
      {
        name: "channel",
        label: "Channel",
        type: "select",
        options: status(
          "website",
          "referral",
          "partner",
          "event",
          "advertising",
          "social",
          "email",
          "phone",
          "walk_in",
          "import",
          "other",
        ),
      },
      { name: "sortOrder", label: "Display order", type: "number" },
      { name: "isDefault", label: "Default source", type: "checkbox" },
    ],
  ),
tags: config("tags", "CRM tags", "tag", PERMISSIONS.crmSettingsManage, [
    { name: "name", label: "Name", type: "text", required: true },
    { name: "color", label: "Colour", type: "text" },
    {
      name: "status",
      label: "Status",
      type: "select",
      options: status("active", "inactive"),
    },
  ]),
"capture-forms": config(
    "capture-forms",
    "Lead capture forms",
    "capture form",
    PERMISSIONS.crmCaptureManage,
    [
      company,
      branch,
      { name: "name", label: "Name", type: "text", required: true },
      {
        name: "sourceId",
        label: "Source",
        type: "select",
        optionsKey: "sources",
      },
      owner,
      {
        name: "allowedOrigins",
        label: "Allowed origins JSON",
        type: "textarea",
      },
      {
        name: "requiredFields",
        label: "Required fields JSON",
        type: "textarea",
      },
      { name: "successMessage", label: "Success message", type: "textarea" },
      {
        name: "rateLimitPerHour",
        label: "Hourly submission limit",
        type: "number",
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status("active", "inactive"),
      },
    ],
  ),
"account-plans": {
    key: "account-plans",
    title: "Account plans",
    singular: "account plan",
    group: "Work",
    description:
      "Plan strategic accounts, renewal risk, health, white-space opportunities and executive sponsorship.",
    permission: PERMISSIONS.crmAccountsManage,
    columns: [
      { key: "partyId", label: "Account", optionsKey: "parties" },
      { key: "accountTier", label: "Tier", format: "status" },
      { key: "lifecycleStage", label: "Lifecycle", format: "status" },
      { key: "healthStatus", label: "Health", format: "status" },
      { key: "healthScore", label: "Score", format: "score" },
      { key: "renewalDate", label: "Renewal", format: "date" },
    ],
    fields: [
      company,
      {
        name: "partyId",
        label: "Account",
        type: "select",
        optionsKey: "parties",
        required: true,
      },
      owner,
      {
        name: "executiveSponsorUserId",
        label: "Executive sponsor",
        type: "select",
        optionsKey: "users",
      },
      {
        name: "accountTier",
        label: "Account tier",
        type: "select",
        options: status(
          "strategic",
          "enterprise",
          "growth",
          "standard",
          "long_tail",
        ),
      },
      {
        name: "lifecycleStage",
        label: "Lifecycle stage",
        type: "select",
        options: status(
          "prospect",
          "onboarding",
          "active",
          "at_risk",
          "renewal",
          "churned",
        ),
      },
      { name: "objectives", label: "Objectives JSON", type: "textarea" },
      { name: "risks", label: "Risks JSON", type: "textarea" },
      { name: "whiteSpace", label: "White-space JSON", type: "textarea" },
      { name: "successPlan", label: "Success plan JSON", type: "textarea" },
      { name: "renewalDate", label: "Renewal date", type: "date" },
      { name: "annualRevenue", label: "Annual revenue", type: "number" },
      { name: "potentialRevenue", label: "Potential revenue", type: "number" },
      { name: "healthScore", label: "Health score", type: "number" },
      {
        name: "healthStatus",
        label: "Health status",
        type: "select",
        options: status("healthy", "watch", "at_risk", "critical", "unknown"),
      },
      {
        name: "lastReviewedAt",
        label: "Last reviewed",
        type: "datetime-local",
      },
      { name: "nextReviewAt", label: "Next review", type: "datetime-local" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status("active", "inactive", "archived"),
      },
    ],
  },
"account-stakeholders": {
    key: "account-stakeholders",
    title: "Account stakeholders",
    singular: "stakeholder",
    group: "Work",
    description:
      "Map economic buyers, champions, decision makers, blockers and relationship ownership.",
    permission: PERMISSIONS.crmAccountsManage,
    columns: [
      { key: "name", label: "Stakeholder" },
      { key: "title", label: "Title" },
      { key: "stakeholderRole", label: "Role", format: "status" },
      { key: "influenceLevel", label: "Influence", format: "status" },
      { key: "sentiment", label: "Sentiment", format: "status" },
      { key: "engagementScore", label: "Engagement", format: "score" },
    ],
    fields: [
      company,
      {
        name: "accountPlanId",
        label: "Account plan",
        type: "select",
        optionsKey: "accountPlans",
        required: true,
      },
      {
        name: "contactId",
        label: "Contact",
        type: "select",
        optionsKey: "contacts",
      },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "title", label: "Title", type: "text" },
      {
        name: "stakeholderRole",
        label: "Role",
        type: "select",
        options: status(
          "economic_buyer",
          "decision_maker",
          "champion",
          "influencer",
          "user",
          "blocker",
          "procurement",
          "legal",
          "technical",
        ),
      },
      {
        name: "influenceLevel",
        label: "Influence",
        type: "select",
        options: status("low", "medium", "high", "critical"),
      },
      {
        name: "sentiment",
        label: "Sentiment",
        type: "select",
        options: status(
          "strong_supporter",
          "supporter",
          "neutral",
          "detractor",
          "strong_detractor",
          "unknown",
        ),
      },
      {
        name: "relationshipOwnerUserId",
        label: "Relationship owner",
        type: "select",
        optionsKey: "users",
      },
      { name: "engagementScore", label: "Engagement score", type: "number" },
      { name: "notes", label: "Notes", type: "textarea" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status("active", "inactive"),
      },
    ],
  },
"buying-committees": workspace(
    "buying-committees",
    "Buying committees",
    "buying committee",
    "Intelligence",
    PERMISSIONS.crmAccountsManage,
    "Model multi-stakeholder B2B decisions, authority coverage and decision process for strategic accounts and opportunities.",
    [
      company,
      {
        name: "partyId",
        label: "Account",
        type: "select",
        optionsKey: "parties",
        required: true,
      },
      {
        name: "opportunityId",
        label: "Opportunity",
        type: "select",
        optionsKey: "opportunities",
      },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "decisionProcess", label: "Decision process", type: "textarea" },
      { name: "decisionDate", label: "Decision date", type: "date" },
      { name: "coverageScore", label: "Coverage score", type: "number" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status("active", "complete", "inactive", "archived"),
      },
    ],
    [
      { key: "name", label: "Committee" },
      { key: "partyId", label: "Account", optionsKey: "parties" },
      {
        key: "opportunityId",
        label: "Opportunity",
        optionsKey: "opportunities",
      },
      { key: "coverageScore", label: "Coverage", format: "score" },
      { key: "status", label: "Status", format: "status" },
    ],
  ),
"buying-committee-members": workspace(
    "buying-committee-members",
    "Buying committee members",
    "committee member",
    "Intelligence",
    PERMISSIONS.crmAccountsManage,
    "Capture economic buyers, champions, blockers, influence, authority, sentiment and engagement gaps.",
    [
      company,
      {
        name: "committeeId",
        label: "Buying committee",
        type: "select",
        optionsKey: "buyingCommittees",
        required: true,
      },
      {
        name: "contactId",
        label: "Contact",
        type: "select",
        optionsKey: "contacts",
      },
      { name: "name", label: "Name", type: "text", required: true },
      {
        name: "memberRole",
        label: "Role",
        type: "select",
        options: status(
          "economic_buyer",
          "decision_maker",
          "champion",
          "influencer",
          "user",
          "blocker",
          "procurement",
          "legal",
          "technical",
        ),
      },
      {
        name: "influenceLevel",
        label: "Influence",
        type: "select",
        options: status("low", "medium", "high", "critical"),
      },
      {
        name: "sentiment",
        label: "Sentiment",
        type: "select",
        options: status(
          "strong_supporter",
          "supporter",
          "neutral",
          "detractor",
          "strong_detractor",
          "unknown",
        ),
      },
      { name: "engagementScore", label: "Engagement score", type: "number" },
      {
        name: "authorityConfirmed",
        label: "Authority confirmed",
        type: "checkbox",
      },
      {
        name: "relationshipOwnerUserId",
        label: "Relationship owner",
        type: "select",
        optionsKey: "users",
      },
      { name: "gaps", label: "Coverage gaps", type: "textarea" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status("active", "inactive"),
      },
    ],
    [
      { key: "name", label: "Member" },
      { key: "memberRole", label: "Role", format: "status" },
      { key: "influenceLevel", label: "Influence", format: "status" },
      { key: "sentiment", label: "Sentiment", format: "status" },
      { key: "engagementScore", label: "Engagement", format: "score" },
    ],
  ),
"relationship-edges": workspace(
    "relationship-edges",
    "Relationship graph",
    "relationship edge",
    "Intelligence",
    PERMISSIONS.crmAccountsManage,
    "Map internal and external relationships, introductions, influence, strength and validity for enterprise selling.",
    [
      company,
      {
        name: "fromEntityType",
        label: "From type",
        type: "select",
        options: status(
          "user",
          "party",
          "contact",
          "lead",
          "opportunity",
          "partner",
        ),
        required: true,
      },
      {
        name: "fromEntityId",
        label: "From entity ID",
        type: "text",
        required: true,
      },
      {
        name: "toEntityType",
        label: "To type",
        type: "select",
        options: status(
          "user",
          "party",
          "contact",
          "lead",
          "opportunity",
          "partner",
        ),
        required: true,
      },
      {
        name: "toEntityId",
        label: "To entity ID",
        type: "text",
        required: true,
      },
      {
        name: "relationshipType",
        label: "Relationship type",
        type: "select",
        options: status(
          "reports_to",
          "knows",
          "introduced_by",
          "influences",
          "champions",
          "blocks",
          "partner_of",
          "subsidiary_of",
          "custom",
        ),
        required: true,
      },
      { name: "strength", label: "Strength", type: "number" },
      {
        name: "source",
        label: "Source",
        type: "select",
        options: status("manual", "import", "integration", "ai"),
      },
      { name: "validFrom", label: "Valid from", type: "date" },
      { name: "validTo", label: "Valid to", type: "date" },
      { name: "notes", label: "Notes", type: "textarea" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status("active", "inactive", "expired"),
      },
    ],
    [
      { key: "relationshipType", label: "Relationship", format: "status" },
      { key: "fromEntityType", label: "From", format: "status" },
      { key: "toEntityType", label: "To", format: "status" },
      { key: "strength", label: "Strength", format: "score" },
      { key: "status", label: "Status", format: "status" },
    ],
  ),
"account-signals": workspace(
    "account-signals",
    "Account signals",
    "account signal",
    "Intelligence",
    PERMISSIONS.crmAccountsManage,
    "Capture intent, engagement, product, financial, service, renewal, competitive and news signals for account prioritisation.",
    [
      company,
      {
        name: "partyId",
        label: "Account",
        type: "select",
        optionsKey: "parties",
        required: true,
      },
      {
        name: "opportunityId",
        label: "Opportunity",
        type: "select",
        optionsKey: "opportunities",
      },
      {
        name: "signalType",
        label: "Signal type",
        type: "select",
        options: status(
          "intent",
          "engagement",
          "product_usage",
          "financial",
          "service",
          "renewal",
          "competitive",
          "news",
          "manual",
        ),
        required: true,
      },
      { name: "title", label: "Title", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea" },
      { name: "signalValue", label: "Signal value", type: "text" },
      { name: "score", label: "Score", type: "number" },
      { name: "occurredAt", label: "Occurred", type: "datetime-local" },
      { name: "expiresAt", label: "Expires", type: "datetime-local" },
      { name: "source", label: "Source", type: "text" },
      { name: "metadata", label: "Metadata JSON", type: "textarea" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status("active", "expired", "dismissed"),
      },
    ],
    [
      { key: "title", label: "Signal" },
      { key: "partyId", label: "Account", optionsKey: "parties" },
      { key: "signalType", label: "Type", format: "status" },
      { key: "score", label: "Score" },
      { key: "occurredAt", label: "Occurred", format: "datetime" },
    ],
  ),
"enrichment-jobs": workspace(
    "enrichment-jobs",
    "Data enrichment jobs",
    "enrichment job",
    "Intelligence",
    PERMISSIONS.crmDataQualityManage,
    "Queue provider-neutral lead, account and contact enrichment with requested fields, confidence, result and error evidence.",
    [
      company,
      {
        name: "entityType",
        label: "Entity type",
        type: "select",
        options: status("lead", "party", "contact"),
        required: true,
      },
      { name: "entityId", label: "Entity ID", type: "text", required: true },
      { name: "provider", label: "Provider", type: "text", required: true },
      {
        name: "requestedFields",
        label: "Requested fields JSON",
        type: "textarea",
      },
      { name: "resultData", label: "Result JSON", type: "textarea" },
      { name: "confidence", label: "Confidence", type: "number" },
      { name: "errorMessage", label: "Error", type: "textarea" },
      { name: "requestedAt", label: "Requested at", type: "datetime-local" },
      { name: "completedAt", label: "Completed at", type: "datetime-local" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status(
          "queued",
          "processing",
          "completed",
          "failed",
          "cancelled",
        ),
      },
      {
        name: "requestedBy",
        label: "Requested by",
        type: "select",
        optionsKey: "users",
      },
    ],
    [
      { key: "entityType", label: "Entity", format: "status" },
      { key: "provider", label: "Provider" },
      { key: "confidence", label: "Confidence" },
      { key: "requestedAt", label: "Requested", format: "datetime" },
      { key: "status", label: "Status", format: "status" },
    ],
  ),
} satisfies Partial<Record<CrmResourceKey, CrmDefinition>>;
