import type { CrmResourceKey } from "@vercentlabs/shared-types";
import { PERMISSIONS } from "@/core/authorization";
import { branch, company, config, owner, status, workspace, type CrmDefinition } from "./core";

export const salesOrganizationDefinitions = {
"sales-teams": config(
    "sales-teams",
    "Sales teams",
    "sales team",
    PERMISSIONS.crmRevenueManage,
    [
      company,
      {
        name: "parentTeamId",
        label: "Parent team",
        type: "select",
        optionsKey: "salesTeams",
      },
      { name: "code", label: "Code", type: "text", required: true },
      { name: "name", label: "Name", type: "text", required: true },
      {
        name: "managerUserId",
        label: "Manager",
        type: "select",
        optionsKey: "users",
      },
      {
        name: "defaultPipelineId",
        label: "Default pipeline",
        type: "select",
        optionsKey: "pipelines",
      },
      {
        name: "currencyCode",
        label: "Currency",
        type: "select",
        optionsKey: "currencies",
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status("active", "inactive"),
      },
    ],
  ),
"sales-team-members": {
    key: "sales-team-members",
    title: "Sales team members",
    singular: "sales team member",
    group: "Configuration",
    description:
      "Assign sellers, managers, overlays and sales-operations users to governed sales teams.",
    permission: PERMISSIONS.crmRevenueManage,
    columns: [
      { key: "teamId", label: "Sales team", optionsKey: "salesTeams" },
      { key: "userId", label: "User", optionsKey: "users" },
      { key: "memberRole", label: "Role", format: "status" },
      { key: "allocationPercent", label: "Allocation" },
      { key: "effectiveFrom", label: "Effective from", format: "date" },
      { key: "status", label: "Status", format: "status" },
    ],
    fields: [
      company,
      {
        name: "teamId",
        label: "Sales team",
        type: "select",
        optionsKey: "salesTeams",
        required: true,
      },
      {
        name: "userId",
        label: "User",
        type: "select",
        optionsKey: "users",
        required: true,
      },
      {
        name: "memberRole",
        label: "Member role",
        type: "select",
        options: status(
          "manager",
          "seller",
          "sales_ops",
          "overlay",
          "observer",
        ),
      },
      { name: "allocationPercent", label: "Allocation %", type: "number" },
      {
        name: "effectiveFrom",
        label: "Effective from",
        type: "date",
        required: true,
      },
      { name: "effectiveTo", label: "Effective to", type: "date" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status("active", "inactive"),
      },
    ],
  },
territories: config(
    "territories",
    "Territories",
    "territory",
    PERMISSIONS.crmRevenueManage,
    [
      company,
      {
        name: "parentTerritoryId",
        label: "Parent territory",
        type: "select",
        optionsKey: "territories",
      },
      { name: "code", label: "Code", type: "text", required: true },
      { name: "name", label: "Name", type: "text", required: true },
      {
        name: "territoryType",
        label: "Territory type",
        type: "select",
        options: status(
          "geographic",
          "industry",
          "account",
          "product",
          "channel",
          "named",
          "hybrid",
        ),
      },
      {
        name: "managerUserId",
        label: "Manager",
        type: "select",
        optionsKey: "users",
      },
      {
        name: "assignmentRules",
        label: "Assignment rules JSON",
        type: "textarea",
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status("draft", "active", "inactive", "archived"),
      },
    ],
  ),
"territory-assignments": {
    key: "territory-assignments",
    title: "Territory assignments",
    singular: "territory assignment",
    group: "Configuration",
    description:
      "Assign users, teams, accounts, leads and opportunities to governed sales territories.",
    permission: PERMISSIONS.crmRevenueManage,
    columns: [
      { key: "territoryId", label: "Territory", optionsKey: "territories" },
      { key: "assigneeType", label: "Assignee type", format: "status" },
      { key: "assigneeId", label: "Assignee ID" },
      { key: "assignmentRole", label: "Role", format: "status" },
      { key: "effectiveFrom", label: "Effective from", format: "date" },
      { key: "source", label: "Source", format: "status" },
    ],
    fields: [
      company,
      {
        name: "territoryId",
        label: "Territory",
        type: "select",
        optionsKey: "territories",
        required: true,
      },
      {
        name: "assigneeType",
        label: "Assignee type",
        type: "select",
        options: status("user", "team", "party", "lead", "opportunity"),
        required: true,
      },
      {
        name: "assigneeId",
        label: "Assignee UUID",
        type: "text",
        required: true,
      },
      {
        name: "assignmentRole",
        label: "Assignment role",
        type: "select",
        options: status("primary", "overlay", "shared", "manager"),
      },
      {
        name: "effectiveFrom",
        label: "Effective from",
        type: "date",
        required: true,
      },
      { name: "effectiveTo", label: "Effective to", type: "date" },
      {
        name: "source",
        label: "Source",
        type: "select",
        options: status("manual", "rule", "import", "integration"),
      },
    ],
  },
"quota-plans": config(
    "quota-plans",
    "Quota plans",
    "quota plan",
    PERMISSIONS.crmRevenueManage,
    [
      company,
      {
        name: "teamId",
        label: "Sales team",
        type: "select",
        optionsKey: "salesTeams",
      },
      {
        name: "territoryId",
        label: "Territory",
        type: "select",
        optionsKey: "territories",
      },
      {
        name: "userId",
        label: "Salesperson",
        type: "select",
        optionsKey: "users",
      },
      { name: "name", label: "Name", type: "text", required: true },
      {
        name: "quotaType",
        label: "Quota type",
        type: "select",
        options: status(
          "revenue",
          "bookings",
          "margin",
          "quantity",
          "new_logo",
          "activity",
        ),
      },
      {
        name: "periodStart",
        label: "Period start",
        type: "date",
        required: true,
      },
      { name: "periodEnd", label: "Period end", type: "date", required: true },
      {
        name: "currencyCode",
        label: "Currency",
        type: "select",
        optionsKey: "currencies",
      },
      {
        name: "targetAmount",
        label: "Target amount",
        type: "number",
        required: true,
      },
      { name: "stretchAmount", label: "Stretch amount", type: "number" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status("draft", "active", "closed", "cancelled"),
      },
    ],
  ),
"field-visits": workspace(
    "field-visits",
    "Field visits",
    "field visit",
    "Field Sales",
    PERMISSIONS.crmFieldSalesManage,
    "Plan and record customer visits, objectives, geolocation, route order, actual timing and outcomes.",
    [
      company,
      {
        name: "partyId",
        label: "Account",
        type: "select",
        optionsKey: "parties",
      },
      {
        name: "contactId",
        label: "Contact",
        type: "select",
        optionsKey: "contacts",
      },
      {
        name: "opportunityId",
        label: "Opportunity",
        type: "select",
        optionsKey: "opportunities",
      },
      owner,
      {
        name: "visitType",
        label: "Visit type",
        type: "select",
        options: status(
          "customer_visit",
          "prospecting",
          "site_survey",
          "demo",
          "review",
          "collection",
          "other",
        ),
      },
      {
        name: "plannedStartAt",
        label: "Planned start",
        type: "datetime-local",
        required: true,
      },
      { name: "plannedEndAt", label: "Planned end", type: "datetime-local" },
      { name: "actualStartAt", label: "Actual start", type: "datetime-local" },
      { name: "actualEndAt", label: "Actual end", type: "datetime-local" },
      { name: "latitude", label: "Latitude", type: "number" },
      { name: "longitude", label: "Longitude", type: "number" },
      { name: "address", label: "Address", type: "textarea" },
      { name: "objective", label: "Objective", type: "textarea" },
      { name: "outcome", label: "Outcome", type: "textarea" },
      { name: "routeSequence", label: "Route sequence", type: "number" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status(
          "planned",
          "confirmed",
          "in_progress",
          "completed",
          "cancelled",
          "missed",
        ),
      },
    ],
    [
      { key: "visitType", label: "Visit", format: "status" },
      { key: "partyId", label: "Account", optionsKey: "parties" },
      { key: "ownerUserId", label: "Owner", optionsKey: "users" },
      { key: "plannedStartAt", label: "Planned", format: "datetime" },
      { key: "status", label: "Status", format: "status" },
    ],
  ),
} satisfies Partial<Record<CrmResourceKey, CrmDefinition>>;
