import type { CrmResourceKey } from "@vercentlabs/shared-types";
import { PERMISSIONS } from "@/core/authorization";
import { branch, company, config, owner, status, workspace, type CrmDefinition } from "./core";

export const sellerActivityDefinitions = {
activities: {
    key: "activities",
    title: "Activities",
    singular: "activity",
    group: "Work",
    description:
      "Schedule tasks, calls, meetings, messages and follow-ups with accountable ownership.",
    permission: PERMISSIONS.crmActivitiesManage,
    columns: [
      { key: "activityType", label: "Type" },
      { key: "subject", label: "Subject" },
      { key: "assignedTo", label: "Assigned to", optionsKey: "users" },
      { key: "dueAt", label: "Due", format: "datetime" },
      { key: "priority", label: "Priority", format: "status" },
      { key: "status", label: "Status", format: "status" },
    ],
    fields: [
      company,
      branch,
      {
        name: "entityType",
        label: "Related record type",
        type: "select",
        options: status(
          "lead",
          "opportunity",
          "party",
          "contact",
          "campaign",
          "general",
        ),
      },
      { name: "entityId", label: "Related record ID", type: "text" },
      {
        name: "activityType",
        label: "Activity type",
        type: "select",
        options: status(
          "task",
          "call",
          "meeting",
          "email",
          "whatsapp",
          "sms",
          "note",
        ),
      },
      { name: "subject", label: "Subject", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea" },
      {
        name: "assignedTo",
        label: "Assigned to",
        type: "select",
        optionsKey: "users",
      },
      {
        name: "priority",
        label: "Priority",
        type: "select",
        options: status("low", "medium", "high", "urgent"),
      },
      { name: "startAt", label: "Start", type: "datetime-local" },
      { name: "dueAt", label: "Due", type: "datetime-local" },
      { name: "reminderAt", label: "Reminder", type: "datetime-local" },
      { name: "location", label: "Location", type: "text" },
    ],
  },
communications: {
    key: "communications",
    title: "Communication log",
    singular: "communication",
    group: "Engagement",
    description:
      "Keep a provider-neutral history of email, calls, SMS, chat and WhatsApp conversations.",
    permission: PERMISSIONS.crmCommunicationsManage,
    columns: [
      { key: "channel", label: "Channel" },
      { key: "direction", label: "Direction" },
      { key: "subject", label: "Subject" },
      { key: "status", label: "Status", format: "status" },
      { key: "occurredAt", label: "Occurred", format: "datetime" },
    ],
    fields: [
      {
        name: "channel",
        label: "Channel",
        type: "select",
        options: status("email", "whatsapp", "sms", "call", "chat", "other"),
      },
      {
        name: "direction",
        label: "Direction",
        type: "select",
        options: status("inbound", "outbound"),
      },
      { name: "leadId", label: "Lead", type: "select", optionsKey: "leads" },
      {
        name: "opportunityId",
        label: "Opportunity",
        type: "select",
        optionsKey: "opportunities",
      },
      {
        name: "partyId",
        label: "Business partner",
        type: "select",
        optionsKey: "parties",
      },
      {
        name: "contactId",
        label: "Contact",
        type: "select",
        optionsKey: "contacts",
      },
      { name: "provider", label: "Provider", type: "text" },
      { name: "subject", label: "Subject", type: "text" },
      {
        name: "body",
        label: "Message / notes",
        type: "textarea",
        required: true,
      },
      { name: "fromAddress", label: "From", type: "text" },
      { name: "occurredAt", label: "Occurred at", type: "datetime-local" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status(
          "logged",
          "draft",
          "queued",
          "sent",
          "delivered",
          "read",
          "failed",
          "received",
        ),
      },
    ],
  },
sequences: config(
    "sequences",
    "Follow-up sequences",
    "sequence",
    PERMISSIONS.crmAutomationManage,
    [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea" },
      owner,
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status("draft", "active", "paused", "archived"),
      },
    ],
  ),
"sequence-steps": config(
    "sequence-steps",
    "Sequence steps",
    "sequence step",
    PERMISSIONS.crmAutomationManage,
    [
      {
        name: "sequenceId",
        label: "Sequence",
        type: "select",
        optionsKey: "sequences",
        required: true,
      },
      {
        name: "stepOrder",
        label: "Step order",
        type: "number",
        required: true,
      },
      { name: "delayMinutes", label: "Delay in minutes", type: "number" },
      {
        name: "actionType",
        label: "Action type",
        type: "select",
        options: status("task", "call", "email", "whatsapp", "sms"),
      },
      { name: "subjectTemplate", label: "Subject template", type: "text" },
      { name: "bodyTemplate", label: "Body template", type: "textarea" },
      {
        name: "assignedToOwner",
        label: "Assign to record owner",
        type: "checkbox",
      },
    ],
  ),
"sequence-enrollments": config(
    "sequence-enrollments",
    "Sequence enrollments",
    "sequence enrollment",
    PERMISSIONS.crmAutomationManage,
    [
      {
        name: "sequenceId",
        label: "Sequence",
        type: "select",
        optionsKey: "sequences",
        required: true,
      },
      { name: "leadId", label: "Lead", type: "select", optionsKey: "leads" },
      {
        name: "contactId",
        label: "Contact",
        type: "select",
        optionsKey: "contacts",
      },
      {
        name: "opportunityId",
        label: "Opportunity",
        type: "select",
        optionsKey: "opportunities",
      },
      { name: "nextRunAt", label: "Next run", type: "datetime-local" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status("active", "paused", "completed", "cancelled"),
      },
    ],
  ),
"engagement-templates": workspace(
    "engagement-templates",
    "Engagement templates",
    "engagement template",
    "Engagement",
    PERMISSIONS.crmCommunicationsManage,
    "Create reusable email, messaging, call-script and snippet content with version and ownership controls.",
    [
      company,
      {
        name: "templateType",
        label: "Template type",
        type: "select",
        options: status("email", "sms", "whatsapp", "call_script", "snippet"),
        required: true,
      },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "subjectTemplate", label: "Subject template", type: "text" },
      {
        name: "bodyTemplate",
        label: "Body template",
        type: "textarea",
        required: true,
      },
      { name: "languageCode", label: "Language code", type: "text" },
      owner,
      { name: "isShared", label: "Shared", type: "checkbox" },
      { name: "version", label: "Version", type: "number" },
      { name: "metadata", label: "Metadata JSON", type: "textarea" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status("draft", "active", "inactive", "archived"),
      },
    ],
    [
      { key: "name", label: "Template" },
      { key: "templateType", label: "Type", format: "status" },
      { key: "languageCode", label: "Language" },
      { key: "version", label: "Version" },
      { key: "status", label: "Status", format: "status" },
    ],
  ),
"meeting-links": workspace(
    "meeting-links",
    "Meeting links",
    "meeting link",
    "Engagement",
    PERMISSIONS.crmCommunicationsManage,
    "Publish governed meeting links with availability, buffers, provider and duration controls.",
    [
      company,
      owner,
      { name: "name", label: "Name", type: "text", required: true },
      { name: "slug", label: "Public slug", type: "text", required: true },
      {
        name: "durationMinutes",
        label: "Duration minutes",
        type: "number",
        required: true,
      },
      { name: "bufferBeforeMinutes", label: "Buffer before", type: "number" },
      { name: "bufferAfterMinutes", label: "Buffer after", type: "number" },
      { name: "timezone", label: "Timezone", type: "text" },
      { name: "availability", label: "Availability JSON", type: "textarea" },
      {
        name: "meetingProvider",
        label: "Meeting provider",
        type: "select",
        options: status(
          "manual",
          "google_meet",
          "microsoft_teams",
          "zoom",
          "other",
        ),
      },
      { name: "locationTemplate", label: "Location template", type: "text" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status("active", "inactive", "archived"),
      },
    ],
    [
      { key: "name", label: "Meeting link" },
      { key: "slug", label: "Slug" },
      { key: "durationMinutes", label: "Minutes" },
      { key: "meetingProvider", label: "Provider", format: "status" },
      { key: "status", label: "Status", format: "status" },
    ],
  ),
conversations: workspace(
    "conversations",
    "Sales conversations",
    "conversation",
    "Engagement",
    PERMISSIONS.crmCommunicationsManage,
    "Govern calls, meetings, recordings, transcript state, consent and retention for every customer conversation.",
    [
      company,
      { name: "leadId", label: "Lead", type: "select", optionsKey: "leads" },
      {
        name: "opportunityId",
        label: "Opportunity",
        type: "select",
        optionsKey: "opportunities",
      },
      {
        name: "partyId",
        label: "Account",
        type: "select",
        optionsKey: "parties",
      },
      {
        name: "contactId",
        label: "Contact",
        type: "select",
        optionsKey: "contacts",
      },
      { name: "communicationId", label: "Communication ID", type: "text" },
      {
        name: "channel",
        label: "Channel",
        type: "select",
        options: status(
          "call",
          "meeting",
          "video",
          "email_thread",
          "chat",
          "other",
        ),
        required: true,
      },
      { name: "provider", label: "Provider", type: "text" },
      { name: "externalId", label: "External ID", type: "text" },
      { name: "title", label: "Title", type: "text" },
      {
        name: "startedAt",
        label: "Started",
        type: "datetime-local",
        required: true,
      },
      { name: "endedAt", label: "Ended", type: "datetime-local" },
      {
        name: "recordingReference",
        label: "Recording reference",
        type: "text",
      },
      {
        name: "transcriptStatus",
        label: "Transcript status",
        type: "select",
        options: status(
          "not_requested",
          "queued",
          "processing",
          "ready",
          "failed",
          "redacted",
        ),
      },
      {
        name: "consentStatus",
        label: "Consent",
        type: "select",
        options: status("granted", "not_required", "denied", "unknown"),
      },
      { name: "retentionUntil", label: "Retain until", type: "datetime-local" },
      { name: "metadata", label: "Metadata JSON", type: "textarea" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status(
          "scheduled",
          "in_progress",
          "completed",
          "cancelled",
          "failed",
          "archived",
        ),
      },
    ],
    [
      { key: "title", label: "Conversation" },
      { key: "channel", label: "Channel", format: "status" },
      { key: "startedAt", label: "Started", format: "datetime" },
      { key: "transcriptStatus", label: "Transcript", format: "status" },
      { key: "status", label: "Status", format: "status" },
    ],
  ),
"conversation-insights": workspace(
    "conversation-insights",
    "Conversation insights",
    "conversation insight",
    "Intelligence",
    PERMISSIONS.crmAiManage,
    "Store reviewable summaries, objections, commitments, sentiment, risks, coaching insights and next actions.",
    [
      company,
      {
        name: "conversationId",
        label: "Conversation",
        type: "select",
        optionsKey: "conversations",
        required: true,
      },
      {
        name: "insightType",
        label: "Insight type",
        type: "select",
        options: status(
          "summary",
          "sentiment",
          "topic",
          "objection",
          "commitment",
          "next_action",
          "risk",
          "coaching",
        ),
        required: true,
      },
      { name: "title", label: "Title", type: "text", required: true },
      { name: "content", label: "Content", type: "textarea", required: true },
      { name: "score", label: "Score", type: "number" },
      { name: "evidence", label: "Evidence JSON", type: "textarea" },
      { name: "modelProvider", label: "Model provider", type: "text" },
      { name: "modelName", label: "Model name", type: "text" },
      { name: "requiresReview", label: "Requires review", type: "checkbox" },
      {
        name: "reviewedBy",
        label: "Reviewed by",
        type: "select",
        optionsKey: "users",
      },
      { name: "reviewedAt", label: "Reviewed at", type: "datetime-local" },
      {
        name: "reviewStatus",
        label: "Review status",
        type: "select",
        options: status("pending", "approved", "rejected", "superseded"),
      },
    ],
    [
      { key: "title", label: "Insight" },
      { key: "insightType", label: "Type", format: "status" },
      { key: "score", label: "Score" },
      { key: "reviewStatus", label: "Review", format: "status" },
      { key: "createdAt", label: "Generated", format: "datetime" },
    ],
  ),
} satisfies Partial<Record<CrmResourceKey, CrmDefinition>>;
