// Plain data (no components) so a Server Component page can read it.
export const ASSETS_PAGES: Record<string, { title: string }> = {
  register: { title: "Asset register" },
  categories: { title: "Asset categories" },
  locations: { title: "Locations" },
  acquisition: { title: "Acquisition" },
  capitalization: { title: "Capitalization" },
  assignments: { title: "Assignments" },
  transfers: { title: "Transfers" },
  depreciation: { title: "Depreciation" },
  revaluation: { title: "Revaluation" },
  impairment: { title: "Impairment" },
  "maintenance-plans": { title: "Maintenance plans" },
  "work-orders": { title: "Work orders" },
  downtime: { title: "Downtime" },
  warranties: { title: "Warranties" },
  inspections: { title: "Inspections" },
  calibration: { title: "Calibration" },
  "physical-verification": { title: "Physical verification" },
  retirement: { title: "Retirement" },
  disposal: { title: "Disposal and sale" },
  analytics: { title: "Asset analytics" },
  reports: { title: "Reports" },
  settings: { title: "Asset settings" },
};
