apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: microsoft-oauth-secrets
  namespace: vercentlabs
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/${GCP_PROJECT_ID}/secrets/${SECRET_PREFIX}-microsoft-oauth-client-secret/versions/latest"
        path: "MICROSOFT_OAUTH_CLIENT_SECRET"
