export type WebParityEntry = {
  web: string;
  mobile: string;
  delivery: "native" | "secure-browser-handoff";
};

export const protectedWebParity: readonly WebParityEntry[] = [
  { web: "/dashboard", mobile: "/(protected)/(tabs)", delivery: "native" },
  { web: "/accounting", mobile: "/(protected)/workspace/accounting", delivery: "native" },
  { web: "/accounting/assets", mobile: "/(protected)/workspace/accounting", delivery: "native" },
  { web: "/accounting/assets/[id]", mobile: "/(protected)/workspace/accounting", delivery: "native" },
  { web: "/accounting/assets/new", mobile: "/(protected)/workspace/accounting", delivery: "native" },
  { web: "/accounting/banking", mobile: "/(protected)/workspace/accounting", delivery: "native" },
  { web: "/accounting/close", mobile: "/(protected)/workspace/accounting", delivery: "native" },
  { web: "/accounting/close/[id]", mobile: "/(protected)/workspace/accounting", delivery: "native" },
  { web: "/accounting/journals", mobile: "/(protected)/workspace/accounting", delivery: "native" },
  { web: "/accounting/journals/[id]", mobile: "/(protected)/workspace/accounting", delivery: "native" },
  { web: "/accounting/journals/new", mobile: "/(protected)/workspace/accounting", delivery: "native" },
  { web: "/accounting/operations", mobile: "/(protected)/workspace/accounting", delivery: "native" },
  { web: "/accounting/payables", mobile: "/(protected)/workspace/accounting", delivery: "native" },
  { web: "/accounting/payables/[id]", mobile: "/(protected)/workspace/accounting", delivery: "native" },
  { web: "/accounting/payables/new", mobile: "/(protected)/workspace/accounting", delivery: "native" },
  { web: "/accounting/planning", mobile: "/(protected)/workspace/accounting", delivery: "native" },
  { web: "/accounting/receivables", mobile: "/(protected)/workspace/accounting", delivery: "native" },
  { web: "/accounting/receivables/[id]", mobile: "/(protected)/workspace/accounting", delivery: "native" },
  { web: "/accounting/receivables/new", mobile: "/(protected)/workspace/accounting", delivery: "native" },
  { web: "/accounting/reports", mobile: "/(protected)/workspace/accounting", delivery: "native" },
  { web: "/accounting/settings", mobile: "/(protected)/workspace/accounting", delivery: "native" },
  { web: "/accounting/tax", mobile: "/(protected)/workspace/accounting", delivery: "native" },
  { web: "/procurement", mobile: "/(protected)/workspace/procurement", delivery: "native" },
  { web: "/procurement/requisitions", mobile: "/(protected)/workspace/procurement", delivery: "native" },
  { web: "/procurement/requisitions/[id]", mobile: "/(protected)/workspace/procurement", delivery: "native" },
  { web: "/procurement/requisitions/new", mobile: "/(protected)/workspace/procurement", delivery: "native" },
  { web: "/procurement/sourcing", mobile: "/(protected)/workspace/procurement", delivery: "native" },
  { web: "/procurement/sourcing/[id]", mobile: "/(protected)/workspace/procurement", delivery: "native" },
  { web: "/procurement/sourcing/new", mobile: "/(protected)/workspace/procurement", delivery: "native" },
  { web: "/procurement/suppliers", mobile: "/(protected)/workspace/procurement", delivery: "native" },
  { web: "/procurement/suppliers/[id]", mobile: "/(protected)/workspace/procurement", delivery: "native" },
  { web: "/procurement/contracts", mobile: "/(protected)/workspace/procurement", delivery: "native" },
  { web: "/procurement/contracts/[id]", mobile: "/(protected)/workspace/procurement", delivery: "native" },
  { web: "/procurement/orders", mobile: "/(protected)/workspace/procurement", delivery: "native" },
  { web: "/procurement/orders/[id]", mobile: "/(protected)/workspace/procurement", delivery: "native" },
  { web: "/procurement/orders/new", mobile: "/(protected)/workspace/procurement", delivery: "native" },
  { web: "/procurement/receipts", mobile: "/(protected)/workspace/procurement", delivery: "native" },
  { web: "/procurement/receipts/[id]", mobile: "/(protected)/workspace/procurement", delivery: "native" },
  { web: "/procurement/matching", mobile: "/(protected)/workspace/procurement", delivery: "native" },
  { web: "/procurement/reports", mobile: "/(protected)/workspace/procurement", delivery: "native" },
  { web: "/procurement/settings", mobile: "/(protected)/workspace/procurement", delivery: "native" },
  { web: "/sales", mobile: "/(protected)/workspace/sales", delivery: "native" },
  { web: "/sales/orders", mobile: "/(protected)/workspace/sales", delivery: "native" },
  { web: "/sales/orders/[id]", mobile: "/(protected)/workspace/sales", delivery: "native" },
  { web: "/sales/orders/new", mobile: "/(protected)/workspace/sales", delivery: "native" },
  { web: "/sales/quotations", mobile: "/(protected)/workspace/sales", delivery: "native" },
  { web: "/sales/quotations/[id]", mobile: "/(protected)/workspace/sales", delivery: "native" },
  { web: "/sales/quotations/new", mobile: "/(protected)/workspace/sales", delivery: "native" },
  { web: "/sales/reports", mobile: "/(protected)/workspace/sales", delivery: "native" },
  { web: "/sales/settings", mobile: "/(protected)/workspace/sales", delivery: "native" },
  { web: "/crm", mobile: "/(protected)/workspace/crm", delivery: "native" },
  { web: "/crm/[resource]", mobile: "/(protected)/workspace/crm/[resource]", delivery: "native" },
  { web: "/crm/leads/[id]", mobile: "/(protected)/crm/leads/[id]", delivery: "native" },
  { web: "/crm/opportunities/[id]", mobile: "/(protected)/crm/opportunities/[id]", delivery: "native" },
  { web: "/crm/pipeline", mobile: "/(protected)/(tabs)/pipeline", delivery: "native" },
  { web: "/crm/reports", mobile: "/(protected)/workspace/crm-reports", delivery: "native" },
  { web: "/crm/settings", mobile: "/(protected)/workspace/crm-settings", delivery: "native" },
  { web: "/master-data", mobile: "/(protected)/workspace/master-data", delivery: "native" },
  { web: "/master-data/[resource]", mobile: "/(protected)/workspace/master-data/[resource]", delivery: "native" },
  { web: "/modules", mobile: "/(protected)/workspace/modules", delivery: "native" },
  { web: "/notifications", mobile: "/(protected)/notifications", delivery: "native" },
  { web: "/billing", mobile: "/(protected)/workspace/billing", delivery: "native" },
  { web: "/audit-logs", mobile: "/(protected)/workspace/audit-logs", delivery: "native" },
  { web: "/approvals", mobile: "/(protected)/workspace/approvals", delivery: "native" },
  { web: "/profile", mobile: "/(protected)/workspace/profile", delivery: "native" },
  { web: "/search", mobile: "/(protected)/search", delivery: "native" },
  { web: "/security", mobile: "/(protected)/workspace/security", delivery: "native" },
  { web: "/settings", mobile: "/(protected)/workspace/settings", delivery: "native" },
  { web: "/settings/[resource]", mobile: "/(protected)/workspace/settings/[resource]", delivery: "native" },
  { web: "/settings/company", mobile: "/(protected)/workspace/settings/companies", delivery: "native" },
  { web: "/settings/users", mobile: "/(protected)/workspace/users", delivery: "native" },
  { web: "/settings/roles", mobile: "/(protected)/workspace/roles", delivery: "native" },
];

export const authenticationWebParity: readonly WebParityEntry[] = [
  { web: "/login", mobile: "/(auth)/login", delivery: "native" },
  { web: "/signup", mobile: "/signup", delivery: "secure-browser-handoff" },
  { web: "/forgot-password", mobile: "/forgot-password", delivery: "secure-browser-handoff" },
  { web: "/reset-password", mobile: "/reset-password", delivery: "secure-browser-handoff" },
  { web: "/invite", mobile: "/invite", delivery: "secure-browser-handoff" },
  { web: "/verify-email", mobile: "/verify-email", delivery: "secure-browser-handoff" },
];
