// Plain data (no components) so a Server Component page can read it.
export const HR_PAGES: Record<string, { title: string }> = {
  employees: { title: "Employees" },
  organization: { title: "Organization" },
  departments: { title: "Departments" },
  positions: { title: "Designations" },
  "document-types": { title: "Document types" },
  documents: { title: "Employee documents" },
  transfers: { title: "Transfers" },
  promotions: { title: "Promotions" },
  confirmations: { title: "Confirmations" },
  "probation-extensions": { title: "Probation extensions" },
  probation: { title: "Probation" },
  onboarding: { title: "Onboarding" },
  offboarding: { title: "Offboarding" },
  separations: { title: "Separations" },
  "profile-requests": { title: "Profile change requests" },
  openings: { title: "Job openings" },
  candidates: { title: "Candidates" },
  applications: { title: "Recruitment pipeline" },
  interviews: { title: "Interviews" },
  "my-interviews": { title: "My interviews" },
  offers: { title: "Offers" },
  shifts: { title: "Shifts" },
  "shift-assignments": { title: "Shift assignments" },
  "holiday-calendars": { title: "Holiday calendars" },
  holidays: { title: "Holidays" },
  attendance: { title: "Attendance" },
  "my-attendance": { title: "My attendance" },
  regularizations: { title: "Attendance corrections" },
  "team-corrections": { title: "Team corrections" },
  "my-corrections": { title: "My corrections" },
  overtime: { title: "Overtime" },
  "team-overtime": { title: "Team overtime" },
  "late-early": { title: "Late arrivals and early exits" },
  "leave-types": { title: "Leave types" },
  "leave-policies": { title: "Leave policies" },
  "leave-balances": { title: "Leave balances" },
  "my-leave-balances": { title: "My leave balances" },
  "leave-requests": { title: "Leave requests" },
  "team-leave": { title: "Team leave" },
  "my-leave": { title: "My leave" },
  "leave-admin": { title: "Leave administration" },
  payroll: { title: "Payroll" },
  "salary-components": { title: "Pay components" },
  "pay-components": { title: "Pay components" },
  "salary-structures": { title: "Salary structures" },
  compensation: { title: "Compensation" },
  "payroll-periods": { title: "Payroll periods" },
  "payroll-runs": { title: "Payroll runs" },
  payslips: { title: "Payslips" },
  "my-payslips": { title: "My payslips" },
  "payroll-exceptions": { title: "Payroll exceptions" },
  "payroll-inputs": { title: "Payroll adjustments" },
  "expense-categories": { title: "Expense categories" },
  expenses: { title: "Expenses" },
  "my-expenses": { title: "My expenses" },
  "team-expenses": { title: "Team expenses" },
  loans: { title: "Loans and advances" },
  "my-loans": { title: "My loans" },
  "final-settlements": { title: "Final settlements" },
  "bank-files": { title: "Bank transfer files" },
  "statutory-components": { title: "Statutory components" },
  "gratuity-records": { title: "Gratuity" },
  "compliance-report": { title: "Compliance report" },
  "review-cycles": { title: "Review cycles" },
  appraisals: { title: "Appraisals" },
  "my-appraisals": { title: "My appraisals" },
  "appraisals-to-review": { title: "Appraisals to review" },
  goals: { title: "Goals" },
  "my-goals": { title: "My goals" },
  "team-goals": { title: "Team goals" },
  skills: { title: "Skills" },
  "employee-skills": { title: "Skills matrix" },
  "my-skills": { title: "My skills" },
  courses: { title: "Courses" },
  "training-sessions": { title: "Training sessions" },
  "training-enrolments": { title: "Training enrolments" },
  "my-training": { title: "My training" },
  me: { title: "My profile" },
  settings: { title: "HR settings" },
};
