// Plain data (no components) so a Server Component page can read it.
export const HR_PAGES: Record<string, { title: string }> = {
  employees: { title: "Employees" },
  organization: { title: "Organization" },
  departments: { title: "Departments" },
  positions: { title: "Designations" },
  onboarding: { title: "Onboarding" },
  shifts: { title: "Shifts" },
  "shift-assignments": { title: "Shift assignments" },
  "holiday-calendars": { title: "Holiday calendars" },
  holidays: { title: "Holidays" },
  attendance: { title: "Attendance" },
  "my-attendance": { title: "My attendance" },
  "leave-types": { title: "Leave types" },
  "leave-policies": { title: "Leave policies" },
  "leave-balances": { title: "Leave balances" },
  "my-leave-balances": { title: "My leave balances" },
  "leave-requests": { title: "Leave requests" },
  "team-leave": { title: "Team leave" },
  "my-leave": { title: "My leave" },
  "leave-admin": { title: "Leave administration" },
  payroll: { title: "Payroll" },
  "salary-components": { title: "Pay components" },
  "pay-components": { title: "Pay components" },
  "salary-structures": { title: "Salary structures" },
  compensation: { title: "Compensation" },
  "payroll-periods": { title: "Payroll periods" },
  "payroll-runs": { title: "Payroll runs" },
  payslips: { title: "Payslips" },
  "my-payslips": { title: "My payslips" },
  "payroll-exceptions": { title: "Payroll exceptions" },
  me: { title: "My profile" },
  settings: { title: "HR settings" },
};
