// Purchase Orders, goods receipts, purchase returns, supplier quotations and bills from orders. Loosely typed: the module validates every input.
/* eslint-disable @typescript-eslint/no-explicit-any */
type QueryClient = { query(text: string, values?: unknown[]): Promise<{ rows: any[]; rowCount?: number | null }> };

export declare class PurchaseOrderError extends Error { status: number; code: string; details?: Record<string, unknown>; constructor(status: number, message: string, code?: string, details?: Record<string, unknown>); }
export declare const PURCHASE_ORDER_CANCEL_REASONS: any;
export declare const PURCHASE_ORDER_PERMISSIONS: any;
export declare const PURCHASE_ORDER_VIEWS: any;
export declare const PURCHASE_ORDER_STATUS: any;
export declare const PURCHASE_ORDER_FILE_ENTITY: any;
export declare function calculatePurchaseOrderTotals(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function addPurchaseOrderLine(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function createPurchaseOrder(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function getPurchaseOrder(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function getPurchaseOrderDefaults(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function getPurchaseOrderOptions(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function getPurchaseOrderTracking(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function listPurchaseOrderHistory(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function listPurchaseOrders(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function previewPurchaseOrder(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function removeDraftPurchaseOrderLine(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function updateDraftPurchaseOrder(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function updateDraftPurchaseOrderLine(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function amendPurchaseOrder(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function calculatePurchaseOrderClosureEligibility(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function cancelPurchaseOrder(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function cancelRemainingPurchaseOrderQty(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function changePurchaseOrderLineWarehouse(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function closePurchaseOrder(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function confirmPurchaseOrder(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function updatePurchaseOrderExpectedDates(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function derivePurchaseOrderPaymentStatus(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function loadPurchaseOrderLineProgress(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function acknowledgePurchaseOrder(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function getPurchaseOrderDocument(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function markPurchaseOrderSent(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function sendPurchaseOrder(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function listPurchaseOrderFiles(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function preparePurchaseOrderFileUpload(input: { fileName: string; bytes: Uint8Array }, env?: Record<string, string | undefined>): Promise<any>;
export declare function readPurchaseOrderFile(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function removePurchaseOrderFile(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function uploadPurchaseOrderFile(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function cancelSupplierQuotation(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function createPurchaseOrderFromQuotation(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function createSupplierQuotation(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function getSupplierQuotation(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function listSupplierQuotations(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function updateSupplierQuotation(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function createGoodsReceiptFromPurchaseOrder(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function getGoodsReceipt(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function listGoodsReceipts(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function postGoodsReceipt(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function getProcurementSettings(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function updateProcurementSettings(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function validatePurchaseOrder(...args: any[]): any;
export declare function calculateClosureEligibility(...args: any[]): any;
export declare function derivePurchaseOrderBillingStatus(...args: any[]): any;
export declare function derivePurchaseOrderReceiptStatus(...args: any[]): any;
export declare function calculateRemainingBillableQty(...args: any[]): any;
export declare function calculateRemainingReceivableQty(...args: any[]): any;
export declare function cancelDraftGoodsReceipt(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function getGoodsReceiptsForPurchaseOrder(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function getPurchaseOrderRemainingReceivableQty(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function recordReceiptDiscrepancy(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function releaseHeldGoods(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function reversePostedGoodsReceipt(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function updateDraftGoodsReceipt(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function validateGoodsReceiptForPosting(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function listGoodsReceiptFiles(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function readGoodsReceiptFile(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function removeGoodsReceiptFile(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function uploadGoodsReceiptFile(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare const GOODS_RECEIPT_DISCREPANCY_TYPES: any;
export declare const GOODS_RECEIPT_FILE_ENTITY: string;
export declare function prepareGoodsReceiptFileUpload(input: { fileName: string; bytes: Uint8Array }, env?: Record<string, string | undefined>): Promise<any>;
export declare const GOODS_RECEIPT_VIEWS: readonly string[];
export declare function createDraftGoodsReceipt(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function recordGoodsReceiptDiscrepancy(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function getPurchaseOrderReceiptProgress(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function reconcileGoodsReceiptInventory(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function isReceiptAccrualEnabled(client: QueryClient, organizationId: string): Promise<boolean>;
export declare function postReceiptAccrual(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function reverseReceiptAccrual(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare const REJECTION_REASONS: ReadonlyArray<{ code: string; label: string }>;
export declare const REJECTION_RESOLUTION_TYPES: ReadonlyArray<{ code: string; label: string; stage: string }>;
export declare const REJECTION_EXPECTED_RESOLUTIONS: ReadonlyArray<{ code: string; label: string }>;
export declare const REJECTION_VIEWS: ReadonlyArray<{ key: string; label: string }>;
export declare const REJECTION_FILE_ENTITY: string;
export declare function recordDockRejection(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function recordPostReceiptRejection(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function quarantineRejectedStock(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function createRejectionFromQualityInspection(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function getEligibleRejectableQuantity(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function getRejectionResolutionOptions(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function recordRejectionResolution(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function linkReplacementReceipt(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function cancelOutstandingQuantityFromRejection(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function closeRejectionCase(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function cancelInvalidRejectionCase(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function updateOpenRejection(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function getRejection(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function listRejections(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function getPurchaseOrderRejections(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function getGoodsReceiptRejections(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function getOpenSupplierRejections(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function getRejectionSummary(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function listRejectionFiles(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function uploadRejectionFile(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function removeRejectionFile(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function readRejectionFile(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function prepareRejectionFileUpload(input: { fileName: string; bytes: Uint8Array }, env?: Record<string, string | undefined>): Promise<any>;
export declare function getInspectionRejections(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare function changePurchaseOrderMatchingPolicy(client: QueryClient, context: any, ...args: any[]): Promise<any>;
export declare const MATCHING_POLICY_LABELS: Record<string, string>;
