// The 12 canonical module navigation trees — extracted verbatim from
// apps/web/src/components/app-shell.tsx (previously ~740 lines of inline
// literal objects with no shared registry file, see Prompt 1's audit
// Section 11 and docs/implementation/ERP_NAVIGATION_FOUNDATION_006.md
// Section 2). Every href below is a real, already-shipped route — this
// file intentionally does not add the deeper aspirational capability trees
// from the product navigation handoff where no route exists yet; those are
// tracked in the doc's Route Gap Matrix instead of being fabricated here.
import { PERMISSIONS } from "@/lib/permissions-catalog";
import type { ModuleNavigationGroup } from "@/lib/navigation/types";

export const moduleNavigation: ModuleNavigationGroup[] = [
  {
    label: "CRM",
    moduleId: "crm",
    icon: "crm",
    keywords: ["customers", "pipeline", "deals"],
    items: [
      {
        href: "/crm",
        label: "Overview",
        icon: "dashboard",
        exact: true,
        permission: PERMISSIONS.crmView,
      },
      {
        href: "/crm/leads",
        label: "Leads",
        icon: "crm",
        group: "Customers",
        activePrefixes: ["/crm/lead-acquisition", "/crm/lead-intelligence"],
        permission: PERMISSIONS.crmView,
      },
      {
        href: "/crm/accounts",
        label: "Accounts",
        icon: "companies",
        group: "Customers",
        permission: PERMISSIONS.crmView,
      },
      {
        href: "/crm/contacts",
        label: "Contacts",
        icon: "users",
        group: "Customers",
        permission: PERMISSIONS.crmView,
      },
      {
        href: "/crm/opportunities",
        label: "Opportunities",
        icon: "sales",
        group: "Sales",
        permission: PERMISSIONS.crmView,
      },
      {
        href: "/crm/activities",
        label: "Activities",
        icon: "approvals",
        group: "Sales",
        permission: PERMISSIONS.crmView,
      },
      {
        href: "/crm/pipeline",
        label: "Pipeline & forecasting",
        icon: "sales",
        group: "Sales",
        activePrefixes: ["/crm/opportunity-revenue"],
        permission: PERMISSIONS.crmView,
      },
      {
        href: "/crm/communications",
        label: "Communications",
        icon: "notifications",
        group: "Engagement",
        activePrefixes: ["/crm/conversation-intelligence"],
        permission: PERMISSIONS.crmView,
      },
      {
        href: "/crm/marketing",
        label: "Marketing",
        icon: "sparkles",
        group: "Engagement",
        permission: PERMISSIONS.crmView,
      },
      {
        href: "/crm/customer-success",
        label: "Customer success",
        icon: "companies",
        group: "Engagement",
        permission: PERMISSIONS.crmView,
      },
      {
        href: "/crm/partner-engagement",
        label: "Partner management",
        icon: "teams",
        group: "Engagement",
        permission: PERMISSIONS.crmView,
      },
      {
        href: "/crm/reports",
        label: "Reports",
        icon: "audit",
        group: "Insights",
        permission: PERMISSIONS.crmReportsView,
      },
      {
        href: "/crm/ai-intelligence",
        label: "CRM intelligence",
        icon: "sparkles",
        group: "Insights",
        permission: PERMISSIONS.crmView,
      },
      {
        href: "/crm/settings",
        label: "Settings",
        icon: "settings",
        group: "Administration",
        activePrefixes: ["/crm/mobile-readiness"],
        permission: PERMISSIONS.crmSettingsManage,
      },
    ],
  },
  {
    label: "Sales",
    moduleId: "sales",
    icon: "sales",
    keywords: ["orders", "quotes"],
    items: [
      {
        href: "/sales",
        label: "Overview",
        icon: "dashboard",
        exact: true,
        permission: PERMISSIONS.salesView,
      },
      {
        href: "/sales/quotations",
        label: "Quotations",
        icon: "sales",
        permission: PERMISSIONS.salesView,
      },
      {
        href: "/sales/orders",
        label: "Sales orders",
        icon: "sales",
        permission: PERMISSIONS.salesView,
      },
      {
        href: "/sales/reports",
        label: "Reports",
        icon: "audit",
        permission: PERMISSIONS.salesReportsView,
      },
      {
        href: "/sales/settings",
        label: "Settings",
        icon: "settings",
        permission: PERMISSIONS.salesSettingsManage,
      },
    ],
  },
  {
    label: "Procurement",
    moduleId: "procurement",
    icon: "procurement",
    keywords: ["purchasing", "buying", "vendors"],
    items: [
      {
        href: "/procurement",
        label: "Overview",
        icon: "dashboard",
        exact: true,
        permission: PERMISSIONS.procurementView,
      },
      {
        href: "/procurement/requisitions",
        label: "Requisitions",
        icon: "procurement",
        permission: PERMISSIONS.procurementView,
      },
      {
        href: "/procurement/sourcing",
        label: "Sourcing",
        icon: "procurement",
        permission: PERMISSIONS.procurementView,
      },
      {
        href: "/procurement/suppliers",
        label: "Suppliers",
        icon: "companies",
        permission: PERMISSIONS.procurementSuppliersView,
      },
      {
        href: "/procurement/contracts",
        label: "Agreements",
        icon: "audit",
        permission: PERMISSIONS.procurementView,
      },
      {
        href: "/procurement/orders",
        label: "Purchase orders",
        icon: "procurement",
        permission: PERMISSIONS.procurementView,
      },
      {
        href: "/procurement/receipts",
        label: "Receipts",
        icon: "check",
        permission: PERMISSIONS.procurementView,
      },
      {
        href: "/procurement/matching",
        label: "Matching",
        icon: "approvals",
        permission: PERMISSIONS.procurementView,
      },
      {
        href: "/procurement/reports",
        label: "Reports",
        icon: "audit",
        permission: PERMISSIONS.procurementReportsView,
      },
      {
        href: "/procurement/settings",
        label: "Settings",
        icon: "settings",
        permission: PERMISSIONS.procurementSettingsManage,
      },
    ],
  },
  {
    label: "Stock",
    moduleId: "stock",
    icon: "stock",
    keywords: ["inventory", "warehouse"],
    items: [
      {
        href: "/stock",
        label: "Overview",
        icon: "dashboard",
        exact: true,
        permission: PERMISSIONS.stockView,
      },
      {
        href: "/stock/balances",
        label: "Stock balances",
        icon: "modules",
        permission: PERMISSIONS.stockView,
      },
      {
        href: "/stock/movements",
        label: "Movements",
        icon: "audit",
        permission: PERMISSIONS.stockView,
      },
      {
        href: "/stock/transfers",
        label: "Transfers",
        icon: "procurement",
        permission: PERMISSIONS.stockTransfer,
      },
      {
        href: "/stock/batches",
        label: "Batches",
        icon: "check",
        permission: PERMISSIONS.stockView,
      },
      {
        href: "/stock/serials",
        label: "Serial numbers",
        icon: "check",
        permission: PERMISSIONS.stockView,
      },
      {
        href: "/stock/reservations",
        label: "Reservations",
        icon: "approvals",
        permission: PERMISSIONS.stockView,
      },
      {
        href: "/stock/reorder-rules",
        label: "Replenishment",
        icon: "sales",
        permission: PERMISSIONS.stockView,
      },
    ],
  },
  {
    label: "HR & Payroll",
    moduleId: "hr-payroll",
    icon: "hr-payroll",
    keywords: ["hr", "employee", "salary", "payroll", "people"],
    items: [
      {
        href: "/hr-payroll",
        label: "Overview",
        icon: "dashboard",
        exact: true,
        permission: PERMISSIONS.hrPayrollView,
      },
      {
        href: "/hr-payroll/employees",
        label: "Employees",
        icon: "users",
        permission: PERMISSIONS.hrPayrollEmployeeView,
      },
      {
        href: "/hr-payroll/attendance",
        label: "Attendance",
        icon: "check",
        permission: PERMISSIONS.hrPayrollView,
      },
      {
        href: "/hr-payroll/leave-requests",
        label: "Leave",
        icon: "approvals",
        permission: PERMISSIONS.hrPayrollView,
      },
      {
        href: "/hr-payroll/expenses",
        label: "Expenses",
        icon: "accounting",
        permission: PERMISSIONS.hrPayrollView,
      },
      {
        href: "/hr-payroll/salary-structures",
        label: "Compensation",
        icon: "settings",
        permission: PERMISSIONS.hrPayrollView,
      },
      {
        href: "/hr-payroll/payroll-runs",
        label: "Payroll runs",
        icon: "hr-payroll",
        permission: PERMISSIONS.hrPayrollView,
      },
      {
        href: "/hr-payroll/payslips",
        label: "Payslips",
        icon: "audit",
        permission: PERMISSIONS.hrPayrollPayslipView,
      },
    ],
  },

  {
    label: "Support",
    moduleId: "support",
    icon: "support",
    keywords: ["helpdesk", "tickets"],
    items: [
      {
        href: "/support",
        label: "Overview",
        icon: "dashboard",
        exact: true,
        permission: PERMISSIONS.supportView,
      },
      {
        href: "/support/tickets",
        label: "Tickets",
        icon: "support",
        permission: PERMISSIONS.supportView,
      },
      {
        href: "/support/queues",
        label: "Queues",
        icon: "users",
        permission: PERMISSIONS.supportView,
      },
      {
        href: "/support/sla-policies",
        label: "SLA policies",
        icon: "audit",
        permission: PERMISSIONS.supportView,
      },
      {
        href: "/support/escalations",
        label: "Escalations",
        icon: "approvals",
        permission: PERMISSIONS.supportView,
      },
      {
        href: "/support/communications",
        label: "Communications",
        icon: "crm",
        permission: PERMISSIONS.supportView,
      },
      {
        href: "/support/knowledge",
        label: "Knowledge",
        icon: "support",
        permission: PERMISSIONS.supportView,
      },
      {
        href: "/support/customer-history",
        label: "Customer history",
        icon: "users",
        permission: PERMISSIONS.supportView,
      },
    ],
  },

  {
    label: "Quality",
    moduleId: "quality",
    icon: "quality",
    keywords: ["qa", "inspection"],
    items: [
      {
        href: "/quality",
        label: "Overview",
        icon: "dashboard",
        exact: true,
        permission: PERMISSIONS.qualityView,
      },
      {
        href: "/quality/plans",
        label: "Quality plans",
        icon: "settings",
        permission: PERMISSIONS.qualityView,
      },
      {
        href: "/quality/inspections",
        label: "Inspections",
        icon: "check",
        permission: PERMISSIONS.qualityView,
      },
      {
        href: "/quality/holds",
        label: "Quality holds",
        icon: "stock",
        permission: PERMISSIONS.qualityView,
      },
      {
        href: "/quality/non-conformances",
        label: "Non-conformance",
        icon: "audit",
        permission: PERMISSIONS.qualityView,
      },
      {
        href: "/quality/capa",
        label: "CAPA",
        icon: "approvals",
        permission: PERMISSIONS.qualityView,
      },
      {
        href: "/quality/supplier-quality",
        label: "Supplier quality",
        icon: "procurement",
        permission: PERMISSIONS.qualityView,
      },
      {
        href: "/quality/audits",
        label: "Audits",
        icon: "audit",
        permission: PERMISSIONS.qualityView,
      },
    ],
  },

  {
    label: "Point of Sale",
    moduleId: "point-of-sale",
    icon: "point-of-sale",
    keywords: ["pos", "retail", "terminal", "checkout"],
    items: [
      {
        href: "/point-of-sale",
        label: "Overview",
        icon: "dashboard",
        exact: true,
        permission: PERMISSIONS.posView,
      },
      {
        href: "/point-of-sale/checkout",
        label: "Checkout",
        icon: "sales",
        permission: PERMISSIONS.posOperate,
      },
      {
        href: "/point-of-sale/shifts",
        label: "Shifts",
        icon: "audit",
        permission: PERMISSIONS.posView,
      },
      {
        href: "/point-of-sale/sales",
        label: "Sales",
        icon: "sales",
        permission: PERMISSIONS.posView,
      },
      {
        href: "/point-of-sale/returns",
        label: "Returns",
        icon: "stock",
        permission: PERMISSIONS.posView,
      },
      {
        href: "/point-of-sale/cash-movements",
        label: "Cash movements",
        icon: "accounting",
        permission: PERMISSIONS.posView,
      },
      {
        href: "/point-of-sale/reconciliations",
        label: "Reconciliation",
        icon: "check",
        permission: PERMISSIONS.posView,
      },
      {
        href: "/point-of-sale/terminals",
        label: "Terminals",
        icon: "settings",
        permission: PERMISSIONS.posTerminalManage,
      },
    ],
  },

  {
    label: "Assets",
    moduleId: "assets",
    icon: "assets",
    keywords: ["fixed assets", "equipment"],
    items: [
      {
        href: "/assets",
        label: "Overview",
        icon: "dashboard",
        exact: true,
        permission: PERMISSIONS.assetsView,
      },
      {
        href: "/assets/assets",
        label: "Asset register",
        icon: "modules",
        permission: PERMISSIONS.assetsView,
      },
      {
        href: "/assets/assignments",
        label: "Assignments",
        icon: "users",
        permission: PERMISSIONS.assetsView,
      },
      {
        href: "/assets/transfers",
        label: "Transfers",
        icon: "stock",
        permission: PERMISSIONS.assetsView,
      },
      {
        href: "/assets/maintenance-orders",
        label: "Maintenance",
        icon: "settings",
        permission: PERMISSIONS.assetsView,
      },
      {
        href: "/assets/inspections",
        label: "Inspections",
        icon: "check",
        permission: PERMISSIONS.assetsView,
      },
      {
        href: "/assets/depreciation-runs",
        label: "Depreciation",
        icon: "accounting",
        permission: PERMISSIONS.assetsView,
      },
      {
        href: "/assets/disposals",
        label: "Disposals",
        icon: "audit",
        permission: PERMISSIONS.assetsView,
      },
    ],
  },

  {
    label: "Projects",
    moduleId: "projects",
    icon: "projects",
    keywords: ["tasks", "timesheet"],
    items: [
      {
        href: "/projects",
        label: "Overview",
        icon: "dashboard",
        exact: true,
        permission: PERMISSIONS.projectsView,
      },
      {
        href: "/projects/projects",
        label: "Projects",
        icon: "modules",
        permission: PERMISSIONS.projectsView,
      },
      {
        href: "/projects/milestones",
        label: "Milestones",
        icon: "check",
        permission: PERMISSIONS.projectsView,
      },
      {
        href: "/projects/tasks",
        label: "Tasks",
        icon: "approvals",
        permission: PERMISSIONS.projectsView,
      },
      {
        href: "/projects/time-entries",
        label: "Time",
        icon: "audit",
        permission: PERMISSIONS.projectsView,
      },
      {
        href: "/projects/expenses",
        label: "Expenses",
        icon: "accounting",
        permission: PERMISSIONS.projectsView,
      },
      {
        href: "/projects/budgets",
        label: "Budgets",
        icon: "accounting",
        permission: PERMISSIONS.projectsView,
      },
      {
        href: "/projects/profitability",
        label: "Profitability",
        icon: "sales",
        permission: PERMISSIONS.projectsProfitabilityView,
      },
    ],
  },

  {
    label: "Manufacturing",
    moduleId: "manufacturing",
    icon: "manufacturing",
    keywords: ["production", "mrp"],
    items: [
      {
        href: "/manufacturing",
        label: "Overview",
        icon: "dashboard",
        exact: true,
        permission: PERMISSIONS.manufacturingView,
      },
      {
        href: "/manufacturing/boms",
        label: "Bills of material",
        icon: "modules",
        permission: PERMISSIONS.manufacturingBomView,
      },
      {
        href: "/manufacturing/work-orders",
        label: "Work orders",
        icon: "approvals",
        permission: PERMISSIONS.manufacturingView,
      },
      {
        href: "/manufacturing/work-centers",
        label: "Work centers",
        icon: "settings",
        permission: PERMISSIONS.manufacturingView,
      },
      {
        href: "/manufacturing/routings",
        label: "Routings",
        icon: "audit",
        permission: PERMISSIONS.manufacturingView,
      },
      {
        href: "/manufacturing/material-requirements",
        label: "Material planning",
        icon: "procurement",
        permission: PERMISSIONS.manufacturingView,
      },
      {
        href: "/manufacturing/production-postings",
        label: "Production postings",
        icon: "check",
        permission: PERMISSIONS.manufacturingView,
      },
    ],
  },
  {
    label: "Accounting",
    moduleId: "accounting",
    icon: "accounting",
    keywords: ["finance", "ledger", "journal", "gl"],
    items: [
      {
        href: "/accounting",
        label: "Overview",
        icon: "dashboard",
        exact: true,
        permission: PERMISSIONS.accountingView,
      },
      {
        href: "/accounting/journals",
        label: "Journal entries",
        icon: "accounting",
        permission: PERMISSIONS.accountingView,
      },
      {
        href: "/accounting/receivables",
        label: "Receivables",
        icon: "sales",
        permission: PERMISSIONS.accountingView,
      },
      {
        href: "/accounting/payables",
        label: "Payables",
        icon: "procurement",
        permission: PERMISSIONS.accountingView,
      },
      {
        href: "/accounting/banking",
        label: "Banking",
        icon: "billing",
        permission: PERMISSIONS.accountingView,
      },
      {
        href: "/accounting/assets",
        label: "Fixed assets",
        icon: "assets",
        permission: PERMISSIONS.accountingView,
      },
      {
        href: "/accounting/planning",
        label: "Planning",
        icon: "projects",
        permission: PERMISSIONS.accountingView,
      },
      {
        href: "/accounting/tax",
        label: "Tax",
        icon: "audit",
        permission: PERMISSIONS.accountingView,
      },
      {
        href: "/accounting/operations",
        label: "Operations",
        icon: "settings",
        permission: PERMISSIONS.accountingView,
      },
      {
        href: "/accounting/close",
        label: "Period close",
        icon: "check",
        permission: PERMISSIONS.accountingView,
      },
      {
        href: "/accounting/reports",
        label: "Reports",
        icon: "audit",
        permission: PERMISSIONS.accountingReportsView,
      },
      {
        href: "/accounting/settings",
        label: "Settings",
        icon: "settings",
        permission: PERMISSIONS.accountingSettingsManage,
      },
    ],
  },
];
