import Link from "next/link";
import { getAccountingDashboard, listCustomerInvoices, listJournalEntries, listVendorBills } from "@vercentlabs/api";
import { requireWorkspace } from "@/lib/auth";
import { hasPermission, PERMISSIONS } from "@/lib/authorization";
import { tenantTransaction } from "@/lib/db";
import { accountingContext } from "@/lib/accounting";
export const dynamic = "force-dynamic";
type Row = Record<string, unknown>;
export default async function AccountingOverviewPage() {
  const session = await requireWorkspace();
  if (!hasPermission(session, PERMISSIONS.accountingView)) return <section className="panel"><h1>Accounting access required</h1></section>;
  const context = accountingContext(session);
  const data = await tenantTransaction(context.organizationId, async (client) => ({ dashboard: await getAccountingDashboard(client, context), journals: (await listJournalEntries(client, context)).slice(0, 5), invoices: (await listCustomerInvoices(client, context)).slice(0, 5), bills: (await listVendorBills(client, context)).slice(0, 5) })) as { dashboard: Row; journals: Row[]; invoices: Row[]; bills: Row[] };
  const d = data.dashboard;
  return <><section className="page-heading"><div><p className="eyebrow">Financial operations</p><h1>Accounting command centre</h1><p>Control the general ledger, receivables, payables, banking, tax, reporting and period close from one governed workspace.</p></div><div className="page-heading-actions"><Link className="primary-button" href="/accounting/journals/new">New journal</Link><Link className="secondary-button" href="/accounting/receivables/new">New invoice</Link></div></section>
    <section className="accounting-kpi-grid">{[["Posted journals", d.posted_journals], ["Pending approvals", d.pending_approvals], ["Receivables", d.receivables], ["Payables", d.payables], ["Unreconciled bank lines", d.unreconciled_bank_lines], ["Open periods", d.open_periods]].map(([label, value]) => <article className="metric-card" key={String(label)}><span>{String(label)}</span><strong>{String(value ?? 0)}</strong></article>)}</section>
    <div className="accounting-three-column"><section className="panel"><div className="accounting-section-heading"><div><p className="eyebrow">General ledger</p><h2>Recent journals</h2></div><Link href="/accounting/journals">View all</Link></div><div className="accounting-list">{data.journals.map((row) => <Link key={String(row.id)} href={`/accounting/journals/${String(row.id)}`}><span><strong>{String(row.entry_number)}</strong><small>{String(row.description)} · {String(row.status)}</small></span><b>{String(row.functional_currency_code)} {String(row.total_debit ?? 0)}</b></Link>)}{!data.journals.length ? <p>No journals yet.</p> : null}</div></section>
    <section className="panel"><div className="accounting-section-heading"><div><p className="eyebrow">Receivables</p><h2>Customer invoices</h2></div><Link href="/accounting/receivables">View all</Link></div><div className="accounting-list">{data.invoices.map((row) => <Link key={String(row.id)} href={`/accounting/receivables/${String(row.id)}`}><span><strong>{String(row.invoice_number)}</strong><small>{String(row.customer_name)} · {String(row.status)}</small></span><b>{String(row.currency_code)} {String(row.outstanding_amount)}</b></Link>)}{!data.invoices.length ? <p>No customer invoices yet.</p> : null}</div></section>
    <section className="panel"><div className="accounting-section-heading"><div><p className="eyebrow">Payables</p><h2>Vendor bills</h2></div><Link href="/accounting/payables">View all</Link></div><div className="accounting-list">{data.bills.map((row) => <Link key={String(row.id)} href={`/accounting/payables/${String(row.id)}`}><span><strong>{String(row.bill_number)}</strong><small>{String(row.supplier_name)} · {String(row.status)}</small></span><b>{String(row.currency_code)} {String(row.outstanding_amount)}</b></Link>)}{!data.bills.length ? <p>No vendor bills yet.</p> : null}</div></section></div>
    <section className="accounting-capability-grid">{[["General ledger", "Double-entry journals, approvals, posting, reversals and audit history.", "/accounting/journals"], ["Receivables", "Sales invoice requests, customer invoices, receipts and allocations.", "/accounting/receivables"], ["Payables", "Vendor bills, payments, due dates and allocation controls.", "/accounting/payables"], ["Banking", "Bank accounts, statement import, match suggestions and reconciliation.", "/accounting/banking"], ["Period close", "Task-driven month, quarter and year-end close with period locks.", "/accounting/close"], ["Financial reports", "Trial balance, ledger, income statement, balance sheet, aging and tax.", "/accounting/reports"]].map(([title, description, href]) => <Link key={title} href={href}><strong>{title}</strong><span>{description}</span><b>Open →</b></Link>)}</section></>;
}
