apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: legacy-encryption-key-secrets
  namespace: vercentlabs
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/${GCP_PROJECT_ID}/secrets/${SECRET_PREFIX}-integration-token-encryption-legacy/versions/latest"
        path: "INTEGRATION_TOKEN_ENCRYPTION_KEY"
