import type { SessionContext, WorkspaceSessionContext } from "@/lib/auth";
import { getSessionContext, requireWorkspace } from "@/lib/auth";
import { HttpError } from "@/lib/http";
import {
  ACCOUNTING_PERMISSIONS,
  BILLING_PERMISSIONS,
  BUSINESS_DATA_PERMISSIONS,
  CORE_PERMISSIONS,
  CRM_PERMISSIONS,
  SALES_PERMISSIONS,
  PROCUREMENT_PERMISSIONS,
  STOCK_PERMISSIONS,
  MANUFACTURING_PERMISSIONS,
  PROJECT_PERMISSIONS,
  ASSET_PERMISSIONS,
  POS_PERMISSIONS,
  QUALITY_PERMISSIONS,
  SUPPORT_PERMISSIONS,
  HR_PAYROLL_PERMISSIONS,
} from "@vercentlabs/permissions";

export const PERMISSIONS = {
  ...CORE_PERMISSIONS,
  businessDataView: BUSINESS_DATA_PERMISSIONS.view,
  partiesManage: BUSINESS_DATA_PERMISSIONS.partiesManage,
  itemsManage: BUSINESS_DATA_PERMISSIONS.itemsManage,
  inventorySetupManage: BUSINESS_DATA_PERMISSIONS.inventorySetupManage,
  financeSetupManage: BUSINESS_DATA_PERMISSIONS.financeSetupManage,
  businessDataImport: BUSINESS_DATA_PERMISSIONS.import,
  crmView: CRM_PERMISSIONS.view,
  crmLeadsManage: CRM_PERMISSIONS.leadsManage,
  crmOpportunitiesManage: CRM_PERMISSIONS.opportunitiesManage,
  crmActivitiesManage: CRM_PERMISSIONS.activitiesManage,
  crmCampaignsManage: CRM_PERMISSIONS.campaignsManage,
  crmCommunicationsManage: CRM_PERMISSIONS.communicationsManage,
  crmAutomationManage: CRM_PERMISSIONS.automationManage,
  crmCaptureManage: CRM_PERMISSIONS.captureManage,
  crmImport: CRM_PERMISSIONS.import,
  crmExport: CRM_PERMISSIONS.export,
  crmReportsView: CRM_PERMISSIONS.reportsView,
  crmSettingsManage: CRM_PERMISSIONS.settingsManage,
  crmRevenueManage: CRM_PERMISSIONS.revenueManage,
  crmAccountsManage: CRM_PERMISSIONS.accountsManage,
  crmPlaybooksManage: CRM_PERMISSIONS.playbooksManage,
  crmPrivacyManage: CRM_PERMISSIONS.privacyManage,
  crmDataQualityManage: CRM_PERMISSIONS.dataQualityManage,
  crmIntegrationsManage: CRM_PERMISSIONS.integrationsManage,
  crmAiManage: CRM_PERMISSIONS.aiManage,
  crmAnalyticsManage: CRM_PERMISSIONS.analyticsManage,
  crmCustomizationManage: CRM_PERMISSIONS.customizationManage,
  crmPartnersManage: CRM_PERMISSIONS.partnersManage,
  crmFieldSalesManage: CRM_PERMISSIONS.fieldSalesManage,
  salesView: SALES_PERMISSIONS.view,
  salesQuotationCreate: SALES_PERMISSIONS.quotationCreate,
  salesQuotationSend: SALES_PERMISSIONS.quotationSend,
  salesQuotationApprove: SALES_PERMISSIONS.quotationApprove,
  salesQuotationAcceptOnBehalf: SALES_PERMISSIONS.quotationAcceptOnBehalf,
  salesOrderCreate: SALES_PERMISSIONS.orderCreate,
  salesOrderConfirm: SALES_PERMISSIONS.orderConfirm,
  salesOrderApprove: SALES_PERMISSIONS.orderApprove,
  salesOrderAmend: SALES_PERMISSIONS.orderAmend,
  salesOrderHold: SALES_PERMISSIONS.orderHold,
  salesOrderCancel: SALES_PERMISSIONS.orderCancel,
  salesFulfillmentRequest: SALES_PERMISSIONS.fulfillmentRequest,
  salesInvoiceRequest: SALES_PERMISSIONS.invoiceRequest,
  salesPriceOverride: SALES_PERMISSIONS.priceOverride,
  salesMarginView: SALES_PERMISSIONS.marginView,
  salesCreditOverride: SALES_PERMISSIONS.creditOverride,
  salesReportsView: SALES_PERMISSIONS.reportsView,
  salesSettingsManage: SALES_PERMISSIONS.settingsManage,
  accountingView: ACCOUNTING_PERMISSIONS.view,
  accountingJournalCreate: ACCOUNTING_PERMISSIONS.journalCreate,
  accountingJournalSubmit: ACCOUNTING_PERMISSIONS.journalSubmit,
  accountingJournalApprove: ACCOUNTING_PERMISSIONS.journalApprove,
  accountingJournalPost: ACCOUNTING_PERMISSIONS.journalPost,
  accountingJournalReverse: ACCOUNTING_PERMISSIONS.journalReverse,
  accountingReceivablesManage: ACCOUNTING_PERMISSIONS.receivablesManage,
  accountingReceivablesApprove: ACCOUNTING_PERMISSIONS.receivablesApprove,
  accountingReceiptsManage: ACCOUNTING_PERMISSIONS.receiptsManage,
  accountingCollectionsManage: ACCOUNTING_PERMISSIONS.collectionsManage,
  accountingPayablesManage: ACCOUNTING_PERMISSIONS.payablesManage,
  accountingPayablesApprove: ACCOUNTING_PERMISSIONS.payablesApprove,
  accountingPaymentsManage: ACCOUNTING_PERMISSIONS.paymentsManage,
  accountingPaymentsApprove: ACCOUNTING_PERMISSIONS.paymentsApprove,
  accountingBankManage: ACCOUNTING_PERMISSIONS.bankManage,
  accountingBankReconcile: ACCOUNTING_PERMISSIONS.bankReconcile,
  accountingPeriodManage: ACCOUNTING_PERMISSIONS.periodManage,
  accountingCloseManage: ACCOUNTING_PERMISSIONS.closeManage,
  accountingBudgetManage: ACCOUNTING_PERMISSIONS.budgetManage,
  accountingTaxManage: ACCOUNTING_PERMISSIONS.taxManage,
  accountingFxManage: ACCOUNTING_PERMISSIONS.fxManage,
  accountingIntercompanyManage: ACCOUNTING_PERMISSIONS.intercompanyManage,
  accountingAssetsManage: ACCOUNTING_PERMISSIONS.assetsManage,
  accountingRecurringManage: ACCOUNTING_PERMISSIONS.recurringManage,
  accountingConsolidationManage: ACCOUNTING_PERMISSIONS.consolidationManage,
  accountingReportsView: ACCOUNTING_PERMISSIONS.reportsView,
  accountingSettingsManage: ACCOUNTING_PERMISSIONS.settingsManage,
  accountingAuditView: ACCOUNTING_PERMISSIONS.auditView,
  procurementView: PROCUREMENT_PERMISSIONS.view,
  procurementSettingsManage: PROCUREMENT_PERMISSIONS.settingsManage,
  procurementSuppliersView: PROCUREMENT_PERMISSIONS.suppliersView,
  procurementSuppliersManage: PROCUREMENT_PERMISSIONS.suppliersManage,
  procurementRequisitionCreate: PROCUREMENT_PERMISSIONS.requisitionCreate,
  procurementRequisitionApprove: PROCUREMENT_PERMISSIONS.requisitionApprove,
  procurementSourcingManage: PROCUREMENT_PERMISSIONS.sourcingManage,
  procurementSourcingAward: PROCUREMENT_PERMISSIONS.sourcingAward,
  procurementContractsManage: PROCUREMENT_PERMISSIONS.contractsManage,
  procurementPoCreate: PROCUREMENT_PERMISSIONS.poCreate,
  procurementPoApprove: PROCUREMENT_PERMISSIONS.poApprove,
  procurementReceiptsManage: PROCUREMENT_PERMISSIONS.receiptsManage,
  procurementMatchingManage: PROCUREMENT_PERMISSIONS.matchingManage,
  procurementReportsView: PROCUREMENT_PERMISSIONS.reportsView,
  stockView: STOCK_PERMISSIONS.view,
  stockManage: STOCK_PERMISSIONS.manage,
  stockReceive: STOCK_PERMISSIONS.receive,
  stockIssue: STOCK_PERMISSIONS.issue,
  stockTransfer: STOCK_PERMISSIONS.transfer,
  stockAdjust: STOCK_PERMISSIONS.adjust,
  stockReserve: STOCK_PERMISSIONS.reserve,
  stockCount: STOCK_PERMISSIONS.count,
  stockValuationView: STOCK_PERMISSIONS.valuationView,
  stockReportsView: STOCK_PERMISSIONS.reportsView,
  stockSettingsManage: STOCK_PERMISSIONS.settingsManage,
  manufacturingView: MANUFACTURING_PERMISSIONS.view,
  manufacturingManage: MANUFACTURING_PERMISSIONS.manage,
  manufacturingBomView: MANUFACTURING_PERMISSIONS.bomView,
  manufacturingBomManage: MANUFACTURING_PERMISSIONS.bomManage,
  manufacturingRoutingManage: MANUFACTURING_PERMISSIONS.routingManage,
  manufacturingPlanningRun: MANUFACTURING_PERMISSIONS.planningRun,
  manufacturingWorkOrderManage: MANUFACTURING_PERMISSIONS.workOrderManage,
  manufacturingWorkOrderRelease: MANUFACTURING_PERMISSIONS.workOrderRelease,
  manufacturingProductionPost: MANUFACTURING_PERMISSIONS.productionPost,
  manufacturingScrapPost: MANUFACTURING_PERMISSIONS.scrapPost,
  manufacturingCostingView: MANUFACTURING_PERMISSIONS.costingView,
  manufacturingReportsView: MANUFACTURING_PERMISSIONS.reportsView,
  manufacturingSettingsManage: MANUFACTURING_PERMISSIONS.settingsManage,
  projectsView: PROJECT_PERMISSIONS.view,
  projectsManage: PROJECT_PERMISSIONS.manage,
  projectsCreate: PROJECT_PERMISSIONS.create,
  projectsApprove: PROJECT_PERMISSIONS.approve,
  projectsTaskManage: PROJECT_PERMISSIONS.taskManage,
  projectsMilestoneManage: PROJECT_PERMISSIONS.milestoneManage,
  projectsResourceManage: PROJECT_PERMISSIONS.resourceManage,
  projectsTimeEnter: PROJECT_PERMISSIONS.timeEnter,
  projectsTimeApprove: PROJECT_PERMISSIONS.timeApprove,
  projectsExpenseEnter: PROJECT_PERMISSIONS.expenseEnter,
  projectsExpenseApprove: PROJECT_PERMISSIONS.expenseApprove,
  projectsBudgetManage: PROJECT_PERMISSIONS.budgetManage,
  projectsProcurementLink: PROJECT_PERMISSIONS.procurementLink,
  projectsBillingManage: PROJECT_PERMISSIONS.billingManage,
  projectsProfitabilityView: PROJECT_PERMISSIONS.profitabilityView,
  projectsReportsView: PROJECT_PERMISSIONS.reportsView,
  projectsSettingsManage: PROJECT_PERMISSIONS.settingsManage,
  assetsView: ASSET_PERMISSIONS.view,
  assetsManage: ASSET_PERMISSIONS.manage,
  assetsCreate: ASSET_PERMISSIONS.create,
  assetsCapitalize: ASSET_PERMISSIONS.capitalize,
  assetsAssign: ASSET_PERMISSIONS.assign,
  assetsTransfer: ASSET_PERMISSIONS.transfer,
  assetsMaintain: ASSET_PERMISSIONS.maintain,
  assetsInspect: ASSET_PERMISSIONS.inspect,
  assetsDepreciate: ASSET_PERMISSIONS.depreciate,
  assetsDispose: ASSET_PERMISSIONS.dispose,
  assetsAccountingHandoff: ASSET_PERMISSIONS.accountingHandoff,
  assetsReportsView: ASSET_PERMISSIONS.reportsView,
  assetsSettingsManage: ASSET_PERMISSIONS.settingsManage,
  posView: POS_PERMISSIONS.view,
  posOperate: POS_PERMISSIONS.operate,
  posShiftOpen: POS_PERMISSIONS.shiftOpen,
  posShiftClose: POS_PERMISSIONS.shiftClose,
  posSaleCreate: POS_PERMISSIONS.saleCreate,
  posDiscountApply: POS_PERMISSIONS.discountApply,
  posReturnCreate: POS_PERMISSIONS.returnCreate,
  posReturnApprove: POS_PERMISSIONS.returnApprove,
  posCashAdjust: POS_PERMISSIONS.cashAdjust,
  posPriceOverride: POS_PERMISSIONS.priceOverride,
  posTerminalManage: POS_PERMISSIONS.terminalManage,
  posStoreManage: POS_PERMISSIONS.storeManage,
  posPaymentManage: POS_PERMISSIONS.paymentManage,
  posReportsView: POS_PERMISSIONS.reportsView,
  posSettingsManage: POS_PERMISSIONS.settingsManage,
  qualityView: QUALITY_PERMISSIONS.view,
  qualityManage: QUALITY_PERMISSIONS.manage,
  qualityPlanManage: QUALITY_PERMISSIONS.planManage,
  qualityInspect: QUALITY_PERMISSIONS.inspect,
  qualityRelease: QUALITY_PERMISSIONS.release,
  qualityHold: QUALITY_PERMISSIONS.hold,
  qualityNonconformanceManage: QUALITY_PERMISSIONS.nonconformanceManage,
  qualityCapaManage: QUALITY_PERMISSIONS.capaManage,
  qualitySamplingManage: QUALITY_PERMISSIONS.samplingManage,
  qualitySupplierManage: QUALITY_PERMISSIONS.supplierQualityManage,
  qualityAuditManage: QUALITY_PERMISSIONS.auditManage,
  qualityReportsView: QUALITY_PERMISSIONS.reportsView,
  qualitySettingsManage: QUALITY_PERMISSIONS.settingsManage,
  supportView: SUPPORT_PERMISSIONS.view,
  supportManage: SUPPORT_PERMISSIONS.manage,
  supportTicketCreate: SUPPORT_PERMISSIONS.ticketCreate,
  supportTicketAssign: SUPPORT_PERMISSIONS.ticketAssign,
  supportTicketResolve: SUPPORT_PERMISSIONS.ticketResolve,
  supportTicketClose: SUPPORT_PERMISSIONS.ticketClose,
  supportQueueManage: SUPPORT_PERMISSIONS.queueManage,
  supportSlaManage: SUPPORT_PERMISSIONS.slaManage,
  supportEscalationManage: SUPPORT_PERMISSIONS.escalationManage,
  supportKnowledgeManage: SUPPORT_PERMISSIONS.knowledgeManage,
  supportCommunicationManage: SUPPORT_PERMISSIONS.communicationManage,
  supportSensitiveView: SUPPORT_PERMISSIONS.sensitiveView,
  supportReportsView: SUPPORT_PERMISSIONS.reportsView,
  supportSettingsManage: SUPPORT_PERMISSIONS.settingsManage,
  hrPayrollView: HR_PAYROLL_PERMISSIONS.view,
  hrPayrollEmployeeView: HR_PAYROLL_PERMISSIONS.employeeView,
  hrPayrollEmployeeManage: HR_PAYROLL_PERMISSIONS.employeeManage,
  hrPayrollSensitiveView: HR_PAYROLL_PERMISSIONS.sensitiveView,
  hrPayrollAttendanceManage: HR_PAYROLL_PERMISSIONS.attendanceManage,
  hrPayrollShiftManage: HR_PAYROLL_PERMISSIONS.shiftManage,
  hrPayrollLeaveManage: HR_PAYROLL_PERMISSIONS.leaveManage,
  hrPayrollLeaveApprove: HR_PAYROLL_PERMISSIONS.leaveApprove,
  hrPayrollExpenseManage: HR_PAYROLL_PERMISSIONS.expenseManage,
  hrPayrollExpenseApprove: HR_PAYROLL_PERMISSIONS.expenseApprove,
  hrPayrollPrepare: HR_PAYROLL_PERMISSIONS.payrollPrepare,
  hrPayrollApprove: HR_PAYROLL_PERMISSIONS.payrollApprove,
  hrPayrollPost: HR_PAYROLL_PERMISSIONS.payrollPost,
  hrPayrollPayslipView: HR_PAYROLL_PERMISSIONS.payslipView,
  hrPayrollCompensationManage: HR_PAYROLL_PERMISSIONS.compensationManage,
  hrPayrollStatutoryManage: HR_PAYROLL_PERMISSIONS.statutoryManage,
  hrPayrollReportsView: HR_PAYROLL_PERMISSIONS.reportsView,
  hrPayrollSettingsManage: HR_PAYROLL_PERMISSIONS.settingsManage,
  billingView: BILLING_PERMISSIONS.view,
  billingManage: BILLING_PERMISSIONS.manage,
  billingCheckout: BILLING_PERMISSIONS.checkout,
  billingAudit: BILLING_PERMISSIONS.audit,
} as const;

export function hasPermission(session: SessionContext, permission: string) {
  return (
    session.roleSlugs.includes("organization_owner") ||
    session.permissions.includes(permission)
  );
}

export async function requirePermission(permission: string) {
  const session = await requireWorkspace();
  if (!hasPermission(session, permission))
    throw new HttpError(
      403,
      "You do not have permission to perform this action.",
    );
  return session;
}

export async function requireApiPermission(
  permission: string,
): Promise<WorkspaceSessionContext> {
  const session = await getSessionContext();
  if (!session) throw new HttpError(401, "Authentication is required.");
  if (!session.emailVerified) {
    throw new HttpError(403, "Verify your email before using this workspace.");
  }
  if (!session.organizationId) {
    throw new HttpError(409, "Complete organisation onboarding first.");
  }
  if (!hasPermission(session, permission)) {
    throw new HttpError(
      403,
      "You do not have permission to perform this action.",
    );
  }
  return session as WorkspaceSessionContext;
}

export function requirePermissionFromSession(
  session: SessionContext,
  permission: string,
) {
  if (!hasPermission(session, permission))
    throw new HttpError(
      403,
      "You do not have permission to perform this action.",
    );
}
