import { CrmError } from "@vercent/api";
import type { CrmContext, CrmResourceKey } from "@vercent/shared-types";

import type { SessionContext } from "@/lib/auth";
import { PERMISSIONS } from "@/lib/authorization";
import { HttpError } from "@/lib/http";

export type CrmField = {
  name: string;
  label: string;
  type:
    | "text"
    | "email"
    | "number"
    | "date"
    | "datetime-local"
    | "select"
    | "checkbox"
    | "textarea";
  required?: boolean;
  optionsKey?: string;
  options?: Array<{ value: string; label: string }>;
};
export type CrmColumn = {
  key: string;
  label: string;
  optionsKey?: string;
  format?: "status" | "currency" | "date" | "datetime" | "score";
};
export type CrmDefinition = {
  key: CrmResourceKey;
  title: string;
  singular: string;
  description: string;
  group: "Work" | "Engagement" | "Configuration" | "Automation";
  permission: string;
  fields: CrmField[];
  columns: CrmColumn[];
};

const status = (...values: string[]) =>
  values.map((value) => ({
    value,
    label: value.replaceAll("_", " ").replace(/^./, (c) => c.toUpperCase()),
  }));
const company = {
  name: "companyId",
  label: "Company",
  type: "select" as const,
  optionsKey: "companies",
};
const branch = {
  name: "branchId",
  label: "Branch",
  type: "select" as const,
  optionsKey: "branches",
};
const owner = {
  name: "ownerUserId",
  label: "Owner",
  type: "select" as const,
  optionsKey: "users",
};

export const crmDefinitions: Record<CrmResourceKey, CrmDefinition> = {
  leads: {
    key: "leads",
    title: "Leads",
    singular: "lead",
    group: "Work",
    description:
      "Capture, qualify, score, assign and convert every enquiry without losing its history.",
    permission: PERMISSIONS.crmLeadsManage,
    columns: [
      { key: "code", label: "Code" },
      { key: "fullName", label: "Lead" },
      { key: "companyName", label: "Company" },
      { key: "status", label: "Status", format: "status" },
      { key: "score", label: "Score", format: "score" },
      { key: "estimatedValue", label: "Value", format: "currency" },
      { key: "nextFollowUpAt", label: "Next follow-up", format: "datetime" },
    ],
    fields: [
      company,
      branch,
      { name: "firstName", label: "First name", type: "text", required: true },
      { name: "lastName", label: "Last name", type: "text" },
      { name: "companyName", label: "Company / organisation", type: "text" },
      { name: "jobTitle", label: "Job title", type: "text" },
      { name: "email", label: "Email", type: "email" },
      { name: "mobile", label: "Mobile", type: "text" },
      { name: "phone", label: "Phone", type: "text" },
      {
        name: "sourceId",
        label: "Source",
        type: "select",
        optionsKey: "sources",
      },
      {
        name: "campaignId",
        label: "Campaign",
        type: "select",
        optionsKey: "campaigns",
      },
      owner,
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status(
          "new",
          "contacted",
          "working",
          "qualified",
          "unqualified",
        ),
      },
      {
        name: "priority",
        label: "Priority",
        type: "select",
        options: status("low", "medium", "high", "urgent"),
      },
      {
        name: "rating",
        label: "Rating",
        type: "select",
        options: status("cold", "warm", "hot"),
      },
      { name: "estimatedValue", label: "Estimated value", type: "number" },
      {
        name: "currencyCode",
        label: "Currency",
        type: "select",
        optionsKey: "currencies",
      },
      { name: "industry", label: "Industry", type: "text" },
      { name: "website", label: "Website", type: "text" },
      { name: "city", label: "City", type: "text" },
      { name: "state", label: "State", type: "text" },
      { name: "productInterest", label: "Product interest", type: "textarea" },
      {
        name: "nextFollowUpAt",
        label: "Next follow-up",
        type: "datetime-local",
      },
      { name: "consentEmail", label: "Email consent", type: "checkbox" },
      { name: "consentSms", label: "SMS consent", type: "checkbox" },
      { name: "consentWhatsapp", label: "WhatsApp consent", type: "checkbox" },
      { name: "doNotContact", label: "Do not contact", type: "checkbox" },
    ],
  },
  opportunities: {
    key: "opportunities",
    title: "Opportunities",
    singular: "opportunity",
    group: "Work",
    description:
      "Manage qualified revenue through configurable stages, probability and forecasting.",
    permission: PERMISSIONS.crmOpportunitiesManage,
    columns: [
      { key: "code", label: "Code" },
      { key: "name", label: "Opportunity" },
      { key: "stageId", label: "Stage", optionsKey: "stages" },
      { key: "amount", label: "Amount", format: "currency" },
      { key: "probability", label: "Probability" },
      { key: "expectedCloseDate", label: "Expected close", format: "date" },
      { key: "status", label: "Status", format: "status" },
    ],
    fields: [
      company,
      branch,
      { name: "name", label: "Opportunity name", type: "text", required: true },
      {
        name: "pipelineId",
        label: "Pipeline",
        type: "select",
        optionsKey: "pipelines",
      },
      { name: "stageId", label: "Stage", type: "select", optionsKey: "stages" },
      { name: "leadId", label: "Lead", type: "select", optionsKey: "leads" },
      {
        name: "partyId",
        label: "Customer",
        type: "select",
        optionsKey: "parties",
      },
      {
        name: "contactId",
        label: "Contact",
        type: "select",
        optionsKey: "contacts",
      },
      owner,
      { name: "amount", label: "Amount", type: "number" },
      {
        name: "currencyCode",
        label: "Currency",
        type: "select",
        optionsKey: "currencies",
      },
      { name: "probability", label: "Probability %", type: "number" },
      { name: "expectedCloseDate", label: "Expected close date", type: "date" },
      {
        name: "forecastCategory",
        label: "Forecast category",
        type: "select",
        options: status(
          "pipeline",
          "best_case",
          "committed",
          "closed",
          "omitted",
        ),
      },
      { name: "nextStep", label: "Next step", type: "textarea" },
      { name: "description", label: "Description", type: "textarea" },
    ],
  },
  activities: {
    key: "activities",
    title: "Activities",
    singular: "activity",
    group: "Work",
    description:
      "Schedule tasks, calls, meetings, messages and follow-ups with accountable ownership.",
    permission: PERMISSIONS.crmActivitiesManage,
    columns: [
      { key: "activityType", label: "Type" },
      { key: "subject", label: "Subject" },
      { key: "assignedTo", label: "Assigned to", optionsKey: "users" },
      { key: "dueAt", label: "Due", format: "datetime" },
      { key: "priority", label: "Priority", format: "status" },
      { key: "status", label: "Status", format: "status" },
    ],
    fields: [
      company,
      branch,
      {
        name: "entityType",
        label: "Related record type",
        type: "select",
        options: status(
          "lead",
          "opportunity",
          "party",
          "contact",
          "campaign",
          "general",
        ),
      },
      { name: "entityId", label: "Related record ID", type: "text" },
      {
        name: "activityType",
        label: "Activity type",
        type: "select",
        options: status(
          "task",
          "call",
          "meeting",
          "email",
          "whatsapp",
          "sms",
          "note",
        ),
      },
      { name: "subject", label: "Subject", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea" },
      {
        name: "assignedTo",
        label: "Assigned to",
        type: "select",
        optionsKey: "users",
      },
      {
        name: "priority",
        label: "Priority",
        type: "select",
        options: status("low", "medium", "high", "urgent"),
      },
      { name: "startAt", label: "Start", type: "datetime-local" },
      { name: "dueAt", label: "Due", type: "datetime-local" },
      { name: "reminderAt", label: "Reminder", type: "datetime-local" },
      { name: "location", label: "Location", type: "text" },
    ],
  },
  campaigns: {
    key: "campaigns",
    title: "Campaigns",
    singular: "campaign",
    group: "Engagement",
    description:
      "Attribute lead origin, budget, responses and conversions to governed campaigns.",
    permission: PERMISSIONS.crmCampaignsManage,
    columns: [
      { key: "code", label: "Code" },
      { key: "name", label: "Campaign" },
      { key: "campaignType", label: "Type" },
      { key: "status", label: "Status", format: "status" },
      { key: "budget", label: "Budget", format: "currency" },
      { key: "startDate", label: "Start", format: "date" },
    ],
    fields: [
      company,
      { name: "name", label: "Campaign name", type: "text", required: true },
      {
        name: "campaignType",
        label: "Campaign type",
        type: "select",
        options: status(
          "email",
          "event",
          "webinar",
          "referral",
          "partner",
          "advertising",
          "social",
          "other",
        ),
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status(
          "planned",
          "active",
          "paused",
          "completed",
          "cancelled",
        ),
      },
      { name: "startDate", label: "Start date", type: "date" },
      { name: "endDate", label: "End date", type: "date" },
      { name: "budget", label: "Budget", type: "number" },
      { name: "expectedRevenue", label: "Expected revenue", type: "number" },
      { name: "actualCost", label: "Actual cost", type: "number" },
      owner,
      { name: "description", label: "Description", type: "textarea" },
    ],
  },
  communications: {
    key: "communications",
    title: "Communication log",
    singular: "communication",
    group: "Engagement",
    description:
      "Keep a provider-neutral history of email, calls, SMS, chat and WhatsApp conversations.",
    permission: PERMISSIONS.crmCommunicationsManage,
    columns: [
      { key: "channel", label: "Channel" },
      { key: "direction", label: "Direction" },
      { key: "subject", label: "Subject" },
      { key: "status", label: "Status", format: "status" },
      { key: "occurredAt", label: "Occurred", format: "datetime" },
    ],
    fields: [
      {
        name: "channel",
        label: "Channel",
        type: "select",
        options: status("email", "whatsapp", "sms", "call", "chat", "other"),
      },
      {
        name: "direction",
        label: "Direction",
        type: "select",
        options: status("inbound", "outbound"),
      },
      { name: "leadId", label: "Lead", type: "select", optionsKey: "leads" },
      {
        name: "opportunityId",
        label: "Opportunity",
        type: "select",
        optionsKey: "opportunities",
      },
      {
        name: "partyId",
        label: "Business partner",
        type: "select",
        optionsKey: "parties",
      },
      {
        name: "contactId",
        label: "Contact",
        type: "select",
        optionsKey: "contacts",
      },
      { name: "provider", label: "Provider", type: "text" },
      { name: "subject", label: "Subject", type: "text" },
      {
        name: "body",
        label: "Message / notes",
        type: "textarea",
        required: true,
      },
      { name: "fromAddress", label: "From", type: "text" },
      { name: "occurredAt", label: "Occurred at", type: "datetime-local" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status(
          "logged",
          "draft",
          "queued",
          "sent",
          "delivered",
          "read",
          "failed",
          "received",
        ),
      },
    ],
  },
  pipelines: config(
    "pipelines",
    "Pipelines",
    "pipeline",
    PERMISSIONS.crmSettingsManage,
    [
      company,
      { name: "name", label: "Name", type: "text", required: true },
      { name: "code", label: "Code", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea" },
      { name: "isDefault", label: "Default pipeline", type: "checkbox" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status("active", "inactive"),
      },
    ],
  ),
  stages: config(
    "stages",
    "Pipeline stages",
    "stage",
    PERMISSIONS.crmSettingsManage,
    [
      {
        name: "pipelineId",
        label: "Pipeline",
        type: "select",
        optionsKey: "pipelines",
        required: true,
      },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "code", label: "Code", type: "text", required: true },
      { name: "sequence", label: "Sequence", type: "number" },
      { name: "probability", label: "Probability %", type: "number" },
      {
        name: "forecastCategory",
        label: "Forecast category",
        type: "select",
        options: status(
          "pipeline",
          "best_case",
          "committed",
          "closed",
          "omitted",
        ),
      },
      { name: "isWon", label: "Won stage", type: "checkbox" },
      { name: "isLost", label: "Lost stage", type: "checkbox" },
      { name: "staleAfterDays", label: "Stale after days", type: "number" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status("active", "inactive"),
      },
    ],
  ),
  sources: config(
    "sources",
    "Lead sources",
    "source",
    PERMISSIONS.crmSettingsManage,
    [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "code", label: "Code", type: "text", required: true },
      { name: "channel", label: "Channel", type: "text" },
      { name: "isDefault", label: "Default source", type: "checkbox" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status("active", "inactive"),
      },
    ],
  ),
  "lost-reasons": config(
    "lost-reasons",
    "Lost reasons",
    "lost reason",
    PERMISSIONS.crmSettingsManage,
    [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "code", label: "Code", type: "text", required: true },
      { name: "category", label: "Category", type: "text" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status("active", "inactive"),
      },
    ],
  ),
  tags: config("tags", "CRM tags", "tag", PERMISSIONS.crmSettingsManage, [
    { name: "name", label: "Name", type: "text", required: true },
    { name: "color", label: "Colour", type: "text" },
    {
      name: "status",
      label: "Status",
      type: "select",
      options: status("active", "inactive"),
    },
  ]),
  "scoring-rules": config(
    "scoring-rules",
    "Lead scoring rules",
    "scoring rule",
    PERMISSIONS.crmAutomationManage,
    [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "sequence", label: "Sequence", type: "number" },
      { name: "fieldName", label: "Lead field", type: "text", required: true },
      {
        name: "operator",
        label: "Operator",
        type: "select",
        options: status(
          "equals",
          "not_equals",
          "contains",
          "not_empty",
          "empty",
          "greater_than",
          "less_than",
          "in",
        ),
      },
      { name: "comparisonValue", label: "Comparison JSON", type: "textarea" },
      { name: "points", label: "Points", type: "number" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status("active", "inactive"),
      },
    ],
  ),
  "assignment-rules": config(
    "assignment-rules",
    "Assignment rules",
    "assignment rule",
    PERMISSIONS.crmAutomationManage,
    [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "sequence", label: "Sequence", type: "number" },
      { name: "criteria", label: "Criteria JSON", type: "textarea" },
      {
        name: "assignmentMode",
        label: "Mode",
        type: "select",
        options: status("fixed", "round_robin"),
      },
      {
        name: "assigneeUserId",
        label: "Fixed assignee",
        type: "select",
        optionsKey: "users",
      },
      {
        name: "roundRobinUserIds",
        label: "Round-robin user IDs JSON",
        type: "textarea",
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status("active", "inactive"),
      },
    ],
  ),
  sequences: config(
    "sequences",
    "Follow-up sequences",
    "sequence",
    PERMISSIONS.crmAutomationManage,
    [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea" },
      owner,
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status("draft", "active", "paused", "archived"),
      },
    ],
  ),
  "sequence-steps": config(
    "sequence-steps",
    "Sequence steps",
    "sequence step",
    PERMISSIONS.crmAutomationManage,
    [
      {
        name: "sequenceId",
        label: "Sequence",
        type: "select",
        optionsKey: "sequences",
        required: true,
      },
      {
        name: "stepOrder",
        label: "Step order",
        type: "number",
        required: true,
      },
      { name: "delayMinutes", label: "Delay in minutes", type: "number" },
      {
        name: "actionType",
        label: "Action type",
        type: "select",
        options: status("task", "call", "email", "whatsapp", "sms"),
      },
      { name: "subjectTemplate", label: "Subject template", type: "text" },
      { name: "bodyTemplate", label: "Body template", type: "textarea" },
      {
        name: "assignedToOwner",
        label: "Assign to record owner",
        type: "checkbox",
      },
    ],
  ),
  "sequence-enrollments": config(
    "sequence-enrollments",
    "Sequence enrollments",
    "sequence enrollment",
    PERMISSIONS.crmAutomationManage,
    [
      {
        name: "sequenceId",
        label: "Sequence",
        type: "select",
        optionsKey: "sequences",
        required: true,
      },
      { name: "leadId", label: "Lead", type: "select", optionsKey: "leads" },
      {
        name: "contactId",
        label: "Contact",
        type: "select",
        optionsKey: "contacts",
      },
      {
        name: "opportunityId",
        label: "Opportunity",
        type: "select",
        optionsKey: "opportunities",
      },
      { name: "nextRunAt", label: "Next run", type: "datetime-local" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status("active", "paused", "completed", "cancelled"),
      },
    ],
  ),
  "automation-rules": config(
    "automation-rules",
    "Automation rules",
    "automation rule",
    PERMISSIONS.crmAutomationManage,
    [
      { name: "name", label: "Name", type: "text", required: true },
      {
        name: "eventType",
        label: "Event",
        type: "select",
        options: status(
          "lead.created",
          "lead.updated",
          "lead.qualified",
          "opportunity.created",
          "opportunity.stage_changed",
          "activity.overdue",
          "campaign.member_responded",
        ),
      },
      { name: "sequence", label: "Sequence", type: "number" },
      { name: "conditions", label: "Conditions JSON", type: "textarea" },
      { name: "actions", label: "Actions JSON", type: "textarea" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status("active", "inactive"),
      },
    ],
  ),
  "capture-forms": config(
    "capture-forms",
    "Lead capture forms",
    "capture form",
    PERMISSIONS.crmCaptureManage,
    [
      company,
      branch,
      { name: "name", label: "Name", type: "text", required: true },
      {
        name: "sourceId",
        label: "Source",
        type: "select",
        optionsKey: "sources",
      },
      {
        name: "campaignId",
        label: "Campaign",
        type: "select",
        optionsKey: "campaigns",
      },
      owner,
      {
        name: "allowedOrigins",
        label: "Allowed origins JSON",
        type: "textarea",
      },
      {
        name: "requiredFields",
        label: "Required fields JSON",
        type: "textarea",
      },
      { name: "successMessage", label: "Success message", type: "textarea" },
      {
        name: "rateLimitPerHour",
        label: "Hourly submission limit",
        type: "number",
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status("active", "inactive"),
      },
    ],
  ),
  competitors: config(
    "competitors",
    "Competitors",
    "competitor",
    PERMISSIONS.crmSettingsManage,
    [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "website", label: "Website", type: "text" },
      { name: "strengths", label: "Strengths", type: "textarea" },
      { name: "weaknesses", label: "Weaknesses", type: "textarea" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status("active", "inactive"),
      },
    ],
  ),
  "forecast-targets": config(
    "forecast-targets",
    "Forecast targets",
    "target",
    PERMISSIONS.crmSettingsManage,
    [
      company,
      {
        name: "userId",
        label: "Salesperson",
        type: "select",
        optionsKey: "users",
      },
      {
        name: "periodStart",
        label: "Period start",
        type: "date",
        required: true,
      },
      { name: "periodEnd", label: "Period end", type: "date", required: true },
      {
        name: "currencyCode",
        label: "Currency",
        type: "select",
        optionsKey: "currencies",
      },
      { name: "targetAmount", label: "Target amount", type: "number" },
    ],
  ),
  integrations: config(
    "integrations",
    "Communication integrations",
    "integration",
    PERMISSIONS.crmIntegrationsManage,
    [
      {
        name: "provider",
        label: "Provider",
        type: "select",
        options: status(
          "gmail",
          "microsoft365",
          "whatsapp",
          "twilio",
          "zoom",
          "webhook",
          "other",
        ),
      },
      {
        name: "displayName",
        label: "Display name",
        type: "text",
        required: true,
      },
      {
        name: "credentialReference",
        label: "Secret-manager reference",
        type: "text",
      },
      {
        name: "configuration",
        label: "Non-secret configuration JSON",
        type: "textarea",
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status("disconnected", "connected", "error", "disabled"),
      },
    ],
  ),
  "webhook-subscriptions": config(
    "webhook-subscriptions",
    "Webhook subscriptions",
    "webhook",
    PERMISSIONS.crmIntegrationsManage,
    [
      { name: "name", label: "Name", type: "text", required: true },
      {
        name: "endpointUrl",
        label: "Endpoint URL",
        type: "text",
        required: true,
      },
      { name: "eventTypes", label: "Event types JSON", type: "textarea" },
      {
        name: "secretReference",
        label: "Secret-manager reference",
        type: "text",
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: status("active", "inactive"),
      },
    ],
  ),
  "sales-teams": config(
    "sales-teams",
    "Sales teams",
    "sales team",
    PERMISSIONS.crmRevenueManage,
    [
      company,
      { name: "parentTeamId", label: "Parent team", type: "select", optionsKey: "salesTeams" },
      { name: "code", label: "Code", type: "text", required: true },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "managerUserId", label: "Manager", type: "select", optionsKey: "users" },
      { name: "defaultPipelineId", label: "Default pipeline", type: "select", optionsKey: "pipelines" },
      { name: "currencyCode", label: "Currency", type: "select", optionsKey: "currencies" },
      { name: "status", label: "Status", type: "select", options: status("active", "inactive") },
    ],
  ),
  "sales-team-members": {
    key: "sales-team-members",
    title: "Sales team members",
    singular: "sales team member",
    group: "Configuration",
    description: "Assign sellers, managers, overlays and sales-operations users to governed sales teams.",
    permission: PERMISSIONS.crmRevenueManage,
    columns: [
      { key: "teamId", label: "Sales team", optionsKey: "salesTeams" },
      { key: "userId", label: "User", optionsKey: "users" },
      { key: "memberRole", label: "Role", format: "status" },
      { key: "allocationPercent", label: "Allocation" },
      { key: "effectiveFrom", label: "Effective from", format: "date" },
      { key: "status", label: "Status", format: "status" },
    ],
    fields: [
      company,
      { name: "teamId", label: "Sales team", type: "select", optionsKey: "salesTeams", required: true },
      { name: "userId", label: "User", type: "select", optionsKey: "users", required: true },
      { name: "memberRole", label: "Member role", type: "select", options: status("manager", "seller", "sales_ops", "overlay", "observer") },
      { name: "allocationPercent", label: "Allocation %", type: "number" },
      { name: "effectiveFrom", label: "Effective from", type: "date", required: true },
      { name: "effectiveTo", label: "Effective to", type: "date" },
      { name: "status", label: "Status", type: "select", options: status("active", "inactive") },
    ],
  },
  territories: config(
    "territories",
    "Territories",
    "territory",
    PERMISSIONS.crmRevenueManage,
    [
      company,
      { name: "parentTerritoryId", label: "Parent territory", type: "select", optionsKey: "territories" },
      { name: "code", label: "Code", type: "text", required: true },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "territoryType", label: "Territory type", type: "select", options: status("geographic", "industry", "account", "product", "channel", "named", "hybrid") },
      { name: "managerUserId", label: "Manager", type: "select", optionsKey: "users" },
      { name: "assignmentRules", label: "Assignment rules JSON", type: "textarea" },
      { name: "status", label: "Status", type: "select", options: status("draft", "active", "inactive", "archived") },
    ],
  ),
  "territory-assignments": {
    key: "territory-assignments",
    title: "Territory assignments",
    singular: "territory assignment",
    group: "Configuration",
    description: "Assign users, teams, accounts, leads and opportunities to governed sales territories.",
    permission: PERMISSIONS.crmRevenueManage,
    columns: [
      { key: "territoryId", label: "Territory", optionsKey: "territories" },
      { key: "assigneeType", label: "Assignee type", format: "status" },
      { key: "assigneeId", label: "Assignee ID" },
      { key: "assignmentRole", label: "Role", format: "status" },
      { key: "effectiveFrom", label: "Effective from", format: "date" },
      { key: "source", label: "Source", format: "status" },
    ],
    fields: [
      company,
      { name: "territoryId", label: "Territory", type: "select", optionsKey: "territories", required: true },
      { name: "assigneeType", label: "Assignee type", type: "select", options: status("user", "team", "party", "lead", "opportunity"), required: true },
      { name: "assigneeId", label: "Assignee UUID", type: "text", required: true },
      { name: "assignmentRole", label: "Assignment role", type: "select", options: status("primary", "overlay", "shared", "manager") },
      { name: "effectiveFrom", label: "Effective from", type: "date", required: true },
      { name: "effectiveTo", label: "Effective to", type: "date" },
      { name: "source", label: "Source", type: "select", options: status("manual", "rule", "import", "integration") },
    ],
  },
  "quota-plans": config(
    "quota-plans",
    "Quota plans",
    "quota plan",
    PERMISSIONS.crmRevenueManage,
    [
      company,
      { name: "teamId", label: "Sales team", type: "select", optionsKey: "salesTeams" },
      { name: "territoryId", label: "Territory", type: "select", optionsKey: "territories" },
      { name: "userId", label: "Salesperson", type: "select", optionsKey: "users" },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "quotaType", label: "Quota type", type: "select", options: status("revenue", "bookings", "margin", "quantity", "new_logo", "activity") },
      { name: "periodStart", label: "Period start", type: "date", required: true },
      { name: "periodEnd", label: "Period end", type: "date", required: true },
      { name: "currencyCode", label: "Currency", type: "select", optionsKey: "currencies" },
      { name: "targetAmount", label: "Target amount", type: "number", required: true },
      { name: "stretchAmount", label: "Stretch amount", type: "number" },
      { name: "status", label: "Status", type: "select", options: status("draft", "active", "closed", "cancelled") },
    ],
  ),
  "forecast-periods": config(
    "forecast-periods",
    "Forecast periods",
    "forecast period",
    PERMISSIONS.crmRevenueManage,
    [
      company,
      { name: "name", label: "Name", type: "text", required: true },
      { name: "periodType", label: "Period type", type: "select", options: status("week", "month", "quarter", "year", "custom") },
      { name: "periodStart", label: "Period start", type: "date", required: true },
      { name: "periodEnd", label: "Period end", type: "date", required: true },
      { name: "currencyCode", label: "Currency", type: "select", optionsKey: "currencies" },
      { name: "freezeAt", label: "Freeze at", type: "datetime-local" },
      { name: "status", label: "Status", type: "select", options: status("planned", "open", "frozen", "closed") },
    ],
  ),
  "forecast-submissions": {
    key: "forecast-submissions",
    title: "Forecast submissions",
    singular: "forecast submission",
    group: "Work",
    description: "Submit seller and manager forecasts with pipeline, best-case, commit, closed and confidence values.",
    permission: PERMISSIONS.crmRevenueManage,
    columns: [
      { key: "ownerUserId", label: "Owner", optionsKey: "users" },
      { key: "periodId", label: "Period", optionsKey: "forecastPeriods" },
      { key: "commitAmount", label: "Commit", format: "currency" },
      { key: "bestCaseAmount", label: "Best case", format: "currency" },
      { key: "closedAmount", label: "Closed", format: "currency" },
      { key: "status", label: "Status", format: "status" },
    ],
    fields: [
      company,
      { name: "periodId", label: "Forecast period", type: "select", optionsKey: "forecastPeriods", required: true },
      { name: "teamId", label: "Sales team", type: "select", optionsKey: "salesTeams" },
      { name: "territoryId", label: "Territory", type: "select", optionsKey: "territories" },
      owner,
      { name: "pipelineAmount", label: "Pipeline amount", type: "number" },
      { name: "bestCaseAmount", label: "Best-case amount", type: "number" },
      { name: "commitAmount", label: "Commit amount", type: "number" },
      { name: "closedAmount", label: "Closed amount", type: "number" },
      { name: "managerAdjustment", label: "Manager adjustment", type: "number" },
      { name: "currencyCode", label: "Currency", type: "select", optionsKey: "currencies" },
      { name: "confidencePercent", label: "Confidence %", type: "number" },
      { name: "notes", label: "Notes", type: "textarea" },
      { name: "status", label: "Status", type: "select", options: status("draft", "submitted", "approved", "rejected", "superseded") },
    ],
  },
  "account-plans": {
    key: "account-plans",
    title: "Account plans",
    singular: "account plan",
    group: "Work",
    description: "Plan strategic accounts, renewal risk, health, white-space opportunities and executive sponsorship.",
    permission: PERMISSIONS.crmAccountsManage,
    columns: [
      { key: "partyId", label: "Account", optionsKey: "parties" },
      { key: "accountTier", label: "Tier", format: "status" },
      { key: "lifecycleStage", label: "Lifecycle", format: "status" },
      { key: "healthStatus", label: "Health", format: "status" },
      { key: "healthScore", label: "Score", format: "score" },
      { key: "renewalDate", label: "Renewal", format: "date" },
    ],
    fields: [
      company,
      { name: "partyId", label: "Account", type: "select", optionsKey: "parties", required: true },
      owner,
      { name: "executiveSponsorUserId", label: "Executive sponsor", type: "select", optionsKey: "users" },
      { name: "accountTier", label: "Account tier", type: "select", options: status("strategic", "enterprise", "growth", "standard", "long_tail") },
      { name: "lifecycleStage", label: "Lifecycle stage", type: "select", options: status("prospect", "onboarding", "active", "at_risk", "renewal", "churned") },
      { name: "objectives", label: "Objectives JSON", type: "textarea" },
      { name: "risks", label: "Risks JSON", type: "textarea" },
      { name: "whiteSpace", label: "White-space JSON", type: "textarea" },
      { name: "successPlan", label: "Success plan JSON", type: "textarea" },
      { name: "renewalDate", label: "Renewal date", type: "date" },
      { name: "annualRevenue", label: "Annual revenue", type: "number" },
      { name: "potentialRevenue", label: "Potential revenue", type: "number" },
      { name: "healthScore", label: "Health score", type: "number" },
      { name: "healthStatus", label: "Health status", type: "select", options: status("healthy", "watch", "at_risk", "critical", "unknown") },
      { name: "lastReviewedAt", label: "Last reviewed", type: "datetime-local" },
      { name: "nextReviewAt", label: "Next review", type: "datetime-local" },
      { name: "status", label: "Status", type: "select", options: status("active", "inactive", "archived") },
    ],
  },
  "account-stakeholders": {
    key: "account-stakeholders",
    title: "Account stakeholders",
    singular: "stakeholder",
    group: "Work",
    description: "Map economic buyers, champions, decision makers, blockers and relationship ownership.",
    permission: PERMISSIONS.crmAccountsManage,
    columns: [
      { key: "name", label: "Stakeholder" },
      { key: "title", label: "Title" },
      { key: "stakeholderRole", label: "Role", format: "status" },
      { key: "influenceLevel", label: "Influence", format: "status" },
      { key: "sentiment", label: "Sentiment", format: "status" },
      { key: "engagementScore", label: "Engagement", format: "score" },
    ],
    fields: [
      company,
      { name: "accountPlanId", label: "Account plan", type: "select", optionsKey: "accountPlans", required: true },
      { name: "contactId", label: "Contact", type: "select", optionsKey: "contacts" },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "title", label: "Title", type: "text" },
      { name: "stakeholderRole", label: "Role", type: "select", options: status("economic_buyer", "decision_maker", "champion", "influencer", "user", "blocker", "procurement", "legal", "technical") },
      { name: "influenceLevel", label: "Influence", type: "select", options: status("low", "medium", "high", "critical") },
      { name: "sentiment", label: "Sentiment", type: "select", options: status("strong_supporter", "supporter", "neutral", "detractor", "strong_detractor", "unknown") },
      { name: "relationshipOwnerUserId", label: "Relationship owner", type: "select", optionsKey: "users" },
      { name: "engagementScore", label: "Engagement score", type: "number" },
      { name: "notes", label: "Notes", type: "textarea" },
      { name: "status", label: "Status", type: "select", options: status("active", "inactive") },
    ],
  },
  playbooks: config(
    "playbooks",
    "Sales playbooks",
    "playbook",
    PERMISSIONS.crmPlaybooksManage,
    [
      company,
      { name: "pipelineId", label: "Pipeline", type: "select", optionsKey: "pipelines" },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "framework", label: "Framework", type: "select", options: status("bant", "meddic", "meddpicc", "spin", "challenger", "custom") },
      { name: "description", label: "Description", type: "textarea" },
      { name: "guidance", label: "Guidance", type: "textarea" },
      { name: "status", label: "Status", type: "select", options: status("draft", "active", "inactive", "archived") },
    ],
  ),
  "playbook-questions": {
    key: "playbook-questions",
    title: "Playbook questions",
    singular: "playbook question",
    group: "Configuration",
    description: "Define qualification evidence, stage requirements and guided questions for each playbook.",
    permission: PERMISSIONS.crmPlaybooksManage,
    columns: [
      { key: "playbookId", label: "Playbook", optionsKey: "playbooks" },
      { key: "prompt", label: "Question" },
      { key: "responseType", label: "Response", format: "status" },
      { key: "required", label: "Required" },
      { key: "blocksStageExit", label: "Blocks stage exit" },
      { key: "status", label: "Status", format: "status" },
    ],
    fields: [
      company,
      { name: "playbookId", label: "Playbook", type: "select", optionsKey: "playbooks", required: true },
      { name: "stageId", label: "Pipeline stage", type: "select", optionsKey: "stages" },
      { name: "questionKey", label: "Question key", type: "text", required: true },
      { name: "prompt", label: "Question", type: "textarea", required: true },
      { name: "responseType", label: "Response type", type: "select", options: status("text", "number", "date", "boolean", "select", "multi_select") },
      { name: "responseOptions", label: "Response options JSON", type: "textarea" },
      { name: "required", label: "Required", type: "checkbox" },
      { name: "blocksStageExit", label: "Block stage exit", type: "checkbox" },
      { name: "sequence", label: "Sequence", type: "number" },
      { name: "scoringWeight", label: "Scoring weight", type: "number" },
      { name: "status", label: "Status", type: "select", options: status("active", "inactive") },
    ],
  },
  "playbook-responses": {
    key: "playbook-responses",
    title: "Playbook responses",
    singular: "playbook response",
    group: "Work",
    description: "Capture auditable qualification evidence for leads and opportunities before governed stage progression.",
    permission: PERMISSIONS.crmPlaybooksManage,
    columns: [
      { key: "questionId", label: "Question", optionsKey: "playbookQuestions" },
      { key: "opportunityId", label: "Opportunity", optionsKey: "opportunities" },
      { key: "leadId", label: "Lead", optionsKey: "leads" },
      { key: "respondedBy", label: "Responded by", optionsKey: "users" },
      { key: "respondedAt", label: "Responded", format: "datetime" },
      { key: "source", label: "Source", format: "status" },
    ],
    fields: [
      company,
      { name: "playbookId", label: "Playbook", type: "select", optionsKey: "playbooks", required: true },
      { name: "questionId", label: "Question", type: "select", optionsKey: "playbookQuestions", required: true },
      { name: "opportunityId", label: "Opportunity", type: "select", optionsKey: "opportunities" },
      { name: "leadId", label: "Lead", type: "select", optionsKey: "leads" },
      { name: "response", label: "Response JSON", type: "textarea", required: true },
      { name: "respondedBy", label: "Responded by", type: "select", optionsKey: "users" },
      { name: "respondedAt", label: "Responded at", type: "datetime-local" },
      { name: "source", label: "Source", type: "select", options: status("manual", "import", "integration", "ai_suggestion") },
    ],
  },
  "consent-events": {
    key: "consent-events",
    title: "Consent evidence",
    singular: "consent event",
    group: "Engagement",
    description: "Keep immutable channel, purpose, lawful-basis and evidence records for customer communication consent.",
    permission: PERMISSIONS.crmPrivacyManage,
    columns: [
      { key: "channel", label: "Channel", format: "status" },
      { key: "purpose", label: "Purpose", format: "status" },
      { key: "action", label: "Action", format: "status" },
      { key: "source", label: "Source" },
      { key: "occurredAt", label: "Occurred", format: "datetime" },
    ],
    fields: [
      company,
      { name: "leadId", label: "Lead", type: "select", optionsKey: "leads" },
      { name: "contactId", label: "Contact", type: "select", optionsKey: "contacts" },
      { name: "partyId", label: "Account", type: "select", optionsKey: "parties" },
      { name: "channel", label: "Channel", type: "select", options: status("email", "sms", "whatsapp", "call", "postal", "all"), required: true },
      { name: "purpose", label: "Purpose", type: "select", options: status("sales", "marketing", "service", "transactional", "research", "other") },
      { name: "action", label: "Action", type: "select", options: status("granted", "withdrawn", "suppressed", "resubscribed", "expired"), required: true },
      { name: "lawfulBasis", label: "Lawful basis", type: "select", options: status("consent", "contract", "legal_obligation", "legitimate_interest", "vital_interest", "public_task") },
      { name: "source", label: "Source", type: "select", options: status("form", "manual", "import", "integration", "preference_center", "system") },
      { name: "evidence", label: "Evidence JSON", type: "textarea" },
      { name: "occurredAt", label: "Occurred at", type: "datetime-local" },
      { name: "expiresAt", label: "Expires at", type: "datetime-local" },
    ],
  },
  "privacy-requests": {
    key: "privacy-requests",
    title: "Privacy requests",
    singular: "privacy request",
    group: "Work",
    description: "Track access, export, correction, deletion, restriction, objection and consent-withdrawal requests.",
    permission: PERMISSIONS.crmPrivacyManage,
    columns: [
      { key: "requestType", label: "Request", format: "status" },
      { key: "subjectType", label: "Subject", format: "status" },
      { key: "requesterName", label: "Requester" },
      { key: "dueAt", label: "Due", format: "datetime" },
      { key: "status", label: "Status", format: "status" },
    ],
    fields: [
      company,
      { name: "requestType", label: "Request type", type: "select", options: status("access", "export", "correction", "deletion", "restriction", "objection", "consent_withdrawal"), required: true },
      { name: "subjectType", label: "Subject type", type: "select", options: status("lead", "contact", "party"), required: true },
      { name: "subjectId", label: "Subject ID", type: "text", required: true },
      { name: "requesterName", label: "Requester name", type: "text" },
      { name: "requesterEmail", label: "Requester email", type: "email" },
      { name: "identityVerifiedAt", label: "Identity verified", type: "datetime-local" },
      { name: "dueAt", label: "Due at", type: "datetime-local", required: true },
      { name: "status", label: "Status", type: "select", options: status("received", "verification_pending", "in_progress", "completed", "rejected", "cancelled") },
      { name: "resolutionNotes", label: "Resolution notes", type: "textarea" },
      { name: "completedAt", label: "Completed at", type: "datetime-local" },
      { name: "assignedTo", label: "Assigned to", type: "select", optionsKey: "users" },
    ],
  },
  "data-quality-scores": {
    key: "data-quality-scores",
    title: "Data quality scores",
    singular: "data quality score",
    group: "Configuration",
    description: "Measure completeness, validity, freshness and duplicate risk for governed CRM records.",
    permission: PERMISSIONS.crmDataQualityManage,
    columns: [
      { key: "entityType", label: "Entity", format: "status" },
      { key: "entityId", label: "Entity ID" },
      { key: "overallScore", label: "Overall", format: "score" },
      { key: "duplicateRiskScore", label: "Duplicate risk", format: "score" },
      { key: "calculatedAt", label: "Calculated", format: "datetime" },
    ],
    fields: [
      company,
      { name: "entityType", label: "Entity type", type: "select", options: status("lead", "opportunity", "party", "contact"), required: true },
      { name: "entityId", label: "Entity ID", type: "text", required: true },
      { name: "completenessScore", label: "Completeness score", type: "number", required: true },
      { name: "validityScore", label: "Validity score", type: "number", required: true },
      { name: "freshnessScore", label: "Freshness score", type: "number", required: true },
      { name: "duplicateRiskScore", label: "Duplicate risk", type: "number", required: true },
      { name: "overallScore", label: "Overall score", type: "number", required: true },
      { name: "issues", label: "Issues JSON", type: "textarea" },
      { name: "calculatedAt", label: "Calculated at", type: "datetime-local" },
      { name: "calculationVersion", label: "Calculation version", type: "text" },
    ],
  },
  "saved-views": config(
    "saved-views",
    "Saved views",
    "saved view",
    PERMISSIONS.crmView,
    [
      {
        name: "resource",
        label: "Resource",
        type: "select",
        options: status(
          "leads",
          "opportunities",
          "activities",
          "campaigns",
          "communications",
        ),
      },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "filters", label: "Filters JSON", type: "textarea" },
      { name: "sort", label: "Sort JSON", type: "textarea" },
      { name: "columns", label: "Columns JSON", type: "textarea" },
      { name: "isDefault", label: "Default view", type: "checkbox" },
    ],
  ),
};

function config(
  key: CrmResourceKey,
  title: string,
  singular: string,
  permission: string,
  fields: CrmField[],
): CrmDefinition {
  return {
    key,
    title,
    singular,
    permission,
    fields,
    group:
      key === "scoring-rules" ||
      key === "assignment-rules" ||
      key === "sequences"
        ? "Automation"
        : "Configuration",
    description: `Configure governed ${title.toLowerCase()} for the CRM workspace.`,
    columns: [
      { key: "name", label: "Name" },
      { key: "code", label: "Code" },
      { key: "status", label: "Status", format: "status" },
    ],
  };
}

export function isCrmDefinition(value: string): value is CrmResourceKey {
  return value in crmDefinitions;
}
export function crmContext(session: SessionContext): CrmContext {
  return {
    organizationId: session.organizationId as string,
    userId: session.userId,
    activeCompanyId: session.activeCompanyId,
    activeBranchId: session.activeBranchId,
    allowAllCompanies:
      session.roleSlugs.includes("organization_owner") ||
      session.roleSlugs.includes("system_administrator"),
  };
}
export function rethrowCrmError(error: unknown): never {
  if (error instanceof CrmError)
    throw new HttpError(error.status, error.message);
  throw error;
}
