import type { QueryClient } from "./index.js";
export type AccountingContext = { organizationId: string; userId: string; activeCompanyId: string | null; activeBranchId: string | null; allowAllCompanies: boolean; permissions: string[]; roleSlugs: string[] };
export class AccountingError extends Error { readonly status: number; readonly code: string; constructor(status: number, message: string, code?: string); }
export type AccountingRecord = Record<string, unknown>;
export function getAccountingDashboard(client: QueryClient, context: AccountingContext, filters?: AccountingRecord): Promise<AccountingRecord>;
export function getAccountingOptions(client: QueryClient, context: AccountingContext, companyId?: string | null): Promise<AccountingRecord>;
export function getAccountingSettings(client: QueryClient, context: AccountingContext, companyId?: string | null): Promise<AccountingRecord>;
export function updateAccountingSettings(client: QueryClient, context: AccountingContext, input: AccountingRecord): Promise<AccountingRecord>;
export function createAccountingAccount(client: QueryClient, context: AccountingContext, input: AccountingRecord): Promise<AccountingRecord>;
export function upsertAccountMapping(client: QueryClient, context: AccountingContext, input: AccountingRecord): Promise<AccountingRecord>;
export function createAccountingDimension(client: QueryClient, context: AccountingContext, input: AccountingRecord): Promise<AccountingRecord>;
export function createAccountingDimensionValue(client: QueryClient, context: AccountingContext, input: AccountingRecord): Promise<AccountingRecord>;
export function listJournalEntries(client: QueryClient, context: AccountingContext, filters?: AccountingRecord): Promise<AccountingRecord[]>;
export function getJournalEntry(client: QueryClient, context: AccountingContext, id: string): Promise<{ entry: AccountingRecord; lines: AccountingRecord[]; events: AccountingRecord[] }>;
export function createJournalEntry(client: QueryClient, context: AccountingContext, input: AccountingRecord, options?: AccountingRecord): Promise<{ entry: AccountingRecord; lines: AccountingRecord[] }>;
export function submitJournalEntry(client: QueryClient, context: AccountingContext, id: string, assignedTo?: string | null): Promise<AccountingRecord>;
export function approveJournalEntry(client: QueryClient, context: AccountingContext, id: string, contentHash: string): Promise<AccountingRecord>;
export function rejectJournalApproval(client: QueryClient, context: AccountingContext, id: string): Promise<AccountingRecord>;
export function postJournalEntry(client: QueryClient, context: AccountingContext, id: string, options?: AccountingRecord): Promise<AccountingRecord>;
export function reverseJournalEntry(client: QueryClient, context: AccountingContext, id: string, input?: AccountingRecord): Promise<AccountingRecord>;
export function listCustomerInvoices(client: QueryClient, context: AccountingContext, filters?: AccountingRecord): Promise<AccountingRecord[]>;
export function getCustomerInvoice(client: QueryClient, context: AccountingContext, id: string): Promise<AccountingRecord>;
export function createCustomerInvoice(client: QueryClient, context: AccountingContext, input: AccountingRecord, options?: AccountingRecord): Promise<AccountingRecord>;
export function createInvoiceFromSalesRequest(client: QueryClient, context: AccountingContext, requestId: string): Promise<AccountingRecord>;
export function submitCustomerInvoice(client: QueryClient, context: AccountingContext, id: string, assignedTo?: string | null): Promise<AccountingRecord>;
export function approveCustomerInvoice(client: QueryClient, context: AccountingContext, id: string, contentHash: string): Promise<AccountingRecord>;
export function rejectCustomerInvoiceApproval(client: QueryClient, context: AccountingContext, id: string): Promise<AccountingRecord>;
export function postCustomerInvoice(client: QueryClient, context: AccountingContext, id: string): Promise<AccountingRecord>;
export function applyCustomerCreditNote(client: QueryClient, context: AccountingContext, id: string, input: AccountingRecord): Promise<AccountingRecord>;
export function createCustomerReceipt(client: QueryClient, context: AccountingContext, input: AccountingRecord): Promise<AccountingRecord>;
export function postCustomerReceipt(client: QueryClient, context: AccountingContext, id: string): Promise<AccountingRecord>;
export function allocateCustomerReceipt(client: QueryClient, context: AccountingContext, id: string, input: AccountingRecord): Promise<AccountingRecord>;
export function listVendorBills(client: QueryClient, context: AccountingContext, filters?: AccountingRecord): Promise<AccountingRecord[]>;
export function getVendorBill(client: QueryClient, context: AccountingContext, id: string): Promise<AccountingRecord>;
export function createVendorBill(client: QueryClient, context: AccountingContext, input: AccountingRecord): Promise<AccountingRecord>;
export function submitVendorBill(client: QueryClient, context: AccountingContext, id: string, assignedTo?: string | null): Promise<AccountingRecord>;
export function approveVendorBill(client: QueryClient, context: AccountingContext, id: string, contentHash: string): Promise<AccountingRecord>;
export function rejectVendorBillApproval(client: QueryClient, context: AccountingContext, id: string): Promise<AccountingRecord>;
export function postVendorBill(client: QueryClient, context: AccountingContext, id: string): Promise<AccountingRecord>;
export function applyVendorCreditNote(client: QueryClient, context: AccountingContext, id: string, input: AccountingRecord): Promise<AccountingRecord>;
export function createVendorPayment(client: QueryClient, context: AccountingContext, input: AccountingRecord): Promise<AccountingRecord>;
export function submitVendorPayment(client: QueryClient, context: AccountingContext, id: string, assignedTo?: string | null): Promise<AccountingRecord>;
export function approveVendorPayment(client: QueryClient, context: AccountingContext, id: string, contentHash: string): Promise<AccountingRecord>;
export function rejectVendorPaymentApproval(client: QueryClient, context: AccountingContext, id: string): Promise<AccountingRecord>;
export function postVendorPayment(client: QueryClient, context: AccountingContext, id: string): Promise<AccountingRecord>;
export function allocateVendorPayment(client: QueryClient, context: AccountingContext, id: string, input: AccountingRecord): Promise<AccountingRecord>;
export function listBankAccounts(client: QueryClient, context: AccountingContext): Promise<AccountingRecord[]>;
export function createBankAccount(client: QueryClient, context: AccountingContext, input: AccountingRecord): Promise<AccountingRecord>;
export function importBankStatement(client: QueryClient, context: AccountingContext, input: AccountingRecord): Promise<AccountingRecord>;
export function listBankStatements(client: QueryClient, context: AccountingContext, filters?: AccountingRecord): Promise<AccountingRecord[]>;
export function getBankStatement(client: QueryClient, context: AccountingContext, id: string): Promise<AccountingRecord>;
export function suggestBankMatches(client: QueryClient, context: AccountingContext, statementLineId: string): Promise<AccountingRecord[]>;
export function startBankReconciliation(client: QueryClient, context: AccountingContext, input: AccountingRecord): Promise<AccountingRecord>;
export function matchBankStatementLine(client: QueryClient, context: AccountingContext, reconciliationId: string, input: AccountingRecord): Promise<AccountingRecord>;
export function completeBankReconciliation(client: QueryClient, context: AccountingContext, reconciliationId: string): Promise<AccountingRecord>;
export function listFiscalPeriods(client: QueryClient, context: AccountingContext, filters?: AccountingRecord): Promise<AccountingRecord[]>;
export function getPeriodCloseBlockers(client: QueryClient, context: AccountingContext, companyId: string, periodId: string): Promise<AccountingRecord[]>;
export function updateFiscalPeriodStatus(client: QueryClient, context: AccountingContext, id: string, input: AccountingRecord): Promise<AccountingRecord>;
export function createCloseRun(client: QueryClient, context: AccountingContext, input: AccountingRecord): Promise<AccountingRecord>;
export function listCloseRuns(client: QueryClient, context: AccountingContext): Promise<AccountingRecord[]>;
export function getCloseRun(client: QueryClient, context: AccountingContext, id: string): Promise<AccountingRecord>;
export function updateCloseTask(client: QueryClient, context: AccountingContext, runId: string, taskId: string, input: AccountingRecord): Promise<AccountingRecord>;
export function completeCloseRun(client: QueryClient, context: AccountingContext, id: string): Promise<AccountingRecord>;
export function getAccountingReport(client: QueryClient, context: AccountingContext, reportKey: string, filters?: AccountingRecord): Promise<AccountingRecord[]>;
export function listAssetCategories(client: QueryClient, context: AccountingContext, filters?: AccountingRecord): Promise<AccountingRecord[]>;
export function createAssetCategory(client: QueryClient, context: AccountingContext, input: AccountingRecord): Promise<AccountingRecord>;
export function listAssets(client: QueryClient, context: AccountingContext, filters?: AccountingRecord): Promise<AccountingRecord[]>;
export function getAsset(client: QueryClient, context: AccountingContext, id: string): Promise<{ asset: AccountingRecord; schedule: AccountingRecord[]; transactions: AccountingRecord[]; events: AccountingRecord[] }>;
export function createAsset(client: QueryClient, context: AccountingContext, input: AccountingRecord): Promise<AccountingRecord>;
export function capitalizeAsset(client: QueryClient, context: AccountingContext, id: string, input?: AccountingRecord): Promise<AccountingRecord>;
export function postAssetDepreciation(client: QueryClient, context: AccountingContext, scheduleId: string): Promise<AccountingRecord>;
export function disposeAsset(client: QueryClient, context: AccountingContext, id: string, input: AccountingRecord): Promise<AccountingRecord>;
export function createTaxReturn(client: QueryClient, context: AccountingContext, input: AccountingRecord): Promise<AccountingRecord>;
export function listTaxReturns(client: QueryClient, context: AccountingContext, filters?: AccountingRecord): Promise<AccountingRecord[]>;
export function createRecurringTemplate(client: QueryClient, context: AccountingContext, input: AccountingRecord): Promise<AccountingRecord>;
export function listRecurringTemplates(client: QueryClient, context: AccountingContext, filters?: AccountingRecord): Promise<AccountingRecord[]>;
export function runDueRecurringTemplates(client: QueryClient, context: AccountingContext, runDate?: string | null): Promise<AccountingRecord[]>;
export function createAccrualSchedule(client: QueryClient, context: AccountingContext, input: AccountingRecord): Promise<AccountingRecord>;
export function listAccrualSchedules(client: QueryClient, context: AccountingContext, filters?: AccountingRecord): Promise<AccountingRecord[]>;
export function getAccrualSchedule(client: QueryClient, context: AccountingContext, id: string): Promise<{ schedule: AccountingRecord; recognitions: AccountingRecord[] }>;
export function runDueAccruals(client: QueryClient, context: AccountingContext, input?: AccountingRecord): Promise<AccountingRecord[]>;
export function createBudget(client: QueryClient, context: AccountingContext, input: AccountingRecord): Promise<AccountingRecord>;
export function listBudgets(client: QueryClient, context: AccountingContext): Promise<AccountingRecord[]>;
export function submitBudget(client: QueryClient, context: AccountingContext, id: string, assignedTo?: string | null): Promise<AccountingRecord>;
export function approveBudget(client: QueryClient, context: AccountingContext, id: string): Promise<AccountingRecord>;
export function rejectBudgetApproval(client: QueryClient, context: AccountingContext, id: string): Promise<AccountingRecord>;
export function activateBudget(client: QueryClient, context: AccountingContext, id: string): Promise<AccountingRecord>;
export function calculateRevaluation(client: QueryClient, context: AccountingContext, input: AccountingRecord): Promise<AccountingRecord>;
export function postRevaluation(client: QueryClient, context: AccountingContext, id: string): Promise<AccountingRecord>;
export function listRevaluationRuns(client: QueryClient, context: AccountingContext, filters?: AccountingRecord): Promise<AccountingRecord[]>;
export function createIntercompanyRule(client: QueryClient, context: AccountingContext, input: AccountingRecord): Promise<AccountingRecord>;
export function listIntercompanyRules(client: QueryClient, context: AccountingContext): Promise<AccountingRecord[]>;
export function createIntercompanyJournal(client: QueryClient, context: AccountingContext, input: AccountingRecord): Promise<AccountingRecord>;
export function runDunning(client: QueryClient, context: AccountingContext, input: AccountingRecord): Promise<AccountingRecord>;
export function listDunningRuns(client: QueryClient, context: AccountingContext): Promise<AccountingRecord[]>;
export function createConsolidationGroup(client: QueryClient, context: AccountingContext, input: AccountingRecord): Promise<AccountingRecord>;
export function listConsolidationGroups(client: QueryClient, context: AccountingContext): Promise<AccountingRecord[]>;
export function calculateConsolidation(client: QueryClient, context: AccountingContext, input: AccountingRecord): Promise<AccountingRecord>;
export function addConsolidationAdjustment(client: QueryClient, context: AccountingContext, id: string, input: AccountingRecord): Promise<AccountingRecord>;
export function listConsolidationRuns(client: QueryClient, context: AccountingContext, filters?: AccountingRecord): Promise<AccountingRecord[]>;
export function finalizeConsolidationRun(client: QueryClient, context: AccountingContext, id: string): Promise<AccountingRecord>;
export function getAccountingOrganisationOptions(client: QueryClient, context: AccountingContext): Promise<{ companies: AccountingRecord[]; ledgers: AccountingRecord[]; accounts: AccountingRecord[]; currencies: AccountingRecord[] }>;
export function initializeAccountingCompany(
  client: QueryClient,
  input: { organizationId: string; companyId: string; userId: string },
): Promise<{ ledgerId: string; accountCount: number }>;
export function updateTaxReturnStatus(client: QueryClient, context: AccountingContext, id: string, input: AccountingRecord): Promise<AccountingRecord>;

export function getVendorBillMatch(client: QueryClient, context: AccountingContext, id: string): Promise<AccountingRecord | null>;
export function evaluateVendorBillMatch(client: QueryClient, context: AccountingContext, id: string, input?: AccountingRecord): Promise<AccountingRecord>;
export function overrideVendorBillMatch(client: QueryClient, context: AccountingContext, id: string, input?: AccountingRecord): Promise<AccountingRecord>;
export function createComplianceRequest(client: QueryClient, context: AccountingContext, input: AccountingRecord): Promise<AccountingRecord>;
export function listComplianceRequests(client: QueryClient, context: AccountingContext, filters?: AccountingRecord): Promise<AccountingRecord[]>;
export function updateComplianceRequest(client: QueryClient, context: AccountingContext, id: string, input: AccountingRecord): Promise<AccountingRecord>;
export function createCashForecastScenario(client: QueryClient, context: AccountingContext, input: AccountingRecord): Promise<AccountingRecord>;
export function generateCashForecast(client: QueryClient, context: AccountingContext, id: string, input?: AccountingRecord): Promise<AccountingRecord>;
export function getCashForecast(client: QueryClient, context: AccountingContext, id: string): Promise<AccountingRecord>;
export function listCashForecasts(client: QueryClient, context: AccountingContext, filters?: AccountingRecord): Promise<AccountingRecord[]>;
export function transferAsset(client: QueryClient, context: AccountingContext, id: string, input: AccountingRecord): Promise<AccountingRecord>;
export function impairAsset(client: QueryClient, context: AccountingContext, id: string, input: AccountingRecord): Promise<AccountingRecord>;
export function changeAssetSuspension(client: QueryClient, context: AccountingContext, id: string, input: AccountingRecord): Promise<AccountingRecord>;
export function allocateInstallments(total: string | number, termLines: AccountingRecord[], precision?: number): AccountingRecord[];

export function calculateSettlementBaseAmounts(client: QueryClient, context: AccountingContext, input: AccountingRecord): Promise<AccountingRecord>;
export function createCustomerSettlementAdjustment(client: QueryClient, context: AccountingContext, input: AccountingRecord): Promise<AccountingRecord>;
export function createVendorSettlementAdjustment(client: QueryClient, context: AccountingContext, input: AccountingRecord): Promise<AccountingRecord>;
export function resolvePaymentSchedule(client: QueryClient, context: AccountingContext, options: AccountingRecord): Promise<AccountingRecord>;
