import { listComplianceRequests, listTaxReturns } from "@vercentlabs/api";
import SimpleAccountingForm from "@/components/accounting/simple-accounting-form";
import { requireWorkspace } from "@/lib/auth";
import { hasPermission, PERMISSIONS } from "@/lib/authorization";
import { accountingContext } from "@/lib/accounting";
import { tenantTransaction } from "@/lib/db";

export const dynamic = "force-dynamic";
type Row = Record<string, unknown>;

export default async function AccountingTaxPage() {
  const session = await requireWorkspace();
  if (!hasPermission(session, PERMISSIONS.accountingView)) return <section className="panel"><h1>Accounting access required</h1></section>;
  if (!session.activeCompanyId) return <section className="panel"><h1>Select a company first</h1></section>;
  const context = accountingContext(session);
  const data = await tenantTransaction(context.organizationId, async (client) => ({ returns: await listTaxReturns(client, context), compliance: await listComplianceRequests(client, context) })) as unknown as { returns: Row[]; compliance: Row[] };
  const rows = data.returns;
  return <>
    <section className="page-heading"><div><p className="eyebrow">Tax accounting</p><h1>Tax ledger and returns</h1><p>Reconcile output tax, recoverable input tax, withholding, reverse charge, place of supply and filing periods.</p></div></section>
    <section className="panel"><div className="accounting-table"><div className="accounting-table-row accounting-table-head"><span>Return</span><span>Period</span><span>Status</span><span>Taxable amount</span><span>Output tax</span><span>Net payable</span></div>{rows.map((row) => <div className="accounting-table-row" key={String(row.id)}><span><strong>{String(row.return_type)}</strong><small>{String(row.tax_registration || "Default registration")}</small></span><span>{String(row.period_start).slice(0, 10)} to {String(row.period_end).slice(0, 10)}</span><span>{String(row.status)}</span><span>{String(row.taxable_amount)}</span><span>{String(row.output_tax)}</span><span>{String(row.net_tax_payable)}</span></div>)}{!rows.length ? <p>No tax returns have been generated.</p> : null}</div></section>
    {hasPermission(session, PERMISSIONS.accountingTaxManage) ? <SimpleAccountingForm title="Generate tax return" description="Aggregate component-level tax ledger entries into a governed filing period." endpoint="/api/accounting/tax/returns" submitLabel="Generate return" basePayload={{ companyId: session.activeCompanyId }} fields={[{ name: "returnType", label: "Return type", required: true, defaultValue: "GST" }, { name: "taxRegistration", label: "Tax registration" }, { name: "periodStart", label: "Period start", type: "date", required: true }, { name: "periodEnd", label: "Period end", type: "date", required: true }, { name: "filingDueDate", label: "Filing due date", type: "date" }]} /> : null}
    <section className="panel"><p className="eyebrow">Statutory outbox</p><h2>Compliance requests</h2><div className="accounting-list">{data.compliance.map((row) => <div key={String(row.id)}><span><strong>{String(row.request_number)} · {String(row.compliance_type).replaceAll("_", " ")}</strong><small>{String(row.source_type)} · requested {new Date(String(row.requested_at)).toLocaleString("en-IN")}</small></span><b>{String(row.status)}{row.external_reference ? ` · ${String(row.external_reference)}` : ""}</b></div>)}{!data.compliance.length ? <p>No statutory request has been queued.</p> : null}</div></section>
    {hasPermission(session, PERMISSIONS.accountingTaxManage) ? <SimpleAccountingForm title="Queue statutory compliance" description="Create an idempotent request for an e-invoice, e-way bill, TDS statement, tax payment or statutory report. Provider adapters update this outbox without changing ledger logic." endpoint="/api/accounting/compliance/requests" submitLabel="Queue compliance request" basePayload={{ companyId: session.activeCompanyId }} fields={[{ name: "complianceType", label: "Compliance type", type: "select", required: true, options: [{ value: "gst_einvoice", label: "GST e-invoice" }, { value: "gst_eway_bill", label: "GST e-way bill" }, { value: "tds_statement", label: "TDS statement" }, { value: "tax_payment", label: "Tax payment" }, { value: "statutory_report", label: "Statutory report" }, { value: "other", label: "Other" }] }, { name: "sourceType", label: "Source type", type: "select", required: true, options: [{ value: "customer_invoice", label: "Customer invoice" }, { value: "vendor_bill", label: "Vendor bill" }, { value: "tax_return", label: "Tax return" }, { value: "journal_entry", label: "Journal entry" }] }, { name: "sourceId", label: "Source record ID", required: true }, { name: "idempotencyKey", label: "Idempotency key" }]} /> : null}
    <section className="accounting-capability-grid">{[["Component tax ledger", "CGST, SGST, IGST, cess, VAT, withholding and future tax components."], ["Source traceability", "Every tax amount links to its source invoice, bill, journal and party."], ["Input tax credit", "Recoverable and non-recoverable input tax remain separately auditable."], ["Return controls", "Draft, review, filing and payment status are preserved by period."], ["Tax reports", "Tax summary and detailed tax-ledger reports reconcile to the general ledger."], ["Compliance adapters", "Government filing APIs remain versioned adapters, not hard-coded accounting logic."]].map(([title, description]) => <article key={title}><strong>{title}</strong><span>{description}</span></article>)}</section>
  </>;
}
